// Грамматика — задания с выбором варианта и разбором ошибки.
//
// Отличие от словарных упражнений: здесь проверяется не «знаешь ли слово»,
// а «понимаешь ли правило». Поэтому у каждого задания обязателен разбор:
// увидеть правильный ответ мало, ученик должен понять, ПОЧЕМУ так.
// Без этого он запомнит конкретное предложение и ошибётся в следующем.
//
// Файл грузится по требованию (ensureGrammar в js/util.js) — как словарь
// и выражения. На главной он не нужен.
//
// Поля записи:
//   s     предложение, пропуск обозначен ___
//   o     варианты ответа (первый — НЕ обязательно верный, порядок мешается)
//   a     правильный вариант (строкой, как в o)
//   ru    перевод предложения
//   why   разбор: правило человеческим языком
//   lvl   A2 | B1 | B2

const GRAMMAR_TOPICS = [
  { id: "present",    name: "Present Simple и Continuous" },
  { id: "past",       name: "Прошедшее время" },
  { id: "perfect",    name: "Present Perfect" },
  { id: "articles",   name: "Артикли" },
  { id: "preps",      name: "Предлоги" },
  { id: "compare",    name: "Степени сравнения" },
  { id: "modals",     name: "Модальные глаголы" },
  { id: "condition",  name: "Условные предложения" },
  { id: "passive",    name: "Пассивный залог" },
  { id: "ing-to",     name: "Герундий и инфинитив" },
];

const GRAMMAR = {

  // ================= Present Simple vs Continuous =================
  present: [
    { s: "Look! The cat ___ on your laptop again.", o: ["sits", "is sitting", "sit"], a: "is sitting",
      ru: "Смотри! Кот снова сидит на твоём ноутбуке.",
      why: "«Look!» указывает на то, что происходит прямо сейчас — Present Continuous: is sitting.", lvl: "A2" },
    { s: "My father ___ coffee every morning.", o: ["drinks", "is drinking", "drink"], a: "drinks",
      ru: "Мой папа пьёт кофе каждое утро.",
      why: "«Every morning» — регулярное действие, Present Simple. У he/she/it добавляется -s: drinks.", lvl: "A2" },
    { s: "She ___ to music right now, so she cannot hear you.", o: ["listens", "is listening", "listen"], a: "is listening",
      ru: "Она сейчас слушает музыку, поэтому не слышит тебя.",
      why: "«Right now» — действие в момент речи, Present Continuous.", lvl: "A2" },
    { s: "Water ___ at 100 degrees.", o: ["is boiling", "boils", "boil"], a: "boils",
      ru: "Вода кипит при ста градусах.",
      why: "Факт, который верен всегда, — Present Simple.", lvl: "A2" },
    { s: "I ___ this film — it is my favourite.", o: ["am liking", "like", "likes"], a: "like",
      ru: "Мне нравится этот фильм — он мой любимый.",
      why: "Глаголы чувств (like, love, hate, want, know) в Continuous не ставятся.", lvl: "B1" },
    { s: "They usually ___ football on Sundays.", o: ["are playing", "play", "plays"], a: "play",
      ru: "Они обычно играют в футбол по воскресеньям.",
      why: "«Usually» — регулярность, Present Simple. They — без -s.", lvl: "A2" },
    { s: "Be quiet, the baby ___ .", o: ["sleeps", "is sleeping", "sleep"], a: "is sleeping",
      ru: "Потише, малыш спит.",
      why: "Действие идёт прямо сейчас — Present Continuous.", lvl: "A2" },
    { s: "___ your sister speak French?", o: ["Do", "Does", "Is"], a: "Does",
      ru: "Твоя сестра говорит по-французски?",
      why: "Вопрос в Present Simple с he/she/it строится через does.", lvl: "A2" },
    { s: "We ___ not go to school on Saturdays.", o: ["do", "does", "are"], a: "do",
      ru: "По субботам мы не ходим в школу.",
      why: "Отрицание в Present Simple с we — do not.", lvl: "A2" },
    { s: "This week I ___ at my grandmother's house.", o: ["stay", "am staying", "stays"], a: "am staying",
      ru: "На этой неделе я живу у бабушки.",
      why: "Временная ситуация, ограниченная этой неделей, — Present Continuous.", lvl: "B1" },
    { s: "He ___ the guitar very well.", o: ["is playing", "plays", "play"], a: "plays",
      ru: "Он очень хорошо играет на гитаре.",
      why: "Постоянное умение, а не действие сейчас, — Present Simple.", lvl: "A2" },
    { s: "Why ___ you laughing?", o: ["do", "are", "does"], a: "are",
      ru: "Почему ты смеёшься?",
      why: "Форма laughing требует be: are you laughing.", lvl: "A2" },
  ],

  // ================= Past Simple / Past Continuous =================
  past: [
    { s: "Yesterday we ___ to the cinema.", o: ["go", "went", "have gone"], a: "went",
      ru: "Вчера мы ходили в кино.",
      why: "«Yesterday» — точное время в прошлом, Past Simple. go → went.", lvl: "A2" },
    { s: "When I came in, she ___ a letter.", o: ["wrote", "was writing", "writes"], a: "was writing",
      ru: "Когда я вошёл, она писала письмо.",
      why: "Длинное действие прерывается коротким: длинное — Past Continuous.", lvl: "B1" },
    { s: "He ___ not see the sign and turned left.", o: ["did", "was", "does"], a: "did",
      ru: "Он не увидел знак и повернул налево.",
      why: "Отрицание в Past Simple — did not, дальше глагол без изменений.", lvl: "A2" },
    { s: "What ___ you do last summer?", o: ["did", "do", "were"], a: "did",
      ru: "Что ты делал прошлым летом?",
      why: "Вопрос в Past Simple строится через did.", lvl: "A2" },
    { s: "The children ___ in the garden all afternoon.", o: ["played", "were playing", "play"], a: "were playing",
      ru: "Дети играли в саду весь день.",
      why: "«All afternoon» — процесс, растянутый во времени: Past Continuous.", lvl: "B1" },
    { s: "She ___ her keys on the table and left.", o: ["put", "was putting", "puts"], a: "put",
      ru: "Она положила ключи на стол и ушла.",
      why: "Одно законченное действие за другим — Past Simple. put не меняется.", lvl: "A2" },
    { s: "It ___ heavily when we left the house.", o: ["rained", "was raining", "rains"], a: "was raining",
      ru: "Шёл сильный дождь, когда мы вышли из дома.",
      why: "Фон, на котором произошло событие, — Past Continuous.", lvl: "B1" },
    { s: "I ___ him two years ago in Moscow.", o: ["meet", "met", "have met"], a: "met",
      ru: "Я встретил его два года назад в Москве.",
      why: "«Two years ago» — точное время в прошлом, Past Simple.", lvl: "A2" },
    { s: "While she ___ , the phone rang.", o: ["cooked", "was cooking", "cooks"], a: "was cooking",
      ru: "Пока она готовила, зазвонил телефон.",
      why: "После while — длительное действие, Past Continuous.", lvl: "B1" },
    { s: "They ___ at the station at seven.", o: ["arrived", "were arriving", "arrive"], a: "arrived",
      ru: "Они прибыли на вокзал в семь.",
      why: "Точный момент — Past Simple.", lvl: "A2" },
    { s: "He was tired because he ___ all night.", o: ["worked", "had worked", "works"], a: "had worked",
      ru: "Он устал, потому что работал всю ночь.",
      why: "Действие раньше другого прошедшего — Past Perfect: had worked.", lvl: "B2" },
    { s: "I did not recognise her — she ___ her hair.", o: ["cut", "had cut", "cuts"], a: "had cut",
      ru: "Я её не узнал — она подстриглась.",
      why: "Причина случилась раньше момента в прошлом — Past Perfect.", lvl: "B2" },
  ],

  // ================= Present Perfect =================
  perfect: [
    { s: "I ___ never been to Japan.", o: ["have", "am", "did"], a: "have",
      ru: "Я никогда не был в Японии.",
      why: "Опыт за всю жизнь без указания времени — Present Perfect: have been.", lvl: "B1" },
    { s: "She ___ just finished her homework.", o: ["has", "have", "is"], a: "has",
      ru: "Она только что закончила домашнюю работу.",
      why: "«Just» — маркер Present Perfect. С she — has.", lvl: "B1" },
    { s: "We ___ in this town since 2019.", o: ["live", "have lived", "lived"], a: "have lived",
      ru: "Мы живём в этом городе с 2019 года.",
      why: "«Since» — действие началось в прошлом и продолжается: Present Perfect.", lvl: "B1" },
    { s: "___ you ever seen a whale?", o: ["Did", "Have", "Do"], a: "Have",
      ru: "Ты когда-нибудь видел кита?",
      why: "«Ever» в вопросе про опыт — Present Perfect.", lvl: "B1" },
    { s: "He ___ his phone yesterday.", o: ["has lost", "lost", "loses"], a: "lost",
      ru: "Он потерял телефон вчера.",
      why: "«Yesterday» — точное время в прошлом, поэтому Past Simple, а не Perfect.", lvl: "B1" },
    { s: "They have known each other ___ ten years.", o: ["since", "for", "from"], a: "for",
      ru: "Они знакомы десять лет.",
      why: "For — про длительность отрезка, since — про точку начала.", lvl: "B1" },
    { s: "I have not seen him ___ Monday.", o: ["for", "since", "during"], a: "since",
      ru: "Я не видел его с понедельника.",
      why: "Monday — точка отсчёта, поэтому since.", lvl: "B1" },
    { s: "The train ___ already left.", o: ["has", "have", "is"], a: "has",
      ru: "Поезд уже ушёл.",
      why: "«Already» — Present Perfect. The train = it, поэтому has.", lvl: "B1" },
    { s: "She ___ that film three times.", o: ["watched", "has watched", "watches"], a: "has watched",
      ru: "Она смотрела этот фильм три раза.",
      why: "Счёт повторов к настоящему моменту — Present Perfect.", lvl: "B1" },
    { s: "___ you finished yet?", o: ["Have", "Did", "Are"], a: "Have",
      ru: "Ты уже закончил?",
      why: "«Yet» в вопросе — Present Perfect.", lvl: "B1" },
    { s: "This is the best book I ___ ever read.", o: ["have", "did", "am"], a: "have",
      ru: "Это лучшая книга, которую я когда-либо читал.",
      why: "После превосходной степени с ever — Present Perfect.", lvl: "B2" },
    { s: "How long ___ she worked here?", o: ["did", "has", "does"], a: "has",
      ru: "Как долго она здесь работает?",
      why: "«How long» про период до настоящего — Present Perfect.", lvl: "B1" },
  ],

  // ================= Артикли =================
  articles: [
    { s: "I saw ___ interesting film last night.", o: ["a", "an", "the"], a: "an",
      ru: "Вчера вечером я посмотрел интересный фильм.",
      why: "Перед гласным звуком — an: an interesting film.", lvl: "A2" },
    { s: "___ sun rises in the east.", o: ["A", "An", "The"], a: "The",
      ru: "Солнце встаёт на востоке.",
      why: "Предмет единственный в своём роде — the.", lvl: "A2" },
    { s: "She is ___ teacher at our school.", o: ["a", "an", "the"], a: "a",
      ru: "Она учительница в нашей школе.",
      why: "Профессия называется с a/an. Перед согласным звуком — a.", lvl: "A2" },
    { s: "We had ___ dinner at seven.", o: ["a", "the", "—"], a: "—",
      ru: "Мы поужинали в семь.",
      why: "Названия приёмов пищи идут без артикля: have dinner.", lvl: "B1" },
    { s: "He plays ___ piano very well.", o: ["a", "the", "—"], a: "the",
      ru: "Он очень хорошо играет на пианино.",
      why: "С музыкальными инструментами ставится the: play the piano.", lvl: "B1" },
    { s: "___ Volga is the longest river in Europe.", o: ["A", "The", "—"], a: "The",
      ru: "Волга — самая длинная река в Европе.",
      why: "С названиями рек употребляется the.", lvl: "B1" },
    { s: "I go to ___ school by bus.", o: ["a", "the", "—"], a: "—",
      ru: "Я езжу в школу на автобусе.",
      why: "Когда говорим о школе как о занятии, а не о здании, артикля нет.", lvl: "B1" },
    { s: "Give me ___ book on the table, please.", o: ["a", "an", "the"], a: "the",
      ru: "Дай мне книгу, которая на столе, пожалуйста.",
      why: "Собеседник понимает, о какой книге речь, — the.", lvl: "A2" },
    { s: "She wants to be ___ engineer.", o: ["a", "an", "the"], a: "an",
      ru: "Она хочет быть инженером.",
      why: "Перед гласным звуком — an: an engineer.", lvl: "A2" },
    { s: "___ life is short.", o: ["A", "The", "—"], a: "—",
      ru: "Жизнь коротка.",
      why: "Абстрактное понятие в общем смысле — без артикля.", lvl: "B2" },
    { s: "This is ___ most difficult question.", o: ["a", "the", "—"], a: "the",
      ru: "Это самый сложный вопрос.",
      why: "Перед превосходной степенью всегда the.", lvl: "A2" },
    { s: "We visited ___ United Kingdom last year.", o: ["a", "the", "—"], a: "the",
      ru: "В прошлом году мы побывали в Соединённом Королевстве.",
      why: "Названия стран со словами Kingdom, States, Republic идут с the.", lvl: "B1" },
  ],

  // ================= Предлоги =================
  preps: [
    { s: "The lesson starts ___ nine o'clock.", o: ["in", "on", "at"], a: "at",
      ru: "Урок начинается в девять часов.",
      why: "С точным временем — at: at nine o'clock.", lvl: "A2" },
    { s: "My birthday is ___ July.", o: ["in", "on", "at"], a: "in",
      ru: "Мой день рождения в июле.",
      why: "С месяцами и годами — in.", lvl: "A2" },
    { s: "We meet ___ Monday morning.", o: ["in", "on", "at"], a: "on",
      ru: "Мы встречаемся в понедельник утром.",
      why: "С днями недели и датами — on.", lvl: "A2" },
    { s: "The book is ___ the table.", o: ["in", "on", "at"], a: "on",
      ru: "Книга на столе.",
      why: "Предмет лежит НА поверхности — on. Внутри чего-то было бы in.", lvl: "A2" },
    { s: "She is waiting ___ the bus stop.", o: ["in", "on", "at"], a: "at",
      ru: "Она ждёт на автобусной остановке.",
      why: "Точка на карте, место встречи — at.", lvl: "A2" },
    { s: "There is milk ___ the fridge.", o: ["in", "on", "at"], a: "in",
      ru: "Молоко в холодильнике.",
      why: "Внутри замкнутого пространства — in.", lvl: "A2" },
    { s: "I am afraid ___ spiders.", o: ["of", "from", "for"], a: "of",
      ru: "Я боюсь пауков.",
      why: "Устойчивое сочетание: be afraid of.", lvl: "B1" },
    { s: "This present is ___ you.", o: ["to", "for", "at"], a: "for",
      ru: "Этот подарок для тебя.",
      why: "Кому предназначено — for.", lvl: "A2" },
    { s: "He is good ___ mathematics.", o: ["in", "at", "on"], a: "at",
      ru: "Он хорош в математике.",
      why: "Устойчивое сочетание: be good at.", lvl: "B1" },
    { s: "We arrived ___ the airport late.", o: ["to", "at", "in"], a: "at",
      ru: "Мы поздно приехали в аэропорт.",
      why: "Arrive at — для зданий и точек; arrive in — для городов и стран.", lvl: "B1" },
    { s: "She depends ___ her parents.", o: ["from", "of", "on"], a: "on",
      ru: "Она зависит от родителей.",
      why: "Устойчивое сочетание: depend on.", lvl: "B2" },
    { s: "Thank you ___ your help.", o: ["for", "of", "to"], a: "for",
      ru: "Спасибо за твою помощь.",
      why: "Устойчивое сочетание: thank you for.", lvl: "A2" },
  ],

  // ================= Степени сравнения =================
  compare: [
    { s: "This box is ___ than that one.", o: ["heavy", "heavier", "heaviest"], a: "heavier",
      ru: "Эта коробка тяжелее той.",
      why: "Сравнение двух предметов — сравнительная степень. Короткое слово: heavy → heavier.", lvl: "A2" },
    { s: "He is the ___ boy in the class.", o: ["tall", "taller", "tallest"], a: "tallest",
      ru: "Он самый высокий мальчик в классе.",
      why: "«In the class» — сравнение со всей группой, превосходная степень.", lvl: "A2" },
    { s: "This task is ___ difficult than the last one.", o: ["more", "most", "much"], a: "more",
      ru: "Это задание сложнее предыдущего.",
      why: "Длинные прилагательные сравниваются через more.", lvl: "A2" },
    { s: "Your idea is ___ than mine.", o: ["gooder", "better", "best"], a: "better",
      ru: "Твоя идея лучше моей.",
      why: "good → better → best, форма неправильная.", lvl: "A2" },
    { s: "Today is ___ day of the year.", o: ["the hotter", "the hottest", "hotter"], a: "the hottest",
      ru: "Сегодня самый жаркий день в году.",
      why: "Превосходная степень с the, согласная удваивается: hottest.", lvl: "B1" },
    { s: "She sings ___ than her sister.", o: ["good", "better", "well"], a: "better",
      ru: "Она поёт лучше сестры.",
      why: "Сравнивается действие: well → better.", lvl: "B1" },
    { s: "This film is not ___ interesting as the book.", o: ["so", "as", "more"], a: "as",
      ru: "Этот фильм не такой интересный, как книга.",
      why: "Конструкция равенства: as … as.", lvl: "B1" },
    { s: "The ___ you start, the sooner you finish.", o: ["early", "earlier", "earliest"], a: "earlier",
      ru: "Чем раньше начнёшь, тем скорее закончишь.",
      why: "Конструкция «the … the …» требует сравнительной степени.", lvl: "B2" },
    { s: "My room is ___ smaller than yours.", o: ["very", "much", "more"], a: "much",
      ru: "Моя комната намного меньше твоей.",
      why: "Сравнительную степень усиливают much, far, a lot — но не very.", lvl: "B2" },
    { s: "It was the ___ film I have ever seen.", o: ["worse", "worst", "bad"], a: "worst",
      ru: "Это был худший фильм, который я когда-либо видел.",
      why: "bad → worse → worst — форма неправильная, запоминается наизусть. Здесь превосходная степень, поэтому worst.", lvl: "B1" },
    { s: "This road is ___ than that one.", o: ["more narrow", "narrower", "narrowest"], a: "narrower",
      ru: "Эта дорога уже той.",
      why: "Двусложные на -ow сравниваются через -er: narrower.", lvl: "B2" },
    { s: "He runs ___ of all the boys.", o: ["faster", "fastest", "the fastest"], a: "the fastest",
      ru: "Он бегает быстрее всех мальчиков.",
      why: "«Of all» — превосходная степень, с the.", lvl: "B1" },
  ],

  // ================= Модальные глаголы =================
  modals: [
    { s: "You ___ wear a helmet — it is the rule.", o: ["can", "must", "may"], a: "must",
      ru: "Ты обязан надеть шлем — это правило.",
      why: "Обязанность, которая идёт от правила, — must.", lvl: "A2" },
    { s: "___ I open the window?", o: ["May", "Must", "Should"], a: "May",
      ru: "Можно я открою окно?",
      why: "Вежливая просьба разрешить — may (в разговорной речи ещё can).", lvl: "A2" },
    { s: "She ___ swim when she was five.", o: ["can", "could", "must"], a: "could",
      ru: "Она умела плавать в пять лет.",
      why: "Умение в прошлом — could.", lvl: "A2" },
    { s: "You ___ see a doctor, you look pale.", o: ["should", "must not", "can"], a: "should",
      ru: "Тебе стоит сходить к врачу, ты бледный.",
      why: "Совет, а не приказ, — should. Must значило бы «обязан», а тут просто рекомендация.", lvl: "A2" },
    { s: "We ___ hurry, we have plenty of time.", o: ["must not", "do not have to", "should not"], a: "do not have to",
      ru: "Нам не нужно спешить, у нас полно времени.",
      why: "Отсутствие необходимости — do not have to. Must not значит «нельзя».", lvl: "B1" },
    { s: "You ___ smoke here — it is a hospital.", o: ["must not", "do not have to", "need not"], a: "must not",
      ru: "Здесь нельзя курить — это больница.",
      why: "Строгий запрет — must not.", lvl: "B1" },
    { s: "___ you help me with this box?", o: ["Could", "Must", "Should"], a: "Could",
      ru: "Не мог бы ты помочь мне с этой коробкой?",
      why: "Вежливая просьба — could.", lvl: "A2" },
    { s: "He ___ be at home, his car is outside.", o: ["must", "can", "should"], a: "must",
      ru: "Он, должно быть, дома — его машина у подъезда.",
      why: "Уверенное предположение — must.", lvl: "B2" },
    { s: "It ___ rain later, take an umbrella.", o: ["must", "might", "should"], a: "might",
      ru: "Позже может пойти дождь, возьми зонт.",
      why: "Неуверенное предположение — might или may.", lvl: "B1" },
    { s: "I ___ to finish this today.", o: ["must", "have", "can"], a: "have",
      ru: "Я должен закончить это сегодня.",
      why: "Перед to может стоять только have: have to finish.", lvl: "B1" },
    { s: "You ___ have told me earlier!", o: ["should", "must", "can"], a: "should",
      ru: "Тебе следовало сказать мне раньше!",
      why: "Упрёк о прошлом — should have + третья форма.", lvl: "B2" },
    { s: "Students ___ use dictionaries during the test.", o: ["are not allowed to", "must not to", "do not must"], a: "are not allowed to",
      ru: "Ученикам не разрешается пользоваться словарями во время теста.",
      why: "«Не разрешено» — be allowed to. После must частица to не ставится.", lvl: "B2" },
  ],

  // ================= Условные предложения =================
  condition: [
    { s: "If you heat ice, it ___ .", o: ["melts", "will melt", "would melt"], a: "melts",
      ru: "Если нагреть лёд, он тает.",
      why: "Нулевое условие: всегда верный факт — Present Simple в обеих частях.", lvl: "B1" },
    { s: "If it rains tomorrow, we ___ at home.", o: ["stay", "will stay", "would stay"], a: "will stay",
      ru: "Если завтра пойдёт дождь, мы останемся дома.",
      why: "Первое условие: реальное будущее — if + Present, главная часть с will.", lvl: "B1" },
    { s: "If I ___ you, I would say sorry.", o: ["am", "was", "were"], a: "were",
      ru: "На твоём месте я бы извинился.",
      why: "Второе условие: в конструкции If I were you всегда were.", lvl: "B2" },
    { s: "She would travel more if she ___ more money.", o: ["has", "had", "will have"], a: "had",
      ru: "Она бы больше путешествовала, будь у неё больше денег.",
      why: "Второе условие: нереальное настоящее — Past Simple после if.", lvl: "B2" },
    { s: "If you ___ hurry, you will miss the train.", o: ["do not", "will not", "would not"], a: "do not",
      ru: "Если не поторопишься, опоздаешь на поезд.",
      why: "После if будущее время не ставится — только Present Simple.", lvl: "B1" },
    { s: "I will call you when I ___ home.", o: ["will get", "get", "got"], a: "get",
      ru: "Я позвоню тебе, когда доберусь домой.",
      why: "После when о будущем — Present Simple, как и после if.", lvl: "B1" },
    { s: "If he had studied, he ___ the exam.", o: ["would pass", "would have passed", "will pass"], a: "would have passed",
      ru: "Если бы он занимался, он бы сдал экзамен.",
      why: "Третье условие: сожаление о прошлом — would have + третья форма.", lvl: "B2" },
    { s: "Unless you ___ , you will not understand.", o: ["listen", "do not listen", "will listen"], a: "listen",
      ru: "Если не будешь слушать, не поймёшь.",
      why: "Unless уже содержит отрицание — второй раз его добавлять нельзя.", lvl: "B2" },
    { s: "If I ___ time, I will help you.", o: ["have", "will have", "had"], a: "have",
      ru: "Если у меня будет время, я тебе помогу.",
      why: "Первое условие: after if — Present Simple.", lvl: "B1" },
    { s: "What would you do if you ___ a million?", o: ["win", "won", "will win"], a: "won",
      ru: "Что бы ты сделал, если бы выиграл миллион?",
      why: "Второе условие: воображаемая ситуация — Past Simple после if.", lvl: "B2" },
    { s: "We would have come if we ___ about the party.", o: ["knew", "had known", "know"], a: "had known",
      ru: "Мы бы пришли, если бы знали о вечеринке.",
      why: "Третье условие: had + третья форма после if.", lvl: "B2" },
    { s: "If you press this button, the machine ___ .", o: ["starts", "would start", "started"], a: "starts",
      ru: "Если нажать эту кнопку, машина запускается.",
      why: "Нулевое условие: неизменный результат.", lvl: "B1" },
  ],

  // ================= Пассивный залог =================
  passive: [
    { s: "This house ___ in 1920.", o: ["built", "was built", "is building"], a: "was built",
      ru: "Этот дом был построен в 1920 году.",
      why: "Дом не строит сам себя — пассив: was + третья форма.", lvl: "B1" },
    { s: "English ___ all over the world.", o: ["speaks", "is spoken", "is speaking"], a: "is spoken",
      ru: "На английском говорят по всему миру.",
      why: "Кто говорит — неважно, важен сам язык: пассив в настоящем.", lvl: "B1" },
    { s: "The letter ___ yesterday.", o: ["sent", "was sent", "has sent"], a: "was sent",
      ru: "Письмо было отправлено вчера.",
      why: "Пассив в прошедшем: was sent.", lvl: "B1" },
    { s: "The room ___ every morning.", o: ["cleans", "is cleaned", "cleaned"], a: "is cleaned",
      ru: "Комнату убирают каждое утро.",
      why: "Регулярное действие над предметом — пассив в Present Simple.", lvl: "B1" },
    { s: "The bridge ___ next year.", o: ["will build", "will be built", "builds"], a: "will be built",
      ru: "Мост построят в следующем году.",
      why: "Пассив в будущем: will be + третья форма.", lvl: "B2" },
    { s: "The window ___ by the wind.", o: ["broke", "was broken", "is breaking"], a: "was broken",
      ru: "Окно было разбито ветром.",
      why: "Пассив: подлежащее не действует, а испытывает действие.", lvl: "B1" },
    { s: "This song ___ by millions of people.", o: ["knows", "is known", "is knowing"], a: "is known",
      ru: "Эту песню знают миллионы.",
      why: "Пассив от know — is known.", lvl: "B1" },
    { s: "The work ___ already ___ .", o: ["has / done", "has been / done", "is / doing"], a: "has been / done",
      ru: "Работа уже сделана.",
      why: "Пассив в Present Perfect: has been + третья форма.", lvl: "B2" },
    { s: "Our car ___ at the moment.", o: ["is repairing", "is being repaired", "repairs"], a: "is being repaired",
      ru: "Нашу машину сейчас чинят.",
      why: "Пассив в Present Continuous: is being + третья форма.", lvl: "B2" },
    { s: "The books ___ on the shelf yesterday.", o: ["put", "were put", "was put"], a: "were put",
      ru: "Книги вчера положили на полку.",
      why: "Books — множественное число, значит were put.", lvl: "B1" },
    { s: "The problem must ___ today.", o: ["solve", "be solved", "is solved"], a: "be solved",
      ru: "Проблему нужно решить сегодня.",
      why: "После модального глагола пассив строится как be + третья форма.", lvl: "B2" },
    { s: "This picture ___ by my grandmother.", o: ["painted", "was painted", "is painting"], a: "was painted",
      ru: "Эта картина была написана моей бабушкой.",
      why: "Пассив с указанием исполнителя через by.", lvl: "B1" },
  ],

  // ================= Герундий и инфинитив =================
  "ing-to": [
    { s: "I enjoy ___ books in the evening.", o: ["read", "reading", "to read"], a: "reading",
      ru: "Я люблю читать книги по вечерам.",
      why: "После enjoy всегда идёт -ing.", lvl: "B1" },
    { s: "She decided ___ the job.", o: ["take", "taking", "to take"], a: "to take",
      ru: "Она решила взяться за эту работу.",
      why: "После decide — инфинитив с to.", lvl: "B1" },
    { s: "He is good at ___ chess.", o: ["play", "playing", "to play"], a: "playing",
      ru: "Он хорошо играет в шахматы.",
      why: "После предлога всегда -ing.", lvl: "B1" },
    { s: "They want ___ home early.", o: ["go", "going", "to go"], a: "to go",
      ru: "Они хотят пойти домой пораньше.",
      why: "После want — инфинитив с to.", lvl: "A2" },
    { s: "Stop ___ ! I cannot hear the teacher.", o: ["talk", "talking", "to talk"], a: "talking",
      ru: "Прекрати разговаривать! Я не слышу учителя.",
      why: "Stop + -ing значит «прекратить делать».", lvl: "B1" },
    { s: "Let me ___ you.", o: ["help", "helping", "to help"], a: "help",
      ru: "Позволь мне тебе помочь.",
      why: "После let и make инфинитив идёт без to.", lvl: "B1" },
    { s: "I look forward to ___ from you.", o: ["hear", "hearing", "to hear"], a: "hearing",
      ru: "Жду от тебя вестей.",
      why: "В look forward to слово to — предлог, поэтому дальше -ing.", lvl: "B2" },
    { s: "It is worth ___ this museum.", o: ["visit", "visiting", "to visit"], a: "visiting",
      ru: "Этот музей стоит посетить.",
      why: "После worth всегда -ing: worth visiting, worth trying. Инфинитив с to здесь невозможен.", lvl: "B2" },
    { s: "She promised ___ me tomorrow.", o: ["call", "calling", "to call"], a: "to call",
      ru: "Она пообещала позвонить мне завтра.",
      why: "После promise — инфинитив с to.", lvl: "B1" },
    { s: "Would you mind ___ the door?", o: ["close", "closing", "to close"], a: "closing",
      ru: "Не могли бы вы закрыть дверь?",
      why: "После mind всегда -ing. «Would you mind doing…» — вежливая просьба, дословно «вы не против сделать…».", lvl: "B1" },
    { s: "He made me ___ the whole story.", o: ["tell", "telling", "to tell"], a: "tell",
      ru: "Он заставил меня рассказать всю историю.",
      why: "После make инфинитив идёт без to.", lvl: "B2" },
    { s: "I need ___ some milk.", o: ["buy", "buying", "to buy"], a: "to buy",
      ru: "Мне нужно купить молока.",
      why: "После need — инфинитив с to.", lvl: "A2" },
  ],
};
