// Грамматика — задания с выбором варианта и разбором ошибки.
//
// Отличие от словарных упражнений: здесь проверяется не «знаешь ли слово»,
// а «понимаешь ли правило». Поэтому у каждого задания обязателен разбор:
// увидеть правильный ответ мало, ученик должен понять, ПОЧЕМУ так.
// Без этого он запомнит конкретное предложение и ошибётся в следующем.
//
// Файл грузится по требованию (ensureGrammar в js/util.js) — как словарь
// и выражения. На главной он не нужен.
//
// Поля записи:
//   s     предложение, пропуск обозначен ___
//   o     варианты ответа (первый — НЕ обязательно верный, порядок мешается)
//   a     правильный вариант (строкой, как в o)
//   ru    перевод предложения
//   why   разбор: правило человеческим языком
//   lvl   A2 | B1 | B2

const GRAMMAR_TOPICS = [
  { id: "present",    name: "Present Simple и Continuous" },
  { id: "past",       name: "Прошедшее время" },
  { id: "perfect",    name: "Present Perfect" },
  { id: "articles",   name: "Артикли" },
  { id: "preps",      name: "Предлоги" },
  { id: "compare",    name: "Степени сравнения" },
  { id: "modals",     name: "Модальные глаголы" },
  { id: "condition",  name: "Условные предложения" },
  { id: "passive",    name: "Пассивный залог" },
  { id: "ing-to",     name: "Герундий и инфинитив" },
  // Добавлено по просьбе методиста: в ОГЭ эти темы спрашивают отдельно,
  // а разбросанные по другим темам задания их не отрабатывают.
  { id: "questions",  name: "Вопросы и порядок слов" },
  { id: "reported",   name: "Косвенная речь" },
  { id: "quantity",   name: "Количество: much, many, some, any" },
  { id: "pronouns",   name: "Местоимения" },
  { id: "future",     name: "Будущее время" },
];

const GRAMMAR = {

  // ================= Present Simple vs Continuous =================
  present: [
    { s: "Look! The cat ___ on your laptop again.", o: ["sits", "is sitting", "sit"], a: "is sitting",
      ru: "Смотри! Кот снова сидит на твоём ноутбуке.",
      why: "«Look!» указывает на то, что происходит прямо сейчас — Present Continuous: is sitting.", lvl: "A2" },
    { s: "My father ___ coffee every morning.", o: ["drinks", "is drinking", "drink"], a: "drinks",
      ru: "Мой папа пьёт кофе каждое утро.",
      why: "«Every morning» — регулярное действие, Present Simple. У he/she/it добавляется -s: drinks.", lvl: "A2" },
    { s: "She ___ to music right now, so she cannot hear you.", o: ["listens", "is listening", "listen"], a: "is listening",
      ru: "Она сейчас слушает музыку, поэтому не слышит тебя.",
      why: "«Right now» — действие в момент речи, Present Continuous.", lvl: "A2" },
    { s: "Water ___ at 100 degrees.", o: ["is boiling", "boils", "boil"], a: "boils",
      ru: "Вода кипит при ста градусах.",
      why: "Факт, который верен всегда, — Present Simple.", lvl: "A2" },
    { s: "I ___ this film — it is my favourite.", o: ["am liking", "like", "likes"], a: "like",
      ru: "Мне нравится этот фильм — он мой любимый.",
      why: "Глаголы чувств (like, love, hate, want, know) в Continuous не ставятся.", lvl: "B1" },
    { s: "They usually ___ football on Sundays.", o: ["are playing", "play", "plays"], a: "play",
      ru: "Они обычно играют в футбол по воскресеньям.",
      why: "«Usually» — регулярность, Present Simple. They — без -s.", lvl: "A2" },
    { s: "Be quiet, the baby ___ .", o: ["sleeps", "is sleeping", "sleep"], a: "is sleeping",
      ru: "Потише, малыш спит.",
      why: "Действие идёт прямо сейчас — Present Continuous.", lvl: "A2" },
    { s: "___ your sister speak French?", o: ["Do", "Does", "Is"], a: "Does",
      ru: "Твоя сестра говорит по-французски?",
      why: "Вопрос в Present Simple с he/she/it строится через does.", lvl: "A2" },
    { s: "We ___ not go to school on Saturdays.", o: ["do", "does", "are"], a: "do",
      ru: "По субботам мы не ходим в школу.",
      why: "Отрицание в Present Simple с we — do not.", lvl: "A2" },
    { s: "This week I ___ at my grandmother's house.", o: ["stay", "am staying", "stays"], a: "am staying",
      ru: "На этой неделе я живу у бабушки.",
      why: "Временная ситуация, ограниченная этой неделей, — Present Continuous.", lvl: "B1" },
    { s: "He ___ the guitar very well.", o: ["is playing", "plays", "play"], a: "plays",
      ru: "Он очень хорошо играет на гитаре.",
      why: "Постоянное умение, а не действие сейчас, — Present Simple.", lvl: "A2" },
    { s: "Why ___ you laughing?", o: ["do", "are", "does"], a: "are",
      ru: "Почему ты смеёшься?",
      why: "Форма laughing требует be: are you laughing.", lvl: "A2" },

    { s: "My parents ___ in a bank.", o: ["work", "works", "are working"], a: "work",
      ru: "Мои родители работают в банке.",
      why: "Постоянный факт о жизни — Present Simple. They/we/I — без -s.", lvl: "A2" },
    { s: "Listen! Somebody ___ the piano.", o: ["plays", "is playing", "play"], a: "is playing",
      ru: "Послушай! Кто-то играет на пианино.",
      why: "«Listen!» — звучит прямо сейчас, Present Continuous.", lvl: "A2" },
    { s: "I ___ my grandmother every weekend.", o: ["visit", "am visiting", "visits"], a: "visit",
      ru: "Я навещаю бабушку каждые выходные.",
      why: "«Every weekend» — регулярность, Present Simple.", lvl: "A2" },
    { s: "She ___ a shower at the moment, call back later.", o: ["takes", "is taking", "take"], a: "is taking",
      ru: "Она сейчас в душе, перезвони позже.",
      why: "«At the moment» — в момент речи, Present Continuous.", lvl: "A2" },
    { s: "The Earth ___ around the Sun.", o: ["is going", "goes", "go"], a: "goes",
      ru: "Земля вращается вокруг Солнца.",
      why: "Законы природы — всегда Present Simple.", lvl: "A2" },
    { s: "We ___ for the bus — it is late again.", o: ["wait", "are waiting", "waits"], a: "are waiting",
      ru: "Мы ждём автобус — он опять опаздывает.",
      why: "Действие идёт прямо сейчас — Present Continuous.", lvl: "A2" },
    { s: "He never ___ meat.", o: ["eat", "eats", "is eating"], a: "eats",
      ru: "Он никогда не ест мясо.",
      why: "«Never» — привычка, Present Simple; he — с окончанием -s.", lvl: "A2" },
    { s: "___ it often snow in your city?", o: ["Does", "Is", "Do"], a: "Does",
      ru: "У вас в городе часто идёт снег?",
      why: "Вопрос о регулярном явлении: Present Simple, it — через does.", lvl: "A2" },
    { s: "Take your umbrella — it ___ .", o: ["rains", "is raining", "rain"], a: "is raining",
      ru: "Возьми зонт — идёт дождь.",
      why: "Дождь идёт в момент речи — Present Continuous.", lvl: "A2" },
    { s: "The film ___ at eight, so do not be late.", o: ["starts", "is starting", "start"], a: "starts",
      ru: "Фильм начинается в восемь, не опаздывай.",
      why: "Расписания и сеансы — Present Simple, даже про будущее.", lvl: "B1" },
    { s: "I ___ for my keys — have you seen them?", o: ["look", "am looking", "looks"], a: "am looking",
      ru: "Я ищу ключи — ты их не видел?",
      why: "Поиск идёт прямо сейчас — Present Continuous.", lvl: "A2" },
    { s: "She usually drinks tea, but today she ___ coffee.", o: ["drinks", "is drinking", "drink"], a: "is drinking",
      ru: "Обычно она пьёт чай, но сегодня пьёт кофе.",
      why: "«Today» — исключение из привычки, действие вокруг настоящего момента: Continuous.", lvl: "B1" },
    { s: "These shoes ___ too much, choose another pair.", o: ["are costing", "cost", "costs"], a: "cost",
      ru: "Эти туфли стоят слишком дорого, выбери другие.",
      why: "Cost — глагол состояния, в Continuous не ставится. These shoes — множественное число, без -s.", lvl: "B1" },
    { s: "My brother ___ for his exams this month.", o: ["prepares", "is preparing", "prepare"], a: "is preparing",
      ru: "Мой брат готовится к экзаменам в этом месяце.",
      why: "«This month» — процесс вокруг настоящего момента, Present Continuous.", lvl: "B1" },
    { s: "How often ___ you go swimming?", o: ["are", "do", "does"], a: "do",
      ru: "Как часто ты ходишь плавать?",
      why: "«How often» спрашивает о регулярности — Present Simple с do.", lvl: "A2" },
    { s: "This soup ___ delicious!", o: ["is tasting", "tastes", "taste"], a: "tastes",
      ru: "Этот суп очень вкусный!",
      why: "Taste в значении «быть на вкус» — глагол состояния, без Continuous.", lvl: "B1" },
    { s: "Tom cannot come out — he ___ chess with his brother.", o: ["plays", "is playing", "play"], a: "is playing",
      ru: "Том не может выйти — он играет с братом в шахматы.",
      why: "Занят прямо сейчас — Present Continuous.", lvl: "A2" },
    { s: "I ___ what you mean.", o: ["am seeing", "see", "sees"], a: "see",
      ru: "Я понимаю, что ты имеешь в виду.",
      why: "See в значении «понимать» — глагол состояния, Continuous невозможен.", lvl: "B1" },
    { s: "The bus ___ every ten minutes, we will not wait long.", o: ["runs", "is running", "run"], a: "runs",
      ru: "Автобус ходит каждые десять минут, долго ждать не будем.",
      why: "Расписание транспорта — Present Simple.", lvl: "B1" },
    { s: "More and more people ___ online these days.", o: ["shop", "are shopping", "shops"], a: "are shopping",
      ru: "Всё больше людей в наши дни покупают онлайн.",
      why: "Меняющаяся тенденция («all the time», «these days») — Present Continuous.", lvl: "B2" }
  ],

  // ================= Past Simple / Past Continuous =================
  past: [
    { s: "Yesterday we ___ to the cinema.", o: ["go", "went", "have gone"], a: "went",
      ru: "Вчера мы ходили в кино.",
      why: "«Yesterday» — точное время в прошлом, Past Simple. go → went.", lvl: "A2" },
    { s: "When I came in, she ___ a letter.", o: ["wrote", "was writing", "writes"], a: "was writing",
      ru: "Когда я вошёл, она писала письмо.",
      why: "Длинное действие прерывается коротким: длинное — Past Continuous.", lvl: "B1" },
    { s: "He ___ not see the sign and turned left.", o: ["did", "was", "does"], a: "did",
      ru: "Он не увидел знак и повернул налево.",
      why: "Отрицание в Past Simple — did not, дальше глагол без изменений.", lvl: "A2" },
    { s: "What ___ you do last summer?", o: ["did", "do", "were"], a: "did",
      ru: "Что ты делал прошлым летом?",
      why: "Вопрос в Past Simple строится через did.", lvl: "A2" },
    { s: "The children ___ in the garden all afternoon.", o: ["played", "were playing", "play"], a: "were playing",
      ru: "Дети играли в саду весь день.",
      why: "«All afternoon» — процесс, растянутый во времени: Past Continuous.", lvl: "B1" },
    { s: "She ___ her keys on the table and left.", o: ["put", "was putting", "puts"], a: "put",
      ru: "Она положила ключи на стол и ушла.",
      why: "Одно законченное действие за другим — Past Simple. put не меняется.", lvl: "A2" },
    { s: "It ___ heavily when we left the house.", o: ["rained", "was raining", "rains"], a: "was raining",
      ru: "Шёл сильный дождь, когда мы вышли из дома.",
      why: "Фон, на котором произошло событие, — Past Continuous.", lvl: "B1" },
    { s: "I ___ him two years ago in Moscow.", o: ["meet", "met", "have met"], a: "met",
      ru: "Я встретил его два года назад в Москве.",
      why: "«Two years ago» — точное время в прошлом, Past Simple.", lvl: "A2" },
    { s: "While she ___ , the phone rang.", o: ["cooked", "was cooking", "cooks"], a: "was cooking",
      ru: "Пока она готовила, зазвонил телефон.",
      why: "После while — длительное действие, Past Continuous.", lvl: "B1" },
    { s: "They ___ at the station at seven.", o: ["arrived", "were arriving", "arrive"], a: "arrived",
      ru: "Они прибыли на вокзал в семь.",
      why: "Точный момент — Past Simple.", lvl: "A2" },
    { s: "He was tired because he ___ all night.", o: ["worked", "had worked", "works"], a: "had worked",
      ru: "Он устал, потому что работал всю ночь.",
      why: "Действие раньше другого прошедшего — Past Perfect: had worked.", lvl: "B2" },
    { s: "I did not recognise her — she ___ her hair.", o: ["cut", "had cut", "cuts"], a: "had cut",
      ru: "Я её не узнал — она подстриглась.",
      why: "Причина случилась раньше момента в прошлом — Past Perfect.", lvl: "B2" },

    { s: "Last night I ___ a strange noise and woke up.", o: ["hear", "heard", "was hearing"], a: "heard",
      ru: "Ночью я услышал странный звук и проснулся.",
      why: "Короткое законченное событие — Past Simple: hear → heard (неправильный глагол).", lvl: "A2" },
    { s: "We ___ TV when the lights went out.", o: ["watched", "were watching", "watch"], a: "were watching",
      ru: "Мы смотрели телевизор, когда погас свет.",
      why: "Длинное действие (смотрели) прервано коротким (погас свет) — длинное в Past Continuous.", lvl: "B1" },
    { s: "She ___ born in 2010.", o: ["is", "was", "were"], a: "was",
      ru: "Она родилась в 2010 году.",
      why: "Be born — всегда в прошедшем: she was born.", lvl: "A2" },
    { s: "They ___ not at school yesterday.", o: ["was", "were", "did"], a: "were",
      ru: "Вчера их не было в школе.",
      why: "Отрицание с глаголом be: they were not. Did нужен только для обычных глаголов.", lvl: "A2" },
    { s: "He ___ his leg while he was skiing.", o: ["broke", "was breaking", "breaks"], a: "broke",
      ru: "Он сломал ногу, когда катался на лыжах.",
      why: "Короткое событие на фоне длинного: сломал — Past Simple, катался — Continuous.", lvl: "B1" },
    { s: "I ___ my homework and went for a walk.", o: ["do", "did", "was doing"], a: "did",
      ru: "Я сделал уроки и пошёл гулять.",
      why: "Цепочка законченных действий по порядку — Past Simple.", lvl: "A2" },
    { s: "Who ___ this window?", o: ["did break", "broke", "break"], a: "broke",
      ru: "Кто разбил это окно?",
      why: "Вопрос к подлежащему (кто?) строится БЕЗ did: сразу глагол в прошедшем.", lvl: "B1" },
    { s: "At six o'clock yesterday I ___ dinner with my family.", o: ["had", "was having", "have"], a: "was having",
      ru: "Вчера в шесть я ужинал с семьёй.",
      why: "Точный момент в прошлом («в шесть») — действие шло, Past Continuous.", lvl: "B1" },
    { s: "The Titanic ___ in 1912.", o: ["sank", "was sinking", "sinks"], a: "sank",
      ru: "«Титаник» затонул в 1912 году.",
      why: "Исторический факт с датой — Past Simple: sink → sank.", lvl: "B1" },
    { s: "She ___ German before she moved to Berlin.", o: ["learned", "had learned", "was learning"], a: "had learned",
      ru: "Она выучила немецкий до того, как переехала в Берлин.",
      why: "Действие ДО другого прошедшего действия — Past Perfect: had learned.", lvl: "B2" },
    { s: "When we arrived, the film ___ already started.", o: ["has", "had", "was"], a: "had",
      ru: "Когда мы пришли, фильм уже начался.",
      why: "Начался раньше, чем мы пришли, — Past Perfect: had started.", lvl: "B1" },
    { s: "I ___ not sleep well last night.", o: ["did", "was", "do"], a: "did",
      ru: "Я плохо спал этой ночью.",
      why: "Отрицание в Past Simple — did not + начальная форма.", lvl: "A2" },
    { s: "While the children ___ , their mother cooked dinner.", o: ["played", "were playing", "play"], a: "were playing",
      ru: "Пока дети играли, мама приготовила ужин.",
      why: "While — фоновое длинное действие, Past Continuous.", lvl: "B1" },
    { s: "Columbus ___ America in 1492.", o: ["discovered", "was discovering", "discovers"], a: "discovered",
      ru: "Колумб открыл Америку в 1492 году.",
      why: "Дата в прошлом — Past Simple.", lvl: "A2" },
    { s: "He told me he ___ his phone at home.", o: ["left", "had left", "leaves"], a: "had left",
      ru: "Он сказал мне, что оставил телефон дома.",
      why: "Оставил раньше, чем сказал, — Past Perfect.", lvl: "B2" },
    { s: "We ___ each other for years before we met in person.", o: ["knew", "had known", "know"], a: "had known",
      ru: "Мы знали друг друга много лет до того, как встретились вживую.",
      why: "Состояние до момента в прошлом — Past Perfect: had known.", lvl: "B2" },
    { s: "What ___ she wearing at the party?", o: ["was", "did", "were"], a: "was",
      ru: "Во что она была одета на вечеринке?",
      why: "Past Continuous: was/were + -ing. She — was.", lvl: "B1" },
    { s: "I ___ up at seven and made breakfast.", o: ["get", "got", "was getting"], a: "got",
      ru: "Я встал в семь и приготовил завтрак.",
      why: "Последовательные события — Past Simple: get → got.", lvl: "A2" },
    { s: "Ann ___ the piano for two hours yesterday.", o: ["practised", "was practising", "practises"], a: "practised",
      ru: "Вчера Аня два часа занималась на пианино.",
      why: "Законченный отрезок времени («два часа вчера») — Past Simple.", lvl: "B1" },
    { s: "The phone rang while I ___ a shower.", o: ["took", "was taking", "take"], a: "was taking",
      ru: "Телефон зазвонил, когда я был в душе.",
      why: "Звонок прервал длинное действие — оно в Past Continuous.", lvl: "B1" },
    { s: "By the time we got to the station, the train ___ .", o: ["left", "had left", "was leaving"], a: "had left",
      ru: "К тому времени, как мы добрались до вокзала, поезд уже ушёл.",
      why: "«By the time» + прошедшее — более раннее действие в Past Perfect.", lvl: "B2" }
  ],

  // ================= Present Perfect =================
  perfect: [
    { s: "I ___ never been to Japan.", o: ["have", "am", "did"], a: "have",
      ru: "Я никогда не был в Японии.",
      why: "Опыт за всю жизнь без указания времени — Present Perfect: have been.", lvl: "B1" },
    { s: "She ___ just finished her homework.", o: ["has", "have", "is"], a: "has",
      ru: "Она только что закончила домашнюю работу.",
      why: "«Just» — маркер Present Perfect. С she — has.", lvl: "B1" },
    { s: "We ___ in this town since 2019.", o: ["live", "have lived", "lived"], a: "have lived",
      ru: "Мы живём в этом городе с 2019 года.",
      why: "«Since» — действие началось в прошлом и продолжается: Present Perfect.", lvl: "B1" },
    { s: "___ you ever seen a whale?", o: ["Did", "Have", "Do"], a: "Have",
      ru: "Ты когда-нибудь видел кита?",
      why: "«Ever» в вопросе про опыт — Present Perfect.", lvl: "B1" },
    { s: "He ___ his phone yesterday.", o: ["has lost", "lost", "loses"], a: "lost",
      ru: "Он потерял телефон вчера.",
      why: "«Yesterday» — точное время в прошлом, поэтому Past Simple, а не Perfect.", lvl: "B1" },
    { s: "They have known each other ___ ten years.", o: ["since", "for", "from"], a: "for",
      ru: "Они знакомы десять лет.",
      why: "For — про длительность отрезка, since — про точку начала.", lvl: "B1" },
    { s: "I have not seen him ___ Monday.", o: ["for", "since", "during"], a: "since",
      ru: "Я не видел его с понедельника.",
      why: "Monday — точка отсчёта, поэтому since.", lvl: "B1" },
    { s: "The train ___ already left.", o: ["has", "have", "is"], a: "has",
      ru: "Поезд уже ушёл.",
      why: "«Already» — Present Perfect. The train = it, поэтому has.", lvl: "B1" },
    { s: "She ___ that film three times.", o: ["watched", "has watched", "watches"], a: "has watched",
      ru: "Она смотрела этот фильм три раза.",
      why: "Счёт повторов к настоящему моменту — Present Perfect.", lvl: "B1" },
    { s: "___ you finished yet?", o: ["Have", "Did", "Are"], a: "Have",
      ru: "Ты уже закончил?",
      why: "«Yet» в вопросе — Present Perfect.", lvl: "B1" },
    { s: "This is the best book I ___ ever read.", o: ["have", "did", "am"], a: "have",
      ru: "Это лучшая книга, которую я когда-либо читал.",
      why: "После превосходной степени с ever — Present Perfect.", lvl: "B2" },
    { s: "How long ___ she worked here?", o: ["did", "has", "does"], a: "has",
      ru: "Как долго она здесь работает?",
      why: "«How long» про период до настоящего — Present Perfect.", lvl: "B1" },

    { s: "We ___ already bought the tickets, so we can go in.", o: ["have", "has", "had"], a: "have",
      ru: "Мы уже купили билеты, так что можем заходить.",
      why: "Результат к настоящему моменту — Present Perfect: we have bought.", lvl: "A2" },
    { s: "I ___ my keys — I cannot open the door.", o: ["lost", "have lost", "lose"], a: "have lost",
      ru: "Я потерял ключи — не могу открыть дверь.",
      why: "Важен результат сейчас (дверь не открыть) — Present Perfect.", lvl: "B1" },
    { s: "She has lived here ___ she was a child.", o: ["for", "since", "from"], a: "since",
      ru: "Она живёт здесь с детства.",
      why: "Since — точка отсчёта (с какого момента), for — длительность.", lvl: "B1" },
    { s: "___ you done your homework yet?", o: ["Have", "Did", "Do"], a: "Have",
      ru: "Ты уже сделал домашку?",
      why: "Yet в вопросе — спутник Present Perfect: Have you done?", lvl: "A2" },
    { s: "He has worked at this school ___ twenty years.", o: ["since", "for", "during"], a: "for",
      ru: "Он работает в этой школе двадцать лет.",
      why: "For + отрезок времени (сколько), since + точка (с когда).", lvl: "A2" },
    { s: "I ___ him last week.", o: ["have seen", "saw", "see"], a: "saw",
      ru: "Я видел его на прошлой неделе.",
      why: "«Last week» — законченное время, поэтому Past Simple, а не Present Perfect.", lvl: "B1" },
    { s: "This is the first time I ___ sushi.", o: ["try", "have tried", "tried"], a: "have tried",
      ru: "Я впервые пробую суши.",
      why: "«The first time» — конструкция с Present Perfect: первый раз в жизни к этому моменту.", lvl: "B1" },
    { s: "They ___ just come back from holiday.", o: ["have", "has", "are"], a: "have",
      ru: "Они только что вернулись из отпуска.",
      why: "Just + Present Perfect: have just come.", lvl: "A2" },
    { s: "We have been friends ___ 2015.", o: ["for", "since", "in"], a: "since",
      ru: "Мы дружим с 2015 года.",
      why: "Год — это точка отсчёта, значит since.", lvl: "A2" },
    { s: "She ___ her project an hour ago.", o: ["has finished", "finished", "finishes"], a: "finished",
      ru: "Она закончила проект час назад.",
      why: "Ago — всегда Past Simple: указано, когда именно.", lvl: "B1" },
    { s: "I have never ___ such a tall building.", o: ["saw", "seen", "see"], a: "seen",
      ru: "Я никогда не видел такого высокого здания.",
      why: "Present Perfect = have + третья форма: see — saw — seen.", lvl: "A2" },
    { s: "How many countries ___ you visited?", o: ["did", "have", "do"], a: "have",
      ru: "Сколько стран ты посетил?",
      why: "Опыт за всю жизнь к настоящему моменту — Present Perfect.", lvl: "A2" },
    { s: "He ___ in three school plays so far.", o: ["acted", "has acted", "acts"], a: "has acted",
      ru: "Он сыграл уже в трёх школьных спектаклях.",
      why: "«So far» (на данный момент) — спутник Present Perfect.", lvl: "B2" },
    { s: "Somebody ___ my sandwich! It was here a minute ago.", o: ["ate", "has eaten", "eats"], a: "has eaten",
      ru: "Кто-то съел мой бутерброд! Он только что был здесь.",
      why: "Видим результат (бутерброда нет) — Present Perfect.", lvl: "B1" },
    { s: "I ___ my grandparents last summer.", o: ["have visited", "visited", "visit"], a: "visited",
      ru: "Прошлым летом я гостил у бабушки с дедушкой.",
      why: "«Last summer» закончилось — Past Simple.", lvl: "B1" },
    { s: "The lesson ___ not started yet.", o: ["has", "have", "is"], a: "has",
      ru: "Урок ещё не начался.",
      why: "Yet в отрицании — Present Perfect; the lesson (it) — has.", lvl: "A2" },
    { s: "We ___ each other since primary school.", o: ["knew", "have known", "know"], a: "have known",
      ru: "Мы знакомы с начальной школы.",
      why: "Since тянет действие из прошлого в настоящее — Present Perfect.", lvl: "B1" },
    { s: "___ she ever won a prize?", o: ["Did", "Has", "Have"], a: "Has",
      ru: "Она когда-нибудь выигрывала приз?",
      why: "Ever (когда-нибудь в жизни) — Present Perfect; she — has.", lvl: "A2" },
    { s: "It is the most interesting book I ___ read this year.", o: ["have", "has", "had"], a: "have",
      ru: "Это самая интересная книга, которую я прочитал в этом году.",
      why: "После превосходной степени об опыте — Present Perfect: I have read.", lvl: "B1" },
    { s: "I cannot find my glasses. ___ you seen them?", o: ["Did", "Have", "Do"], a: "Have",
      ru: "Не могу найти очки. Ты их не видел?",
      why: "Результат важен сейчас (очков нет) — Present Perfect.", lvl: "A2" }
  ],

  // ================= Артикли =================
  articles: [
    { s: "I saw ___ interesting film last night.", o: ["a", "an", "the"], a: "an",
      ru: "Вчера вечером я посмотрел интересный фильм.",
      why: "Перед гласным звуком — an: an interesting film.", lvl: "A2" },
    { s: "___ sun rises in the east.", o: ["A", "An", "The"], a: "The",
      ru: "Солнце встаёт на востоке.",
      why: "Предмет единственный в своём роде — the.", lvl: "A2" },
    { s: "She is ___ teacher at our school.", o: ["a", "an", "the"], a: "a",
      ru: "Она учительница в нашей школе.",
      why: "Профессия называется с a/an. Перед согласным звуком — a.", lvl: "A2" },
    { s: "We had ___ dinner at seven.", o: ["a", "the", "—"], a: "—",
      ru: "Мы поужинали в семь.",
      why: "Названия приёмов пищи идут без артикля: have dinner.", lvl: "B1" },
    { s: "He plays ___ piano very well.", o: ["a", "the", "—"], a: "the",
      ru: "Он очень хорошо играет на пианино.",
      why: "С музыкальными инструментами ставится the: play the piano.", lvl: "B1" },
    { s: "___ Volga is the longest river in Europe.", o: ["A", "The", "—"], a: "The",
      ru: "Волга — самая длинная река в Европе.",
      why: "С названиями рек употребляется the.", lvl: "B1" },
    { s: "I go to ___ school by bus.", o: ["a", "the", "—"], a: "—",
      ru: "Я езжу в школу на автобусе.",
      why: "Когда говорим о школе как о занятии, а не о здании, артикля нет.", lvl: "B1" },
    { s: "Give me ___ book on the table, please.", o: ["a", "an", "the"], a: "the",
      ru: "Дай мне книгу, которая на столе, пожалуйста.",
      why: "Собеседник понимает, о какой книге речь, — the.", lvl: "A2" },
    { s: "She wants to be ___ engineer.", o: ["a", "an", "the"], a: "an",
      ru: "Она хочет быть инженером.",
      why: "Перед гласным звуком — an: an engineer.", lvl: "A2" },
    { s: "___ life is short.", o: ["A", "The", "—"], a: "—",
      ru: "Жизнь коротка.",
      why: "Абстрактное понятие в общем смысле — без артикля.", lvl: "B2" },
    { s: "This is ___ most difficult question.", o: ["a", "the", "—"], a: "the",
      ru: "Это самый сложный вопрос.",
      why: "Перед превосходной степенью всегда the.", lvl: "A2" },
    { s: "We visited ___ United Kingdom last year.", o: ["a", "the", "—"], a: "the",
      ru: "В прошлом году мы побывали в Соединённом Королевстве.",
      why: "Названия стран со словами Kingdom, States, Republic идут с the.", lvl: "B1" },

    { s: "My mother is ___ doctor.", o: ["a", "an", "the"], a: "a",
      ru: "Моя мама — врач.",
      why: "Профессия в единственном числе — с артиклем a.", lvl: "A2" },
    { s: "We swam in ___ Black Sea.", o: ["a", "the", "—"], a: "the",
      ru: "Мы купались в Чёрном море.",
      why: "Моря, океаны и реки — всегда с the: the Black Sea.", lvl: "A2" },
    { s: "I usually have ___ breakfast at eight.", o: ["a", "the", "—"], a: "—",
      ru: "Я обычно завтракаю в восемь.",
      why: "Приёмы пищи (breakfast, lunch, dinner) — без артикля.", lvl: "A2" },
    { s: "There is ___ apple on the plate.", o: ["a", "an", "the"], a: "an",
      ru: "На тарелке лежит яблоко.",
      why: "Apple начинается с гласного ЗВУКА — значит an.", lvl: "A2" },
    { s: "The Moon goes around ___ Earth.", o: ["a", "the", "—"], a: "the",
      ru: "Луна вращается вокруг Земли.",
      why: "Единственные в своём роде объекты (the Sun, the Earth, the Moon) — с the.", lvl: "A2" },
    { s: "He watches TV in ___ evening.", o: ["a", "the", "—"], a: "the",
      ru: "Он смотрит телевизор по вечерам.",
      why: "Устойчиво: in the morning / in the evening / in the afternoon.", lvl: "A2" },
    { s: "She goes to ___ bed at ten.", o: ["a", "the", "—"], a: "—",
      ru: "Она ложится спать в десять.",
      why: "Go to bed / go to school «по назначению» — без артикля.", lvl: "B1" },
    { s: "It was ___ unusual story.", o: ["a", "an", "the"], a: "an",
      ru: "Это была необычная история.",
      why: "Смотрим на ЗВУК следующего слова: unusual начинается с гласного звука — an.", lvl: "B1" },
    { s: "We went skiing in ___ Alps.", o: ["a", "the", "—"], a: "the",
      ru: "Мы катались на лыжах в Альпах.",
      why: "Горные ЦЕПИ — с the (the Alps), одиночные горы — без (Elbrus).", lvl: "B1" },
    { s: "There is ___ university near my house.", o: ["a", "an", "the"], a: "a",
      ru: "Рядом с моим домом есть университет.",
      why: "University начинается со звука [ю] — это согласный звук, поэтому a.", lvl: "B1" },
    { s: "What ___ beautiful day!", o: ["a", "an", "the"], a: "a",
      ru: "Какой прекрасный день!",
      why: "Восклицание What a + прилагательное + существительное.", lvl: "A2" },
    { s: "He is ___ best player in our team.", o: ["a", "the", "—"], a: "the",
      ru: "Он лучший игрок нашей команды.",
      why: "Превосходная степень — всегда с the: the best.", lvl: "A2" },
    { s: "We travelled around ___ Europe last year.", o: ["a", "the", "—"], a: "—",
      ru: "В прошлом году мы путешествовали по Европе.",
      why: "Континенты и большинство стран — без артикля.", lvl: "B1" },
    { s: "Can you pass me ___ salt, please?", o: ["a", "the", "—"], a: "the",
      ru: "Передай, пожалуйста, соль.",
      why: "Оба понимают, о какой соли речь (вот эта, на столе) — the.", lvl: "B1" },
    { s: "She plays ___ violin in the school orchestra.", o: ["a", "the", "—"], a: "the",
      ru: "Она играет на скрипке в школьном оркестре.",
      why: "Play + the + музыкальный инструмент: play the violin.", lvl: "A2" },
    { s: "They live on ___ fifth floor.", o: ["a", "the", "—"], a: "the",
      ru: "Они живут на пятом этаже.",
      why: "Порядковые числительные (first, second, fifth) — с the.", lvl: "A2" },
    { s: "I read for ___ hour every day.", o: ["a", "an", "the"], a: "an",
      ru: "Я читаю по часу каждый день.",
      why: "В hour буква h не читается, слово начинается с гласного звука — an hour.", lvl: "B1" },
    { s: "___ honesty is the best policy.", o: ["An", "The", "—"], a: "—",
      ru: "Честность — лучшая политика.",
      why: "Абстрактные понятия в общем смысле (honesty, love, music) — без артикля.", lvl: "B2" },
    { s: "Lake Baikal is ___ deepest lake in the world.", o: ["a", "the", "—"], a: "the",
      ru: "Байкал — самое глубокое озеро в мире.",
      why: "Превосходная степень: the deepest.", lvl: "A2" },
    { s: "He was ___ only person who helped me.", o: ["an", "the", "—"], a: "the",
      ru: "Он был единственным, кто мне помог.",
      why: "Only в значении «единственный» — с the: the only person.", lvl: "B1" }
  ],

  // ================= Предлоги =================
  preps: [
    { s: "The lesson starts ___ nine o'clock.", o: ["in", "on", "at"], a: "at",
      ru: "Урок начинается в девять часов.",
      why: "С точным временем — at: at nine o'clock.", lvl: "A2" },
    { s: "My birthday is ___ July.", o: ["in", "on", "at"], a: "in",
      ru: "Мой день рождения в июле.",
      why: "С месяцами и годами — in.", lvl: "A2" },
    { s: "We meet ___ Monday morning.", o: ["in", "on", "at"], a: "on",
      ru: "Мы встречаемся в понедельник утром.",
      why: "С днями недели и датами — on.", lvl: "A2" },
    { s: "The book is ___ the table.", o: ["in", "on", "at"], a: "on",
      ru: "Книга на столе.",
      why: "Предмет лежит НА поверхности — on. Внутри чего-то было бы in.", lvl: "A2" },
    { s: "She is waiting ___ the bus stop.", o: ["in", "on", "at"], a: "at",
      ru: "Она ждёт на автобусной остановке.",
      why: "Точка на карте, место встречи — at.", lvl: "A2" },
    { s: "There is milk ___ the fridge.", o: ["in", "on", "at"], a: "in",
      ru: "Молоко в холодильнике.",
      why: "Внутри замкнутого пространства — in.", lvl: "A2" },
    { s: "I am afraid ___ spiders.", o: ["of", "from", "for"], a: "of",
      ru: "Я боюсь пауков.",
      why: "Устойчивое сочетание: be afraid of.", lvl: "B1" },
    { s: "This present is ___ you.", o: ["to", "for", "at"], a: "for",
      ru: "Этот подарок для тебя.",
      why: "Кому предназначено — for.", lvl: "A2" },
    { s: "He is good ___ mathematics.", o: ["in", "at", "on"], a: "at",
      ru: "Он хорош в математике.",
      why: "Устойчивое сочетание: be good at.", lvl: "B1" },
    { s: "We arrived ___ the airport late.", o: ["to", "at", "in"], a: "at",
      ru: "Мы поздно приехали в аэропорт.",
      why: "Arrive at — для зданий и точек; arrive in — для городов и стран.", lvl: "B1" },
    { s: "She depends ___ her parents.", o: ["from", "of", "on"], a: "on",
      ru: "Она зависит от родителей.",
      why: "Устойчивое сочетание: depend on.", lvl: "B2" },
    { s: "Thank you ___ your help.", o: ["for", "of", "to"], a: "for",
      ru: "Спасибо за твою помощь.",
      why: "Устойчивое сочетание: thank you for.", lvl: "A2" },

    { s: "The concert is ___ Friday evening.", o: ["in", "on", "at"], a: "on",
      ru: "Концерт в пятницу вечером.",
      why: "Дни недели (и день + часть суток) — предлог on: on Friday evening.", lvl: "A2" },
    { s: "She has lived in this town ___ 2020.", o: ["for", "since", "from"], a: "since",
      ru: "Она живёт в этом городе с 2020 года.",
      why: "Точка отсчёта (год) — since.", lvl: "B1" },
    { s: "We went to the seaside ___ summer.", o: ["on", "in", "at"], a: "in",
      ru: "Летом мы ездили на море.",
      why: "Времена года, месяцы, годы — предлог in.", lvl: "A2" },
    { s: "The picture is hanging ___ the wall.", o: ["in", "on", "at"], a: "on",
      ru: "Картина висит на стене.",
      why: "На поверхности — on: on the wall.", lvl: "A2" },
    { s: "He jumped ___ the cold water.", o: ["in", "into", "on"], a: "into",
      ru: "Он прыгнул в холодную воду.",
      why: "Движение ВНУТРЬ — into. In — уже внутри, без движения.", lvl: "B1" },
    { s: "I have lessons ___ weekdays.", o: ["in", "on", "at"], a: "on",
      ru: "По будням у меня уроки.",
      why: "On weekdays, on Mondays — дни с предлогом on.", lvl: "A2" },
    { s: "The cat is hiding ___ the sofa.", o: ["under", "at", "between"], a: "under",
      ru: "Кот прячется под диваном.",
      why: "Under — под чем-то.", lvl: "A2" },
    { s: "We walked ___ the forest to the lake.", o: ["through", "across", "over"], a: "through",
      ru: "Мы шли через лес к озеру.",
      why: "Сквозь пространство с деревьями вокруг — through. Across — поперёк открытой поверхности.", lvl: "B1" },
    { s: "She is married ___ a pilot.", o: ["with", "to", "on"], a: "to",
      ru: "Она замужем за лётчиком.",
      why: "Be married TO — устойчивое сочетание, «married with» — частая русская калька.", lvl: "B2" },
    { s: "Everything depends ___ the weather.", o: ["from", "of", "on"], a: "on",
      ru: "Всё зависит от погоды.",
      why: "Depend ON — не from! Русское «зависеть от» здесь обманывает.", lvl: "B1" },
    { s: "I am proud ___ my school.", o: ["of", "for", "about"], a: "of",
      ru: "Я горжусь своей школой.",
      why: "Be proud OF — гордиться чем-то.", lvl: "B1" },
    { s: "He is interested ___ history.", o: ["in", "at", "about"], a: "in",
      ru: "Он интересуется историей.",
      why: "Be interested IN — устойчивое сочетание.", lvl: "A2" },
    { s: "We waited ___ the rain to stop.", o: ["for", "of", "to"], a: "for",
      ru: "Мы ждали, когда закончится дождь.",
      why: "Wait FOR — ждать кого-то или что-то.", lvl: "B1" },
    { s: "The bakery is ___ the bank and the café.", o: ["among", "between", "in"], a: "between",
      ru: "Булочная — между банком и кафе.",
      why: "Between — между ДВУМЯ, among — среди многих.", lvl: "A2" },
    { s: "She was late ___ the first lesson.", o: ["to", "for", "on"], a: "for",
      ru: "Она опоздала на первый урок.",
      why: "Be late FOR — опоздать на что-то.", lvl: "A2" },
    { s: "The book is quite different ___ the film.", o: ["of", "from", "with"], a: "from",
      ru: "Книга сильно отличается от фильма.",
      why: "Different FROM — отличаться от.", lvl: "B1" },
    { s: "I completely agree ___ you.", o: ["to", "with", "of"], a: "with",
      ru: "Я полностью с тобой согласен.",
      why: "Agree WITH somebody — соглашаться с кем-то.", lvl: "A2" },
    { s: "He spends a lot of money ___ computer games.", o: ["for", "on", "to"], a: "on",
      ru: "Он тратит много денег на компьютерные игры.",
      why: "Spend money ON something — тратить НА.", lvl: "B1" },
    { s: "The plane flew ___ the mountains.", o: ["over", "on", "above of"], a: "over",
      ru: "Самолёт пролетел над горами.",
      why: "Over — над, с движением поверх.", lvl: "B1" },
    { s: "Cut the pizza ___ eight pieces.", o: ["on", "into", "at"], a: "into",
      ru: "Разрежь пиццу на восемь кусков.",
      why: "Divide/cut INTO pieces — деление на части.", lvl: "B2" }
  ],

  // ================= Степени сравнения =================
  compare: [
    { s: "This box is ___ than that one.", o: ["heavy", "heavier", "heaviest"], a: "heavier",
      ru: "Эта коробка тяжелее той.",
      why: "Сравнение двух предметов — сравнительная степень. Короткое слово: heavy → heavier.", lvl: "A2" },
    { s: "He is the ___ boy in the class.", o: ["tall", "taller", "tallest"], a: "tallest",
      ru: "Он самый высокий мальчик в классе.",
      why: "«In the class» — сравнение со всей группой, превосходная степень.", lvl: "A2" },
    { s: "This task is ___ difficult than the last one.", o: ["more", "most", "much"], a: "more",
      ru: "Это задание сложнее предыдущего.",
      why: "Длинные прилагательные сравниваются через more.", lvl: "A2" },
    { s: "Your idea is ___ than mine.", o: ["gooder", "better", "best"], a: "better",
      ru: "Твоя идея лучше моей.",
      why: "good → better → best, форма неправильная.", lvl: "A2" },
    { s: "Today is ___ day of the year.", o: ["the hotter", "the hottest", "hotter"], a: "the hottest",
      ru: "Сегодня самый жаркий день в году.",
      why: "Превосходная степень с the, согласная удваивается: hottest.", lvl: "B1" },
    { s: "She sings ___ than her sister.", o: ["good", "better", "well"], a: "better",
      ru: "Она поёт лучше сестры.",
      why: "Сравнивается действие: well → better.", lvl: "B1" },
    { s: "This film is not ___ interesting as the book.", o: ["so", "as", "more"], a: "as",
      ru: "Этот фильм не такой интересный, как книга.",
      why: "Конструкция равенства: as … as.", lvl: "B1" },
    { s: "The ___ you start, the sooner you finish.", o: ["early", "earlier", "earliest"], a: "earlier",
      ru: "Чем раньше начнёшь, тем скорее закончишь.",
      why: "Конструкция «the … the …» требует сравнительной степени.", lvl: "B2" },
    { s: "My room is ___ smaller than yours.", o: ["very", "much", "more"], a: "much",
      ru: "Моя комната намного меньше твоей.",
      why: "Сравнительную степень усиливают much, far, a lot — но не very.", lvl: "B2" },
    { s: "It was the ___ film I have ever seen.", o: ["worse", "worst", "bad"], a: "worst",
      ru: "Это был худший фильм, который я когда-либо видел.",
      why: "bad → worse → worst — форма неправильная, запоминается наизусть. Здесь превосходная степень, поэтому worst.", lvl: "B1" },
    { s: "This road is ___ than that one.", o: ["more narrow", "narrower", "narrowest"], a: "narrower",
      ru: "Эта дорога уже той.",
      why: "Двусложные на -ow сравниваются через -er: narrower.", lvl: "B2" },
    { s: "He runs ___ of all the boys.", o: ["faster", "fastest", "the fastest"], a: "the fastest",
      ru: "Он бегает быстрее всех мальчиков.",
      why: "«Of all» — превосходная степень, с the.", lvl: "B1" },

    { s: "February is ___ than January.", o: ["short", "shorter", "the shortest"], a: "shorter",
      ru: "Февраль короче января.",
      why: "Сравниваем два месяца — сравнительная степень с than: shorter.", lvl: "A2" },
    { s: "This is ___ house in our street.", o: ["older", "the oldest", "old"], a: "the oldest",
      ru: "Это самый старый дом на нашей улице.",
      why: "Один из всех на улице — превосходная степень с the: the oldest.", lvl: "A2" },
    { s: "Maths is ___ for me than PE.", o: ["difficult", "more difficult", "the most difficult"], a: "more difficult",
      ru: "Математика для меня труднее физкультуры.",
      why: "Длинные прилагательные сравниваются через more: more difficult.", lvl: "A2" },
    { s: "Her marks are ___ than mine.", o: ["gooder", "better", "more good"], a: "better",
      ru: "Её оценки лучше моих.",
      why: "Good — исключение: good → better → the best.", lvl: "A2" },
    { s: "Forgetting your ticket is ___ mistake you could make.", o: ["worse", "the worst", "bad"], a: "the worst",
      ru: "Забыть билет — худшая ошибка, какую можно совершить.",
      why: "Bad — исключение: bad → worse → the worst.", lvl: "B1" },
    { s: "The test was ___ easier than I expected.", o: ["much", "very", "more"], a: "much",
      ru: "Тест оказался гораздо легче, чем я ожидал.",
      why: "Усилить сравнение можно словами much / far / a lot, но не very.", lvl: "B1" },
    { s: "He is as ___ as his father.", o: ["tall", "taller", "tallest"], a: "tall",
      ru: "Он такой же высокий, как его папа.",
      why: "As … as — «такой же, как»: внутри обычная форма без -er.", lvl: "A2" },
    { s: "It is getting ___ every day.", o: ["cold", "colder", "the coldest"], a: "colder",
      ru: "С каждым днём становится холоднее.",
      why: "Изменение «всё холоднее» — сравнительная степень: getting colder.", lvl: "A2" },
    { s: "This street is ___ than ours.", o: ["noisier", "more noisy", "noisiest"], a: "noisier",
      ru: "Эта улица более шумная, чем наша.",
      why: "Двусложные на -y меняют её на -i: noisy → noisier.", lvl: "B1" },
    { s: "Tom is two years ___ than me.", o: ["elder", "older", "more old"], a: "older",
      ru: "Том на два года старше меня.",
      why: "С than используется older; elder — только перед словом (elder brother) и без than.", lvl: "B1" },
    { s: "It was ___ far the best concert of the year.", o: ["by", "so", "much"], a: "by",
      ru: "Это был безусловно лучший концерт года.",
      why: "By far + превосходная степень — «безусловно, намного»: by far the best.", lvl: "B2" },
    { s: "The more you practise, ___ you play.", o: ["better", "the better", "the best"], a: "the better",
      ru: "Чем больше занимаешься, тем лучше играешь.",
      why: "Конструкция «чем …, тем …»: the more …, the better ….", lvl: "B1" },
    { s: "This is ___ expensive phone in the shop — take it if you want to save money.", o: ["the least", "the most", "less"], a: "the least",
      ru: "Это самый недорогой телефон в магазине — бери, если хочешь сэкономить.",
      why: "The least — «наименее», противоположность the most.", lvl: "B1" },
    { s: "Silver is ___ than gold.", o: ["cheap", "cheaper", "the cheapest"], a: "cheaper",
      ru: "Серебро дешевле золота.",
      why: "Короткое прилагательное + than — сравнительная на -er.", lvl: "A2" },
    { s: "My bag is not ___ heavy as yours.", o: ["so", "as", "than"], a: "as",
      ru: "Моя сумка не такая тяжёлая, как твоя.",
      why: "Not as … as — «не такой …, как». Вторая часть пары всегда as.", lvl: "B1" },
    { s: "He speaks English ___ than I do.", o: ["fluently", "more fluently", "most fluently"], a: "more fluently",
      ru: "Он говорит по-английски свободнее, чем я.",
      why: "Наречия на -ly сравниваются через more: more fluently.", lvl: "B2" },
    { s: "It was one of ___ days of my life.", o: ["the happiest", "happier", "the most happy"], a: "the happiest",
      ru: "Это был один из счастливейших дней моей жизни.",
      why: "One of + превосходная степень: happy → the happiest (y → i).", lvl: "B1" },
    { s: "The exam was ___ difficult than we had feared.", o: ["least", "less", "little"], a: "less",
      ru: "Экзамен оказался менее сложным, чем мы боялись.",
      why: "Less + прилагательное + than — «менее … чем».", lvl: "B2" },
    { s: "Trains here run ___ often than buses.", o: ["more", "many", "much"], a: "more",
      ru: "Поезда здесь ходят чаще автобусов.",
      why: "Сравнение наречия often — через more: more often.", lvl: "B1" },
    { s: "Her hair is ___ than her sister's.", o: ["longer", "more long", "the longest"], a: "longer",
      ru: "У неё волосы длиннее, чем у сестры.",
      why: "Короткое прилагательное — сравнительная на -er: longer.", lvl: "A2" }
  ],

  // ================= Модальные глаголы =================
  modals: [
    { s: "You ___ wear a helmet — it is the rule.", o: ["can", "must", "may"], a: "must",
      ru: "Ты обязан надеть шлем — это правило.",
      why: "Обязанность, которая идёт от правила, — must.", lvl: "A2" },
    { s: "___ I open the window?", o: ["May", "Must", "Should"], a: "May",
      ru: "Можно я открою окно?",
      why: "Вежливая просьба разрешить — may (в разговорной речи ещё can).", lvl: "A2" },
    { s: "She ___ swim when she was five.", o: ["can", "could", "must"], a: "could",
      ru: "Она умела плавать в пять лет.",
      why: "Умение в прошлом — could.", lvl: "A2" },
    { s: "You ___ see a doctor, you look pale.", o: ["should", "must not", "can"], a: "should",
      ru: "Тебе стоит сходить к врачу, ты бледный.",
      why: "Совет, а не приказ, — should. Must значило бы «обязан», а тут просто рекомендация.", lvl: "A2" },
    { s: "We ___ hurry, we have plenty of time.", o: ["must not", "do not have to", "should not"], a: "do not have to",
      ru: "Нам не нужно спешить, у нас полно времени.",
      why: "Отсутствие необходимости — do not have to. Must not значит «нельзя».", lvl: "B1" },
    { s: "You ___ smoke here — it is a hospital.", o: ["must not", "do not have to", "need not"], a: "must not",
      ru: "Здесь нельзя курить — это больница.",
      why: "Строгий запрет — must not.", lvl: "B1" },
    { s: "___ you help me with this box?", o: ["Could", "Must", "Should"], a: "Could",
      ru: "Не мог бы ты помочь мне с этой коробкой?",
      why: "Вежливая просьба — could.", lvl: "A2" },
    { s: "He ___ be at home, his car is outside.", o: ["must", "can", "should"], a: "must",
      ru: "Он, должно быть, дома — его машина у подъезда.",
      why: "Уверенное предположение — must.", lvl: "B2" },
    { s: "It ___ rain later, take an umbrella.", o: ["must", "might", "should"], a: "might",
      ru: "Позже может пойти дождь, возьми зонт.",
      why: "Неуверенное предположение — might или may.", lvl: "B1" },
    { s: "I ___ to finish this today.", o: ["must", "have", "can"], a: "have",
      ru: "Я должен закончить это сегодня.",
      why: "Перед to может стоять только have: have to finish.", lvl: "B1" },
    { s: "You ___ have told me earlier!", o: ["should", "must", "can"], a: "should",
      ru: "Тебе следовало сказать мне раньше!",
      why: "Упрёк о прошлом — should have + третья форма.", lvl: "B2" },
    { s: "Students ___ use dictionaries during the test.", o: ["are not allowed to", "must not to", "do not must"], a: "are not allowed to",
      ru: "Ученикам не разрешается пользоваться словарями во время теста.",
      why: "«Не разрешено» — be allowed to. После must частица to не ставится.", lvl: "B2" },

    { s: "You ___ cross the street at a red light.", o: ["must not", "need not", "may not"], a: "must not",
      ru: "Нельзя переходить улицу на красный свет.",
      why: "Строгий запрет — must not.", lvl: "A2" },
    { s: "___ you speak any foreign languages?", o: ["Can", "Must", "Should"], a: "Can",
      ru: "Ты говоришь на каких-нибудь иностранных языках?",
      why: "Умение, способность — can.", lvl: "A2" },
    { s: "You ___ come if you do not want to.", o: ["must not", "do not have to", "cannot"], a: "do not have to",
      ru: "Можешь не приходить, если не хочешь.",
      why: "Отсутствие обязанности — do not have to. Must not — запрет, это другое.", lvl: "B1" },
    { s: "He ___ be hungry — he has just had lunch.", o: ["must not", "cannot", "should not"], a: "cannot",
      ru: "Не может быть, чтобы он был голоден — он только что пообедал.",
      why: "Уверенное «не может быть» — cannot (can't). Must not здесь не работает.", lvl: "B1" },
    { s: "We ___ wear a uniform at our school.", o: ["have to", "can", "may"], a: "have to",
      ru: "У нас в школе обязательна форма.",
      why: "Обязанность по внешнему правилу — have to.", lvl: "A2" },
    { s: "You ___ take my umbrella, I do not need it.", o: ["can", "must", "have to"], a: "can",
      ru: "Можешь взять мой зонт, мне он не нужен.",
      why: "Разрешение — can.", lvl: "A2" },
    { s: "I ___ ride a bike when I was four.", o: ["can", "could", "may"], a: "could",
      ru: "В четыре года я умел кататься на велосипеде.",
      why: "Умение в прошлом — could.", lvl: "A2" },
    { s: "You look tired. You ___ go to bed.", o: ["should", "can", "may"], a: "should",
      ru: "Ты выглядишь уставшим. Тебе стоит лечь спать.",
      why: "Совет — should.", lvl: "A2" },
    { s: "___ I borrow your pen, please?", o: ["May", "Must", "Should"], a: "May",
      ru: "Можно взять твою ручку?",
      why: "Вежливая просьба о разрешении — May I …?", lvl: "A2" },
    { s: "They ___ win — they are playing really well today.", o: ["might", "must not", "need"], a: "might",
      ru: "Они могут и выиграть — сегодня они играют очень хорошо.",
      why: "Предположение «возможно» — might.", lvl: "B1" },
    { s: "You ___ be joking!", o: ["must", "should", "need"], a: "must",
      ru: "Ты, должно быть, шутишь!",
      why: "Уверенный вывод — must: «наверняка, должно быть».", lvl: "B1" },
    { s: "Pupils ___ not use phones during lessons.", o: ["must", "need", "have"], a: "must",
      ru: "Ученикам нельзя пользоваться телефонами на уроках.",
      why: "Запрет правилом — must not.", lvl: "B1" },
    { s: "He ___ play chess at all two years ago, and now he wins prizes.", o: ["could not", "must not", "may not"], a: "could not",
      ru: "Два года назад он совсем не умел играть в шахматы, а теперь берёт призы.",
      why: "Неумение в прошлом — could not.", lvl: "B1" },
    { s: "You ___ water the cactus every day — once a month is enough.", o: ["need not", "must not", "cannot"], a: "need not",
      ru: "Кактус не обязательно поливать каждый день — раза в месяц хватит.",
      why: "«Не обязательно» — need not (= do not have to). Must not запрещал бы поливать вовсе.", lvl: "B2" },
    { s: "___ you pass me the salt, please?", o: ["Could", "Must", "Need"], a: "Could",
      ru: "Не передашь соль, пожалуйста?",
      why: "Вежливая просьба — Could you …?", lvl: "A2" },
    { s: "It is late. We ___ better go home.", o: ["had", "would", "should"], a: "had",
      ru: "Уже поздно. Нам бы лучше пойти домой.",
      why: "Устойчивое had better + глагол — настойчивый совет.", lvl: "B2" },
    { s: "She ___ have missed the bus — that is why she is late.", o: ["must", "should", "need"], a: "must",
      ru: "Она, наверное, опоздала на автобус — вот почему её нет.",
      why: "Уверенная догадка о прошлом — must have + третья форма.", lvl: "B2" },
    { s: "You ___ have seen him yesterday — he was abroad.", o: ["must not", "cannot", "need not"], a: "cannot",
      ru: "Ты не мог видеть его вчера — он был за границей.",
      why: "«Не может быть, что это было» — cannot have + третья форма.", lvl: "B2" },
    { s: "Visitors ___ leave their coats in the cloakroom.", o: ["should", "might", "could"], a: "should",
      ru: "Посетителям следует оставлять верхнюю одежду в гардеробе.",
      why: "Рекомендация-правило — should.", lvl: "B1" },
    { s: "I ___ swim very well yet, but I am learning.", o: ["cannot", "must not", "may not"], a: "cannot",
      ru: "Я пока не очень хорошо плаваю, но учусь.",
      why: "Отсутствие умения — cannot.", lvl: "A2" }
  ],

  // ================= Условные предложения =================
  condition: [
    { s: "If you heat ice, it ___ .", o: ["melts", "will melt", "would melt"], a: "melts",
      ru: "Если нагреть лёд, он тает.",
      why: "Нулевое условие: всегда верный факт — Present Simple в обеих частях.", lvl: "B1" },
    { s: "If it rains tomorrow, we ___ at home.", o: ["stay", "will stay", "would stay"], a: "will stay",
      ru: "Если завтра пойдёт дождь, мы останемся дома.",
      why: "Первое условие: реальное будущее — if + Present, главная часть с will.", lvl: "B1" },
    { s: "If I ___ you, I would say sorry.", o: ["am", "was", "were"], a: "were",
      ru: "На твоём месте я бы извинился.",
      why: "Второе условие: в конструкции If I were you всегда were.", lvl: "B2" },
    { s: "She would travel more if she ___ more money.", o: ["has", "had", "will have"], a: "had",
      ru: "Она бы больше путешествовала, будь у неё больше денег.",
      why: "Второе условие: нереальное настоящее — Past Simple после if.", lvl: "B2" },
    { s: "If you ___ hurry, you will miss the train.", o: ["do not", "will not", "would not"], a: "do not",
      ru: "Если не поторопишься, опоздаешь на поезд.",
      why: "После if будущее время не ставится — только Present Simple.", lvl: "B1" },
    { s: "I will call you when I ___ home.", o: ["will get", "get", "got"], a: "get",
      ru: "Я позвоню тебе, когда доберусь домой.",
      why: "После when о будущем — Present Simple, как и после if.", lvl: "B1" },
    { s: "If he had studied, he ___ the exam.", o: ["would pass", "would have passed", "will pass"], a: "would have passed",
      ru: "Если бы он занимался, он бы сдал экзамен.",
      why: "Третье условие: сожаление о прошлом — would have + третья форма.", lvl: "B2" },
    { s: "Unless you ___ , you will not understand.", o: ["listen", "do not listen", "will listen"], a: "listen",
      ru: "Если не будешь слушать, не поймёшь.",
      why: "Unless уже содержит отрицание — второй раз его добавлять нельзя.", lvl: "B2" },
    { s: "If I ___ time, I will help you.", o: ["have", "will have", "had"], a: "have",
      ru: "Если у меня будет время, я тебе помогу.",
      why: "Первое условие: after if — Present Simple.", lvl: "B1" },
    { s: "What would you do if you ___ a million?", o: ["win", "won", "will win"], a: "won",
      ru: "Что бы ты сделал, если бы выиграл миллион?",
      why: "Второе условие: воображаемая ситуация — Past Simple после if.", lvl: "B2" },
    { s: "We would have come if we ___ about the party.", o: ["knew", "had known", "know"], a: "had known",
      ru: "Мы бы пришли, если бы знали о вечеринке.",
      why: "Третье условие: had + третья форма после if.", lvl: "B2" },
    { s: "If you press this button, the machine ___ .", o: ["starts", "would start", "started"], a: "starts",
      ru: "Если нажать эту кнопку, машина запускается.",
      why: "Нулевое условие: неизменный результат.", lvl: "B1" },

    { s: "If you mix blue and yellow, you ___ green.", o: ["get", "will get", "would get"], a: "get",
      ru: "Если смешать синий и жёлтый, получится зелёный.",
      why: "Нулевой тип — законы и факты: if + Present, Present.", lvl: "A2" },
    { s: "If she ___ hard, she will pass the exam.", o: ["works", "will work", "worked"], a: "works",
      ru: "Если она будет стараться, она сдаст экзамен.",
      why: "Первый тип: после if будущее НЕ ставится — только Present Simple.", lvl: "A2" },
    { s: "We will be late if we ___ now.", o: ["will not leave", "do not leave", "did not leave"], a: "do not leave",
      ru: "Мы опоздаем, если не выйдем сейчас.",
      why: "Первый тип, часть с if — Present Simple: do not leave.", lvl: "A2" },
    { s: "If I had wings, I ___ to school.", o: ["will fly", "would fly", "fly"], a: "would fly",
      ru: "Если бы у меня были крылья, я бы летал в школу.",
      why: "Второй тип (нереальное сейчас): if + Past, would + глагол.", lvl: "B1" },
    { s: "If it ___ sunny tomorrow, we will go to the park.", o: ["will be", "is", "was"], a: "is",
      ru: "Если завтра будет солнечно, пойдём в парк.",
      why: "Реальное будущее условие: if + Present Simple, даже про завтра.", lvl: "A2" },
    { s: "If he ___ earlier, he would not have missed the train.", o: ["left", "had left", "leaves"], a: "had left",
      ru: "Если бы он вышел раньше, он не опоздал бы на поезд.",
      why: "Третий тип (нереальное прошлое): if + Past Perfect.", lvl: "B2" },
    { s: "I would buy this game if it ___ cheaper.", o: ["is", "were", "will be"], a: "were",
      ru: "Я купил бы эту игру, если бы она была дешевле.",
      why: "Второй тип: с be в if-части ставится were для всех лиц.", lvl: "B1" },
    { s: "When the water ___ , add the pasta.", o: ["boils", "will boil", "boiled"], a: "boils",
      ru: "Когда вода закипит, добавь макароны.",
      why: "После when о будущем — Present Simple, как после if.", lvl: "B1" },
    { s: "Call me if you ___ any questions.", o: ["will have", "have", "had"], a: "have",
      ru: "Позвони мне, если будут вопросы.",
      why: "Первый тип: if + Present Simple.", lvl: "A2" },
    { s: "If I ___ the answer, I would tell you.", o: ["know", "knew", "will know"], a: "knew",
      ru: "Если бы я знал ответ, я бы тебе сказал.",
      why: "Второй тип: нереальное сейчас — if + Past Simple.", lvl: "B1" },
    { s: "She ___ angry if you break her pencil.", o: ["will be", "would be", "is being"], a: "will be",
      ru: "Она разозлится, если ты сломаешь её карандаш.",
      why: "Первый тип: главная часть — will + глагол.", lvl: "A2" },
    { s: "If we ___ in the south, we would swim every day.", o: ["live", "lived", "will live"], a: "lived",
      ru: "Если бы мы жили на юге, мы бы купались каждый день.",
      why: "Второй тип: if + Past Simple (lived), would в главной части.", lvl: "B1" },
    { s: "You will not pass ___ you study.", o: ["if", "unless", "when"], a: "unless",
      ru: "Ты не сдашь, если не будешь заниматься.",
      why: "Unless = if … not: «если не». Второе отрицание не нужно.", lvl: "B1" },
    { s: "If they had invited me, I ___ .", o: ["would come", "would have come", "came"], a: "would have come",
      ru: "Если бы меня пригласили, я бы пришёл.",
      why: "Третий тип: would have + третья форма.", lvl: "B2" },
    { s: "What ___ you do if you saw a bear?", o: ["will", "would", "did"], a: "would",
      ru: "Что бы ты сделал, если бы увидел медведя?",
      why: "Второй тип: вопрос с would.", lvl: "B1" },
    { s: "If I ___ up earlier, I would not have been late.", o: ["got", "had got", "get"], a: "had got",
      ru: "Если бы я встал раньше, я бы не опоздал.",
      why: "Третий тип: if + Past Perfect (had got).", lvl: "B2" },
    { s: "Plants die if you ___ water them.", o: ["do not", "will not", "would not"], a: "do not",
      ru: "Растения погибают, если их не поливать.",
      why: "Нулевой тип — общий факт: if + Present Simple.", lvl: "A2" },
    { s: "If I were you, I ___ that jacket.", o: ["will buy", "would buy", "bought"], a: "would buy",
      ru: "На твоём месте я купил бы эту куртку.",
      why: "If I were you — совет; в главной части would + глагол.", lvl: "B1" },
    { s: "We ___ swimming tomorrow if the weather is good.", o: ["go", "will go", "would go"], a: "will go",
      ru: "Завтра пойдём купаться, если будет хорошая погода.",
      why: "Первый тип: главная часть — will go.", lvl: "A2" },
    { s: "He would have called you if he ___ your number.", o: ["knew", "had known", "knows"], a: "had known",
      ru: "Он позвонил бы тебе, если бы знал твой номер.",
      why: "Третий тип: условие в прошлом — if + Past Perfect.", lvl: "B2" }
  ],

  // ================= Пассивный залог =================
  passive: [
    { s: "This house ___ in 1920.", o: ["built", "was built", "is building"], a: "was built",
      ru: "Этот дом был построен в 1920 году.",
      why: "Дом не строит сам себя — пассив: was + третья форма.", lvl: "B1" },
    { s: "English ___ all over the world.", o: ["speaks", "is spoken", "is speaking"], a: "is spoken",
      ru: "На английском говорят по всему миру.",
      why: "Кто говорит — неважно, важен сам язык: пассив в настоящем.", lvl: "B1" },
    { s: "The letter ___ yesterday.", o: ["sent", "was sent", "has sent"], a: "was sent",
      ru: "Письмо было отправлено вчера.",
      why: "Пассив в прошедшем: was sent.", lvl: "B1" },
    { s: "The room ___ every morning.", o: ["cleans", "is cleaned", "cleaned"], a: "is cleaned",
      ru: "Комнату убирают каждое утро.",
      why: "Регулярное действие над предметом — пассив в Present Simple.", lvl: "B1" },
    { s: "The bridge ___ next year.", o: ["will build", "will be built", "builds"], a: "will be built",
      ru: "Мост построят в следующем году.",
      why: "Пассив в будущем: will be + третья форма.", lvl: "B2" },
    { s: "The window ___ by the wind.", o: ["broke", "was broken", "is breaking"], a: "was broken",
      ru: "Окно было разбито ветром.",
      why: "Пассив: подлежащее не действует, а испытывает действие.", lvl: "B1" },
    { s: "This song ___ by millions of people.", o: ["knows", "is known", "is knowing"], a: "is known",
      ru: "Эту песню знают миллионы.",
      why: "Пассив от know — is known.", lvl: "B1" },
    { s: "The work ___ already ___ .", o: ["has / done", "has been / done", "is / doing"], a: "has been / done",
      ru: "Работа уже сделана.",
      why: "Пассив в Present Perfect: has been + третья форма.", lvl: "B2" },
    { s: "Our car ___ at the moment.", o: ["is repairing", "is being repaired", "repairs"], a: "is being repaired",
      ru: "Нашу машину сейчас чинят.",
      why: "Пассив в Present Continuous: is being + третья форма.", lvl: "B2" },
    { s: "The books ___ on the shelf yesterday.", o: ["put", "were put", "was put"], a: "were put",
      ru: "Книги вчера положили на полку.",
      why: "Books — множественное число, значит were put.", lvl: "B1" },
    { s: "The problem must ___ today.", o: ["solve", "be solved", "is solved"], a: "be solved",
      ru: "Проблему нужно решить сегодня.",
      why: "После модального глагола пассив строится как be + третья форма.", lvl: "B2" },
    { s: "This picture ___ by my grandmother.", o: ["painted", "was painted", "is painting"], a: "was painted",
      ru: "Эта картина была написана моей бабушкой.",
      why: "Пассив с указанием исполнителя через by.", lvl: "B1" },

    { s: "Rice ___ in China.", o: ["grows", "is grown", "grown"], a: "is grown",
      ru: "Рис выращивают в Китае.",
      why: "Действие над предметом — пассив: is/are + третья форма.", lvl: "A2" },
    { s: "The homework must ___ by Monday.", o: ["do", "be done", "done"], a: "be done",
      ru: "Домашняя работа должна быть сделана к понедельнику.",
      why: "После модального глагола пассив — be + третья форма.", lvl: "B1" },
    { s: "America ___ by Columbus.", o: ["discovered", "was discovered", "is discovered"], a: "was discovered",
      ru: "Америку открыл Колумб.",
      why: "Прошлое, действие НАД Америкой — was + discovered.", lvl: "A2" },
    { s: "These toys ___ in Germany.", o: ["make", "are made", "made"], a: "are made",
      ru: "Эти игрушки делают в Германии.",
      why: "Наст. время, множественное число: are made.", lvl: "A2" },
    { s: "The letter ___ tomorrow.", o: ["will send", "will be sent", "sends"], a: "will be sent",
      ru: "Письмо отправят завтра.",
      why: "Будущий пассив — will be + третья форма.", lvl: "B1" },
    { s: "My bike ___ last week.", o: ["stole", "was stolen", "is stolen"], a: "was stolen",
      ru: "Мой велосипед украли на прошлой неделе.",
      why: "Прошлое: was stolen (steal — stole — stolen).", lvl: "A2" },
    { s: "Dinner ___ right now, wait ten minutes.", o: ["is cooked", "is being cooked", "cooks"], a: "is being cooked",
      ru: "Ужин готовится прямо сейчас, подожди десять минут.",
      why: "Пассив в процессе — is being + третья форма.", lvl: "B2" },
    { s: "The tickets have already ___ .", o: ["been sold", "sold", "being sold"], a: "been sold",
      ru: "Билеты уже проданы.",
      why: "Present Perfect в пассиве — have/has been + третья форма.", lvl: "B1" },
    { s: "This dictionary ___ by many students.", o: ["uses", "is used", "using"], a: "is used",
      ru: "Этим словарём пользуются многие ученики.",
      why: "Регулярный пассив — is used.", lvl: "A2" },
    { s: "The classroom ___ when I came in.", o: ["was cleaned", "was being cleaned", "cleaned"], a: "was being cleaned",
      ru: "Когда я вошёл, класс как раз убирали.",
      why: "Пассив в процессе в прошлом — was being + третья форма.", lvl: "B2" },
    { s: "Football ___ in almost every country.", o: ["is played", "plays", "is playing"], a: "is played",
      ru: "В футбол играют почти в каждой стране.",
      why: "Действие над предметом (в него играют) — is played.", lvl: "A2" },
    { s: "The Mona Lisa ___ by Leonardo da Vinci.", o: ["painted", "was painted", "is painted"], a: "was painted",
      ru: "«Мону Лизу» написал Леонардо да Винчи.",
      why: "Факт из прошлого о картине — was painted.", lvl: "A2" },
    { s: "All the cakes ___ before we arrived.", o: ["had been eaten", "were eaten", "have been eaten"], a: "had been eaten",
      ru: "Все пирожные съели до нашего прихода.",
      why: "Раньше другого прошедшего события — Past Perfect Passive: had been eaten.", lvl: "B2" },
    { s: "English and French ___ in Canada.", o: ["speak", "are spoken", "spoken"], a: "are spoken",
      ru: "В Канаде говорят на английском и французском.",
      why: "На языках говорят — пассив: are spoken.", lvl: "A2" },
    { s: "The results ___ next Friday.", o: ["will announce", "will be announced", "announce"], a: "will be announced",
      ru: "Результаты объявят в следующую пятницу.",
      why: "Будущий пассив — will be announced.", lvl: "B1" },
    { s: "This castle ___ in the twelfth century.", o: ["built", "was built", "is built"], a: "was built",
      ru: "Этот замок построили в двенадцатом веке.",
      why: "Прошлое: was built (build — built — built).", lvl: "A2" },
    { s: "The children ___ to the zoo yesterday.", o: ["took", "were taken", "taken"], a: "were taken",
      ru: "Вчера детей сводили в зоопарк.",
      why: "Действие над детьми (их отвели) — were taken.", lvl: "B1" },
    { s: "A new hospital ___ in our town now.", o: ["is built", "is being built", "builds"], a: "is being built",
      ru: "В нашем городе сейчас строится новая больница.",
      why: "Стройка идёт прямо сейчас — is being built.", lvl: "B2" },
    { s: "The rules must ___ by everyone.", o: ["follow", "be followed", "followed"], a: "be followed",
      ru: "Правила должны соблюдаться всеми.",
      why: "Модальный + пассив: must be followed.", lvl: "B1" },
    { s: "I ___ a watch for my birthday.", o: ["gave", "was given", "given"], a: "was given",
      ru: "Мне подарили часы на день рождения.",
      why: "Пассив от give: мне дали — I was given.", lvl: "B1" }
  ],

  // ================= Герундий и инфинитив =================
  "ing-to": [
    { s: "I enjoy ___ books in the evening.", o: ["read", "reading", "to read"], a: "reading",
      ru: "Я люблю читать книги по вечерам.",
      why: "После enjoy всегда идёт -ing.", lvl: "B1" },
    { s: "She decided ___ the job.", o: ["take", "taking", "to take"], a: "to take",
      ru: "Она решила взяться за эту работу.",
      why: "После decide — инфинитив с to.", lvl: "B1" },
    { s: "He is good at ___ chess.", o: ["play", "playing", "to play"], a: "playing",
      ru: "Он хорошо играет в шахматы.",
      why: "После предлога всегда -ing.", lvl: "B1" },
    { s: "They want ___ home early.", o: ["go", "going", "to go"], a: "to go",
      ru: "Они хотят пойти домой пораньше.",
      why: "После want — инфинитив с to.", lvl: "A2" },
    { s: "Stop ___ ! I cannot hear the teacher.", o: ["talk", "talking", "to talk"], a: "talking",
      ru: "Прекрати разговаривать! Я не слышу учителя.",
      why: "Stop + -ing значит «прекратить делать».", lvl: "B1" },
    { s: "Let me ___ you.", o: ["help", "helping", "to help"], a: "help",
      ru: "Позволь мне тебе помочь.",
      why: "После let и make инфинитив идёт без to.", lvl: "B1" },
    { s: "I look forward to ___ from you.", o: ["hear", "hearing", "to hear"], a: "hearing",
      ru: "Жду от тебя вестей.",
      why: "В look forward to слово to — предлог, поэтому дальше -ing.", lvl: "B2" },
    { s: "It is worth ___ this museum.", o: ["visit", "visiting", "to visit"], a: "visiting",
      ru: "Этот музей стоит посетить.",
      why: "После worth всегда -ing: worth visiting, worth trying. Инфинитив с to здесь невозможен.", lvl: "B2" },
    { s: "She promised ___ me tomorrow.", o: ["call", "calling", "to call"], a: "to call",
      ru: "Она пообещала позвонить мне завтра.",
      why: "После promise — инфинитив с to.", lvl: "B1" },
    { s: "Would you mind ___ the door?", o: ["close", "closing", "to close"], a: "closing",
      ru: "Не могли бы вы закрыть дверь?",
      why: "После mind всегда -ing. «Would you mind doing…» — вежливая просьба, дословно «вы не против сделать…».", lvl: "B1" },
    { s: "He made me ___ the whole story.", o: ["tell", "telling", "to tell"], a: "tell",
      ru: "Он заставил меня рассказать всю историю.",
      why: "После make инфинитив идёт без to.", lvl: "B2" },
    { s: "I need ___ some milk.", o: ["buy", "buying", "to buy"], a: "to buy",
      ru: "Мне нужно купить молока.",
      why: "После need — инфинитив с to.", lvl: "A2" },

    { s: "She avoids ___ sweets before dinner.", o: ["to eat", "eating", "eat"], a: "eating",
      ru: "Она старается не есть сладкое перед ужином.",
      why: "Avoid + герундий (-ing): avoids eating.", lvl: "B1" },
    { s: "They agreed ___ us with the project.", o: ["helping", "to help", "help"], a: "to help",
      ru: "Они согласились помочь нам с проектом.",
      why: "Agree + инфинитив с to: agreed to help.", lvl: "B1" },
    { s: "I cannot stand ___ in queues.", o: ["to wait", "waiting", "wait"], a: "waiting",
      ru: "Терпеть не могу стоять в очередях.",
      why: "Cannot stand + герундий: cannot stand waiting.", lvl: "B1" },
    { s: "He offered ___ me home.", o: ["driving", "to drive", "drive"], a: "to drive",
      ru: "Он предложил подвезти меня домой.",
      why: "Offer + инфинитив с to: offered to drive.", lvl: "B1" },
    { s: "Do you fancy ___ to the cinema tonight?", o: ["to go", "going", "go"], a: "going",
      ru: "Не хочешь сходить в кино сегодня вечером?",
      why: "Fancy + герундий: fancy going.", lvl: "B2" },
    { s: "She seems ___ very tired today.", o: ["being", "to be", "be"], a: "to be",
      ru: "Она сегодня кажется очень уставшей.",
      why: "Seem + инфинитив с to: seems to be.", lvl: "B1" },
    { s: "I do not mind ___ the dishes.", o: ["to wash", "washing", "wash"], a: "washing",
      ru: "Я не против помыть посуду.",
      why: "Mind + герундий: mind washing.", lvl: "A2" },
    { s: "We hope ___ the final on Saturday.", o: ["winning", "to win", "win"], a: "to win",
      ru: "Мы надеемся выиграть финал в субботу.",
      why: "Hope + инфинитив с to: hope to win.", lvl: "A2" },
    { s: "He suggested ___ a break.", o: ["to take", "taking", "take"], a: "taking",
      ru: "Он предложил сделать перерыв.",
      why: "Suggest + герундий: suggested taking. «Suggest to take» — частая ошибка.", lvl: "B1" },
    { s: "Remember ___ the door when you leave.", o: ["locking", "to lock", "lock"], a: "to lock",
      ru: "Не забудь закрыть дверь, когда будешь уходить.",
      why: "Remember + to = не забыть СДЕЛАТЬ. Remember + -ing — помнить, что уже делал.", lvl: "B2" },
    { s: "I will never forget ___ the sea for the first time.", o: ["to see", "seeing", "see"], a: "seeing",
      ru: "Никогда не забуду, как впервые увидел море.",
      why: "Forget + -ing — воспоминание о прошлом. Forget + to — забыть сделать.", lvl: "B2" },
    { s: "My dad gave up ___ two years ago.", o: ["to smoke", "smoking", "smoke"], a: "smoking",
      ru: "Папа бросил курить два года назад.",
      why: "Give up + герундий: gave up smoking.", lvl: "B1" },
    { s: "It is difficult ___ new words without practice.", o: ["remembering", "to remember", "remember"], a: "to remember",
      ru: "Трудно запоминать новые слова без практики.",
      why: "It is + прилагательное + инфинитив с to: it is difficult to remember.", lvl: "A2" },
    { s: "Keep ___ ! You are almost at the finish.", o: ["to run", "running", "run"], a: "running",
      ru: "Продолжай бежать! Ты почти у финиша.",
      why: "Keep + герундий — «продолжать делать».", lvl: "B1" },
    { s: "She refused ___ the question.", o: ["answering", "to answer", "answer"], a: "to answer",
      ru: "Она отказалась отвечать на вопрос.",
      why: "Refuse + инфинитив с to: refused to answer.", lvl: "B1" },
    { s: "Swimming is a great way ___ fit.", o: ["staying", "to stay", "stay"], a: "to stay",
      ru: "Плавание — отличный способ оставаться в форме.",
      why: "A way + инфинитив с to: a way to stay fit.", lvl: "B1" },
    { s: "I am used to ___ up early on school days.", o: ["get", "getting", "got"], a: "getting",
      ru: "Я привык рано вставать в учебные дни.",
      why: "Be used TO + герундий: to здесь предлог, после него -ing.", lvl: "B2" },
    { s: "The teacher let us ___ home early.", o: ["to go", "go", "going"], a: "go",
      ru: "Учитель отпустил нас домой пораньше.",
      why: "Let + голый инфинитив без to: let us go.", lvl: "A2" },
    { s: "He practises ___ the piano every day.", o: ["to play", "playing", "play"], a: "playing",
      ru: "Он занимается на пианино каждый день.",
      why: "Practise + герундий: practises playing.", lvl: "A2" },
    { s: "It has stopped ___ — we can go out now.", o: ["to rain", "raining", "rain"], a: "raining",
      ru: "Дождь закончился — можно выходить.",
      why: "Stop + -ing — действие прекратилось. Stop + to — остановиться, ЧТОБЫ сделать.", lvl: "B1" }
  ],

  // ================= Вопросы и порядок слов =================
  questions: [
    { s: "___ does your brother work?", o: ["Where", "What", "Who"], a: "Where",
      ru: "Где работает твой брат?",
      why: "Спрашиваем о месте — Where.", lvl: "A2" },
    { s: "Where ___ you go last summer?", o: ["did", "do", "does"], a: "did",
      ru: "Куда ты ездил прошлым летом?",
      why: "Прошедшее время: вопрос строится через did + начальная форма глагола.", lvl: "A2" },
    { s: "___ wrote this letter?", o: ["Who", "Whom", "Whose"], a: "Who",
      ru: "Кто написал это письмо?",
      why: "Вопрос к подлежащему — Who, и вспомогательный глагол не нужен.", lvl: "B1" },
    { s: "How ___ books do you read a month?", o: ["much", "many", "long"], a: "many",
      ru: "Сколько книг ты читаешь за месяц?",
      why: "Books можно посчитать — how many.", lvl: "A2" },
    { s: "You like pizza, ___ ?", o: ["do you", "don't you", "aren't you"], a: "don't you",
      ru: "Ты ведь любишь пиццу?",
      why: "Разделительный вопрос: утверждение → отрицательный хвостик с тем же вспомогательным.", lvl: "B1" },
    { s: "She isn't at home, ___ ?", o: ["is she", "isn't she", "does she"], a: "is she",
      ru: "Её ведь нет дома?",
      why: "Отрицание → утвердительный хвостик: is she.", lvl: "B1" },
    { s: "___ is your favourite subject?", o: ["What", "Which", "How"], a: "What",
      ru: "Какой у тебя любимый предмет?",
      why: "Выбор не ограничен списком — What. Which спрашивает о выборе из известных вариантов.", lvl: "A2" },
    { s: "Tell me where ___ .", o: ["is the station", "the station is", "does the station"], a: "the station is",
      ru: "Скажи мне, где находится вокзал.",
      why: "В придаточном вопросе порядок слов ПРЯМОЙ: подлежащее перед сказуемым.", lvl: "B2" },
    { s: "I wonder what time ___ .", o: ["does the film start", "the film starts", "starts the film"], a: "the film starts",
      ru: "Интересно, во сколько начинается фильм.",
      why: "После I wonder — прямой порядок слов, без вспомогательного do.", lvl: "B2" },
    { s: "___ long have you lived here?", o: ["How", "What", "When"], a: "How",
      ru: "Как долго ты здесь живёшь?",
      why: "Про длительность — how long.", lvl: "A2" },
    { s: "___ bag is this?", o: ["Who", "Whose", "Which"], a: "Whose",
      ru: "Чья это сумка?",
      why: "Про принадлежность — Whose.", lvl: "A2" },
    { s: "Why ___ she crying?", o: ["is", "does", "do"], a: "is",
      ru: "Почему она плачет?",
      why: "Present Continuous: вопрос через формы be.", lvl: "A2" },
    { s: "___ there any milk in the fridge?", o: ["Is", "Are", "Does"], a: "Is",
      ru: "В холодильнике есть молоко?",
      why: "Milk неисчисляемое — is there.", lvl: "A2" },
    { s: "Never ___ I seen such a beautiful sunset.", o: ["have", "has", "did"], a: "have",
      ru: "Никогда я не видел такого красивого заката.",
      why: "После never в начале предложения порядок слов как в вопросе: have I seen.", lvl: "B2" },
    { s: "What ___ you doing at six yesterday?", o: ["was", "were", "did"], a: "were",
      ru: "Что ты делал вчера в шесть?",
      why: "Past Continuous: were + you + -ing.", lvl: "B1" },
    { s: "___ your parents speak English?", o: ["Do", "Does", "Are"], a: "Do",
      ru: "Твои родители говорят по-английски?",
      why: "Parents — множественное число, вопрос через do.", lvl: "A2" },
    { s: "She always ___ her homework in the evening.", o: ["does", "do", "is doing"], a: "does",
      ru: "Она всегда делает уроки вечером.",
      why: "Наречие частоты стоит перед смысловым глаголом, а глагол — с -s.", lvl: "A2" },
    { s: "___ many people came to the concert?", o: ["How", "What", "Which"], a: "How",
      ru: "Сколько людей пришло на концерт?",
      why: "How many — вопрос о количестве исчисляемого.", lvl: "A2" },
    { s: "Let's go to the park, ___ ?", o: ["shall we", "will we", "do we"], a: "shall we",
      ru: "Пойдём в парк, а?",
      why: "У предложения с Let's хвостик всегда shall we.", lvl: "B2" },
    { s: "Do you know if ___ tomorrow?", o: ["will he come", "he will come", "does he come"], a: "he will come",
      ru: "Не знаешь, придёт ли он завтра?",
      why: "После if в косвенном вопросе — прямой порядок слов.", lvl: "B2" },
  ],

  // ================= Косвенная речь =================
  reported: [
    { s: "He said that he ___ tired.", o: ["is", "was", "will be"], a: "was",
      ru: "Он сказал, что устал.",
      why: "После said время сдвигается на шаг назад: is → was.", lvl: "B1" },
    { s: "She told me she ___ my letter.", o: ["gets", "had got", "will get"], a: "had got",
      ru: "Она сказала мне, что получила моё письмо.",
      why: "Прошедшее в косвенной речи уходит в Past Perfect.", lvl: "B2" },
    { s: "Ann said she ___ come the next day.", o: ["will", "would", "can"], a: "would",
      ru: "Аня сказала, что придёт на следующий день.",
      why: "will → would при сдвиге времён.", lvl: "B1" },
    { s: "He asked me where I ___ .", o: ["live", "lived", "do live"], a: "lived",
      ru: "Он спросил, где я живу.",
      why: "Косвенный вопрос: прямой порядок слов и сдвиг времени.", lvl: "B1" },
    { s: "She asked ___ I liked the film.", o: ["that", "if", "what"], a: "if",
      ru: "Она спросила, понравился ли мне фильм.",
      why: "Общий вопрос в косвенной речи вводится через if или whether.", lvl: "B1" },
    { s: "The teacher told us ___ quiet.", o: ["be", "to be", "being"], a: "to be",
      ru: "Учитель велел нам вести себя тихо.",
      why: "Просьба или приказ в косвенной речи — told somebody TO do.", lvl: "B1" },
    { s: "Mum asked me not ___ late.", o: ["be", "to be", "being"], a: "to be",
      ru: "Мама попросила меня не задерживаться.",
      why: "Отрицательная просьба: asked not TO be.", lvl: "B1" },
    { s: "He said he ___ never been to London.", o: ["has", "had", "was"], a: "had",
      ru: "Он сказал, что никогда не был в Лондоне.",
      why: "Present Perfect → Past Perfect: has been → had been.", lvl: "B2" },
    { s: "She said she would call me ___ day.", o: ["the next", "tomorrow", "next"], a: "the next",
      ru: "Она сказала, что позвонит мне на следующий день.",
      why: "В косвенной речи tomorrow превращается в the next day.", lvl: "B2" },
    { s: "They said they ___ there the day before.", o: ["are", "had been", "were being"], a: "had been",
      ru: "Они сказали, что были там накануне.",
      why: "Действие раньше момента речи в прошлом — Past Perfect.", lvl: "B2" },
    { s: "He asked what my name ___ .", o: ["is", "was", "does"], a: "was",
      ru: "Он спросил, как меня зовут.",
      why: "Сдвиг времён: is → was, порядок слов прямой.", lvl: "B1" },
    { s: "She says she ___ busy today.", o: ["is", "was", "had been"], a: "is",
      ru: "Она говорит, что сегодня занята.",
      why: "Says (настоящее время) сдвига НЕ вызывает — время остаётся прежним.", lvl: "B1" },
    { s: "The doctor advised him ___ more water.", o: ["drink", "to drink", "drinking"], a: "to drink",
      ru: "Врач посоветовал ему пить больше воды.",
      why: "advise somebody TO do — совет в косвенной речи.", lvl: "B2" },
    { s: "He said that he ___ football every Sunday.", o: ["plays", "played", "is playing"], a: "played",
      ru: "Он сказал, что играет в футбол каждое воскресенье.",
      why: "Present Simple → Past Simple при сдвиге.", lvl: "B1" },
    { s: "I asked her ___ she could help me.", o: ["that", "if", "so"], a: "if",
      ru: "Я спросил, может ли она мне помочь.",
      why: "Вопрос без вопросительного слова — через if.", lvl: "B1" },
    { s: "She said she was going to visit us ___ week.", o: ["next", "the following", "this"], a: "the following",
      ru: "Она сказала, что навестит нас на следующей неделе.",
      why: "next week в косвенной речи становится the following week.", lvl: "B2" },

    { s: "He said he ___ help me the following day.", o: ["will", "would", "can"], a: "would",
      ru: "Он сказал, что поможет мне на следующий день.",
      why: "will → would при сдвиге времён.", lvl: "B1" },
    { s: "She asked me what I ___ doing.", o: ["am", "was", "will be"], a: "was",
      ru: "Она спросила, что я делаю.",
      why: "Present Continuous → Past Continuous: am → was.", lvl: "B1" },
    { s: "They said they ___ finish the work on time.", o: ["can", "could", "may"], a: "could",
      ru: "Они сказали, что смогут закончить работу вовремя.",
      why: "can → could при сдвиге времён.", lvl: "B2" },
    { s: "The coach told the team ___ give up.", o: ["not to", "to not", "don't"], a: "not to",
      ru: "Тренер сказал команде не сдаваться.",
      why: "Отрицательный приказ: told somebody NOT TO do.", lvl: "B2" },
    { s: "Tom said he had bought that car ___ year before.", o: ["last", "the", "next"], a: "the",
      ru: "Том сказал, что купил ту машину годом раньше.",
      why: "last year в косвенной речи становится the year before.", lvl: "B2" },
    { s: "She wondered ___ the shop was still open.", o: ["that", "whether", "what"], a: "whether",
      ru: "Она гадала, открыт ли ещё магазин.",
      why: "Косвенный общий вопрос вводится через whether или if.", lvl: "B2" },
  ],

  // ================= Количество =================
  quantity: [
    { s: "How ___ sugar do you take?", o: ["many", "much", "long"], a: "much",
      ru: "Сколько сахара тебе положить?",
      why: "Sugar не считается по штукам — much.", lvl: "A2" },
    { s: "There are ___ apples in the basket.", o: ["much", "many", "a little"], a: "many",
      ru: "В корзине много яблок.",
      why: "Apples можно посчитать — many.", lvl: "A2" },
    { s: "I have ___ money, let's take a taxi.", o: ["a few", "enough", "many"], a: "enough",
      ru: "У меня достаточно денег, давай возьмём такси.",
      why: "Enough — «достаточно», подходит и к исчисляемым, и к неисчисляемым.", lvl: "B1" },
    { s: "Would you like ___ tea?", o: ["some", "any", "many"], a: "some",
      ru: "Хочешь чаю?",
      why: "В предложении угощения ставится some, хотя это вопрос.", lvl: "A2" },
    { s: "There isn't ___ bread left.", o: ["some", "any", "many"], a: "any",
      ru: "Хлеба совсем не осталось.",
      why: "В отрицании — any.", lvl: "A2" },
    { s: "Only ___ students came to the extra lesson.", o: ["a little", "a few", "much"], a: "a few",
      ru: "На дополнительный урок пришло всего несколько учеников.",
      why: "Students исчисляемые — a few.", lvl: "B1" },
    { s: "Add ___ salt, the soup is almost ready.", o: ["a few", "a little", "many"], a: "a little",
      ru: "Добавь немного соли, суп почти готов.",
      why: "Salt неисчисляемая — a little.", lvl: "B1" },
    { s: "There is ___ furniture in the room.", o: ["many", "few", "little"], a: "little",
      ru: "В комнате мало мебели.",
      why: "Furniture неисчисляемое, и мебели мало — little (без a значит «мало, почти нет»).", lvl: "B2" },
    { s: "___ of my friends live abroad.", o: ["Much", "Some", "A little"], a: "Some",
      ru: "Некоторые мои друзья живут за границей.",
      why: "Some of + множественное число.", lvl: "B1" },
    { s: "He has too ___ homework today.", o: ["many", "much", "few"], a: "much",
      ru: "У него сегодня слишком много домашки.",
      why: "Homework неисчисляемое — too much.", lvl: "B1" },
    { s: "Is there ___ juice in the bottle?", o: ["some", "any", "many"], a: "any",
      ru: "В бутылке есть сок?",
      why: "Обычный вопрос — any.", lvl: "A2" },
    { s: "I have ___ time, so I can help you.", o: ["a little", "little", "few"], a: "a little",
      ru: "У меня есть немного времени, так что могу помочь.",
      why: "A little — «немного, но есть»; little без артикля означало бы «почти нет».", lvl: "B2" },
    { s: "There were ___ people at the station.", o: ["much", "a lot of", "a little"], a: "a lot of",
      ru: "На вокзале было много людей.",
      why: "A lot of подходит и к исчисляемым, и к неисчисляемым.", lvl: "A2" },
    { s: "We don't need ___ help, thanks.", o: ["some", "any", "much of"], a: "any",
      ru: "Нам не нужна помощь, спасибо.",
      why: "Отрицание — any.", lvl: "A2" },
    { s: "___ information in this article is wrong.", o: ["Many", "Some", "A few"], a: "Some",
      ru: "Часть информации в этой статье неверна.",
      why: "Information неисчисляемое: many и a few к нему не подходят.", lvl: "B2" },
    { s: "How ___ does this bag cost?", o: ["many", "much", "long"], a: "much",
      ru: "Сколько стоит эта сумка?",
      why: "О цене спрашивают how much.", lvl: "A2" },

    { s: "There are ___ chairs for everyone, bring two more.", o: ["enough", "not enough", "too many"], a: "not enough",
      ru: "Стульев на всех не хватает, принеси ещё два.",
      why: "«Не хватает» — not enough.", lvl: "B1" },
    { s: "I bought ___ new pens yesterday.", o: ["much", "a few", "a little"], a: "a few",
      ru: "Вчера я купил несколько новых ручек.",
      why: "Pens исчисляемые — a few.", lvl: "A2" },
    { s: "___ of the pizza is left, help yourself.", o: ["A few", "Some", "Many"], a: "Some",
      ru: "Немного пиццы осталось, угощайся.",
      why: "Часть неисчисляемого целого — some of.", lvl: "B1" },
    { s: "He drinks too ___ coffee in the evening.", o: ["many", "much", "few"], a: "much",
      ru: "Он пьёт слишком много кофе по вечерам.",
      why: "Coffee здесь неисчисляемый — too much.", lvl: "A2" },
    { s: "___ my classmates play a musical instrument.", o: ["Much of", "Several of", "A little of"], a: "Several of",
      ru: "Несколько моих одноклассников играют на музыкальных инструментах.",
      why: "Several of + исчисляемое множественное.", lvl: "B2" },
    { s: "We have ___ time before the train, no need to run.", o: ["plenty of", "a few", "many"], a: "plenty of",
      ru: "У нас полно времени до поезда, бежать не нужно.",
      why: "Plenty of — «более чем достаточно», подходит к неисчисляемому time.", lvl: "B2" },
  ],

  // ================= Местоимения =================
  pronouns: [
    { s: "This book is ___ , I bought it yesterday.", o: ["my", "mine", "me"], a: "mine",
      ru: "Эта книга моя, я купил её вчера.",
      why: "После глагола-связки нужна самостоятельная форма: mine, а не my.", lvl: "B1" },
    { s: "Give ___ the keys, please.", o: ["I", "me", "my"], a: "me",
      ru: "Дай мне ключи, пожалуйста.",
      why: "После глагола — объектная форма: me.", lvl: "A2" },
    { s: "She hurt ___ while cooking.", o: ["her", "herself", "hers"], a: "herself",
      ru: "Она поранилась, когда готовила.",
      why: "Действие направлено на самого себя — возвратное herself.", lvl: "B1" },
    { s: "___ is nothing in the box.", o: ["It", "There", "That"], a: "There",
      ru: "В коробке ничего нет.",
      why: "О наличии чего-либо: there is / there are.", lvl: "A2" },
    { s: "___ is cold today, take a jacket.", o: ["There", "It", "That"], a: "It",
      ru: "Сегодня холодно, возьми куртку.",
      why: "О погоде и времени говорят через it.", lvl: "A2" },
    { s: "We met ___ at the school gate.", o: ["ourselves", "each other", "us"], a: "each other",
      ru: "Мы встретились у школьных ворот.",
      why: "Друг друга — each other; ourselves значило бы «сами себя».", lvl: "B2" },
    { s: "___ of the two answers is correct.", o: ["Both", "Neither", "None"], a: "Neither",
      ru: "Ни один из двух ответов не верен.",
      why: "Neither — «ни один из двух». None — из трёх и больше.", lvl: "B2" },
    { s: "Is this your pen? — No, ___ is red.", o: ["my", "mine", "me"], a: "mine",
      ru: "Это твоя ручка? — Нет, моя красная.",
      why: "Существительного дальше нет — нужна форма mine.", lvl: "B1" },
    { s: "___ knows the answer to this question.", o: ["Anybody", "Nobody", "Somebody's"], a: "Nobody",
      ru: "Никто не знает ответа на этот вопрос.",
      why: "Nobody уже содержит отрицание, второго не нужно.", lvl: "B1" },
    { s: "Help ___ to the cake!", o: ["you", "yourself", "your"], a: "yourself",
      ru: "Угощайся тортом!",
      why: "Устойчивое help yourself — «угощайся».", lvl: "B2" },
    { s: "Their house is bigger than ___ .", o: ["our", "ours", "us"], a: "ours",
      ru: "Их дом больше нашего.",
      why: "После than — самостоятельная форма ours.", lvl: "B1" },
    { s: "I did it ___ , nobody helped me.", o: ["myself", "me", "mine"], a: "myself",
      ru: "Я сделал это сам, никто мне не помогал.",
      why: "«Сам» в значении «без помощи» — myself.", lvl: "B1" },
    { s: "___ students in our class like maths.", o: ["Most", "Most of", "The most"], a: "Most",
      ru: "Большинству учеников нашего класса нравится математика.",
      why: "Most + существительное без of, если нет the: most students.", lvl: "B2" },
    { s: "Can you see ___ over there?", o: ["someone", "anyone", "no one"], a: "anyone",
      ru: "Ты кого-нибудь там видишь?",
      why: "В вопросе — anyone.", lvl: "A2" },
    { s: "These are my books and ___ are yours.", o: ["that", "those", "this"], a: "those",
      ru: "Это мои книги, а те — твои.",
      why: "Множественное число и «те, дальние» — those.", lvl: "A2" },
    { s: "The dog wagged ___ tail.", o: ["it's", "its", "his"], a: "its",
      ru: "Собака виляла хвостом.",
      why: "Its — притяжательное «его/её» без апострофа; it's = it is.", lvl: "B1" },

    { s: "Everyone brought ___ own lunch.", o: ["his", "their", "them"], a: "their",
      ru: "Каждый принёс свой обед.",
      why: "После everyone в современном английском ставится their.", lvl: "B2" },
    { s: "Look at ___ ! Your face is dirty.", o: ["you", "yourself", "your"], a: "yourself",
      ru: "Посмотри на себя! У тебя лицо испачкано.",
      why: "Действие направлено на самого себя — yourself.", lvl: "B1" },
    { s: "___ of my parents speak French.", o: ["Both", "Either", "Neither of"], a: "Both",
      ru: "Оба моих родителя говорят по-французски.",
      why: "Both — «оба», глагол во множественном числе.", lvl: "B1" },
    { s: "There is somebody at the door — go and see who ___ is.", o: ["he", "it", "there"], a: "it",
      ru: "Кто-то у двери — иди посмотри, кто это.",
      why: "О неизвестном человеке говорят it, пока не узнали, кто он.", lvl: "B2" },
    { s: "This pen isn't ___ , it's Ann's.", o: ["her", "hers", "she"], a: "hers",
      ru: "Эта ручка не её, она Анина.",
      why: "Существительного дальше нет — самостоятельная форма hers.", lvl: "B1" },
    { s: "I have two bags: one is heavy, ___ is light.", o: ["another", "the other", "other"], a: "the other",
      ru: "У меня две сумки: одна тяжёлая, другая лёгкая.",
      why: "Из двух: one … the other. Another — «ещё один» из многих.", lvl: "B2" },
  ],

  // ================= Будущее время =================
  future: [
    { s: "Look at those clouds! It ___ rain.", o: ["will", "is going to", "goes to"], a: "is going to",
      ru: "Посмотри на тучи! Сейчас пойдёт дождь.",
      why: "Есть видимый признак прямо сейчас — be going to.", lvl: "B1" },
    { s: "I think our team ___ win.", o: ["will", "is going to", "going to"], a: "will",
      ru: "Думаю, наша команда победит.",
      why: "Личное предположение с think — will.", lvl: "A2" },
    { s: "The train ___ at 7:15 tomorrow.", o: ["will leave", "leaves", "is leaving to"], a: "leaves",
      ru: "Поезд отправляется завтра в 7:15.",
      why: "Расписание — Present Simple, даже про будущее.", lvl: "B1" },
    { s: "I ___ my grandmother tomorrow, we agreed yesterday.", o: ["will visit", "am visiting", "visit"], a: "am visiting",
      ru: "Завтра я еду к бабушке, мы договорились вчера.",
      why: "Личная договорённость на конкретное время — Present Continuous.", lvl: "B1" },
    { s: "Wait, I ___ you with the bags.", o: ["will help", "am helping", "help"], a: "will help",
      ru: "Погоди, я помогу тебе с сумками.",
      why: "Решение принято в момент речи — will.", lvl: "A2" },
    { s: "She ___ be twelve next month.", o: ["will", "is going", "does"], a: "will",
      ru: "В следующем месяце ей будет двенадцать.",
      why: "Факт о будущем — will be.", lvl: "A2" },
    { s: "We ___ to move to another city next year.", o: ["will", "are going", "go"], a: "are going",
      ru: "В следующем году мы собираемся переехать в другой город.",
      why: "Заранее принятое намерение — be going to.", lvl: "B1" },
    { s: "By this time tomorrow I ___ on the beach.", o: ["will lie", "will be lying", "lie"], a: "will be lying",
      ru: "Завтра в это время я буду лежать на пляже.",
      why: "Действие в процессе в конкретный момент будущего — Future Continuous.", lvl: "B2" },
    { s: "I will call you when I ___ .", o: ["will arrive", "arrive", "am arriving"], a: "arrive",
      ru: "Я позвоню тебе, когда приеду.",
      why: "После when о будущем ставится настоящее время.", lvl: "B1" },
    { s: "___ you be at home this evening?", o: ["Will", "Are", "Do"], a: "Will",
      ru: "Ты будешь дома сегодня вечером?",
      why: "Вопрос о будущем — Will you be …?", lvl: "A2" },
    { s: "They ___ the new bridge by December.", o: ["will finish", "will have finished", "finish"], a: "will have finished",
      ru: "К декабрю они закончат новый мост.",
      why: "«К такому-то сроку» — Future Perfect: will have + третья форма.", lvl: "B2" },
    { s: "Don't worry, I ___ tell anybody.", o: ["will not", "am not going", "do not"], a: "will not",
      ru: "Не волнуйся, я никому не скажу.",
      why: "Обещание — will not (won't).", lvl: "A2" },
    { s: "What ___ you do after school today?", o: ["will", "are", "do"], a: "are",
      ru: "Что ты делаешь сегодня после школы?",
      why: "О планах на сегодня — are you going to do / are you doing.", lvl: "B1" },
    { s: "The film ___ in ten minutes.", o: ["starts", "will start to", "is start"], a: "starts",
      ru: "Фильм начинается через десять минут.",
      why: "Сеанс по расписанию — Present Simple.", lvl: "B1" },
    { s: "If it snows, we ___ a snowman.", o: ["make", "will make", "made"], a: "will make",
      ru: "Если пойдёт снег, мы слепим снеговика.",
      why: "Первый тип условия: главная часть — will + глагол.", lvl: "A2" },
    { s: "I hope the weather ___ nice at the weekend.", o: ["is", "will be", "was"], a: "will be",
      ru: "Надеюсь, на выходных будет хорошая погода.",
      why: "После hope о будущем — will be.", lvl: "B1" },

    { s: "I promise I ___ be late again.", o: ["won't", "am not going to", "don't"], a: "won't",
      ru: "Обещаю, я больше не опоздаю.",
      why: "Обещание — will not (won't).", lvl: "A2" },
    { s: "We ___ dinner at seven, the table is booked.", o: ["will have", "are having", "have"], a: "are having",
      ru: "Мы ужинаем в семь, столик забронирован.",
      why: "Договорённость с конкретным временем — Present Continuous.", lvl: "B1" },
    { s: "Do not call at eight — I ___ .", o: ["will study", "will be studying", "study"], a: "will be studying",
      ru: "Не звони в восемь — я буду заниматься.",
      why: "Процесс в конкретный момент будущего — Future Continuous.", lvl: "B2" },
    { s: "As soon as she ___ , we will start.", o: ["will come", "comes", "is coming"], a: "comes",
      ru: "Как только она придёт, мы начнём.",
      why: "После as soon as о будущем — настоящее время.", lvl: "B1" },
    { s: "Careful, you ___ the glass!", o: ["will drop", "are going to drop", "drop"], a: "are going to drop",
      ru: "Осторожно, ты сейчас уронишь стакан!",
      why: "Видно, что вот-вот случится, — be going to.", lvl: "B1" },
    { s: "Next Monday I ___ studying here for a year.", o: ["will be", "will have been", "am"], a: "will have been",
      ru: "В следующий понедельник будет год, как я здесь учусь.",
      why: "Длительность к моменту в будущем — Future Perfect Continuous.", lvl: "B2" },
  ],

};
