// Визуальные образы слов для карточек.
// Эмодзи вместо фотографий: мгновенно грузятся, работают офлайн,
// безопасны для детей и не требуют платных фотостоков.
// Абстрактным словам подобран образ-метафора, а не буквальная картинка.

const WORD_ART = {
  "juice": "🧃",
  "spoon": "🥄",
  "plate": "🍽️",
  "garden": "🌷",
  "shop": "🏪",
  "street": "🛣️",
  "park": "🏞️",
  "river": "🏞️",
  "winter": "❄️",
  "summer": "☀️",
  "doctor": "👨‍⚕️",
  "village": "🏘️",
  "forest": "🌲",
  "island": "🏝️",
  "wall": "🧱",
  "floor": "🔲",
  "slow": "🐌",
  "clean": "✨",
  "young": "🌱",
  "heavy": "🏋️",
  "careful": "⚠️",
  "brave": "🦁",
  "nervous": "😰",
  "lend": "🤝",
  "repeat": "🔁",
  "explain": "💬",
  "choose": "👉",
  "collect": "📦",
  "repair": "🔧",
  "save": "🏦",
  "challenge": "🎯",
  "develop": "📈",
  "encourage": "👏",
  "expect": "⏳",
  "familiar": "👀",
  "goal": "🥅",
  "influence": "🌊",
  "prefer": "💛",
  "realise": "💡",
  "responsible": "🎓",
  "solve": "🧩",
  "succeed": "🏆",
  "suffer": "😣",
  "suitable": "✅",
  "adequate": "👌",
  "consequence": "➡️",
  "considerable": "📊",
  "demonstrate": "🎬",
  "emphasise": "❗",
  "essential": "⭐",
  "furthermore": "➕",
  "gradually": "🐢",
  "implement": "🛠️",
  "indicate": "👉",
  "maintain": "🔩",
  "substantial": "📦",
  "tendency": "📉",
  "thorough": "🔍",
  "compile": "📚",
  "conceive": "💭",
  "elaborate": "📝",
  "viable": "✅",
  "astute": "🦉",
  "cogent": "🎯",
  "dearth": "🕳️",
  "eloquent": "🎤",
  "equivocal": "🌫️",
  "juxtapose": "⚖️",
  "penchant": "💘",
  "substantiate": "📑",
  "tacit": "🤐",
  "vociferous": "📢",
  // --- A1 ---
  apple: "🍎", water: "💧", milk: "🥛", food: "🍽️",
  house: "🏠", door: "🚪", book: "📖", school: "🏫",
  sun: "☀️", night: "🌙", morning: "🌅",
  cold: "🥶", big: "🐘", small: "🐁",
  happy: "😄", friend: "👫", family: "👨‍👩‍👧",
  run: "🏃", eat: "😋", sleep: "😴",

  // --- A2 ---
  weather: "🌦️", holiday: "🏖️", breakfast: "🥐",
  expensive: "💎", cheap: "🏷️", journey: "🗺️", luggage: "🧳",
  borrow: "🤲", arrive: "🛬", dangerous: "⚠️", famous: "🌟",
  healthy: "🥗", hungry: "🤤", invite: "💌", neighbour: "🏘️",
  promise: "🤝", quiet: "🤫", share: "🍕", terrible: "😱", weekend: "🎉",

  // --- B1 ---
  achieve: "🏆", advantage: "🃏", avoid: "🚧", behaviour: "🎭",
  confident: "💪", decrease: "📉", environment: "🌍", experience: "🎓",
  improve: "📈", income: "💰", opportunity: "🎯", persuade: "🗣️",
  pollution: "🏭", predict: "🔮", purpose: "🧭", reliable: "🛡️",
  solution: "💡", although: "🔀", definitely: "✅", curious: "🐈",

  // --- B2 ---
  accomplish: "🏁", ambiguous: "❓", anticipate: "🔭", assess: "📊",
  comprehensive: "📚", controversy: "⚖️", deliberately: "👉",
  distinguish: "🔍", emphasize: "❗", inevitable: "⏳", negotiate: "💼",
  perceive: "👁️", reluctant: "😕", significant: "⭐", subtle: "🪶",
  sustain: "🌱", tremendous: "🎆", undermine: "🪓", vague: "🌫️", widespread: "🌐",

  // --- C1 ---
  alleviate: "💊", coherent: "🧩", compelling: "🧲", discrepancy: "📐",
  feasible: "🗝️", meticulous: "🔬", notorious: "🦹", plausible: "🤔",
  profound: "🌊", scrutiny: "🕵️", tangible: "✋", ubiquitous: "📱",
  versatile: "🛠️", advocate: "📢", deteriorate: "🥀", intricate: "🕸️",
  resilient: "🎋", spontaneous: "💥", paradigm: "🏛️", endeavour: "🚀",

  // --- C2 ---
  capricious: "🌪️", ephemeral: "🫧", gregarious: "🫂", idiosyncrasy: "🦄",
  juxtaposition: "🖼️", magnanimous: "👑", obfuscate: "🌀", pernicious: "☠️",
  quintessential: "💯", serendipity: "🍀", taciturn: "🤐", vicissitude: "🎢",
  esoteric: "📜", laconic: "✂️", zealous: "🔥", obsequious: "🙇",

  // --- A1 (расширение) ---
  bread: "🍞", egg: "🥚", cheese: "🧀", tea: "🍵",
  banana: "🍌", cake: "🍰", meat: "🍖", rice: "🍚",
  soup: "🍲", mother: "👩", father: "👨", sister: "👭",
  brother: "👬", baby: "👶", grandmother: "👵", cat: "🐱",
  dog: "🐶", bird: "🐦", horse: "🐴", cow: "🐮",
  fish: "🐟", rabbit: "🐰", red: "🔴", blue: "🔵",
  green: "🟢", yellow: "🟡", black: "⚫", white: "⚪",
  good: "👍", bad: "👎", hot: "🥵", new: "🆕",
  one: "1️⃣", two: "2️⃣", three: "3️⃣", five: "5️⃣",
  ten: "🔟", pen: "🖊️", pencil: "✏️", teacher: "👩‍🏫",
  ruler: "📏", hand: "🖐️", leg: "🦵", foot: "🦶",
  nose: "👃", ear: "👂", mouth: "👄", tooth: "🦷",
  shirt: "👕", shoe: "👟", hat: "🧢", dress: "👗",
  coat: "🧥", sock: "🧦", chair: "🪑", bed: "🛏️",
  window: "🪟", kitchen: "🍳", key: "🔑", rain: "🌧️",
  snow: "❄️", wind: "💨", cloud: "☁️", tree: "🌳",
  flower: "🌷", sea: "🌊", mountain: "⛰️", walk: "🚶",
  swim: "🏊", jump: "🤸", sit: "💺", stand: "🧍",
  write: "✍️", drink: "🥤", sing: "🎤", dance: "💃",
  sad: "😢", angry: "😠", tired: "🥱", love: "❤️",

  // --- A2 (расширение) ---
  supermarket: "🛒", receipt: "🧾", price: "🏷️", spend: "💸",
  earn: "💵", wallet: "👛", bank: "🏦", ticket: "🎫",
  station: "🚉", bicycle: "🚲", taxi: "🚕", passenger: "🚌",
  airport: "🛫", traffic: "🚦", seat: "💺", drive: "🚗",
  bridge: "🌉", road: "🛣️", building: "🏢", museum: "🏛️",
  hotel: "🏨", hospital: "🏥", headache: "🤕", temperature: "🌡️",
  ill: "🤒", heart: "🫀", nurse: "👩‍⚕️", jacket: "🧥",
  scarf: "🧣", gloves: "🧤", boots: "🥾", wear: "👕",
  guitar: "🎸", paint: "🎨", draw: "✏️", win: "🥇",
  chess: "♟️", fishing: "🎣", gym: "🏋️", alarm: "⏰",
  shower: "🚿", wash: "🧼", mirror: "🪞", umbrella: "☂️",
  clock: "🕰️", cook: "👨‍🍳", lunch: "🥪", keyboard: "⌨️",
  headphones: "🎧", camera: "📷", battery: "🔋", message: "💬",
  afraid: "😨", surprised: "😲", worried: "😟", excited: "🤩",
  boring: "😑", lazy: "🦥", polite: "🙏", funny: "🤣",
  cloudy: "☁️", storm: "⛈️", always: "♾️", never: "🚫",
  often: "🔁", sometimes: "🎲", usually: "📆", early: "🐓",
  late: "🕚", busy: "📅",

  // --- B1 (расширение) ---
  colleague: "🧑‍🤝‍🧑", employer: "🧑‍💼", salary: "💵", apply: "📄",
  interview: "🎙️", career: "🧗", skill: "🤹", deadline: "⏰",
  manage: "🎛️", afford: "💳", degree: "🎓", essay: "📝",
  graduate: "👩‍🎓", attend: "🙋", progress: "🪜", knowledge: "🦉",
  concentrate: "🧘", memorize: "🧠", attitude: "💁", realize: "😲",
  consider: "🧐", doubt: "🤨", schedule: "🗓️", postpone: "🔜",
  arrange: "📋", deserve: "🎖️", suggest: "💬", complain: "😤",
  admit: "🫢", apologize: "🙏", discuss: "🗨️", argue: "🗯️",
  remind: "🔔", mention: "☝️", however: "↩️", therefore: "➡️",
  instead: "🔄", actually: "🔎", eventually: "⏱️", relationship: "👩‍❤️‍👨",
  trust: "🛟", support: "🙌", generous: "🎁", patient: "🐢",
  selfish: "🪞", honest: "😇", jealous: "💚", embarrassed: "😳",
  disappointed: "😞", proud: "🦚", lonely: "🧍", device: "🖥️",
  download: "📥", software: "💿", update: "🆕", charge: "🔋",
  compete: "🤼", coach: "📣", score: "🥅", athlete: "🏅",
  injury: "🤕", exhausted: "🥱", recycle: "♻️", waste: "🗑️",
  energy: "⚡", climate: "🌡️", protect: "☂️", increase: "⬆️",

  // --- B2 (расширение) ---
  justify: "🧑‍⚖️", assume: "💭", conclude: "🔚", evidence: "🧾",
  bias: "👓", flaw: "🕳️", outcome: "🎲", analyse: "🧮",
  estimate: "📏", phenomenon: "🌌", observe: "👀", imply: "🗨️",
  contradict: "🙅", clarify: "🔦", acknowledge: "🫡", claim: "🗯️",
  summarize: "📝", outline: "🗂️", objection: "🚫", consequently: "➡️",
  nevertheless: "↪️", moreover: "➕", whereas: "↔️", regardless: "🤷",
  somewhat: "🌗", inequality: "🪜", poverty: "🏚️", discrimination: "🚷",
  authority: "👮", democracy: "🗳️", campaign: "🪧", protest: "✊",
  reform: "🔧", welfare: "🛟", minority: "🧍", corruption: "💸",
  urban: "🏙️", budget: "📒", investment: "🪙", profit: "🤑",
  debt: "⛓️", wealth: "🛥️", consumer: "🛒", shortage: "🫙",
  unemployment: "📭", wage: "💵", currency: "💱", innovation: "⚙️",
  breakthrough: "⚡", artificial: "🤖", conduct: "📋", accurate: "📌",
  relevant: "📎", sufficient: "🔋", crucial: "🔑", beneficial: "💚",
  moderate: "🌡️", diverse: "🌈", gradual: "📶", drastic: "🌋",

  // --- C1 (расширение) ---
  inherent: "🧬", cumbersome: "🗄️", redundant: "🗑️", futile: "🌬️",
  mundane: "🧺", robust: "🦾", arbitrary: "🎲", constraint: "⛓️",
  entail: "🪢", premise: "🧱", criterion: "📋", mitigate: "🧯",
  exacerbate: "⛽", obsolete: "📟", proliferate: "🍄", reconcile: "🕊️",
  foster: "🪴", pragmatic: "🔧", candid: "🪞", sceptical: "🧐",
  complacent: "😌", impartial: "🧑‍⚖️", nuance: "🎨", articulate: "🗨️",
  convey: "📡", concede: "🏳️", lucrative: "🤑", incentive: "🥕",
  deficit: "💸", allocate: "🥧", legitimate: "🪪", consensus: "🙌",
  endorse: "👍", loophole: "🕳️", daunting: "⛰️", resent: "😤",
  apprehensive: "😟", exhilarating: "🪂", imminent: "🌩️", unprecedented: "🆕",
  milestone: "🚩", nonetheless: "↪️", hence: "➡️", conversely: "↔️",
  arguably: "🗯️", adhere: "📌", streamline: "⚙️", depict: "🖌️",

  // --- C2 (расширение) ---
  ineffable: "🌌", lugubrious: "😔", perfunctory: "⏩", recalcitrant: "🐎",
  truculent: "🥊", inexorable: "🚂", mellifluous: "🎶", ostensible: "🪞",
  protean: "🦎", sanguine: "🌤️", tenuous: "🧵", venerate: "🛐",
  assiduous: "🐜", cacophony: "🔊", ebullient: "🍾", fastidious: "🧼",
  garrulous: "🦜", hackneyed: "🥱", impecunious: "👛", maudlin: "😭",
  nebulous: "☁️", opulent: "🏰", supercilious: "🦚", trenchant: "🗡️",
  wistful: "🍂", anachronism: "🕰️", bucolic: "🐑", clandestine: "🕶️",
  incongruous: "🙃", ostracize: "🚷", vitriolic: "🧪", halcyon: "🕊️",
  inscrutable: "🗿", torpor: "🦥", equivocate: "↔️", myopic: "👓",
  seminal: "🌰", nascent: "🐣", wanderlust: "🎒", tantamount: "🟰",
};

// Слова, которые картинка действительно опознаёт: увидел образ — назвал слово.
// Только они попадают в упражнение «Слово и картинка»; у абстрактных слов
// вроде deliberately образ работает как напоминание, но не как загадка.
const PICTURABLE = new Set([
  "juice",
  "spoon",
  "plate",
  "garden",
  "shop",
  "park",
  "river",
  "winter",
  "summer",
  "doctor",
  "forest",
  "island",
  "wall",
  "street",
  "village",
  "apple", "water", "milk", "food", "house", "door", "book", "school",
  "sun", "night", "morning", "cold", "happy", "friend", "family",
  "run", "eat", "sleep",
  "weather", "holiday", "breakfast", "luggage", "dangerous", "healthy",
  "hungry", "quiet", "expensive", "neighbour", "invite",
  "environment", "pollution", "income", "solution", "confident", "achieve",
  "decrease", "improve", "predict",
  "negotiate", "emphasize", "sustain", "vague",
  "alleviate", "meticulous", "intricate", "advocate", "deteriorate",
  "ephemeral", "taciturn", "zealous", "magnanimous", "obsequious", "serendipity",
  // расширение базы
  "bread", "egg", "cheese", "tea", "banana", "cake",
  "meat", "rice", "soup", "baby", "grandmother", "cat",
  "dog", "bird", "horse", "cow", "fish", "rabbit",
  "red", "blue", "green", "yellow", "black", "white",
  "good", "bad", "hot", "new", "one", "two",
  "three", "five", "ten", "pen", "pencil", "teacher",
  "ruler", "hand", "leg", "foot", "nose", "ear",
  "mouth", "tooth", "shirt", "shoe", "hat", "dress",
  "coat", "sock", "chair", "bed", "window", "key",
  "rain", "snow", "cloud", "tree", "flower", "sea",
  "mountain", "walk", "swim", "write", "drink", "sing",
  "dance", "sad", "angry", "tired", "love", "supermarket",
  "receipt", "spend", "wallet", "bank", "ticket", "station",
  "bicycle", "taxi", "seat", "bridge", "road", "building",
  "hotel", "hospital", "headache", "temperature", "ill", "heart",
  "jacket", "scarf", "gloves", "boots", "guitar", "paint",
  "win", "chess", "fishing", "gym", "alarm", "shower",
  "mirror", "umbrella", "cook", "keyboard", "headphones", "camera",
  "battery", "message", "afraid", "surprised", "lazy", "funny",
  "storm", "charge", "injury", "recycle", "energy", "democracy",
  "protest", "urban", "currency", "artificial", "constraint", "concede",
  "endorse", "exhilarating",
]);

// Запасные образы по категориям — для слов, добавленных вручную
const CATEGORY_ART = {
  food: "🍽️", home: "🏠", objects: "📦", places: "📍", nature: "🌿",
  time: "⏰", qualities: "✨", feelings: "💭", people: "👥",
  actions: "⚡", travel: "✈️", communication: "💬", mind: "🧠",
  character: "🎭", change: "🔄", money: "💰", society: "🏙️", linkers: "🔗",
  family: "👨‍👩‍👧", animals: "🐾", school: "🎒", body: "🫀", clothes: "👕",
  weather: "🌦️", city: "🏙️", health: "💊", art: "🎨", sports: "⚽",
  tech: "💻", work: "💼",
};

// Фон карточки — свой оттенок на каждую категорию, чтобы слова
// визуально не сливались в одну кучу
const CATEGORY_TINT = {
  food: "#FFE8CC", home: "#FFE3D3", objects: "#EFE6DA", places: "#DDEEE6",
  nature: "#DCF0DC", time: "#E4E4F5", qualities: "#FFF0CC", feelings: "#FFE0E8",
  people: "#E6E9FA", actions: "#FFE1D6", travel: "#D9EEF7", communication: "#E9E2F7",
  mind: "#E3ECFB", character: "#F6E2F0", change: "#E0F0EA", money: "#E8F2D8",
  society: "#E7E7EF", linkers: "#EDEDED",
  family: "#FFE4EC", animals: "#E8F0D8", school: "#E2ECFA", body: "#FBE4E4",
  clothes: "#EDE4F7", weather: "#DCEEF8", city: "#E6E7EC", health: "#DFF2EC",
  art: "#FFEAD6", sports: "#DDEFE4", tech: "#E3E9F2", work: "#EFE9DC",
};

function wordArt(word, category) {
  const key = String(word || "").toLowerCase().trim();
  return WORD_ART[key] || CATEGORY_ART[category] || "🐾";
}

function wordTint(category) {
  return CATEGORY_TINT[category] || "#FFE8D6";
}

// Готовый блок с картинкой для карточки
function artBlock(word, category, size = "mid") {
  const div = document.createElement("div");
  div.className = "word-art word-art-" + size;
  div.style.background = wordTint(category);
  div.textContent = wordArt(word, category);
  return div;
}
