// Уровни, их названия и небольшие вспомогательные списки.
//
// Вынесено из words.js, и это не косметика. Сам словарь — 1,1 МБ на диске
// и 326 КБ по проводу; эти же константы весят пару килобайт, но нужны
// почти везде: подпись уровня в шапке, названия тем в панели репетитора,
// оценка запаса после теста. Пока они лежали в одном файле со словарём,
// словарь приходилось грузить всем и сразу — в том числе тому, кто ещё
// не завёл аккаунт и видит только экран приветствия.
//
// Теперь маленькое грузится всегда, большое — когда действительно нужно
// (ensureWords в js/util.js).

const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Примерный прирост словарного запаса на каждом уровне
const LEVEL_VOCAB_SIZE = { A1: 500, A2: 500, B1: 1000, B2: 2000, C1: 4000, C2: 8000 };

const LEVEL_NAMES = {
  A1: "Начинающий",
  A2: "Элементарный",
  B1: "Средний",
  B2: "Выше среднего",
  C1: "Продвинутый",
  C2: "Свободное владение",
};

const CATEGORY_NAMES = {
  food: "Еда", home: "Дом", objects: "Вещи", places: "Места", nature: "Природа",
  time: "Время", qualities: "Качества", feelings: "Чувства", people: "Люди",
  actions: "Действия", travel: "Дорога и отдых", communication: "Общение",
  mind: "Мышление", character: "Характер", change: "Изменения",
  money: "Деньги и работа", society: "Общество", linkers: "Слова-связки",
  family: "Семья", animals: "Животные", school: "Школа", body: "Тело",
  clothes: "Одежда", weather: "Погода", city: "Город", health: "Здоровье",
  art: "Творчество", sports: "Спорт", tech: "Техника", work: "Работа",
};

// Устойчивые сочетания (Collocation Matching) — пары подобраны так,
// чтобы перекрёстные комбинации были ошибочными
const COLLOCATIONS = [
  { h: "make", tl: "a decision" },
  { h: "do", tl: "homework" },
  { h: "take", tl: "a photo" },
  { h: "have", tl: "breakfast" },
  { h: "pay", tl: "attention" },
  { h: "tell", tl: "the truth" },
  { h: "keep", tl: "a secret" },
  { h: "catch", tl: "a cold" },

  /* Пополнение банка. Было восемь сочетаний, а за подход показывается
     пять — то есть каждый раз выпадало почти одно и то же, и упражнение
     переставало учить после второго захода. На это и пожаловались.
     Здесь школьные сочетания, которые действительно спрашивают: связки
     с make/do/take/have и обиходные глаголы. Русскому уху они не
     очевидны — «делать ошибку» это make a mistake, а не do. */
  { h: "make", tl: "a mistake" },
  { h: "make", tl: "friends" },
  { h: "make", tl: "noise" },
  { h: "make", tl: "progress" },
  { h: "make", tl: "the bed" },
  { h: "do", tl: "the washing-up" },
  { h: "do", tl: "sport" },
  { h: "do", tl: "your best" },
  { h: "do", tl: "an exercise" },
  { h: "take", tl: "a shower" },
  { h: "take", tl: "a bus" },
  { h: "take", tl: "a seat" },
  { h: "take", tl: "care" },
  { h: "take", tl: "an exam" },
  { h: "have", tl: "a rest" },
  { h: "have", tl: "fun" },
  { h: "have", tl: "a look" },
  { h: "have", tl: "a headache" },
  { h: "have", tl: "a party" },
  { h: "get", tl: "dressed" },
  { h: "get", tl: "married" },
  { h: "get", tl: "lost" },
  { h: "get", tl: "a job" },
  { h: "give", tl: "advice" },
  { h: "give", tl: "a hand" },
  { h: "give", tl: "a speech" },
  { h: "keep", tl: "calm" },
  { h: "keep", tl: "in touch" },
  { h: "keep", tl: "a promise" },
  { h: "pay", tl: "a visit" },
  { h: "pay", tl: "the bill" },
  { h: "catch", tl: "a train" },
  { h: "catch", tl: "fire" },
  { h: "break", tl: "a promise" },
  { h: "break", tl: "the rules" },
  { h: "break", tl: "a record" },
  { h: "save", tl: "money" },
  { h: "save", tl: "time" },
  { h: "spend", tl: "time" },
  { h: "waste", tl: "time" },
  { h: "tell", tl: "a lie" },
  { h: "tell", tl: "a story" },
  { h: "tell", tl: "a joke" },
  { h: "ask", tl: "a question" },
  { h: "ask", tl: "for help" },
  { h: "answer", tl: "the phone" },
  { h: "miss", tl: "the bus" },
  { h: "miss", tl: "a lesson" },
  { h: "watch", tl: "a film" },
  { h: "listen to", tl: "music" },
  { h: "play", tl: "the guitar" },
  { h: "ride", tl: "a bike" },
  { h: "wear", tl: "a uniform" },
  { h: "brush", tl: "your teeth" },
  { h: "solve", tl: "a problem" },
  { h: "set", tl: "a goal" },
  { h: "run", tl: "late" },
  { h: "feel", tl: "at home" },

  { h: "make", tl: "an effort" },
  { h: "make", tl: "a plan" },
  { h: "make", tl: "a suggestion" },
  { h: "make", tl: "a phone call" },
  { h: "make", tl: "money" },
  { h: "make", tl: "a difference" },
  { h: "make", tl: "sense" },
  { h: "make", tl: "a wish" },
  { h: "make", tl: "an excuse" },
  { h: "make", tl: "a choice" },
  { h: "do", tl: "the shopping" },
  { h: "do", tl: "the dishes" },
  { h: "do", tl: "a favour" },
  { h: "do", tl: "research" },
  { h: "do", tl: "damage" },
  { h: "do", tl: "business" },
  { h: "do", tl: "the housework" },
  { h: "take", tl: "a break" },
  { h: "take", tl: "a taxi" },
  { h: "take", tl: "notes" },
  { h: "take", tl: "a risk" },
  { h: "take", tl: "place" },
  { h: "take", tl: "part" },
  { h: "take", tl: "medicine" },
  { h: "take", tl: "a walk" },
  { h: "have", tl: "a dream" },
  { h: "have", tl: "a problem" },
  { h: "have", tl: "an idea" },
  { h: "have", tl: "lunch" },
  { h: "have", tl: "dinner" },
  { h: "have", tl: "a chat" },
  { h: "have", tl: "a good time" },
  { h: "have", tl: "a bath" },
  { h: "have", tl: "a snack" },
  { h: "get", tl: "ready" },
  { h: "get", tl: "angry" },
  { h: "get", tl: "home" },
  { h: "get", tl: "a present" },
  { h: "get", tl: "permission" },
  { h: "get", tl: "a message" },
  { h: "get", tl: "hurt" },
  { h: "get", tl: "better" },
  { h: "give", tl: "an example" },
  { h: "give", tl: "a lift" },
  { h: "give", tl: "an answer" },
  { h: "give", tl: "a call" },
  { h: "give", tl: "a reason" },
  { h: "give", tl: "a present" },
  { h: "keep", tl: "a diary" },
  { h: "keep", tl: "quiet" },
  { h: "keep", tl: "your word" },
  { h: "keep", tl: "fit" },
  { h: "keep", tl: "an eye on" },
  { h: "pay", tl: "a compliment" },
  { h: "pay", tl: "by card" },
  { h: "pay", tl: "respect" },
  { h: "catch", tl: "a bus" },
  { h: "catch", tl: "the ball" },
  { h: "catch", tl: "a fish" },
  { h: "break", tl: "the news" },
  { h: "break", tl: "a window" },
  { h: "break", tl: "the silence" },
  { h: "break", tl: "a habit" },
  { h: "break", tl: "the law" },
  { h: "save", tl: "a life" },
  { h: "save", tl: "a seat" },
  { h: "save", tl: "energy" },
  { h: "save", tl: "a file" },
  { h: "spend", tl: "the weekend" },
  { h: "spend", tl: "a holiday" },
  { h: "spend", tl: "a night" },
  { h: "waste", tl: "money" },
  { h: "waste", tl: "food" },
  { h: "waste", tl: "paper" },
  { h: "tell", tl: "the difference" },
  { h: "tell", tl: "the time" },
  { h: "tell", tl: "the way" },
  { h: "ask", tl: "for directions" },
  { h: "ask", tl: "permission" },
  { h: "ask", tl: "a favour" },
  { h: "answer", tl: "an email" },
  { h: "answer", tl: "the door" },
  { h: "miss", tl: "a chance" },
  { h: "miss", tl: "the point" },
  { h: "miss", tl: "a deadline" },
  { h: "watch", tl: "a match" },
  { h: "watch", tl: "a video" },
  { h: "listen to", tl: "the radio" },
  { h: "listen to", tl: "a podcast" },
  { h: "listen to", tl: "the teacher" },
  { h: "play", tl: "chess" },
  { h: "play", tl: "football" },
  { h: "play", tl: "a game" },
  { h: "play", tl: "a role" },
  { h: "ride", tl: "a horse" },
  { h: "ride", tl: "a scooter" },
  { h: "wear", tl: "glasses" },
  { h: "wear", tl: "a scarf" },
  { h: "wear", tl: "jeans" },
  { h: "solve", tl: "a puzzle" },
  { h: "solve", tl: "a mystery" },
  { h: "set", tl: "an alarm" },
  { h: "set", tl: "the table" },
  { h: "set", tl: "an example" },
  { h: "set", tl: "a date" },
  { h: "run", tl: "a business" },
  { h: "run", tl: "a marathon" },
  { h: "feel", tl: "better" },
  { h: "feel", tl: "sick" },
  { h: "feel", tl: "sorry" },
  { h: "feel", tl: "free" },
  { h: "go", tl: "shopping" },
  { h: "go", tl: "abroad" },
  { h: "go", tl: "online" },
  { h: "go", tl: "to bed" },
  { h: "go", tl: "for a walk" },
  { h: "go", tl: "camping" },
  { h: "go", tl: "on holiday" },
  { h: "come", tl: "home" },
  { h: "come", tl: "first" },
  { h: "come", tl: "true" },
  { h: "come", tl: "on time" },
  { h: "join", tl: "a club" },
  { h: "join", tl: "a team" },
  { h: "win", tl: "a prize" },
  { h: "win", tl: "a medal" },
  { h: "win", tl: "a competition" },
  { h: "lose", tl: "weight" },
  { h: "lose", tl: "your temper" },
  { h: "lose", tl: "your keys" },
  { h: "meet", tl: "a friend" },
  { h: "meet", tl: "a deadline" },
  { h: "meet", tl: "expectations" },
  { h: "follow", tl: "the rules" },
  { h: "follow", tl: "instructions" },
  { h: "follow", tl: "advice" },
  { h: "pass", tl: "an exam" },
  { h: "pass", tl: "the salt" },
  { h: "read", tl: "a book" },
  { h: "read", tl: "a map" },
  { h: "read", tl: "the news" },
  { h: "write", tl: "an essay" },
  { h: "write", tl: "a letter" },
  { h: "draw", tl: "a picture" },
  { h: "draw", tl: "a conclusion" },
  { h: "learn", tl: "a language" },
  { h: "learn", tl: "by heart" },
  { h: "send", tl: "a message" },
  { h: "send", tl: "an email" },
  { h: "send", tl: "a postcard" },
  { h: "book", tl: "a ticket" },
  { h: "book", tl: "a table" },
  { h: "book", tl: "a room" },
  { h: "order", tl: "a pizza" },
  { h: "order", tl: "a taxi" },
  { h: "cook", tl: "dinner" },
  { h: "wash", tl: "your hands" },
  { h: "wash", tl: "the car" },
  { h: "clean", tl: "your room" },
  { h: "clean", tl: "the windows" },
  { h: "climb", tl: "a mountain" },
  { h: "climb", tl: "a tree" },
  { h: "drive", tl: "a car" },
  { h: "cross", tl: "the road" },
  { h: "park", tl: "a car" },
  { h: "change", tl: "your mind" },
  { h: "change", tl: "the subject" },
  { h: "reach", tl: "an agreement" },
  { h: "reach", tl: "the top" },
];

/* Синонимы и антонимы.
 *
 * Переводы обязательны у всех трёх слов. Без них упражнение проверяло
 * чутьё вслепую: ученик видел «meticulous → thorough / careless» и,
 * даже угадав, не узнавал, что это значит (жалоба методиста). Теперь
 * при ошибке показывается разбор с переводами всей тройки.
 *
 * Поля: w — заглавное слово, ru — его перевод; syn/synRu — синоним,
 * ant/antRu — антоним. Пары школьные: и синоним, и антоним должны быть
 * знакомыми словами, иначе упражнение проверяет везение.
 *
 * lvl — уровень пары. Банк вырос с шестидесяти пар до двух с лишним
 * сотен, и вместе с ним выросла разница между «big — large» и
 * «ubiquitous — everywhere». Без уровня шестикласснику прилетало
 * второе, он не понимал ни одного из четырёх вариантов и тыкал наугад.
 * Упражнение берёт пары своего уровня и соседних (см. synonyms()).
 */
const SYNONYMS = [
  { w: "always", ru: "всегда", syn: "constantly", synRu: "постоянно", ant: "never", antRu: "никогда", lvl: "A1" },
  { w: "answer", ru: "отвечать", syn: "reply", synRu: "откликаться", ant: "ask", antRu: "спрашивать", lvl: "A1" },
  { w: "ask", ru: "спрашивать", syn: "enquire", synRu: "осведомляться", ant: "answer", antRu: "отвечать", lvl: "A1" },
  { w: "beautiful", ru: "красивый", syn: "pretty", synRu: "хорошенький", ant: "ugly", antRu: "уродливый", lvl: "A1" },
  { w: "begin", ru: "начинать", syn: "start", synRu: "стартовать", ant: "finish", antRu: "заканчивать", lvl: "A1" },
  { w: "big", ru: "большой", syn: "large", synRu: "крупный", ant: "small", antRu: "маленький", lvl: "A1" },
  { w: "buy", ru: "покупать", syn: "purchase", synRu: "приобретать", ant: "sell", antRu: "продавать", lvl: "A1" },
  { w: "close", ru: "закрывать", syn: "shut", synRu: "затворять", ant: "open", antRu: "открывать", lvl: "A1" },
  { w: "cold", ru: "холодный", syn: "chilly", synRu: "прохладный", ant: "hot", antRu: "горячий", lvl: "A1" },
  { w: "cry", ru: "плакать", syn: "weep", synRu: "рыдать", ant: "laugh", antRu: "смеяться", lvl: "A1" },
  { w: "dirty", ru: "грязный", syn: "filthy", synRu: "чумазый", ant: "clean", antRu: "чистый", lvl: "A1" },
  { w: "easy", ru: "лёгкий", syn: "simple", synRu: "несложный", ant: "hard", antRu: "трудный", lvl: "A1" },
  { w: "end", ru: "конец", syn: "finish", synRu: "финиш", ant: "beginning", antRu: "начало", lvl: "A1" },
  { w: "fast", ru: "быстрый", syn: "quick", synRu: "скорый", ant: "slow", antRu: "медленный", lvl: "A1" },
  { w: "find", ru: "находить", syn: "discover", synRu: "обнаруживать", ant: "lose", antRu: "терять", lvl: "A1" },
  { w: "finish", ru: "заканчивать", syn: "complete", synRu: "завершать", ant: "begin", antRu: "начинать", lvl: "A1" },
  { w: "friend", ru: "друг", syn: "mate", synRu: "приятель", ant: "enemy", antRu: "враг", lvl: "A1" },
  { w: "give", ru: "давать", syn: "hand", synRu: "передавать", ant: "take", antRu: "брать", lvl: "A1" },
  { w: "happy", ru: "счастливый", syn: "glad", synRu: "радостный", ant: "sad", antRu: "грустный", lvl: "A1" },
  { w: "hate", ru: "ненавидеть", syn: "detest", synRu: "терпеть не мочь", ant: "love", antRu: "любить", lvl: "A1" },
  { w: "help", ru: "помогать", syn: "assist", synRu: "содействовать", ant: "hinder", antRu: "мешать", lvl: "A1" },
  { w: "hot", ru: "горячий", syn: "boiling", synRu: "кипящий", ant: "freezing", antRu: "ледяной", lvl: "A1" },
  { w: "hungry", ru: "голодный", syn: "starving", synRu: "умирающий с голоду", ant: "full up", antRu: "сытый", lvl: "A1" },
  { w: "laugh", ru: "смеяться", syn: "giggle", synRu: "хихикать", ant: "cry", antRu: "плакать", lvl: "A1" },
  { w: "long", ru: "длинный", syn: "lengthy", synRu: "затянувшийся", ant: "short", antRu: "короткий", lvl: "A1" },
  { w: "lose", ru: "терять", syn: "mislay", synRu: "задевать куда-то", ant: "find", antRu: "находить", lvl: "A1" },
  { w: "love", ru: "любить", syn: "adore", synRu: "обожать", ant: "hate", antRu: "ненавидеть", lvl: "A1" },
  { w: "never", ru: "никогда", syn: "not once", synRu: "ни разу", ant: "always", antRu: "всегда", lvl: "A1" },
  { w: "new", ru: "новый", syn: "brand-new", synRu: "совсем новый", ant: "old", antRu: "старый", lvl: "A1" },
  { w: "often", ru: "часто", syn: "frequently", synRu: "регулярно", ant: "rarely", antRu: "редко", lvl: "A1" },
  { w: "old", ru: "старый", syn: "ancient", synRu: "древний", ant: "modern", antRu: "современный", lvl: "A1" },
  { w: "pull", ru: "тянуть", syn: "drag", synRu: "волочить", ant: "push", antRu: "толкать", lvl: "A1" },
  { w: "push", ru: "толкать", syn: "shove", synRu: "пихать", ant: "pull", antRu: "тянуть", lvl: "A1" },
  { w: "sad", ru: "грустный", syn: "unhappy", synRu: "несчастный", ant: "cheerful", antRu: "весёлый", lvl: "A1" },
  { w: "short", ru: "короткий", syn: "brief", synRu: "краткий", ant: "long", antRu: "длинный", lvl: "A1" },
  { w: "show", ru: "показывать", syn: "display", synRu: "демонстрировать", ant: "hide", antRu: "прятать", lvl: "A1" },
  { w: "slow", ru: "медленный", syn: "unhurried", synRu: "неторопливый", ant: "rapid", antRu: "стремительный", lvl: "A1" },
  { w: "small", ru: "маленький", syn: "tiny", synRu: "крошечный", ant: "enormous", antRu: "громадный", lvl: "A1" },
  { w: "speak", ru: "говорить", syn: "talk", synRu: "разговаривать", ant: "listen", antRu: "слушать", lvl: "A1" },
  { w: "stop", ru: "останавливать", syn: "halt", synRu: "прекращать", ant: "continue", antRu: "продолжать", lvl: "A1" },
  { w: "strong", ru: "сильный", syn: "powerful", synRu: "мощный", ant: "weak", antRu: "слабый", lvl: "A1" },
  { w: "take", ru: "брать", syn: "grab", synRu: "хватать", ant: "give", antRu: "давать", lvl: "A1" },
  { w: "tired", ru: "усталый", syn: "exhausted", synRu: "измотанный", ant: "energetic", antRu: "энергичный", lvl: "A1" },
  { w: "young", ru: "молодой", syn: "youthful", synRu: "юный", ant: "elderly", antRu: "пожилой", lvl: "A1" },

  { w: "afraid", ru: "испуганный", syn: "scared", synRu: "напуганный", ant: "fearless", antRu: "бесстрашный", lvl: "A2" },
  { w: "angry", ru: "сердитый", syn: "annoyed", synRu: "раздражённый", ant: "calm", antRu: "спокойный", lvl: "A2" },
  { w: "arrive", ru: "прибывать", syn: "reach", synRu: "добираться", ant: "depart", antRu: "отбывать", lvl: "A2" },
  { w: "awful", ru: "ужасный", syn: "horrible", synRu: "отвратительный", ant: "lovely", antRu: "прелестный", lvl: "A2" },
  { w: "beginning", ru: "начало", syn: "opening", synRu: "первые минуты", ant: "ending", antRu: "концовка", lvl: "A2" },
  { w: "boring", ru: "скучный", syn: "dull", synRu: "нудный", ant: "interesting", antRu: "интересный", lvl: "A2" },
  { w: "brave", ru: "храбрый", syn: "courageous", synRu: "отважный", ant: "cowardly", antRu: "трусливый", lvl: "A2" },
  { w: "break", ru: "ломать", syn: "smash", synRu: "разбивать вдребезги", ant: "repair", antRu: "чинить", lvl: "A2" },
  { w: "bright", ru: "яркий", syn: "shiny", synRu: "блестящий", ant: "dull", antRu: "тусклый", lvl: "A2" },
  { w: "build", ru: "строить", syn: "construct", synRu: "возводить", ant: "destroy", antRu: "разрушать", lvl: "A2" },
  { w: "busy", ru: "занятой", syn: "occupied", synRu: "загруженный делами", ant: "free", antRu: "свободный", lvl: "A2" },
  { w: "calm", ru: "спокойный", syn: "peaceful", synRu: "умиротворённый", ant: "nervous", antRu: "нервный", lvl: "A2" },
  { w: "catch", ru: "ловить", syn: "capture", synRu: "поймать", ant: "release", antRu: "отпускать", lvl: "A2" },
  { w: "cheap", ru: "дешёвый", syn: "inexpensive", synRu: "недорогой", ant: "expensive", antRu: "дорогой", lvl: "A2" },
  { w: "choose", ru: "выбирать", syn: "pick", synRu: "отобрать", ant: "refuse", antRu: "отказываться", lvl: "A2" },
  { w: "clean", ru: "чистый", syn: "spotless", synRu: "без единого пятнышка", ant: "dirty", antRu: "грязный", lvl: "A2" },
  { w: "clever", ru: "умный", syn: "smart", synRu: "сообразительный", ant: "stupid", antRu: "глупый", lvl: "A2" },
  { w: "continue", ru: "продолжать", syn: "carry on", synRu: "не бросать", ant: "stop", antRu: "прекращать", lvl: "A2" },
  { w: "correct", ru: "правильный", syn: "right", synRu: "верный", ant: "wrong", antRu: "неверный", lvl: "A2" },
  { w: "danger", ru: "опасность", syn: "risk", synRu: "риск", ant: "safety", antRu: "безопасность", lvl: "A2" },
  { w: "dangerous", ru: "опасный", syn: "risky", synRu: "рискованный", ant: "safe", antRu: "безопасный", lvl: "A2" },
  { w: "deep", ru: "глубокий", syn: "profound", synRu: "глубокий по смыслу", ant: "shallow", antRu: "мелкий", lvl: "A2" },
  { w: "delicious", ru: "вкусный", syn: "tasty", synRu: "аппетитный", ant: "disgusting", antRu: "противный", lvl: "A2" },
  { w: "difficult", ru: "трудный", syn: "hard", synRu: "сложный", ant: "easy", antRu: "лёгкий", lvl: "A2" },
  { w: "early", ru: "ранний", syn: "ahead of time", synRu: "заранее", ant: "late", antRu: "поздний", lvl: "A2" },
  { w: "empty", ru: "пустой", syn: "bare", synRu: "голый, ничем не занятый", ant: "full", antRu: "полный", lvl: "A2" },
  { w: "enemy", ru: "враг", syn: "opponent", synRu: "противник", ant: "friend", antRu: "друг", lvl: "A2" },
  { w: "enter", ru: "входить", syn: "go inside", synRu: "заходить внутрь", ant: "exit", antRu: "выходить", lvl: "A2" },
  { w: "everywhere", ru: "везде", syn: "all over", synRu: "повсюду", ant: "nowhere", antRu: "нигде", lvl: "A2" },
  { w: "excited", ru: "взволнованный от радости", syn: "thrilled", synRu: "в полном восторге", ant: "bored", antRu: "скучающий", lvl: "A2" },
  { w: "expensive", ru: "дорогой", syn: "pricey", synRu: "дороговатый", ant: "cheap", antRu: "дешёвый", lvl: "A2" },
  { w: "fall", ru: "падать", syn: "drop", synRu: "опускаться", ant: "rise", antRu: "подниматься", lvl: "A2" },
  { w: "famous", ru: "знаменитый", syn: "well-known", synRu: "широко известный", ant: "unknown", antRu: "неизвестный", lvl: "A2" },
  { w: "far", ru: "далёкий", syn: "distant", synRu: "отдалённый", ant: "nearby", antRu: "близкий", lvl: "A2" },
  { w: "forget", ru: "забывать", syn: "overlook", synRu: "упускать из виду", ant: "remember", antRu: "помнить", lvl: "A2" },
  { w: "free", ru: "свободный", syn: "available", synRu: "незанятый", ant: "busy", antRu: "занятый", lvl: "A2" },
  { w: "friendly", ru: "дружелюбный", syn: "welcoming", synRu: "приветливый", ant: "unfriendly", antRu: "недружелюбный", lvl: "A2" },
  { w: "funny", ru: "смешной", syn: "amusing", synRu: "забавный", ant: "serious", antRu: "серьёзный", lvl: "A2" },
  { w: "glad", ru: "довольный", syn: "pleased", synRu: "обрадованный", ant: "upset", antRu: "расстроенный", lvl: "A2" },
  { w: "hardworking", ru: "трудолюбивый", syn: "diligent", synRu: "усердный", ant: "lazy", antRu: "ленивый", lvl: "A2" },
  { w: "healthy", ru: "здоровый", syn: "fit", synRu: "в хорошей форме", ant: "unhealthy", antRu: "нездоровый", lvl: "A2" },
  { w: "heavy", ru: "тяжёлый", syn: "weighty", synRu: "увесистый", ant: "light", antRu: "лёгкий", lvl: "A2" },
  { w: "hide", ru: "прятать", syn: "conceal", synRu: "скрывать", ant: "reveal", antRu: "раскрывать", lvl: "A2" },
  { w: "high", ru: "высокий", syn: "elevated", synRu: "приподнятый", ant: "low", antRu: "низкий", lvl: "A2" },
  { w: "honest", ru: "честный", syn: "truthful", synRu: "правдивый", ant: "dishonest", antRu: "нечестный", lvl: "A2" },
  { w: "huge", ru: "огромный", syn: "gigantic", synRu: "гигантский", ant: "tiny", antRu: "крошечный", lvl: "A2" },
  { w: "important", ru: "важный", syn: "essential", synRu: "необходимый", ant: "unimportant", antRu: "неважный", lvl: "A2" },
  { w: "interesting", ru: "интересный", syn: "fascinating", synRu: "увлекательный", ant: "boring", antRu: "скучный", lvl: "A2" },
  { w: "keep", ru: "хранить", syn: "retain", synRu: "сохранять", ant: "throw away", antRu: "выбрасывать", lvl: "A2" },
  { w: "kind", ru: "добрый", syn: "gentle", synRu: "мягкий", ant: "cruel", antRu: "жестокий", lvl: "A2" },
  { w: "late", ru: "поздний", syn: "delayed", synRu: "запоздалый", ant: "early", antRu: "ранний", lvl: "A2" },
  { w: "lazy", ru: "ленивый", syn: "idle", synRu: "бездельничающий", ant: "hardworking", antRu: "трудолюбивый", lvl: "A2" },
  { w: "leave", ru: "уезжать", syn: "set off", synRu: "отправляться", ant: "arrive", antRu: "приезжать", lvl: "A2" },
  { w: "lie", ru: "ложь", syn: "falsehood", synRu: "неправда", ant: "truth", antRu: "правда", lvl: "A2" },
  { w: "light", ru: "лёгкий (по весу)", syn: "lightweight", synRu: "невесомый", ant: "heavy", antRu: "тяжёлый", lvl: "A2" },
  { w: "loud", ru: "громкий", syn: "noisy", synRu: "шумный", ant: "soft", antRu: "тихий", lvl: "A2" },
  { w: "lovely", ru: "прелестный", syn: "delightful", synRu: "восхитительный", ant: "nasty", antRu: "мерзкий", lvl: "A2" },
  { w: "low", ru: "низкий", syn: "minimal", synRu: "самый маленький", ant: "high", antRu: "высокий", lvl: "A2" },
  { w: "messy", ru: "неубранный", syn: "untidy", synRu: "неопрятный", ant: "tidy", antRu: "опрятный", lvl: "A2" },
  { w: "modern", ru: "современный", syn: "up-to-date", synRu: "идущий в ногу со временем", ant: "old-fashioned", antRu: "старомодный", lvl: "A2" },
  { w: "near", ru: "близкий", syn: "close by", synRu: "рядом", ant: "far", antRu: "далёкий", lvl: "A2" },
  { w: "nervous", ru: "нервный", syn: "anxious", synRu: "тревожный", ant: "relaxed", antRu: "расслабленный", lvl: "A2" },
  { w: "noise", ru: "шум", syn: "racket", synRu: "грохот", ant: "silence", antRu: "тишина", lvl: "A2" },
  { w: "polite", ru: "вежливый", syn: "courteous", synRu: "учтивый", ant: "rude", antRu: "грубый", lvl: "A2" },
  { w: "possible", ru: "возможный", syn: "likely", synRu: "вероятный", ant: "impossible", antRu: "невозможный", lvl: "A2" },
  { w: "question", ru: "вопрос", syn: "query", synRu: "запрос", ant: "reply", antRu: "ответ", lvl: "A2" },
  { w: "quickly", ru: "быстро", syn: "rapidly", synRu: "стремительно", ant: "slowly", antRu: "медленно", lvl: "A2" },
  { w: "quiet", ru: "тихий", syn: "silent", synRu: "безмолвный", ant: "noisy", antRu: "шумный", lvl: "A2" },
  { w: "rarely", ru: "редко", syn: "seldom", synRu: "нечасто", ant: "often", antRu: "часто", lvl: "A2" },
  { w: "real", ru: "настоящий", syn: "genuine", synRu: "подлинный", ant: "fake", antRu: "поддельный", lvl: "A2" },
  { w: "remember", ru: "помнить", syn: "recall", synRu: "припоминать", ant: "forget", antRu: "забывать", lvl: "A2" },
  { w: "repair", ru: "чинить", syn: "fix", synRu: "ремонтировать", ant: "break", antRu: "ломать", lvl: "A2" },
  { w: "rich", ru: "богатый", syn: "wealthy", synRu: "состоятельный", ant: "poor", antRu: "бедный", lvl: "A2" },
  { w: "safe", ru: "безопасный", syn: "secure", synRu: "защищённый", ant: "dangerous", antRu: "опасный", lvl: "A2" },
  { w: "safety", ru: "безопасность", syn: "security", synRu: "защищённость", ant: "danger", antRu: "опасность", lvl: "A2" },
  { w: "save", ru: "экономить", syn: "put aside", synRu: "откладывать", ant: "spend", antRu: "тратить", lvl: "A2" },
  { w: "shout", ru: "кричать", syn: "yell", synRu: "вопить", ant: "whisper", antRu: "шептать", lvl: "A2" },
  { w: "shy", ru: "застенчивый", syn: "timid", synRu: "робкий", ant: "confident", antRu: "уверенный в себе", lvl: "A2" },
  { w: "sick", ru: "больной", syn: "ill", synRu: "нездоровый", ant: "healthy", antRu: "здоровый", lvl: "A2" },
  { w: "silence", ru: "тишина", syn: "stillness", synRu: "полное безмолвие", ant: "noise", antRu: "шум", lvl: "A2" },
  { w: "silly", ru: "глупый", syn: "foolish", synRu: "неразумный", ant: "sensible", antRu: "благоразумный", lvl: "A2" },
  { w: "simple", ru: "простой", syn: "straightforward", synRu: "понятный без объяснений", ant: "complicated", antRu: "запутанный", lvl: "A2" },
  { w: "sleepy", ru: "сонный", syn: "drowsy", synRu: "клюющий носом", ant: "wide awake", antRu: "бодрый", lvl: "A2" },
  { w: "slowly", ru: "медленно", syn: "gradually", synRu: "постепенно", ant: "quickly", antRu: "быстро", lvl: "A2" },
  { w: "soft", ru: "мягкий", syn: "tender", synRu: "нежный", ant: "firm", antRu: "твёрдый", lvl: "A2" },
  { w: "spend", ru: "тратить", syn: "use up", synRu: "расходовать", ant: "save", antRu: "копить", lvl: "A2" },
  { w: "stay", ru: "оставаться", syn: "remain", synRu: "пребывать", ant: "go away", antRu: "уходить", lvl: "A2" },
  { w: "strange", ru: "странный", syn: "odd", synRu: "чудной", ant: "normal", antRu: "обычный", lvl: "A2" },
  { w: "sure", ru: "уверенный", syn: "certain", synRu: "не сомневающийся", ant: "doubtful", antRu: "сомневающийся", lvl: "A2" },
  { w: "surprised", ru: "удивлённый", syn: "astonished", synRu: "изумлённый", ant: "unsurprised", antRu: "ничуть не удивлённый", lvl: "A2" },
  { w: "teach", ru: "обучать", syn: "instruct", synRu: "наставлять", ant: "learn", antRu: "учиться", lvl: "A2" },
  { w: "terrible", ru: "ужасный", syn: "awful", synRu: "отвратительный", ant: "wonderful", antRu: "замечательный", lvl: "A2" },
  { w: "thick", ru: "толстый", syn: "dense", synRu: "плотный", ant: "thin", antRu: "тонкий", lvl: "A2" },
  { w: "thin", ru: "тонкий", syn: "slim", synRu: "стройный", ant: "thick", antRu: "толстый", lvl: "A2" },
  { w: "throw", ru: "бросать", syn: "toss", synRu: "кидать", ant: "catch", antRu: "ловить", lvl: "A2" },
  { w: "tidy", ru: "опрятный", syn: "neat", synRu: "аккуратный", ant: "messy", antRu: "неубранный", lvl: "A2" },
  { w: "truth", ru: "правда", syn: "fact", synRu: "факт", ant: "lie", antRu: "ложь", lvl: "A2" },
  { w: "useful", ru: "полезный", syn: "helpful", synRu: "выручающий", ant: "useless", antRu: "бесполезный", lvl: "A2" },
  { w: "usual", ru: "обычный", syn: "ordinary", synRu: "заурядный", ant: "unusual", antRu: "необычный", lvl: "A2" },
  { w: "wet", ru: "мокрый", syn: "damp", synRu: "влажный", ant: "dry", antRu: "сухой", lvl: "A2" },
  { w: "wide", ru: "широкий", syn: "broad", synRu: "просторный", ant: "narrow", antRu: "узкий", lvl: "A2" },
  { w: "win", ru: "побеждать", syn: "triumph", synRu: "торжествовать", ant: "lose", antRu: "проигрывать", lvl: "A2" },
  { w: "wonderful", ru: "замечательный", syn: "marvellous", synRu: "чудесный", ant: "dreadful", antRu: "кошмарный", lvl: "A2" },

  { w: "accept", ru: "принимать", syn: "agree to", synRu: "соглашаться на", ant: "reject", antRu: "отвергать", lvl: "B1" },
  { w: "allow", ru: "разрешать", syn: "permit", synRu: "позволять", ant: "forbid", antRu: "запрещать", lvl: "B1" },
  { w: "ashamed", ru: "пристыжённый", syn: "embarrassed", synRu: "сконфуженный", ant: "proud", antRu: "гордый", lvl: "B1" },
  { w: "bored", ru: "скучающий", syn: "uninterested", synRu: "незаинтересованный", ant: "curious", antRu: "любознательный", lvl: "B1" },
  { w: "borrow", ru: "брать взаймы", syn: "take on loan", synRu: "брать в долг", ant: "lend", antRu: "давать взаймы", lvl: "B1" },
  { w: "caring", ru: "заботливый", syn: "thoughtful", synRu: "внимательный к другим", ant: "uncaring", antRu: "равнодушный", lvl: "B1" },
  { w: "common", ru: "распространённый", syn: "widespread", synRu: "повсеместный", ant: "rare", antRu: "редкий", lvl: "B1" },
  { w: "complicated", ru: "сложный", syn: "complex", synRu: "запутанный", ant: "simple", antRu: "простой", lvl: "B1" },
  { w: "confident", ru: "уверенный в себе", syn: "self-assured", synRu: "не сомневающийся в себе", ant: "insecure", antRu: "неуверенный", lvl: "B1" },
  { w: "creative", ru: "творческий", syn: "imaginative", synRu: "с богатым воображением", ant: "unimaginative", antRu: "лишённый фантазии", lvl: "B1" },
  { w: "crowded", ru: "переполненный", syn: "packed", synRu: "битком набитый", ant: "deserted", antRu: "опустевший", lvl: "B1" },
  { w: "curious", ru: "любознательный", syn: "inquisitive", synRu: "пытливый", ant: "indifferent", antRu: "безразличный", lvl: "B1" },
  { w: "decrease", ru: "уменьшать(ся)", syn: "reduce", synRu: "сокращать", ant: "increase", antRu: "увеличивать", lvl: "B1" },
  { w: "destroy", ru: "разрушать", syn: "ruin", synRu: "губить", ant: "build", antRu: "строить", lvl: "B1" },
  { w: "earn", ru: "зарабатывать", syn: "gain", synRu: "получать", ant: "owe", antRu: "быть должным", lvl: "B1" },
  { w: "fail", ru: "терпеть неудачу", syn: "flop", synRu: "провалиться", ant: "succeed", antRu: "преуспевать", lvl: "B1" },
  { w: "failure", ru: "провал", syn: "defeat", synRu: "поражение", ant: "success", antRu: "успех", lvl: "B1" },
  { w: "fair", ru: "справедливый", syn: "just", synRu: "честный", ant: "unfair", antRu: "несправедливый", lvl: "B1" },
  { w: "fluent", ru: "свободно говорящий", syn: "effortless", synRu: "без запинок", ant: "hesitant", antRu: "запинающийся", lvl: "B1" },
  { w: "forbid", ru: "запрещать", syn: "ban", synRu: "накладывать запрет", ant: "allow", antRu: "разрешать", lvl: "B1" },
  { w: "generous", ru: "щедрый", syn: "unselfish", synRu: "бескорыстный", ant: "mean", antRu: "скупой", lvl: "B1" },
  { w: "guilty", ru: "виноватый", syn: "at fault", synRu: "виновный", ant: "innocent", antRu: "невиновный", lvl: "B1" },
  { w: "improve", ru: "улучшать(ся)", syn: "get better", synRu: "становиться лучше", ant: "worsen", antRu: "ухудшаться", lvl: "B1" },
  { w: "increase", ru: "увеличивать(ся)", syn: "grow", synRu: "прибавляться", ant: "decrease", antRu: "уменьшать(ся)", lvl: "B1" },
  { w: "innocent", ru: "невиновный", syn: "blameless", synRu: "безупречный", ant: "guilty", antRu: "виноватый", lvl: "B1" },
  { w: "jealous", ru: "завистливый", syn: "envious", synRu: "завидующий", ant: "content", antRu: "всем довольный", lvl: "B1" },
  { w: "lend", ru: "давать взаймы", syn: "loan", synRu: "ссужать", ant: "borrow", antRu: "брать взаймы", lvl: "B1" },
  { w: "mean", ru: "скупой", syn: "stingy", synRu: "жадный", ant: "generous", antRu: "щедрый", lvl: "B1" },
  { w: "necessary", ru: "необходимый", syn: "required", synRu: "обязательный", ant: "optional", antRu: "необязательный", lvl: "B1" },
  { w: "old-fashioned", ru: "старомодный", syn: "outdated", synRu: "устаревший", ant: "trendy", antRu: "модный", lvl: "B1" },
  { w: "patient", ru: "терпеливый", syn: "tolerant", synRu: "терпимый", ant: "impatient", antRu: "нетерпеливый", lvl: "B1" },
  { w: "peace", ru: "мир", syn: "harmony", synRu: "согласие", ant: "war", antRu: "война", lvl: "B1" },
  { w: "permanent", ru: "постоянный", syn: "long-lasting", synRu: "долговечный", ant: "temporary", antRu: "временный", lvl: "B1" },
  { w: "pleasant", ru: "приятный", syn: "agreeable", synRu: "милый", ant: "unpleasant", antRu: "неприятный", lvl: "B1" },
  { w: "private", ru: "личный", syn: "personal", synRu: "свой собственный", ant: "public", antRu: "общедоступный", lvl: "B1" },
  { w: "proud", ru: "гордый", syn: "satisfied", synRu: "довольный собой", ant: "ashamed", antRu: "пристыжённый", lvl: "B1" },
  { w: "public", ru: "общественный", syn: "shared", synRu: "общий", ant: "private", antRu: "частный", lvl: "B1" },
  { w: "rare", ru: "редкий", syn: "uncommon", synRu: "нечастый", ant: "common", antRu: "обычный", lvl: "B1" },
  { w: "reject", ru: "отвергать", syn: "turn down", synRu: "отклонять", ant: "accept", antRu: "принимать", lvl: "B1" },
  { w: "reliable", ru: "надёжный", syn: "dependable", synRu: "на которого можно положиться", ant: "unreliable", antRu: "ненадёжный", lvl: "B1" },
  { w: "responsible", ru: "ответственный", syn: "trustworthy", synRu: "заслуживающий доверия", ant: "irresponsible", antRu: "безответственный", lvl: "B1" },
  { w: "rise", ru: "подниматься", syn: "increase", synRu: "расти", ant: "fall", antRu: "падать", lvl: "B1" },
  { w: "selfish", ru: "эгоистичный", syn: "self-centred", synRu: "думающий только о себе", ant: "caring", antRu: "заботливый", lvl: "B1" },
  { w: "sensible", ru: "благоразумный", syn: "reasonable", synRu: "здравомыслящий", ant: "reckless", antRu: "безрассудный", lvl: "B1" },
  { w: "smooth", ru: "гладкий", syn: "even", synRu: "ровный", ant: "rough", antRu: "шершавый", lvl: "B1" },
  { w: "succeed", ru: "добиваться успеха", syn: "manage", synRu: "справляться", ant: "fail", antRu: "терпеть неудачу", lvl: "B1" },
  { w: "success", ru: "успех", syn: "achievement", synRu: "достижение", ant: "failure", antRu: "провал", lvl: "B1" },
  { w: "sudden", ru: "внезапный", syn: "unexpected", synRu: "неожиданный", ant: "gradual", antRu: "постепенный", lvl: "B1" },
  { w: "temporary", ru: "временный", syn: "short-term", synRu: "краткосрочный", ant: "permanent", antRu: "постоянный", lvl: "B1" },
  { w: "tough", ru: "жёсткий, трудный", syn: "demanding", synRu: "требующий сил", ant: "effortless", antRu: "дающийся легко", lvl: "B1" },
  { w: "useless", ru: "бесполезный", syn: "pointless", synRu: "бессмысленный", ant: "valuable", antRu: "ценный", lvl: "B1" },
  { w: "valuable", ru: "ценный", syn: "precious", synRu: "драгоценный", ant: "worthless", antRu: "ничего не стоящий", lvl: "B1" },
  { w: "war", ru: "война", syn: "conflict", synRu: "вооружённый конфликт", ant: "peace", antRu: "мир", lvl: "B1" },

  { w: "accurate", ru: "точный", syn: "exact", synRu: "верный до мелочей", ant: "inaccurate", antRu: "неточный", lvl: "B2" },
  { w: "arrogant", ru: "высокомерный", syn: "conceited", synRu: "заносчивый", ant: "humble", antRu: "скромный", lvl: "B2" },
  { w: "awkward", ru: "неловкий", syn: "clumsy", synRu: "неуклюжий", ant: "graceful", antRu: "грациозный", lvl: "B2" },
  { w: "eager", ru: "жаждущий", syn: "keen", synRu: "увлечённый", ant: "reluctant", antRu: "неохотный", lvl: "B2" },
  { w: "flexible", ru: "гибкий", syn: "adaptable", synRu: "легко приспосабливающийся", ant: "rigid", antRu: "негнущийся", lvl: "B2" },
  { w: "fragile", ru: "хрупкий", syn: "delicate", synRu: "требующий бережности", ant: "sturdy", antRu: "прочный", lvl: "B2" },
  { w: "gradual", ru: "постепенный", syn: "step-by-step", synRu: "идущий шаг за шагом", ant: "abrupt", antRu: "резкий", lvl: "B2" },
  { w: "humble", ru: "скромный", syn: "modest", synRu: "непритязательный", ant: "arrogant", antRu: "высокомерный", lvl: "B2" },
  { w: "inevitable", ru: "неизбежный", syn: "unavoidable", synRu: "которого не миновать", ant: "avoidable", antRu: "которого можно избежать", lvl: "B2" },
  { w: "obvious", ru: "очевидный", syn: "evident", synRu: "явный", ant: "hidden", antRu: "скрытый", lvl: "B2" },
  { w: "reluctant", ru: "делающий нехотя", syn: "unwilling", synRu: "не желающий", ant: "eager", antRu: "рвущийся", lvl: "B2" },
  { w: "significant", ru: "значительный", syn: "important", synRu: "важный", ant: "minor", antRu: "незначительный", lvl: "B2" },
  { w: "stubborn", ru: "упрямый", syn: "obstinate", synRu: "несговорчивый", ant: "flexible", antRu: "гибкий", lvl: "B2" },
  { w: "tremendous", ru: "огромный", syn: "huge", synRu: "громадный", ant: "tiny", antRu: "крошечный", lvl: "B2" },
  { w: "vague", ru: "расплывчатый", syn: "unclear", synRu: "неясный", ant: "precise", antRu: "точный", lvl: "B2" },

  { w: "abundant", ru: "изобилующий", syn: "ample", synRu: "более чем достаточный", ant: "scarce", antRu: "дефицитный", lvl: "C1" },
  { w: "candid", ru: "откровенный", syn: "frank", synRu: "говорящий прямо", ant: "evasive", antRu: "уклончивый", lvl: "C1" },
  { w: "ephemeral", ru: "мимолётный", syn: "short-lived", synRu: "недолговечный", ant: "permanent", antRu: "постоянный", lvl: "C1" },
  { w: "feasible", ru: "выполнимый", syn: "doable", synRu: "осуществимый", ant: "impossible", antRu: "невозможный", lvl: "C1" },
  { w: "gregarious", ru: "общительный", syn: "sociable", synRu: "компанейский", ant: "shy", antRu: "застенчивый", lvl: "C1" },
  { w: "lucid", ru: "ясный", syn: "coherent", synRu: "связный", ant: "confusing", antRu: "сбивающий с толку", lvl: "C1" },
  { w: "meticulous", ru: "дотошный", syn: "thorough", synRu: "тщательный", ant: "careless", antRu: "небрежный", lvl: "C1" },
  { w: "resilient", ru: "стойкий", syn: "hardy", synRu: "выносливый", ant: "fragile", antRu: "хрупкий", lvl: "C1" },
  { w: "scarce", ru: "скудный", syn: "in short supply", synRu: "которого не хватает", ant: "plentiful", antRu: "имеющийся в избытке", lvl: "C1" },
  { w: "taciturn", ru: "неразговорчивый", syn: "reserved", synRu: "сдержанный", ant: "talkative", antRu: "болтливый", lvl: "C1" },
  { w: "ubiquitous", ru: "вездесущий", syn: "everywhere", synRu: "повсюду", ant: "rare", antRu: "редкий", lvl: "C1" },
];
