// Слова для теста на уровень. Файл СОБИРАЕТСЯ скриптом
// tools/build-leveltest.py — руками не править.
//
// Здесь по 60 самых частотных слов каждого уровня. Тест берёт из них
// шесть на уровень. Раньше он брал шесть случайных из всего банка,
// и блок выходил лотереей: рядом с «hotel» попадался «flute», рядом
// с «money» — «vague». Один и тот же ученик получал то A2, то C1.
//
// Редкие слова никуда не делись — они остались в тренировках.
// В тесте им не место: тест меряет уровень, а не везение.
const LEVEL_TEST_WORDS = {
  A1: ["one", "new", "good", "two", "last", "take", "business", "world", "why", "life", "come", "next", "yes", "look", "best", "man", "search", "love", "music", "long", "school", "real", "never", "car", "house", "show", "today", "big", "buy", "city", "date", "family", "give", "three", "money", "old", "again", "high", "better", "service", "sure", "night", "book", "full", "always", "put", "keep", "price", "message", "send", "water", "friend", "talk", "game", "black", "public", "lot", "ever", "power", "special"],
  A2: ["support", "actually", "road", "however", "experience", "trust", "software", "evidence", "instead", "although", "cheap", "knowledge", "expect", "opportunity", "village", "consider", "purpose", "explain", "patient", "promise", "solution", "quote", "flight", "bay", "spirit", "construction", "individual", "log", "mad", "package", "download", "plant", "schedule", "traffic", "therefore", "basic", "evil", "shoot", "modern", "challenge", "forever", "western", "channel", "serve", "valley", "secure", "easily", "vehicle", "function", "dangerous", "select", "powerful", "forest", "wood", "increase", "grant", "unique", "royal", "senior", "various"],
  B1: ["charge", "career", "relationship", "responsible", "protect", "waste", "score", "authority", "proud", "debt", "device", "update", "income", "honest", "fuel", "transport", "witness", "require", "rare", "presence", "monitor", "northern", "wire", "assume", "bin", "neighborhood", "deliver", "critical", "assistance", "connect", "tiny", "stuck", "guilty", "election", "limit", "pure", "ensure", "facility", "bunch", "equal", "lift", "recognize", "mess", "pattern", "employment", "sharp", "vice", "selection", "gain", "satellite", "mayor", "visual", "environmental", "recommend", "palm", "identity", "whenever", "sheet", "upper", "grab"],
  B2: ["environment", "investment", "campaign", "therapy", "alert", "prior", "seller", "suck", "mate", "hardware", "mortgage", "employee", "zip", "enterprise", "procedure", "overall", "patch", "phase", "commander", "profit", "crack", "rental", "certificate", "navy", "fox", "manual", "relief", "edit", "backup", "ultimate", "tag", "sensitive", "label", "spare", "odd", "relevant", "dawn", "reaction", "chip", "acid", "jury", "creek", "domestic", "valid", "hook", "gross", "sue", "assessment", "specifically", "deck", "laptop", "creation", "draft", "underground", "seal", "salary", "fate", "resistance", "constant", "ram"],
  C1: ["majesty", "mason", "witch", "custody", "counsel", "warren", "potter", "buffalo", "notify", "escort", "magnetic", "carrier", "amendment", "toolbar", "mister", "footage", "bachelor", "lounge", "premium", "heather", "sixth", "legacy", "hence", "liability", "elder", "perry", "cargo", "excerpt", "skull", "shark", "vulnerable", "expertise", "ethics", "facial", "grove", "mercury", "conspiracy", "loser", "kidney", "crane", "alley", "instrumental", "insert", "tribal", "porter", "scout", "meantime", "vendor", "shuttle", "chapel", "petition", "jurisdiction", "advocate", "profound", "elaborate", "viable", "upbeat", "flashlight", "driveway", "interrogation"],
  C2: ["courthouse", "reckless", "lantern", "nonlinear", "lever", "robust", "consecutive", "parse", "savior", "immense", "integral", "override", "pursuant", "decree", "marital", "joker", "evolutionary", "flick", "presume", "incorporate", "crate", "spatial", "groceries", "shuffle", "commence", "magistrate", "adolescent", "appliance", "slippery", "cashier", "garland", "rooster", "bedtime", "unreal", "pagan", "rigid", "toddler", "maniac", "dispose", "spyware", "lumber", "pouch", "obscure", "readable", "blackberry", "hound", "mutation", "marrow", "peasant", "pastry", "maritime", "inferior", "yeast", "kinky", "inmate", "sentiment", "footwear", "blackmail", "fingerprint", "snoop"],
};
