// Словообразование — задания формата ОГЭ и ЕГЭ.
//
// В экзамене это выглядит так: предложение с пропуском, а справа от него
// ЗАГЛАВНЫМИ исходное слово. Нужно поставить его в правильную форму —
// сменить часть речи, добавить приставку или суффикс.
//
// Почему отдельным файлом, а не внутри words.js. Это не словарь: здесь
// у каждой записи есть предложение, исходное слово, ответ и разбор.
// Плюс файл грузится только тем, кто дошёл до этих упражнений
// (ensureWordForms в js/util.js), а это ещё 30 КБ.
//
// Поля записи:
//   s     предложение, пропуск обозначен ___
//   base  исходное слово (в интерфейсе показывается ЗАГЛАВНЫМИ)
//   a     правильный ответ
//   alt   другие принимаемые ответы (необязательно)
//   ru    перевод предложения — ученик должен понимать, что переводит
//   why   разбор: почему именно эта форма
//   lvl   A2 | B1 | B2
//   grp   тип преобразования — по нему собираются подборки
//
// ВАЖНО про ответы: сверка идёт без учёта регистра и лишних пробелов,
// но форма должна быть точной. Где допустимы два варианта (realise /
// realize), второй лежит в alt.

const WORD_FORMS = [

  // ---------- -er / -or: кто делает ----------
  { s: "My sister wants to be a ___ at a primary school.", base: "TEACH", a: "teacher",
    ru: "Моя сестра хочет быть учителем в начальной школе.",
    why: "Нужен человек по действию: teach (учить) + -er = teacher.", lvl: "A2", grp: "agent" },
  { s: "He is a famous ___ — you have seen him in three films.", base: "ACT", a: "actor",
    ru: "Он известный актёр — ты видел его в трёх фильмах.",
    why: "От глаголов на латинской основе деятель чаще на -or: act → actor.", lvl: "A2", grp: "agent" },
  { s: "Every ___ to the museum gets a free map.", base: "VISIT", a: "visitor",
    ru: "Каждый посетитель музея получает бесплатную карту.",
    why: "visit → visitor: тот, кто посещает.", lvl: "A2", grp: "agent" },
  { s: "My favourite ___ has just finished a new book.", base: "WRITE", a: "writer",
    ru: "Мой любимый писатель только что закончил новую книгу.",
    why: "write (писать) + -er = writer — тот, кто пишет книги. Немая -e перед -er уходит.", lvl: "A2", grp: "agent" },
  { s: "She is the best ___ in our swimming club.", base: "SWIM", a: "swimmer",
    ru: "Она лучшая пловчиха в нашем клубе плавания.",
    why: "Короткий слог с одной гласной — согласная удваивается: swim → swimmer.", lvl: "B1", grp: "agent" },
  { s: "The radio ___ has a deep, pleasant voice.", base: "ANNOUNCE", a: "announcer",
    ru: "У диктора на радио глубокий, приятный голос.",
    why: "Нужен человек: announce (объявлять) + -er = announcer, немая -e перед -er уходит. Announcement — это само объявление, а голос бывает у человека.", lvl: "B2", grp: "agent" },
  { s: "A good ___ listens more than he speaks.", base: "LEAD", a: "leader",
    ru: "Хороший руководитель слушает больше, чем говорит.",
    why: "lead → leader: тот, кто ведёт.", lvl: "B1", grp: "agent" },
  { s: "The ___ of the company signed the letter herself.", base: "DIRECT", a: "director",
    ru: "Директор компании подписала письмо сама.",
    why: "direct → director, деятель на -or.", lvl: "B1", grp: "agent" },

  // ---------- -ist ----------
  { s: "My brother is an ___ and paints every weekend.", base: "ART", a: "artist",
    ru: "Мой брат художник и рисует каждые выходные.",
    why: "art → artist: занятие человека через -ist.", lvl: "A2", grp: "ist" },
  { s: "The ___ explained her experiment to the students.", base: "SCIENCE", a: "scientist",
    ru: "Учёная объяснила свой эксперимент студентам.",
    why: "science → scientist, конечная -ce меняется на -t перед -ist.", lvl: "B1", grp: "ist" },
  { s: "A ___ from the local paper asked me three questions.", base: "JOURNAL", a: "journalist",
    ru: "Журналист местной газеты задал мне три вопроса.",
    why: "Суффикс -ist называет человека по его делу: journal (журнал, газета) → journalist — тот, кто пишет для газеты. Так же art → artist, piano → pianist.", lvl: "B1", grp: "ist" },
  { s: "The ___ played for two hours without a break.", base: "PIANO", a: "pianist",
    ru: "Пианист играл два часа без перерыва.",
    why: "piano → pianist, конечная -o уходит.", lvl: "B1", grp: "ist" },

  // ---------- -ment ----------
  { s: "The ___ of the new park took two years.", base: "DEVELOP", a: "development",
    ru: "Создание нового парка заняло два года.",
    why: "После the нужно существительное: develop + -ment. Основа при этом не меняется — не появляется ни лишняя -e (*developement), ни вторая -p (*developpment).", lvl: "B1", grp: "ment" },
  { s: "We came to an ___ after a long talk.", base: "AGREE", a: "agreement",
    ru: "Мы пришли к соглашению после долгого разговора.",
    why: "agree → agreement: -ment превращает глагол в существительное.", lvl: "B1", grp: "ment" },
  { s: "His ___ was clear: the trip would cost too much money.", base: "ARGUE", a: "argument",
    ru: "Его довод был ясен: поездка обойдётся слишком дорого.",
    why: "argue → argument: суффикс -ment делает из глагола существительное. Внимание: немая -e перед -ment здесь исчезает — не *arguement.", lvl: "B2", grp: "ment" },
  { s: "The film was pure ___ — nothing to think about.", base: "ENTERTAIN", a: "entertainment",
    ru: "Фильм был чистым развлечением — думать не о чем.",
    why: "После pure нужно существительное: entertain + -ment = entertainment. В этом слове основа не меняется — ничего не выпадает и не удваивается; но правило не всеобщее, ср. argue → argument, где немая -e исчезает.", lvl: "B2", grp: "ment" },
  { s: "Her ___ in the school play was a surprise to us.", base: "INVOLVE", a: "involvement",
    ru: "Её участие в школьном спектакле было для нас неожиданностью.",
    why: "involve → involvement, немая -e сохраняется.", lvl: "B2", grp: "ment" },
  { s: "Read the ___ before you switch the machine on.", base: "INSTRUCT", a: "instructions",
    alt: ["instruction"],
    ru: "Прочитай инструкцию, прежде чем включать прибор.",
    why: "instruct + -ion = instruction, основа не меняется. О правилах пользования техникой англичане обычно говорят во множественном — read the instructions, поэтому здесь ждём форму с -s; единственное число тоже засчитывается.", lvl: "B1", grp: "tion" },

  // ---------- -tion / -sion / -ation ----------
  { s: "___ is free in our country until the age of eighteen.", base: "EDUCATE", a: "education",
    ru: "Образование в нашей стране бесплатное до восемнадцати лет.",
    why: "educate → education: -ate меняется на -ation.", lvl: "B1", grp: "tion" },
  { s: "The ___ was difficult, but she made it quickly.", base: "DECIDE", a: "decision",
    ru: "Решение было трудным, но она приняла его быстро.",
    why: "decide → decision: -de переходит в -sion.", lvl: "B1", grp: "tion" },
  { s: "Thank you for the ___ to your birthday party.", base: "INVITE", a: "invitation",
    ru: "Спасибо за приглашение на твой день рождения.",
    why: "invite → invitation: немая -e отпадает, а на её место встаёт -ation (не -tion и не -ment). Тот же путь: prepare → preparation.", lvl: "A2", grp: "tion" },
  { s: "The ___ of the city is about two million.", base: "POPULATE", a: "population",
    ru: "Население города — около двух миллионов.",
    why: "populate → population: у глаголов на -ate немая -e отпадает и добавляется -ion. Так же: educate → education, decorate → decoration.", lvl: "B1", grp: "tion" },
  { s: "His ___ of the rules was completely wrong.", base: "EXPLAIN", a: "explanation",
    ru: "Его объяснение правил было совершенно неверным.",
    why: "explain → explanation: -ai- сокращается до -a-.", lvl: "B1", grp: "tion" },
  { s: "We need more ___ before we can answer.", base: "INFORM", a: "information",
    ru: "Нам нужно больше информации, прежде чем мы сможем ответить.",
    why: "inform → information. Слово неисчисляемое: без -s.", lvl: "A2", grp: "tion" },
  { s: "The ___ between the two schools started last year.", base: "COMPETE", a: "competition",
    ru: "Соревнование между двумя школами началось в прошлом году.",
    why: "После the нужно существительное, а не competitive. От compete остаётся compet-, к нему прибавляется -ition: competition. Частая ошибка — *competetion: гласная перед -tion здесь i.", lvl: "B1", grp: "tion" },
  { s: "She was a great ___ to the team — everyone liked her at once.", base: "ADD", a: "addition",
    ru: "Она стала отличным пополнением в команде — она сразу всем понравилась.",
    why: "После great нужно существительное. add → addition: -ion превращает глагол в существительное. Пиши addition: две d от add и одна t.", lvl: "B2", grp: "tion" },
  { s: "The ___ of the film takes place in Paris.", base: "ACT", a: "action",
    ru: "Действие фильма происходит в Париже.",
    why: "act → action.", lvl: "A2", grp: "tion" },
  { s: "There was no ___ from the audience at all.", base: "REACT", a: "reaction",
    ru: "От зала не было вообще никакой реакции.",
    why: "react → reaction: суффикс -ion делает из глагола существительное. Сравни: act → action, а re- значит «в ответ».", lvl: "B1", grp: "tion" },

  // ---------- -ness ----------
  { s: "Her ___ was clear from the first minute.", base: "HAPPY", a: "happiness",
    ru: "Её счастье было заметно с первой минуты.",
    why: "happy → happiness: -y после согласной переходит в -i-.", lvl: "A2", grp: "ness" },
  { s: "In complete ___ I could not find the door.", base: "DARK", a: "darkness",
    ru: "В полной темноте я не смог найти дверь.",
    why: "Суффикс -ness превращает прилагательное в существительное: dark (тёмный) → darkness (темнота). После complete (полный) нужно существительное — «в полной темноте».", lvl: "A2", grp: "ness" },
  { s: "His ___ kept him at home for a week.", base: "ILL", a: "illness",
    ru: "Болезнь продержала его дома неделю.",
    why: "ill → illness.", lvl: "B1", grp: "ness" },
  { s: "Thank you for your ___ — I will not forget it.", base: "KIND", a: "kindness",
    ru: "Спасибо за твою доброту — я этого не забуду.",
    why: "kind → kindness.", lvl: "A2", grp: "ness" },
  { s: "The ___ of the mountain surprised the climbers.", base: "STEEP", a: "steepness",
    ru: "Крутизна горы удивила альпинистов.",
    why: "steep → steepness.", lvl: "B2", grp: "ness" },
  { s: "I admire her ___ to help other people.", base: "READY", a: "readiness",
    ru: "Я восхищаюсь её готовностью помогать другим.",
    why: "Суффикс -ness превращает прилагательное в существительное — название качества: ready (готовый) → readiness (готовность); -y после согласной меняется на -i-.", lvl: "B1", grp: "ness" },

  // ---------- -ity ----------
  { s: "There is a ___ that it will rain tomorrow.", base: "POSSIBLE", a: "possibility",
    ru: "Есть вероятность, что завтра пойдёт дождь.",
    why: "possible → possibility: -le меняется на -ility.", lvl: "B1", grp: "ity" },
  { s: "Physical ___ is important at any age.", base: "ACTIVE", a: "activity",
    ru: "Физическая активность важна в любом возрасте.",
    why: "После physical нужно существительное: active «активный» + -ity → activity, конечная -e выпадает.", lvl: "B1", grp: "ity" },
  { s: "The ___ of this song surprised even the singer.", base: "POPULAR", a: "popularity",
    ru: "Популярность этой песни удивила даже певца.",
    why: "popular → popularity.", lvl: "B1", grp: "ity" },
  { s: "Everyone has the ___ to learn a language.", base: "ABLE", a: "ability",
    ru: "У каждого есть способность выучить язык.",
    why: "После the нужно существительное: able «способный» → ability, конечное -le превращается в -ility — так же, как possible → possibility.", lvl: "B1", grp: "ity" },
  { s: "Scientists check the ___ of the water in this lake every month.", base: "PURE", a: "purity",
    ru: "Учёные каждый месяц проверяют чистоту воды в этом озере.",
    why: "После the нужно название качества, то есть существительное: pure «чистый» + -ity → purity, конечная -e выпадает.", lvl: "B2", grp: "ity" },

  // ---------- -ance / -ence ----------
  { s: "The ___ of sleep is often forgotten.", base: "IMPORTANT", a: "importance",
    ru: "О важности сна часто забывают.",
    why: "important → importance: -ant меняется на -ance.", lvl: "B1", grp: "ance" },
  { s: "I see no ___ between these two answers.", base: "DIFFERENT", a: "difference",
    ru: "Я не вижу разницы между этими двумя ответами.",
    why: "different → difference: -ent меняется на -ence.", lvl: "A2", grp: "ance" },
  { s: "Nobody said a word, but everyone felt her ___ in the room.", base: "PRESENT", a: "presence",
    ru: "Никто не сказал ни слова, но все чувствовали её присутствие в комнате.",
    why: "Нужно существительное «присутствие»: у present конечное -ent меняется на -ence → presence.", lvl: "B2", grp: "ance" },
  { s: "The ___ from home to school is two kilometres.", base: "DISTANT", a: "distance",
    ru: "Расстояние от дома до школы — два километра.",
    why: "После the нужно существительное: distant «далёкий» → distance, конечное -ant меняется на -ance.", lvl: "A2", grp: "ance" },
  { s: "Thank you for your ___ with the heavy bags.", base: "ASSIST", a: "assistance",
    ru: "Спасибо за помощь с тяжёлыми сумками.",
    why: "assist → assistance.", lvl: "B2", grp: "ance" },

  // ---------- -ful ----------
  { s: "Be ___ — the plate is very hot.", base: "CARE", a: "careful",
    ru: "Будь осторожен — тарелка очень горячая.",
    why: "care + -ful = «полный чего-то»: careful.", lvl: "A2", grp: "ful" },
  { s: "This map will be very ___ on your trip — it shows every small street.", base: "USE", a: "useful",
    ru: "Эта карта будет очень полезна в поездке — на ней есть каждая маленькая улочка.",
    why: "Суффикс -ful превращает существительное в прилагательное «полный чего-то»: use (польза) → useful (полезный). Вторая часть предложения подсказывает: на карте есть каждая улочка — значит, она пригодится.", lvl: "A2", grp: "ful" },
  { s: "The garden looked ___ in the morning light.", base: "BEAUTY", a: "beautiful",
    ru: "Сад выглядел прекрасно в утреннем свете.",
    why: "beauty → beautiful: -y переходит в -i-.", lvl: "A2", grp: "ful" },
  { s: "She was ___ to everyone who helped her.", base: "THANK", a: "thankful",
    ru: "Она была благодарна всем, кто ей помог.",
    why: "thank → thankful.", lvl: "B1", grp: "ful" },
  { s: "It was a ___ day — nothing went wrong.", base: "PEACE", a: "peaceful",
    ru: "Это был спокойный день — ничего не пошло не так.",
    why: "peace → peaceful.", lvl: "B1", grp: "ful" },
  { s: "The dog is ___ of thunder and hides under the bed during a storm.", base: "FEAR", a: "fearful",
    ru: "Собака боится грома и прячется под кроватью во время грозы.",
    why: "Суффикс -ful даёт прилагательное «полный чего-то»: fear (страх) → fearful (боязливый). От той же основы есть форма с -less («без») — fearless, но она тут не подходит: собака прячется под кроватью во время грозы, значит бесстрашной её не назовёшь.", lvl: "B2", grp: "ful" },

  // ---------- -less ----------
  { s: "This old phone is ___ — it does not switch on.", base: "USE", a: "useless",
    ru: "Этот старый телефон бесполезен — он не включается.",
    why: "use + -less = «без чего-то»: useless.", lvl: "A2", grp: "less" },
  { s: "He was ___ and broke the window.", base: "CARE", a: "careless",
    ru: "Он был невнимателен и разбил окно.",
    why: "care → careless: суффикс -less отнимает качество.", lvl: "A2", grp: "less" },
  { s: "The night was ___ and we could see every star.", base: "CLOUD", a: "cloudless",
    ru: "Ночь была безоблачной, и мы видели каждую звезду.",
    why: "Суффикс -less значит «без чего-то» и отнимает то, что названо корнем: cloud (облако) → cloudless (безоблачный). Раз видно каждую звезду, облаков не было.", lvl: "B1", grp: "less" },
  { s: "Do not be ___ — everything can be fixed.", base: "HOPE", a: "hopeless",
    ru: "Не отчаивайся — всё можно исправить.",
    why: "hope → hopeless.", lvl: "B1", grp: "less" },
  { s: "The task turned out to be ___ — nobody needed it.", base: "POINT", a: "pointless",
    ru: "Задание оказалось бессмысленным — оно никому не понадобилось.",
    why: "point → pointless.", lvl: "B2", grp: "less" },

  // ---------- -able / -ible ----------
  { s: "This chair is not very ___ for long work.", base: "COMFORT", a: "comfortable",
    ru: "Этот стул не очень удобен для долгой работы.",
    why: "comfort → comfortable.", lvl: "B1", grp: "able" },
  { s: "Your writing is not ___ — please write bigger.", base: "READ", a: "readable",
    ru: "Твой почерк неразборчив — пиши крупнее, пожалуйста.",
    why: "read → readable: «который можно прочитать».", lvl: "B1", grp: "able" },
  { s: "He is a ___ friend — he never lets me down.", base: "RELY", a: "reliable",
    ru: "Он надёжный друг — он никогда меня не подводит.",
    why: "rely → reliable: -y переходит в -i-.", lvl: "B1", grp: "able" },
  { s: "The teacher is ___ for thirty students.", base: "RESPOND", a: "responsible",
    ru: "Учитель отвечает за тридцать учеников.",
    why: "Здесь прилагательное образуется от глагола суффиксом -ible (это родственник -able, как в possible, terrible), а в основе d меняется на s: respond (отвечать) → responsible — «тот, кто отвечает за кого-то».", lvl: "B1", grp: "able" },
  { s: "The change was hardly ___ to the eye.", base: "NOTICE", a: "noticeable",
    ru: "Изменение было едва заметно глазу.",
    why: "notice → noticeable: -e сохраняется, чтобы c читалась как [s].", lvl: "B2", grp: "able" },

  // ---------- -ous ----------
  { s: "Swimming here is ___ — the current is strong.", base: "DANGER", a: "dangerous",
    ru: "Плавать здесь опасно — течение сильное.",
    why: "danger → dangerous.", lvl: "A2", grp: "ous" },
  { s: "She became ___ after her first film.", base: "FAME", a: "famous",
    ru: "Она стала знаменитой после первого фильма.",
    why: "fame → famous: немая -e уходит.", lvl: "A2", grp: "ous" },
  { s: "He is very ___ about his little brother.", base: "NERVE", a: "nervous",
    ru: "Он очень переживает за младшего брата.",
    why: "nerve → nervous.", lvl: "B1", grp: "ous" },
  { s: "Be ___ around the dog — it does not know you.", base: "CAUTION", a: "cautious",
    ru: "Будь осторожен рядом с собакой — она тебя не знает.",
    why: "Суффикс -ous превращает существительное в прилагательное: caution (осторожность) → cautious (осторожный). После be нужно слово-признак: «будь каким?».", lvl: "B2", grp: "ous" },
  { s: "The trip was full of ___ moments.", base: "HUMOUR", a: "humorous",
    ru: "Поездка была полна забавных моментов.",
    why: "humour → humorous: -our сокращается до -or-.", lvl: "B2", grp: "ous" },

  // ---------- -ive ----------
  { s: "She has a very ___ mind — always new ideas.", base: "CREATE", a: "creative",
    ru: "У неё очень творческий ум — всегда новые идеи.",
    why: "create → creative.", lvl: "B1", grp: "ive" },
  { s: "Try to be more ___ during the lesson.", base: "ACT", a: "active",
    ru: "Постарайся быть активнее на уроке.",
    why: "act → active.", lvl: "A2", grp: "ive" },
  { s: "This method is more ___ than the old one.", base: "EFFECT", a: "effective",
    ru: "Этот метод эффективнее старого.",
    why: "effect → effective.", lvl: "B1", grp: "ive" },
  { s: "The medicine had a ___ effect on his health.", base: "PROTECT", a: "protective",
    ru: "Лекарство оказало защитное действие на его здоровье.",
    why: "protect → protective.", lvl: "B2", grp: "ive" },
  { s: "He gave a very ___ answer — too many details.", base: "DESCRIBE", a: "descriptive",
    ru: "Он дал очень описательный ответ — слишком много подробностей.",
    why: "describe → descriptive: -be меняется на -ptive.", lvl: "B2", grp: "ive" },

  // ---------- -al ----------
  { s: "This is a ___ way to keep food fresh.", base: "NATURE", a: "natural",
    ru: "Это естественный способ сохранить еду свежей.",
    why: "nature → natural: немая -e уходит.", lvl: "B1", grp: "al" },
  { s: "Her whole family is very ___ : everyone plays an instrument.", base: "MUSIC", a: "musical",
    ru: "Вся её семья очень музыкальна: каждый играет на каком-нибудь инструменте.",
    why: "Суффикс -al делает из существительного прилагательное: music (музыка) → musical (музыкальный). После very нужен признак — «семья какая?», а само название предмета, music, туда не встанет.", lvl: "A2", grp: "al" },
  { s: "She is reading a ___ novel about the nineteenth century.", base: "HISTORY", a: "historical",
    ru: "Она читает исторический роман о девятнадцатом веке.",
    why: "Суффикс -al делает из существительного прилагательное, при этом основа превращается в historic-: history → historical (исторический). Роман о прошлом по-английски именно historical novel.", lvl: "B1", grp: "al" },
  { s: "It was a ___ question, so I did not answer it.", base: "PERSON", a: "personal",
    ru: "Это был личный вопрос, поэтому я не стал отвечать.",
    why: "Суффикс -al делает из существительного прилагательное: person (человек) → personal (личный, касающийся лично меня). Сказать «a person question» по-английски нельзя: нужен признак — вопрос какой? личный.", lvl: "B1", grp: "al" },
  { s: "The ___ team won the championship.", base: "NATION", a: "national",
    ru: "Национальная сборная выиграла чемпионат.",
    why: "nation → national.", lvl: "B1", grp: "al" },

  // ---------- -y ----------
  { s: "It was a ___ day, so we stayed at home.", base: "RAIN", a: "rainy",
    ru: "День был дождливый, поэтому мы остались дома.",
    why: "Суффикс -y превращает существительное в прилагательное: rain (дождь) → rainy (какой? — дождливый).", lvl: "A2", grp: "y" },
  { s: "The weather is ___ today — take your hat.", base: "SUN", a: "sunny",
    ru: "Погода сегодня солнечная — возьми шляпу.",
    why: "sun → sunny: короткий слог, согласная удваивается.", lvl: "A2", grp: "y" },
  { s: "The room was ___ after the party.", base: "DIRT", a: "dirty",
    ru: "Комната была грязной после вечеринки.",
    why: "Существительное становится прилагательным с помощью суффикса -y: dirt (грязь) → dirty (грязный). После was нужно слово-признак, а не название вещества.", lvl: "A2", grp: "y" },
  { s: "The street was too ___ to talk on the phone.", base: "NOISE", a: "noisy",
    ru: "На улице было слишком шумно, чтобы говорить по телефону.",
    why: "noise → noisy: немая -e уходит.", lvl: "B1", grp: "y" },

  // ---------- -ly (наречия) ----------
  { s: "He answered the question ___ and sat down.", base: "QUICK", a: "quickly",
    ru: "Он быстро ответил на вопрос и сел.",
    why: "Действие описывает наречие: quick → quickly.", lvl: "A2", grp: "ly" },
  { s: "She looked at the map ___ before choosing.", base: "CAREFUL", a: "carefully",
    ru: "Она внимательно посмотрела на карту, прежде чем выбрать.",
    why: "Слово отвечает на вопрос «как посмотрела?» — значит, нужно наречие: careful + -ly → carefully.", lvl: "A2", grp: "ly" },
  { s: "The dog ___ ran across the road.", base: "SUDDEN", a: "suddenly",
    ru: "Собака внезапно перебежала дорогу.",
    why: "Пропуск относится к глаголу ran, а не к существительному, поэтому нужна форма на -ly: sudden + -ly → suddenly. Прилагательное sudden стоит только при существительном (a sudden noise), к глаголу его поставить нельзя.", lvl: "B1", grp: "ly" },
  { s: "He speaks English ___ well for his age.", base: "SURPRISE", a: "surprisingly",
    ru: "Он говорит по-английски удивительно хорошо для своего возраста.",
    why: "surprise → surprising → surprisingly.", lvl: "B2", grp: "ly" },
  { s: "___ , nobody was hurt in the accident.", base: "LUCK", a: "luckily",
    ru: "К счастью, в аварии никто не пострадал.",
    why: "luck → lucky → luckily: -y переходит в -i-.", lvl: "B1", grp: "ly" },
  { s: "The child slept ___ all night.", base: "PEACE", a: "peacefully",
    ru: "Ребёнок мирно спал всю ночь.",
    why: "peace → peaceful → peacefully.", lvl: "B1", grp: "ly" },

  // ---------- un- / in- / im- / dis- / ir- ----------
  { s: "She looked ___ after the bad news.", base: "HAPPY", a: "unhappy",
    ru: "Она выглядела несчастной после плохих новостей.",
    why: "Отрицание через un-: unhappy.", lvl: "A2", grp: "neg" },
  { s: "It is ___ to be in two places at once.", base: "POSSIBLE", a: "impossible",
    ru: "Невозможно быть в двух местах одновременно.",
    why: "Перед p, b, m ставится im-: impossible.", lvl: "B1", grp: "neg" },
  { s: "Sorry, but I ___ with you — the answer is 12, not 15.", base: "AGREE", a: "disagree",
    ru: "Извини, но я с тобой не согласен — ответ 12, а не 15.",
    why: "Приставка dis- даёт обратное действие: agree (соглашаться) → disagree (возражать).", lvl: "A2", grp: "neg" },
  { s: "His answer was ___ — it had nothing to do with the question.", base: "RELEVANT", a: "irrelevant",
    ru: "Его ответ был неуместен — он не имел отношения к вопросу.",
    why: "Перед r ставится ir-: irrelevant.", lvl: "B2", grp: "neg" },
  { s: "The information turned out to be ___ — the date and the address were both wrong.", base: "CORRECT", a: "incorrect",
    ru: "Информация оказалась неверной — и дата, и адрес были неправильными.",
    why: "Отрицание тут строится приставкой in-: correct → incorrect. Слова uncorrect в английском нет.", lvl: "B1", grp: "neg" },
  { s: "Do not be ___ — the cake needs another twenty minutes in the oven.", base: "PATIENT", a: "impatient",
    ru: "Не будь нетерпеливым — торту нужно ещё двадцать минут в духовке.",
    why: "Перед p, b, m приставка in- превращается в im-: patient → impatient.", lvl: "B1", grp: "neg" },
  { s: "The old bridge is ___ for heavy trucks, so they have to use another road.", base: "SAFE", a: "unsafe",
    ru: "Старый мост небезопасен для тяжёлых грузовиков, поэтому им приходится ехать по другой дороге.",
    why: "Раз грузовикам приходится ехать в объезд, мост для них опасен — нужно отрицание: safe → unsafe. У прилагательных отрицание чаще всего даёт un-, но не всегда: ср. correct → incorrect, formal → informal.", lvl: "B1", grp: "neg" },
  { s: "Snow in May is quite ___ for this region — it happens once in twenty years.", base: "USUAL", a: "unusual",
    ru: "Снег в мае довольно необычен для этого региона — такое бывает раз в двадцать лет.",
    why: "Приставка un- переворачивает значение на противоположное: usual → unusual.", lvl: "B1", grp: "neg" },

  // ---------- -en / -ise (глаголы) ----------
  { s: "They plan to ___ the road next summer.", base: "WIDE", a: "widen",
    ru: "Они планируют расширить дорогу следующим летом.",
    why: "Суффикс -en делает из прилагательного глагол: wide → widen.", lvl: "B2", grp: "verb" },
  { s: "Exercise helps to ___ your muscles.", base: "STRONG", a: "strengthen",
    ru: "Упражнения помогают укрепить мышцы.",
    why: "strong → strength → strengthen.", lvl: "B2", grp: "verb" },
  { s: "I did not ___ how late it was.", base: "REAL", a: "realise", alt: ["realize"],
    ru: "Я не осознавал, как поздно.",
    why: "real → realise. В американском варианте пишут realize — оба верны.", lvl: "B1", grp: "verb" },
  { s: "You must ___ your pencil before the drawing lesson.", base: "SHARP", a: "sharpen",
    ru: "Тебе нужно наточить карандаш перед уроком рисования.",
    why: "Суффикс -en делает из прилагательного глагол: sharp (острый) → sharpen (наточить, сделать острым). После must стоит глагол.", lvl: "B1", grp: "verb" },

  // ---------- неправильные пары ----------
  { s: "What is the ___ of this room?", base: "LONG", a: "length",
    ru: "Какова длина этой комнаты?",
    why: "long → length: гласная меняется, суффикс -th.", lvl: "B1", grp: "irr" },
  { s: "The ___ of the door is ninety centimetres.", base: "WIDE", a: "width",
    ru: "Ширина двери — девяносто сантиметров.",
    why: "После the нужно существительное. Пара нерегулярная: у wide уходит немая -e и добавляется -th → width, а i начинает читаться коротко. Так же устроены long → length и strong → strength.", lvl: "B1", grp: "irr" },
  { s: "His ___ is one metre eighty.", base: "HIGH", a: "height",
    ru: "Его рост — метр восемьдесят.",
    why: "high → height. Пишется через -eigh-.", lvl: "B1", grp: "irr" },
  { s: "She showed great ___ during the illness.", base: "STRONG", a: "strength",
    ru: "Она проявила большую силу во время болезни.",
    why: "strong → strength: прилагательное становится существительным, гласная меняется (o → e) и добавляется -th, как long → length. Слова strongness в английском нет.", lvl: "B1", grp: "irr" },
  { s: "The ___ of the lake is about ten metres.", base: "DEEP", a: "depth",
    ru: "Глубина озера — около десяти метров.",
    why: "deep → depth: прилагательное становится существительным — гласная сокращается (ee → e), в конце -th. Такая же пара: wide → width, long → length.", lvl: "B2", grp: "irr" },

  // ---------- смешанные, на выбор части речи ----------
  { s: "The ___ of the experiment surprised everyone.", base: "SUCCEED", a: "success",
    ru: "Успех эксперимента всех удивил.",
    why: "После артикля the нужно существительное: succeed (добиваться успеха) → success (успех). Суффикса нет, меняется конец слова: -ceed → -cess, как proceed → process.", lvl: "B1", grp: "mix" },
  { s: "He is a very ___ student.", base: "SUCCEED", a: "successful",
    ru: "Он очень успешный ученик.",
    why: "Перед существительным нужно прилагательное: successful.", lvl: "B1", grp: "mix" },
  { s: "She finished the task ___ .", base: "SUCCEED", a: "successfully",
    ru: "Она успешно завершила задание.",
    why: "Действие описывает наречие: successfully.", lvl: "B2", grp: "mix" },
  { s: "There is a big ___ between the two cities.", base: "DIFFER", a: "difference",
    ru: "Между двумя городами большая разница.",
    why: "differ → difference — существительное после артикля.", lvl: "B1", grp: "mix" },
  { s: "The two brothers are completely ___ .", base: "DIFFER", a: "different",
    ru: "Два брата совершенно разные.",
    why: "После глагола-связки нужно прилагательное: different.", lvl: "A2", grp: "mix" },
  { s: "Her ___ was right, and it helped the whole team.", base: "DECIDE", a: "decision",
    ru: "Её решение было верным, и оно помогло всей команде.",
    why: "После her нужно существительное — «решение»: decide (решать) → decision, -de меняется на -sion (как divide → division). Верным бывает решение, поэтому «решительность» тут не подходит.", lvl: "B1", grp: "mix" },
  { s: "He is a ___ person — he knows what he wants.", base: "DECIDE", a: "decisive",
    ru: "Он решительный человек — он знает, чего хочет.",
    why: "decide → decisive, прилагательное.", lvl: "B2", grp: "mix" },
  { s: "The ___ of the room took all day.", base: "CLEAN", a: "cleaning",
    ru: "Уборка комнаты заняла весь день.",
    why: "Действие как существительное: -ing.", lvl: "B1", grp: "mix" },
  { s: "Nobody knew about his ___ to leave.", base: "DECIDE", a: "decision",
    ru: "Никто не знал о его решении уехать.",
    why: "После притяжательного местоимения нужно существительное.", lvl: "B1", grp: "mix" },
  { s: "This is the ___ book I have ever read.", base: "GOOD", a: "best",
    ru: "Это лучшая книга, которую я когда-либо читал.",
    why: "good → best: превосходная степень, форма неправильная.", lvl: "A2", grp: "mix" },
  { s: "Today the weather is ___ than yesterday.", base: "BAD", a: "worse",
    ru: "Сегодня погода хуже, чем вчера.",
    why: "bad → worse: сравнительная степень, форма неправильная.", lvl: "A2", grp: "mix" },

  /* ==== Пополнение банка (v164). Дальше — новые задания теми же
     группами: банк вырос вдвое, чтобы подходы не повторялись.
     Проверка целостности — tools/check-banks.py. ==== */

  // ---------- -er / -or: кто делает (продолжение) ----------
  { s: "My uncle is a ___ — he works on new houses in our town.", base: "BUILD", a: "builder",
    ru: "Мой дядя строитель — он работает на стройке новых домов в нашем городе.",
    why: "После a нужно название профессии: build (строить) + -er = builder — тот, кто строит.", lvl: "A2", grp: "agent" },
  { s: "The taxi ___ helped us with the bags.", base: "DRIVE", a: "driver",
    ru: "Таксист помог нам с сумками.",
    why: "drive → driver, немая -e перед -er уходит.", lvl: "A2", grp: "agent" },
  { s: "The ___ of the telephone worked on his idea for many years.", base: "INVENT", a: "inventor",
    ru: "Изобретатель телефона много лет работал над своей идеей.",
    why: "Нужен человек: invent (изобретать) + -or = inventor. Само устройство — invention, но работать над идеей годами может только человек.", lvl: "B1", grp: "agent" },
  { s: "She works as a ___ and knows four languages.", base: "TRANSLATE", a: "translator",
    ru: "Она работает переводчицей и знает четыре языка.",
    why: "translate → translator: деятель на -or, немая -e уходит.", lvl: "B1", grp: "agent" },
  { s: "The young ___ crossed the ocean alone.", base: "SAIL", a: "sailor",
    ru: "Молодой моряк пересёк океан в одиночку.",
    why: "sail → sailor: деятель на -or.", lvl: "B1", grp: "agent" },
  { s: "The ___ of the race got a gold medal.", base: "WIN", a: "winner",
    ru: "Победитель гонки получил золотую медаль.",
    why: "win → winner: короткий слог, согласная удваивается.", lvl: "A2", grp: "agent" },
  { s: "A ___ with a big brush was working in our kitchen all morning.", base: "PAINT", a: "painter",
    ru: "Маляр с большой кистью всё утро работал у нас на кухне.",
    why: "Суффикс -er даёт название человека по действию: paint (красить) + -er = painter — тот, кто красит.", lvl: "A2", grp: "agent" },
  { s: "Ask the shop ___ where the milk is.", base: "ASSIST", a: "assistant",
    ru: "Спроси у продавца-консультанта, где молоко.",
    why: "assist → assistant: помощник, суффикс -ant.", lvl: "B1", grp: "agent" },

  // ---------- -ist (продолжение) ----------
  { s: "Thousands of ___ visit the palace every summer.", base: "TOUR", a: "tourists",
    ru: "Тысячи туристов посещают дворец каждое лето.",
    why: "tour → tourist; thousands of — нужно множественное: tourists.", lvl: "A2", grp: "ist" },
  { s: "The ___ played an old rock song.", base: "GUITAR", a: "guitarist",
    ru: "Гитарист сыграл старую рок-песню.",
    why: "Суффикс -ist называет человека по инструменту или занятию: guitar (гитара) → guitarist. Так же piano → pianist, violin → violinist.", lvl: "B1", grp: "ist" },
  { s: "You need a ___ , not a school doctor.", base: "SPECIAL", a: "specialist",
    ru: "Тебе нужен специалист, а не школьный врач.",
    why: "special → specialist.", lvl: "B1", grp: "ist" },
  { s: "A ___ in a yellow helmet passed us at full speed.", base: "CYCLE", a: "cyclist",
    ru: "Велосипедист в жёлтом шлеме пронёсся мимо нас.",
    why: "cycle → cyclist, немая -e уходит.", lvl: "B1", grp: "ist" },

  // ---------- -ment (продолжение) ----------
  { s: "I see a real ___ in your English.", base: "IMPROVE", a: "improvement",
    ru: "Я вижу настоящий прогресс в твоём английском.",
    why: "improve → improvement: существительное на -ment.", lvl: "B1", grp: "ment" },
  { s: "The doctor said that regular ___ is good for your back — try to walk more.", base: "MOVE", a: "movement",
    ru: "Врач сказал, что регулярное движение полезно для спины — старайся больше ходить.",
    why: "move → movement: -ment превращает глагол в существительное. Здесь движение вообще, это неисчисляемое: ни a move, ни moves не годится.", lvl: "B1", grp: "ment" },
  { s: "The children could not hide their ___ before the trip.", base: "EXCITE", a: "excitement",
    ru: "Дети не могли скрыть восторг перед поездкой.",
    why: "excite → excitement.", lvl: "B1", grp: "ment" },
  { s: "The gym bought new sports ___ .", base: "EQUIP", a: "equipment",
    ru: "Спортзал купил новое оборудование.",
    why: "equip → equipment. Неисчисляемое: без множественного числа.", lvl: "B2", grp: "ment" },

  // ---------- -tion / -sion (продолжение) ----------
  { s: "Each pupil made a paper ___ for the school party.", base: "DECORATE", a: "decoration",
    ru: "Каждый ученик сделал бумажное украшение для школьного праздника.",
    why: "После a paper нужно существительное: decorate → decoration, немая -e уходит и добавляется -ion. Артикль a требует единственного числа, и значение здесь предметное — одно бумажное украшение, а не процесс.", lvl: "B1", grp: "tion" },
  { s: "It was a noisy ___ — the music lasted till midnight.", base: "CELEBRATE", a: "celebration",
    ru: "Это был шумный праздник — музыка играла до полуночи.",
    why: "После a нужно существительное в единственном числе: celebrate → celebration. Немая -e уходит, добавляется -ion.", lvl: "B1", grp: "tion" },
  { s: "Use your ___ and draw an unusual animal.", base: "IMAGINE", a: "imagination",
    ru: "Включи воображение и нарисуй необычное животное.",
    why: "imagine → imagination.", lvl: "B1", grp: "tion" },
  { s: "The ___ of the school concert took two weeks.", base: "ORGANISE", a: "organisation", alt: ["organization"],
    ru: "Организация школьного концерта заняла две недели.",
    why: "organise → organisation (амер. organization — тоже верно).", lvl: "B1", grp: "tion" },
  { s: "Air ___ is a big problem in large cities.", base: "POLLUTE", a: "pollution",
    ru: "Загрязнение воздуха — большая проблема больших городов.",
    why: "pollute → pollution.", lvl: "B1", grp: "tion" },
  { s: "Careful ___ is the key to success in any exam.", base: "PREPARE", a: "preparation",
    ru: "Тщательная подготовка — ключ к успеху на любом экзамене.",
    why: "После careful нужно существительное, а не глагол: prepare → preparation, немая -e отпадает и добавляется -ation. Сказуемое is требует единственного числа, поэтому preparations сюда не встанет.", lvl: "B1", grp: "tion" },
  { s: "After a long ___ we chose the red curtains.", base: "DISCUSS", a: "discussion",
    ru: "После долгого обсуждения мы выбрали красные шторы.",
    why: "discuss → discussion: суффикс -ion.", lvl: "B1", grp: "tion" },
  { s: "The art ___ opens on Saturday.", base: "EXHIBIT", a: "exhibition",
    ru: "Художественная выставка открывается в субботу.",
    why: "exhibit → exhibition.", lvl: "B2", grp: "tion" },
  { s: "Check your internet ___ and try again.", base: "CONNECT", a: "connection",
    ru: "Проверь интернет-соединение и попробуй снова.",
    why: "connect → connection.", lvl: "B1", grp: "tion" },
  { s: "The book starts with a short ___ by the author.", base: "INTRODUCE", a: "introduction",
    ru: "Книга начинается с короткого вступления автора.",
    why: "introduce → introduction.", lvl: "B2", grp: "tion" },

  // ---------- -ness (продолжение) ----------
  { s: "After the illness he felt a strange ___ in his legs.", base: "WEAK", a: "weakness",
    ru: "После болезни он чувствовал странную слабость в ногах.",
    why: "weak → weakness.", lvl: "B1", grp: "ness" },
  { s: "___ costs nothing but means a lot.", base: "POLITE", a: "politeness",
    ru: "Вежливость ничего не стоит, но значит очень много.",
    why: "polite → politeness.", lvl: "B1", grp: "ness" },
  { s: "The old sailor spoke about the ___ of life at sea.", base: "LONELY", a: "loneliness",
    ru: "Старый моряк говорил об одиночестве морской жизни.",
    why: "lonely → loneliness: -y меняется на -i.", lvl: "B2", grp: "ness" },
  { s: "Regular exercise improves your ___ .", base: "FIT", a: "fitness",
    ru: "Регулярные упражнения улучшают физическую форму.",
    why: "fit → fitness.", lvl: "B1", grp: "ness" },
  { s: "She could not hide her ___ when the holidays ended.", base: "SAD", a: "sadness",
    ru: "Она не могла скрыть грусть, когда каникулы закончились.",
    why: "sad → sadness.", lvl: "A2", grp: "ness" },
  { s: "___ is the enemy of good driving.", base: "TIRED", a: "tiredness",
    ru: "Усталость — враг хорошего вождения.",
    why: "tired → tiredness.", lvl: "B2", grp: "ness" },

  // ---------- -ity (продолжение) ----------
  { s: "___ killed the cat, says the proverb.", base: "CURIOUS", a: "curiosity",
    ru: "Любопытство сгубило кошку, гласит пословица.",
    why: "Подлежащее — существительное: curious «любопытный» → curiosity, -ous заменяется на -osity (как generous → generosity). Написание curiousity — ошибка.", lvl: "B2", grp: "ity" },
  { s: "Online ___ is worth learning about at school.", base: "SECURE", a: "security",
    ru: "Про безопасность в интернете стоит узнавать ещё в школе.",
    why: "secure → security.", lvl: "B2", grp: "ity" },
  { s: "The ___ of the class voted for the museum trip.", base: "MAJOR", a: "majority",
    ru: "Большинство класса проголосовало за поездку в музей.",
    why: "major → majority.", lvl: "B2", grp: "ity" },
  { s: "I see a strong ___ between these two paintings.", base: "SIMILAR", a: "similarity",
    ru: "Я вижу сильное сходство между этими двумя картинами.",
    why: "similar → similarity.", lvl: "B2", grp: "ity" },
  { s: "The storm left the village without ___ .", base: "ELECTRIC", a: "electricity",
    ru: "Буря оставила деревню без электричества.",
    why: "electric → electricity.", lvl: "B1", grp: "ity" },

  // ---------- -ance / -ence (продолжение) ----------
  { s: "Do not judge people by their ___ .", base: "APPEAR", a: "appearance",
    ru: "Не суди людей по внешности.",
    why: "appear → appearance.", lvl: "B1", grp: "ance" },
  { s: "The band gave their best ___ of the year.", base: "PERFORM", a: "performance",
    ru: "Группа дала своё лучшее выступление за год.",
    why: "perform → performance.", lvl: "B1", grp: "ance" },
  { s: "There was a long ___ before he answered.", base: "SILENT", a: "silence",
    ru: "Прежде чем он ответил, повисла долгая тишина.",
    why: "silent → silence: прилагательное → существительное.", lvl: "B1", grp: "ance" },
  { s: "My ___ is for tea, not coffee.", base: "PREFER", a: "preference",
    ru: "Моё предпочтение — чай, а не кофе.",
    why: "После my нужно существительное: prefer «предпочитать» + -ence → preference. Буква r не удваивается, потому что ударение уходит на первый слог (в отличие от preferred).", lvl: "B2", grp: "ance" },
  { s: "Speak with ___ — you know this topic well.", base: "CONFIDENT", a: "confidence",
    ru: "Говори уверенно — ты хорошо знаешь эту тему.",
    why: "confident → confidence.", lvl: "B2", grp: "ance" },

  // ---------- -ful (продолжение) ----------
  { s: "The concert was very ___ — all the tickets were sold.", base: "SUCCESS", a: "successful",
    ru: "Концерт прошёл очень успешно — все билеты были проданы.",
    why: "success → successful: одна l в суффиксе -ful.", lvl: "B1", grp: "ful" },
  { s: "We had a ___ time at the seaside.", base: "WONDER", a: "wonderful",
    ru: "Мы чудесно провели время на море.",
    why: "wonder → wonderful.", lvl: "A2", grp: "ful" },
  { s: "Autumn parks are ___ in October.", base: "COLOUR", a: "colourful", alt: ["colorful"],
    ru: "Осенние парки в октябре очень красочны.",
    why: "colour → colourful (амер. colorful — тоже верно).", lvl: "A2", grp: "ful" },
  { s: "The bee sting was very ___ and my hand went red.", base: "PAIN", a: "painful",
    ru: "Укус пчелы был очень болезненным, и рука покраснела.",
    why: "Суффикс -ful превращает существительное в прилагательное: pain (боль) → painful (болезненный). Обратный суффикс -less («без») тут не подходит: рука покраснела, боль была.", lvl: "B1", grp: "ful" },
  { s: "The new computer is much more ___ than the old one.", base: "POWER", a: "powerful",
    ru: "Новый компьютер гораздо мощнее старого.",
    why: "power → powerful.", lvl: "B1", grp: "ful" },

  // ---------- -less (продолжение) ----------
  { s: "The charity helps ___ people find shelter.", base: "HOME", a: "homeless",
    ru: "Благотворительный фонд помогает бездомным найти приют.",
    why: "home → homeless: без дома.", lvl: "B1", grp: "less" },
  { s: "The queue seemed ___ — we waited an hour.", base: "END", a: "endless",
    ru: "Очередь казалась бесконечной — мы прождали час.",
    why: "end → endless.", lvl: "B1", grp: "less" },
  { s: "The café has free ___ internet.", base: "WIRE", a: "wireless",
    ru: "В кафе есть бесплатный беспроводной интернет.",
    why: "wire → wireless: без проводов.", lvl: "B2", grp: "less" },
  { s: "The kitten looked small and ___ .", base: "HELP", a: "helpless",
    ru: "Котёнок выглядел маленьким и беспомощным.",
    why: "help → helpless.", lvl: "B1", grp: "less" },
  { s: "Arguing with him is ___ — he never listens.", base: "USE", a: "useless",
    ru: "Спорить с ним бесполезно — он никогда не слушает.",
    why: "use → useless.", lvl: "B1", grp: "less" },

  // ---------- -able / -ible (продолжение) ----------
  { s: "The trip was tiring but very ___ .", base: "ENJOY", a: "enjoyable",
    ru: "Поездка была утомительной, но очень приятной.",
    why: "enjoy → enjoyable.", lvl: "B1", grp: "able" },
  { s: "The plot of the film was too ___ — I guessed the ending after ten minutes.", base: "PREDICT", a: "predictable",
    ru: "Сюжет фильма был слишком предсказуемым — я угадал концовку через десять минут.",
    why: "Суффикс -able превращает глагол в прилагательное «такой, который можно...»: predict (предсказывать) → predictable (который можно предсказать). Приставка un- дала бы обратный смысл, но концовку угадали уже через десять минут — значит, предсказать сюжет было можно.", lvl: "B2", grp: "able" },
  { s: "The result is not brilliant, but it is quite ___ .", base: "ACCEPT", a: "acceptable",
    ru: "Результат не блестящий, но вполне приемлемый.",
    why: "Суффикс -able превращает глагол в прилагательное «такой, который можно...»: accept (принимать) → acceptable (приемлемый, который можно принять). Слово but показывает, что оценка всё-таки положительная, поэтому приставка un- не нужна.", lvl: "B2", grp: "able" },
  { s: "She always wears ___ clothes.", base: "FASHION", a: "fashionable",
    ru: "Она всегда носит модную одежду.",
    why: "fashion → fashionable.", lvl: "B1", grp: "able" },
  { s: "Is the water in this river ___ ?", base: "DRINK", a: "drinkable",
    ru: "Можно ли пить воду из этой реки?",
    why: "drink → drinkable: пригодный для питья.", lvl: "B2", grp: "able" },

  // ---------- -ous (продолжение) ----------
  { s: "The old house looked dark and ___ .", base: "MYSTERY", a: "mysterious",
    ru: "Старый дом выглядел тёмным и таинственным.",
    why: "mystery → mysterious: -y меняется на -i.", lvl: "B2", grp: "ous" },
  { s: "She is brave and ___ — a real traveller.", base: "ADVENTURE", a: "adventurous",
    ru: "Она смелая и любит приключения — настоящая путешественница.",
    why: "adventure → adventurous.", lvl: "B2", grp: "ous" },
  { s: "Some mushrooms are ___ , so be careful.", base: "POISON", a: "poisonous",
    ru: "Некоторые грибы ядовиты, так что будь осторожен.",
    why: "poison → poisonous.", lvl: "B1", grp: "ous" },
  { s: "The students in our class come from ___ countries: Spain, Japan and Brazil.", base: "VARY", a: "various",
    ru: "Ученики нашего класса приехали из разных стран: из Испании, Японии и Бразилии.",
    why: "Суффикс -ous даёт прилагательное, а конечная -y перед ним меняется на -i-: vary (различаться) → various («разные», несколько разных). Так же mystery → mysterious.", lvl: "B2", grp: "ous" },
  { s: "It was a ___ morning: sun, snow and silence.", base: "GLORY", a: "glorious",
    ru: "Это было великолепное утро: солнце, снег и тишина.",
    why: "glory → glorious.", lvl: "B2", grp: "ous" },

  // ---------- -ive (продолжение) ----------
  { s: "The city centre is old and very ___ to tourists.", base: "ATTRACT", a: "attractive",
    ru: "Центр города старинный и очень привлекательный для туристов.",
    why: "Суффикс -ive превращает глагол в прилагательное: attract (привлекать) → attractive (привлекательный). Запомни предлог: attractive to somebody.", lvl: "B1", grp: "ive" },
  { s: "This phone is too ___ for me.", base: "EXPENSE", a: "expensive",
    ru: "Этот телефон слишком дорогой для меня.",
    why: "expense → expensive.", lvl: "A2", grp: "ive" },
  { s: "Her project was the most ___ in the class.", base: "IMPRESS", a: "impressive",
    ru: "Её проект был самым впечатляющим в классе.",
    why: "impress → impressive.", lvl: "B1", grp: "ive" },
  { s: "My parents are very ___ of my hobbies.", base: "SUPPORT", a: "supportive",
    ru: "Мои родители очень поддерживают мои увлечения.",
    why: "support → supportive.", lvl: "B2", grp: "ive" },
  { s: "My little sister is very ___ — she never stops chatting.", base: "TALK", a: "talkative",
    ru: "Моя младшая сестра очень болтливая — не замолкает ни на минуту.",
    why: "talk → talkative.", lvl: "B1", grp: "ive" },

  // ---------- -al (продолжение) ----------
  { s: "Borscht is a ___ dish in our family.", base: "TRADITION", a: "traditional",
    ru: "Борщ — традиционное блюдо в нашей семье.",
    why: "tradition → traditional.", lvl: "B1", grp: "al" },
  { s: "He plays football at a ___ level.", base: "PROFESSION", a: "professional",
    ru: "Он играет в футбол на профессиональном уровне.",
    why: "profession → professional.", lvl: "B1", grp: "al" },
  { s: "You need ___ help, not advice from the internet.", base: "MEDICINE", a: "medical",
    ru: "Тебе нужна медицинская помощь, а не советы из интернета.",
    why: "medicine → medical.", lvl: "B2", grp: "al" },
  { s: "The school is in the ___ part of the town.", base: "CENTRE", a: "central",
    ru: "Школа находится в центральной части города.",
    why: "centre → central.", lvl: "B1", grp: "al" },
  { s: "Is this the ___ painting or a copy?", base: "ORIGIN", a: "original",
    ru: "Это подлинник картины или копия?",
    why: "origin → original.", lvl: "B1", grp: "al" },

  // ---------- -y (продолжение) ----------
  { s: "Drive slowly: the morning is very ___ .", base: "FOG", a: "foggy",
    ru: "Веди машину медленно: утро очень туманное.",
    why: "fog → foggy: согласная удваивается.", lvl: "A2", grp: "y" },
  { s: "It is too ___ to play badminton outside.", base: "WIND", a: "windy",
    ru: "Слишком ветрено, чтобы играть в бадминтон на улице.",
    why: "wind → windy.", lvl: "A2", grp: "y" },
  { s: "The soup is a bit too ___ for me.", base: "SALT", a: "salty",
    ru: "Суп для меня немного пересолен.",
    why: "salt → salty.", lvl: "A2", grp: "y" },
  { s: "After the rain the road was ___ .", base: "MUD", a: "muddy",
    ru: "После дождя дорога была грязной.",
    why: "mud → muddy: согласная удваивается.", lvl: "B1", grp: "y" },

  // ---------- -ly (продолжение) ----------
  { s: "You can ___ find this rule in the textbook.", base: "EASY", a: "easily",
    ru: "Это правило легко найти в учебнике.",
    why: "Наречие отвечает на вопрос «как найти?»: easy + -ly, конечная -y после согласной меняется на -i → easily.", lvl: "A2", grp: "ly" },
  { s: "\u0022Go away!\u0022 she said ___ .", base: "ANGRY", a: "angrily",
    ru: "«Уходи!» — сказала она сердито.",
    why: "Слово отвечает на вопрос «как сказала?» — нужно наречие: angry + -ly, конечная -y после согласной меняется на -i → angrily (как easy → easily).", lvl: "B1", grp: "ly" },
  { s: "After three tries he ___ passed the test.", base: "FINAL", a: "finally",
    ru: "После трёх попыток он наконец сдал тест.",
    why: "final → finally: двойная l на стыке.", lvl: "B1", grp: "ly" },
  { s: "___ , the rain stopped just before the match.", base: "FORTUNATE", a: "fortunately",
    ru: "К счастью, дождь закончился прямо перед матчем.",
    why: "fortunate → fortunately.", lvl: "B2", grp: "ly" },
  { s: "I ___ forgot about the meeting.", base: "COMPLETE", a: "completely",
    ru: "Я совершенно забыл о встрече.",
    why: "complete → completely.", lvl: "B1", grp: "ly" },

  // ---------- приставки-отрицания (продолжение) ----------
  { s: "The shop assistant was cold and ___ .", base: "FRIENDLY", a: "unfriendly",
    ru: "Продавец был холоден и недружелюбен.",
    why: "Отрицание прилагательных чаще всего даёт приставка un-, как в unhappy и unkind: friendly → unfriendly.", lvl: "B1", grp: "neg" },
  { s: "Hiding the truth is simply ___ .", base: "HONEST", a: "dishonest",
    ru: "Скрывать правду — попросту нечестно.",
    why: "honest → dishonest: приставка dis-.", lvl: "B2", grp: "neg" },
  { s: "It is ___ to interrupt people.", base: "POLITE", a: "impolite",
    ru: "Перебивать людей невежливо.",
    why: "polite → impolite: перед p — приставка im-.", lvl: "B1", grp: "neg" },
  { s: "English has many ___ verbs like go and see.", base: "REGULAR", a: "irregular",
    ru: "В английском много неправильных глаголов вроде go и see.",
    why: "regular → irregular: перед r — приставка ir-.", lvl: "B1", grp: "neg" },
  { s: "Parking here is ___ — you will get a fine.", base: "LEGAL", a: "illegal",
    ru: "Парковаться здесь незаконно — получишь штраф.",
    why: "legal → illegal: перед l — приставка il-.", lvl: "B2", grp: "neg" },
  { s: "I ___ getting up early, so on Sundays I sleep till ten.", base: "LIKE", a: "dislike",
    ru: "Я не люблю рано вставать, поэтому по воскресеньям сплю до десяти.",
    why: "like → dislike: приставка dis- даёт глагол-антоним.", lvl: "B1", grp: "neg" },
  { s: "The magician made the coin ___ , and nobody could find it again.", base: "APPEAR", a: "disappear",
    ru: "Фокусник заставил монету исчезнуть, и никто больше не смог её найти.",
    why: "appear → disappear: приставка dis- даёт противоположное действие.", lvl: "B1", grp: "neg" },
  { s: "The hostel is clean and quite ___ — a week there cost us very little.", base: "EXPENSIVE", a: "inexpensive",
    ru: "Хостел чистый и вполне недорогой — неделя там обошлась нам совсем дёшево.",
    why: "expensive → inexpensive: отрицание даёт приставка in-. Un- с этим словом не употребляют.", lvl: "B2", grp: "neg" },
  { s: "It is ___ that she gets all the blame — she was not even there when it happened.", base: "FAIR", a: "unfair",
    ru: "Несправедливо, что вся вина падает на неё — её даже не было там, когда это случилось.",
    why: "У этого слова отрицание даёт приставка un-: fair → unfair. Форм infair или disfair в английском нет.", lvl: "B1", grp: "neg" },
  { s: "The letter was friendly and ___ , full of jokes and family news.", base: "FORMAL", a: "informal",
    ru: "Письмо было дружеским и неформальным, полным шуток и семейных новостей.",
    why: "formal → informal: отрицание тут даёт приставка in-. Слова unformal в английском нет.", lvl: "B2", grp: "neg" },
  { s: "Do not be so ___ — the bus will come.", base: "PATIENT", a: "impatient",
    ru: "Не будь таким нетерпеливым — автобус придёт.",
    why: "patient → impatient: перед p — im-.", lvl: "B1", grp: "neg" },
  { s: "These new shoes are beautiful but ___ — my feet start hurting after ten minutes.", base: "COMFORTABLE", a: "uncomfortable",
    ru: "Эти новые туфли красивые, но неудобные — у меня через десять минут начинают болеть ноги.",
    why: "После but нужно слово с обратным знаком, и хвост про больные ноги показывает какое: comfortable → uncomfortable. У этого слова отрицание даёт приставка un-, а не in- или dis-.", lvl: "B1", grp: "neg" },

  // ---------- глаголы из прилагательных (продолжение) ----------
  { s: "Can you ___ this text to one paragraph?", base: "SHORT", a: "shorten",
    ru: "Можешь сократить этот текст до одного абзаца?",
    why: "short → shorten: суффикс -en делает глагол.", lvl: "B2", grp: "verb" },
  { s: "___ the dough with your hands.", base: "FLAT", a: "flatten",
    ru: "Расплющи тесто руками.",
    why: "flat → flatten: согласная удваивается.", lvl: "B2", grp: "verb" },
  { s: "The town wants to ___ its old library.", base: "MODERN", a: "modernise", alt: ["modernize"],
    ru: "Город хочет модернизировать свою старую библиотеку.",
    why: "modern → modernise (амер. modernize).", lvl: "B2", grp: "verb" },
  { s: "Good teachers ___ students to ask questions.", base: "COURAGE", a: "encourage",
    ru: "Хорошие учителя поощряют учеников задавать вопросы.",
    why: "courage → encourage: приставка en- делает глагол.", lvl: "B2", grp: "verb" },
  { s: "Reading will ___ your vocabulary.", base: "RICH", a: "enrich",
    ru: "Чтение обогатит твой словарный запас.",
    why: "rich → enrich: приставка en-.", lvl: "B2", grp: "verb" },
  { s: "We decided to ___ the photo and hang it on the wall.", base: "LARGE", a: "enlarge",
    ru: "Мы решили увеличить фото и повесить его на стену.",
    why: "large → enlarge.", lvl: "B2", grp: "verb" },

  // ---------- неправильные пары (продолжение) ----------
  { s: "What is the ___ of this box?", base: "WEIGH", a: "weight",
    ru: "Каков вес этой коробки?",
    why: "weigh — глагол «весить», а после the нужно существительное «вес»: добавляется -t, weigh → weight. Буквы gh не читаются ни в том, ни в другом слове.", lvl: "B1", grp: "irr" },
  { s: "Our ___ to Sochi took two hours.", base: "FLY", a: "flight",
    ru: "Наш перелёт в Сочи занял два часа.",
    why: "fly → flight: форма меняется целиком.", lvl: "B1", grp: "irr" },
  { s: "It was a difficult ___ : the museum or the cinema.", base: "CHOOSE", a: "choice",
    ru: "Это был трудный выбор: музей или кино.",
    why: "choose → choice.", lvl: "B1", grp: "irr" },
  { s: "The director gave a short ___ at the school meeting.", base: "SPEAK", a: "speech",
    ru: "Директор произнесла короткую речь на школьном собрании.",
    why: "speak → speech.", lvl: "B1", grp: "irr" },
  { s: "The tower disappeared from ___ in the fog.", base: "SEE", a: "sight",
    ru: "Башня скрылась из виду в тумане.",
    why: "see → sight.", lvl: "B2", grp: "irr" },
  { s: "The ___ of the old oak upset the whole street.", base: "DIE", a: "death",
    ru: "Гибель старого дуба огорчила всю улицу.",
    why: "die → death.", lvl: "B2", grp: "irr" },

  // ---------- вперемешку, как в экзамене (продолжение) ----------
  { s: "Tell me the ___ — did you break the vase?", base: "TRUE", a: "truth",
    ru: "Скажи мне правду — это ты разбил вазу?",
    why: "true → truth.", lvl: "B1", grp: "mix" },
  { s: "She spent her ___ in a small village.", base: "CHILD", a: "childhood",
    ru: "Детство она провела в маленькой деревне.",
    why: "child → childhood: суффикс -hood.", lvl: "B1", grp: "mix" },
  { s: "Their ___ began in the first grade.", base: "FRIEND", a: "friendship",
    ru: "Их дружба началась в первом классе.",
    why: "friend → friendship: суффикс -ship.", lvl: "B1", grp: "mix" },
  { s: "Club ___ costs very little for pupils.", base: "MEMBER", a: "membership",
    ru: "Членство в клубе стоит для школьников совсем немного.",
    why: "member → membership.", lvl: "B2", grp: "mix" },
  { s: "We moved to a quiet ___ last year.", base: "NEIGHBOUR", a: "neighbourhood", alt: ["neighborhood"],
    ru: "В прошлом году мы переехали в тихий район.",
    why: "neighbour → neighbourhood (амер. neighborhood).", lvl: "B2", grp: "mix" },
  { s: "I remember the ___ of my grandmother's kitchen.", base: "WARM", a: "warmth",
    ru: "Я помню тепло бабушкиной кухни.",
    why: "warm → warmth: существительное на -th.", lvl: "B2", grp: "mix" },
  { s: "The ___ of the internet changed everything.", base: "GROW", a: "growth",
    ru: "Рост интернета изменил всё.",
    why: "grow → growth.", lvl: "B2", grp: "mix" },
  { s: "The team took the ___ very hard.", base: "LOSE", a: "loss",
    ru: "Команда тяжело переживала поражение.",
    why: "После the нужно существительное — название события: lose (проигрывать) → loss (поражение). Суффикса нет, но меняется корень — как choose → choice. Поэтому не losing и не loser.", lvl: "B1", grp: "mix" },
  { s: "There is no ___ that he took your pen.", base: "PROVE", a: "proof",
    ru: "Нет доказательств, что он взял твою ручку.",
    why: "После no нужно существительное. От prove существительное образуется без суффикса, с заменой v на f: prove → proof — как believe → belief.", lvl: "B2", grp: "mix" },
  { s: "I had ___ feelings about moving to a new school — I was happy and sad at the same time.", base: "MIX", a: "mixed",
    ru: "У меня были смешанные чувства по поводу переезда в новую школу — мне было и радостно, и грустно одновременно.",
    why: "Слово стоит перед существительным feelings, значит нужно определение, а не глагол: от mix его даёт форма на -ed. Mixed feelings — «смешанные чувства», и вторая часть про happy и sad сразу это как раз описывает.", lvl: "B1", grp: "mix" },
  { s: "There is a lot of ___ on pupils before exams.", base: "PRESS", a: "pressure",
    ru: "Перед экзаменами на учеников оказывается сильное давление.",
    why: "После a lot of нужно существительное. От глагола press (давить) его даёт суффикс -ure: press → pressure (давление) — как fail → failure.", lvl: "B2", grp: "mix" },
  { s: "Put your ___ at the bottom of the page.", base: "SIGN", a: "signature",
    ru: "Поставь подпись внизу страницы.",
    why: "После your нужно существительное. Само sign — это «знак» или «подписывать», а «подпись» — signature: sign + -ature.", lvl: "B2", grp: "mix" },
  { s: "I made a ___ about the noise in the hotel.", base: "COMPLAIN", a: "complaint",
    ru: "Я подал жалобу на шум в отеле.",
    why: "После a нужно существительное в единственном числе: complain (жаловаться) + -t = complaint (жалоба). По-английски жалобу «делают»: make a complaint.", lvl: "B2", grp: "mix" },
];
