// Сгенерировано tools/build_audio.py — руками не править.
// Слова, на которые есть запись живого носителя: файл всегда
// audio/words/<слово>.mp3, где не-[a-z0-9-] заменены на «_»
// (та же замена в speakNative в js/exercises.js).
// Авторы и лицензии — audio/words/manifest.json и credits.html.
const WORD_AUDIO = {
  "abandon": 1, "abandoned": 1, "abandonment": 1, "abatement": 1, "abbey": 1, "abbot": 1,
  "abbreviated": 1, "abdomen": 1, "abdominal": 1, "abduct": 1, "abide": 1, "abnormal": 1,
  "aboard": 1, "abode": 1, "abolish": 1, "aboriginal": 1, "abracadabra": 1, "abridged": 1,
  "abroad": 1, "abrupt": 1, "abruptly": 1, "absence": 1, "absent": 1, "absolute": 1,
  "absolutely": 1, "absolve": 1, "absorb": 1, "absorbed": 1, "absorbing": 1, "absorption": 1,
  "abstinence": 1, "absurd": 1, "abundance": 1, "abundant": 1, "abyss": 1, "academic": 1,
  "academy": 1, "accelerate": 1, "acceleration": 1, "accelerator": 1, "accept": 1,
  "acceptable": 1, "acceptance": 1, "access": 1, "accession": 1, "accessory": 1, "accidental": 1,
  "accidentally": 1, "accommodate": 1, "accompany": 1, "accomplice": 1, "accomplish": 1,
  "accomplished": 1, "accord": 1, "accordance": 1, "accordingly": 1, "accordion": 1,
  "accountable": 1, "accreditation": 1, "accrue": 1, "accumulate": 1, "accumulation": 1,
  "accuracy": 1, "accurate": 1, "accusation": 1, "accuse": 1, "accused": 1, "ace": 1,
  "acetate": 1, "ache": 1, "achieve": 1, "achievement": 1, "acid": 1, "acknowledge": 1,
  "acknowledged": 1, "acne": 1, "acorn": 1, "acoustic": 1, "acoustics": 1, "acquaintance": 1,
  "acquainted": 1, "acquire": 1, "acre": 1, "acronym": 1, "activate": 1, "active": 1, "actor": 1,
  "actually": 1, "acupuncture": 1, "acute": 1, "adamant": 1, "adapt": 1, "add": 1, "addition": 1,
  "additional": 1, "adept": 1, "adhere": 1, "adhesive": 1, "adjacent": 1, "adjoining": 1,
  "adjourn": 1, "adjunct": 1, "adjustment": 1, "administer": 1, "administrative": 1,
  "administrator": 1, "admirable": 1, "admiral": 1, "admiralty": 1, "admiration": 1, "admire": 1,
  "admirer": 1, "admit": 1, "admittedly": 1, "adobe": 1, "adopt": 1, "adore": 1, "adult": 1,
  "advantage": 1, "advent": 1, "adventure": 1, "adventurous": 1, "adversary": 1, "adverse": 1,
  "adversity": 1, "advertisement": 1, "advise": 1, "advisor": 1, "adware": 1, "aesthetic": 1,
  "affair": 1, "affect": 1, "affected": 1, "affection": 1, "affectionate": 1, "affirm": 1,
  "affirmative": 1, "affluent": 1, "afford": 1, "afloat": 1, "afraid": 1, "aftermath": 1,
  "afternoon": 1, "afterwards": 1, "again": 1, "agenda": 1, "aggressive": 1, "aggressively": 1,
  "agile": 1, "agony": 1, "agreeable": 1, "agreement": 1, "agricultural": 1, "agriculture": 1,
  "ahead": 1, "aim": 1, "air": 1, "aircraft": 1, "airfare": 1, "airplane": 1, "airport": 1,
  "aisle": 1, "alarm": 1, "alas": 1, "alchemist": 1, "alchemy": 1, "ale": 1, "alert": 1,
  "algebra": 1, "algorithm": 1, "alibi": 1, "alien": 1, "alignment": 1, "alike": 1, "alimony": 1,
  "alive": 1, "alkaline": 1, "allegation": 1, "alleged": 1, "allegiance": 1, "alleviate": 1,
  "alley": 1, "allied": 1, "alligator": 1, "allow": 1, "allowance": 1, "alloy": 1, "ally": 1,
  "almond": 1, "almost": 1, "alone": 1, "alongside": 1, "aloud": 1, "alpha": 1, "alphabet": 1,
  "alphabetical": 1, "already": 1, "altar": 1, "alteration": 1, "altered": 1, "alternative": 1,
  "although": 1, "alto": 1, "altogether": 1, "aluminium": 1, "always": 1, "amaze": 1,
  "amazing": 1, "amber": 1, "ambiguity": 1, "ambiguous": 1, "ambition": 1, "ambitious": 1,
  "ambulance": 1, "ambulatory": 1, "amethyst": 1, "ammunition": 1, "amongst": 1, "amount": 1,
  "ample": 1, "amplitude": 1, "amusement": 1, "amusing": 1, "analog": 1, "analogous": 1,
  "analogy": 1, "analysis": 1, "analyst": 1, "analyze": 1, "anatomy": 1, "ancestor": 1,
  "anchor": 1, "ancient": 1, "ancillary": 1, "android": 1, "aneurysm": 1, "anew": 1,
  "angelic": 1, "angelica": 1, "anger": 1, "angle": 1, "angry": 1, "angst": 1, "anguish": 1,
  "angular": 1, "animal": 1, "animation": 1, "anime": 1, "ankle": 1, "annex": 1, "annihilate": 1,
  "anniversary": 1, "announce": 1, "announcement": 1, "annoy": 1, "annoyed": 1, "annual": 1,
  "anomaly": 1, "anonymity": 1, "anonymous": 1, "answer": 1, "ant": 1, "ante": 1, "antenna": 1,
  "anterior": 1, "anthology": 1, "anthrax": 1, "anthropology": 1, "antibiotic": 1, "antibody": 1,
  "anticipate": 1, "antigen": 1, "antique": 1, "antiquity": 1, "anxiety": 1, "anxious": 1,
  "anybody": 1, "anyhow": 1, "anyone": 1, "anyway": 1, "anywhere": 1, "apartment": 1,
  "apathy": 1, "ape": 1, "apologize": 1, "apology": 1, "apostle": 1, "app": 1, "apparatus": 1,
  "apparel": 1, "apparent": 1, "apparently": 1, "appeal": 1, "appear": 1, "appearance": 1,
  "append": 1, "appendix": 1, "appetite": 1, "appetizer": 1, "applaud": 1, "applause": 1,
  "apple": 1, "appliance": 1, "applicable": 1, "application": 1, "applied": 1, "apply": 1,
  "appointment": 1, "appraisal": 1, "appreciate": 1, "approaches": 1, "approaching": 1,
  "approval": 1, "approximately": 1, "apricot": 1, "apron": 1, "apt": 1, "aquarium": 1,
  "aquatic": 1, "arbitrary": 1, "arbor": 1, "arc": 1, "arch": 1, "archaeological": 1,
  "archaeology": 1, "archaic": 1, "archbishop": 1, "archipelago": 1, "architect": 1,
  "architecture": 1, "archive": 1, "arguably": 1, "argue": 1, "argument": 1, "arid": 1,
  "arise": 1, "arithmetic": 1, "armchair": 1, "armed": 1, "armor": 1, "armpit": 1, "aroma": 1,
  "arouse": 1, "arrange": 1, "arrangement": 1, "array": 1, "arrival": 1, "arrive": 1,
  "arrogant": 1, "arrow": 1, "arsenic": 1, "art": 1, "artery": 1, "article": 1,
  "articulation": 1, "artificial": 1, "artillery": 1, "artist": 1, "ascend": 1, "ascent": 1,
  "ascertain": 1, "ash": 1, "ashamed": 1, "ashtray": 1, "aside": 1, "ask": 1, "asleep": 1,
  "asp": 1, "asparagus": 1, "aspect": 1, "asphalt": 1, "aspire": 1, "assassin": 1, "assault": 1,
  "assemble": 1, "assembly": 1, "assert": 1, "assertion": 1, "assess": 1, "assiduous": 1,
  "assign": 1, "assignment": 1, "assist": 1, "assistance": 1, "assistant": 1, "associate": 1,
  "assume": 1, "assumption": 1, "assurance": 1, "assure": 1, "asterisk": 1, "asteroid": 1,
  "astonished": 1, "astonishing": 1, "astral": 1, "astray": 1, "astronomer": 1,
  "astronomical": 1, "astronomy": 1, "asylum": 1, "asynchronous": 1, "athlete": 1,
  "atmosphere": 1, "atom": 1, "atomic": 1, "atone": 1, "attachment": 1, "attacker": 1,
  "attain": 1, "attainment": 1, "attempt": 1, "attend": 1, "attendant": 1, "attention": 1,
  "attentive": 1, "attitude": 1, "attorney": 1, "attraction": 1, "attractive": 1, "auction": 1,
  "audience": 1, "audio": 1, "audit": 1, "audition": 1, "auditor": 1, "aunt": 1, "auspicious": 1,
  "authority": 1, "authorize": 1, "autism": 1, "autobiography": 1, "automate": 1, "automatic": 1,
  "automobile": 1, "autonomous": 1, "autonomy": 1, "autumn": 1, "avail": 1, "available": 1,
  "avalanche": 1, "avatar": 1, "avenger": 1, "avenue": 1, "avocado": 1, "avoid": 1, "await": 1,
  "awake": 1, "aware": 1, "awareness": 1, "awe": 1, "awesome": 1, "awful": 1, "awhile": 1,
  "awkward": 1, "axe": 1, "axiom": 1, "axis": 1, "baa": 1, "babe": 1, "baboon": 1, "baby": 1,
  "babysit": 1, "bachelor": 1, "backbone": 1, "backing": 1, "backpack": 1, "backside": 1,
  "bad": 1, "badger": 1, "badly": 1, "badminton": 1, "bag": 1, "bagel": 1, "bait": 1, "bake": 1,
  "baker": 1, "bakery": 1, "balcony": 1, "bald": 1, "bale": 1, "ballad": 1, "ballast": 1,
  "ballistic": 1, "balloon": 1, "bamboo": 1, "banana": 1, "bang": 1, "banjo": 1, "bank": 1,
  "banner": 1, "banquet": 1, "banter": 1, "baptism": 1, "barb": 1, "barbarian": 1, "barbecue": 1,
  "barber": 1, "bard": 1, "bare": 1, "barefoot": 1, "bargain": 1, "bark": 1, "barking": 1,
  "barley": 1, "barrel": 1, "barren": 1, "barricade": 1, "barrier": 1, "barrow": 1, "bars": 1,
  "base": 1, "baseball": 1, "based": 1, "basement": 1, "basically": 1, "basil": 1, "basin": 1,
  "basket": 1, "basketball": 1, "bass": 1, "bat": 1, "batch": 1, "bathe": 1, "bathing": 1,
  "bathroom": 1, "baton": 1, "batter": 1, "battered": 1, "battery": 1, "bay": 1, "bazaar": 1,
  "bead": 1, "beak": 1, "beam": 1, "bean": 1, "beanie": 1, "bear": 1, "beard": 1, "bearing": 1,
  "beast": 1, "beastly": 1, "beating": 1, "beau": 1, "beautiful": 1, "beautifully": 1,
  "beaver": 1, "become": 1, "bed": 1, "bedroom": 1, "bedtime": 1, "bee": 1, "beech": 1,
  "beef": 1, "beetle": 1, "befall": 1, "beforehand": 1, "beg": 1, "beggar": 1, "begin": 1,
  "behave": 1, "behavior": 1, "behold": 1, "beige": 1, "belief": 1, "believe": 1, "believer": 1,
  "bell": 1, "bellows": 1, "belly": 1, "belong": 1, "belonging": 1, "belt": 1, "bench": 1,
  "benevolent": 1, "bent": 1, "berry": 1, "best": 1, "beta": 1, "betrothed": 1, "better": 1,
  "beverage": 1, "beware": 1, "bezel": 1, "bi": 1, "bias": 1, "biased": 1, "bib": 1,
  "biblical": 1, "bicycle": 1, "biennial": 1, "big": 1, "bike": 1, "bikini": 1, "bin": 1,
  "binary": 1, "bind": 1, "binder": 1, "binding": 1, "bingo": 1, "binoculars": 1, "biography": 1,
  "bioinformatics": 1, "biology": 1, "birch": 1, "bird": 1, "birth": 1, "birthday": 1,
  "birthmark": 1, "biscuit": 1, "bishop": 1, "bite": 1, "bitter": 1, "bizarre": 1, "black": 1,
  "blackberry": 1, "blackboard": 1, "blacksmith": 1, "bladder": 1, "blade": 1, "blame": 1,
  "blanket": 1, "blasphemy": 1, "blast": 1, "blasted": 1, "blatant": 1, "blaze": 1, "bleach": 1,
  "bleak": 1, "bleeding": 1, "blend": 1, "blender": 1, "bless": 1, "blessing": 1, "blindness": 1,
  "blizzard": 1, "blob": 1, "bloc": 1, "blog": 1, "bloke": 1, "bloodshed": 1, "bloodstream": 1,
  "bloodthirsty": 1, "bloom": 1, "blooming": 1, "blossom": 1, "blot": 1, "blue": 1,
  "blueberry": 1, "blueprint": 1, "blunt": 1, "blur": 1, "blush": 1, "boar": 1, "boast": 1,
  "boat": 1, "bodily": 1, "body": 1, "bodybuilding": 1, "bog": 1, "bogus": 1, "boiling": 1,
  "bold": 1, "bolt": 1, "bonanza": 1, "bond": 1, "bone": 1, "bonfire": 1, "bonkers": 1,
  "bonnet": 1, "bonsai": 1, "boo": 1, "book": 1, "boot": 1, "boots": 1, "border": 1, "bore": 1,
  "boring": 1, "borough": 1, "borrow": 1, "boss": 1, "bot": 1, "botanical": 1, "botany": 1,
  "bother": 1, "bottle": 1, "boulder": 1, "bounce": 1, "bound": 1, "boundary": 1, "bouquet": 1,
  "bourgeois": 1, "bovine": 1, "bowels": 1, "bowl": 1, "box": 1, "boy": 1, "boyfriend": 1,
  "bracket": 1, "braid": 1, "brains": 1, "brake": 1, "branch": 1, "brass": 1, "brave": 1,
  "bravely": 1, "bravery": 1, "brawn": 1, "bray": 1, "breach": 1, "bread": 1, "breadth": 1,
  "breakfast": 1, "breakthrough": 1, "breath": 1, "breathe": 1, "breathtaking": 1, "breed": 1,
  "breeze": 1, "brethren": 1, "brew": 1, "brick": 1, "bride": 1, "bridge": 1, "brief": 1,
  "briefly": 1, "brig": 1, "brigade": 1, "bright": 1, "brightness": 1, "brilliant": 1,
  "bring": 1, "brittle": 1, "broad": 1, "broadcast": 1, "broccoli": 1, "brochure": 1,
  "bronze": 1, "brood": 1, "brook": 1, "broom": 1, "broth": 1, "brother": 1, "brow": 1,
  "brown": 1, "browse": 1, "bruise": 1, "brush": 1, "brute": 1, "bubble": 1, "bucket": 1,
  "buckle": 1, "bucolic": 1, "bud": 1, "budget": 1, "buffalo": 1, "buffer": 1, "buffet": 1,
  "buffoon": 1, "bug": 1, "build": 1, "building": 1, "bulb": 1, "bulk": 1, "bulky": 1, "bull": 1,
  "bully": 1, "bummer": 1, "bumper": 1, "bunch": 1, "bundle": 1, "burden": 1, "bureau": 1,
  "burn": 1, "burning": 1, "burnt": 1, "burst": 1, "bus": 1, "bush": 1, "business": 1,
  "businessman": 1, "businesswoman": 1, "bust": 1, "busy": 1, "butcher": 1, "butler": 1,
  "butt": 1, "butte": 1, "butter": 1, "buy": 1, "buyer": 1, "buzz": 1, "byte": 1, "cab": 1,
  "cabbage": 1, "cabin": 1, "cable": 1, "cache": 1, "cacophony": 1, "cactus": 1, "caffeine": 1,
  "cage": 1, "cahoots": 1, "cake": 1, "calamity": 1, "calcium": 1, "calculate": 1,
  "calculator": 1, "calendar": 1, "calf": 1, "calm": 1, "calmly": 1, "calorie": 1, "camel": 1,
  "camera": 1, "campaign": 1, "camper": 1, "campsite": 1, "campus": 1, "canal": 1, "canary": 1,
  "candid": 1, "candidate": 1, "candle": 1, "candy": 1, "cane": 1, "cannon": 1, "cannot": 1,
  "canoe": 1, "canopy": 1, "cant": 1, "canvas": 1, "cap": 1, "capable": 1, "capacity": 1,
  "cape": 1, "capillary": 1, "captive": 1, "capture": 1, "car": 1, "caramel": 1, "caravan": 1,
  "carbohydrate": 1, "carbon": 1, "carcass": 1, "cardboard": 1, "cardinal": 1, "career": 1,
  "carefree": 1, "careful": 1, "carefully": 1, "careless": 1, "cargo": 1, "caribou": 1,
  "caring": 1, "carp": 1, "carpet": 1, "carriage": 1, "carrot": 1, "carry": 1, "cart": 1,
  "cartilage": 1, "cartoon": 1, "carve": 1, "carved": 1, "cash": 1, "casserole": 1, "caste": 1,
  "casting": 1, "castle": 1, "casualty": 1, "cat": 1, "catalogue": 1, "catastrophe": 1,
  "catch": 1, "catcher": 1, "cater": 1, "caterpillar": 1, "cathedral": 1, "cattle": 1,
  "cauldron": 1, "caution": 1, "cautious": 1, "cavalry": 1, "cave": 1, "cease": 1, "cedar": 1,
  "ceiling": 1, "celebrate": 1, "celebration": 1, "celery": 1, "celestial": 1, "celibate": 1,
  "cello": 1, "cement": 1, "census": 1, "cent": 1, "central": 1, "cereal": 1, "cerebral": 1,
  "ceremonial": 1, "ceremony": 1, "certain": 1, "certainty": 1, "chain": 1, "chair": 1,
  "chairman": 1, "chalet": 1, "chalk": 1, "challenge": 1, "chamber": 1, "champagne": 1,
  "champion": 1, "championship": 1, "chance": 1, "chandelier": 1, "changelog": 1, "channel": 1,
  "chant": 1, "chaos": 1, "chap": 1, "chapel": 1, "chaplain": 1, "characteristic": 1,
  "charcoal": 1, "charge": 1, "chariot": 1, "charitable": 1, "charity": 1, "charlatan": 1,
  "charlotte": 1, "charm": 1, "charmed": 1, "charming": 1, "chart": 1, "chase": 1, "chastity": 1,
  "chat": 1, "chauffeur": 1, "cheap": 1, "cheek": 1, "cheer": 1, "cheerful": 1, "cheerleader": 1,
  "cheese": 1, "chemical": 1, "chemist": 1, "chemistry": 1, "cherish": 1, "cherry": 1,
  "chess": 1, "chest": 1, "chestnut": 1, "chew": 1, "chi": 1, "chick": 1, "childhood": 1,
  "childish": 1, "chill": 1, "chilly": 1, "chimney": 1, "chin": 1, "chip": 1, "chlorine": 1,
  "chocolate": 1, "choir": 1, "cholera": 1, "choose": 1, "chop": 1, "chopper": 1, "chord": 1,
  "chorus": 1, "chrome": 1, "chromosome": 1, "chug": 1, "chum": 1, "chunk": 1, "cider": 1,
  "cinema": 1, "cinnamon": 1, "cipher": 1, "circle": 1, "circuit": 1, "circular": 1,
  "circulation": 1, "circumstance": 1, "circus": 1, "citadel": 1, "citizen": 1, "citizenship": 1,
  "city": 1, "civil": 1, "civilian": 1, "civilization": 1, "civilized": 1, "claim": 1,
  "clairvoyant": 1, "clam": 1, "clamp": 1, "clan": 1, "clandestine": 1, "clarinet": 1,
  "clarion": 1, "clash": 1, "clasp": 1, "class": 1, "classical": 1, "classroom": 1, "clause": 1,
  "claw": 1, "clay": 1, "clean": 1, "cleanliness": 1, "clergy": 1, "clerical": 1, "clerk": 1,
  "clever": 1, "cliff": 1, "climate": 1, "climax": 1, "climb": 1, "clink": 1, "clip": 1,
  "cloak": 1, "clock": 1, "clone": 1, "close": 1, "closely": 1, "closet": 1, "closing": 1,
  "closure": 1, "cloth": 1, "clothed": 1, "clothes": 1, "cloud": 1, "cloudy": 1, "clumsy": 1,
  "clutch": 1, "coach": 1, "coal": 1, "coarse": 1, "coast": 1, "coat": 1, "cobalt": 1,
  "cobbler": 1, "cockroach": 1, "cocoa": 1, "cocoon": 1, "cod": 1, "codec": 1, "codex": 1,
  "coffee": 1, "cogent": 1, "cognition": 1, "cognitive": 1, "coherent": 1, "cohort": 1,
  "coil": 1, "coin": 1, "coincide": 1, "coincidence": 1, "cold": 1, "collaborate": 1,
  "collage": 1, "collapse": 1, "collar": 1, "colleague": 1, "collect": 1, "collecting": 1,
  "college": 1, "collide": 1, "collier": 1, "colon": 1, "colonel": 1, "colony": 1, "color": 1,
  "colored": 1, "colossal": 1, "colt": 1, "column": 1, "comb": 1, "combat": 1, "combination": 1,
  "combined": 1, "combustion": 1, "come": 1, "comedy": 1, "comet": 1, "comfort": 1,
  "comfortable": 1, "comic": 1, "comma": 1, "commander": 1, "commandment": 1, "commencement": 1,
  "commend": 1, "comment": 1, "commerce": 1, "commodore": 1, "commonly": 1, "commonwealth": 1,
  "communal": 1, "communicate": 1, "community": 1, "companion": 1, "company": 1,
  "comparative": 1, "compare": 1, "comparison": 1, "compass": 1, "compassion": 1, "compel": 1,
  "compelling": 1, "compendium": 1, "compensate": 1, "compensation": 1, "competent": 1,
  "competition": 1, "compilation": 1, "complacent": 1, "complain": 1, "complaint": 1,
  "complete": 1, "completed": 1, "complex": 1, "complexion": 1, "compliance": 1,
  "complicated": 1, "compliment": 1, "complimentary": 1, "comply": 1, "component": 1,
  "compose": 1, "composed": 1, "composer": 1, "composite": 1, "composition": 1, "compound": 1,
  "comprehend": 1, "comprehensive": 1, "comprise": 1, "compromise": 1, "computer": 1,
  "computing": 1, "conceal": 1, "conceive": 1, "concentrated": 1, "concentration": 1,
  "conception": 1, "concern": 1, "concerned": 1, "concerto": 1, "concise": 1, "conclude": 1,
  "conclusion": 1, "concord": 1, "concrete": 1, "concussion": 1, "condemn": 1, "condemned": 1,
  "condensed": 1, "condolences": 1, "conductor": 1, "cone": 1, "confederate": 1, "confess": 1,
  "confession": 1, "confidence": 1, "confident": 1, "confidential": 1, "confined": 1,
  "confirm": 1, "confirmed": 1, "confiscate": 1, "conformity": 1, "confront": 1,
  "confrontation": 1, "confused": 1, "confusion": 1, "congratulate": 1, "congress": 1,
  "conjecture": 1, "conjunction": 1, "connection": 1, "conquer": 1, "conquest": 1,
  "conscience": 1, "conscientious": 1, "conscious": 1, "consciously": 1, "consciousness": 1,
  "consent": 1, "consequence": 1, "consequently": 1, "consider": 1, "considerable": 1,
  "considerably": 1, "consideration": 1, "consistency": 1, "consistent": 1, "consolation": 1,
  "consolidate": 1, "conspicuous": 1, "conspiracy": 1, "constant": 1, "constantly": 1,
  "constituent": 1, "constitute": 1, "constitution": 1, "constitutional": 1, "construction": 1,
  "consulate": 1, "consume": 1, "consumption": 1, "contact": 1, "contaminant": 1,
  "contemplate": 1, "contempt": 1, "contender": 1, "content": 1, "contents": 1, "contest": 1,
  "contestant": 1, "contiguous": 1, "continent": 1, "continual": 1, "continually": 1,
  "continue": 1, "continuity": 1, "continuous": 1, "contour": 1, "contradictory": 1,
  "contraption": 1, "contrast": 1, "contribute": 1, "contribution": 1, "control": 1,
  "controversy": 1, "convenience": 1, "convenient": 1, "convent": 1, "convention": 1,
  "conventional": 1, "conversation": 1, "converse": 1, "conversion": 1, "convey": 1,
  "conviction": 1, "convince": 1, "convinced": 1, "convoy": 1, "cook": 1, "cookbook": 1,
  "cooked": 1, "cooler": 1, "cooperate": 1, "coordinate": 1, "copper": 1, "copying": 1,
  "copyright": 1, "coral": 1, "cord": 1, "cordial": 1, "core": 1, "cork": 1, "corn": 1,
  "corporal": 1, "corporate": 1, "corporation": 1, "corps": 1, "correction": 1, "correctly": 1,
  "correlate": 1, "correspond": 1, "correspondence": 1, "correspondent": 1, "corresponding": 1,
  "corridor": 1, "corroborate": 1, "corruption": 1, "corsair": 1, "cosmetic": 1, "cosmology": 1,
  "cosmopolitan": 1, "cost": 1, "costly": 1, "costume": 1, "cot": 1, "cottage": 1, "cotton": 1,
  "couch": 1, "cough": 1, "counsel": 1, "counselor": 1, "countenance": 1, "counterpart": 1,
  "countess": 1, "countless": 1, "country": 1, "countryside": 1, "coupon": 1, "courage": 1,
  "court": 1, "courteous": 1, "courtesy": 1, "courtyard": 1, "cousin": 1, "covenant": 1,
  "cow": 1, "coy": 1, "coyote": 1, "crab": 1, "crack": 1, "crackpot": 1, "craft": 1,
  "craftsman": 1, "crafty": 1, "crane": 1, "crank": 1, "cranky": 1, "crate": 1, "crave": 1,
  "craving": 1, "crawl": 1, "craze": 1, "crazy": 1, "create": 1, "creation": 1, "creativity": 1,
  "creator": 1, "creature": 1, "credit": 1, "creed": 1, "creek": 1, "creep": 1, "creole": 1,
  "crib": 1, "cricket": 1, "crippled": 1, "crisis": 1, "crisp": 1, "criterion": 1, "critic": 1,
  "critical": 1, "critically": 1, "criticism": 1, "critique": 1, "croissant": 1, "crooked": 1,
  "crop": 1, "crossing": 1, "crossword": 1, "crotch": 1, "crow": 1, "crowd": 1, "crowded": 1,
  "crude": 1, "cruel": 1, "cruelty": 1, "crumb": 1, "crumble": 1, "crunch": 1, "crusade": 1,
  "crush": 1, "crushing": 1, "cry": 1, "crying": 1, "cub": 1, "cube": 1, "cubic": 1, "cuckoo": 1,
  "cucumber": 1, "culprit": 1, "cultivate": 1, "cultural": 1, "culture": 1, "cunning": 1,
  "cup": 1, "cupboard": 1, "cure": 1, "curiosity": 1, "curious": 1, "curl": 1, "curling": 1,
  "currency": 1, "current": 1, "curriculum": 1, "curse": 1, "cursed": 1, "curtain": 1,
  "curtains": 1, "curve": 1, "cushion": 1, "custard": 1, "custom": 1, "customary": 1,
  "customs": 1, "cut": 1, "cute": 1, "cutting": 1, "cyborg": 1, "cycle": 1, "cycling": 1,
  "cyclone": 1, "cylinder": 1, "cynical": 1, "cypress": 1, "dad": 1, "daddy": 1, "daily": 1,
  "dairy": 1, "daisy": 1, "dam": 1, "damage": 1, "damp": 1, "dance": 1, "dancer": 1, "danger": 1,
  "dangerous": 1, "dare": 1, "dark": 1, "darkness": 1, "darling": 1, "darn": 1, "dart": 1,
  "dash": 1, "date": 1, "dated": 1, "daughter": 1, "dawn": 1, "daylight": 1, "dazzling": 1,
  "deadly": 1, "deal": 1, "dealer": 1, "dean": 1, "dearth": 1, "debate": 1, "debit": 1,
  "debris": 1, "debt": 1, "debug": 1, "debugger": 1, "debut": 1, "decade": 1, "deceased": 1,
  "deceit": 1, "deceive": 1, "decent": 1, "deception": 1, "deceptive": 1, "decide": 1,
  "decimal": 1, "deck": 1, "declaration": 1, "declare": 1, "decline": 1, "decor": 1,
  "decorate": 1, "decoration": 1, "decoy": 1, "decrease": 1, "dedicated": 1, "deduction": 1,
  "deed": 1, "deep": 1, "deeply": 1, "deer": 1, "defeat": 1, "defect": 1, "defective": 1,
  "defend": 1, "defendant": 1, "defender": 1, "defiance": 1, "defiant": 1, "define": 1,
  "definite": 1, "definitely": 1, "definition": 1, "defy": 1, "degree": 1, "delay": 1,
  "delete": 1, "deli": 1, "deliberately": 1, "delicate": 1, "delicious": 1, "delight": 1,
  "delighted": 1, "delightful": 1, "delinquent": 1, "deliver": 1, "delta": 1, "deluxe": 1,
  "democratic": 1, "demonstrate": 1, "demonstration": 1, "den": 1, "denial": 1, "denote": 1,
  "dense": 1, "dentist": 1, "deny": 1, "deodorant": 1, "depart": 1, "departure": 1, "depend": 1,
  "dependent": 1, "depict": 1, "deposit": 1, "depot": 1, "depression": 1, "depth": 1,
  "deputy": 1, "derby": 1, "derivation": 1, "derivative": 1, "derive": 1, "descend": 1,
  "descendant": 1, "descent": 1, "describe": 1, "deserted": 1, "deserve": 1, "desirable": 1,
  "desire": 1, "desk": 1, "desolate": 1, "despair": 1, "desperate": 1, "desperately": 1,
  "despise": 1, "dessert": 1, "destination": 1, "destroy": 1, "destruction": 1, "detachment": 1,
  "detail": 1, "detailed": 1, "detain": 1, "deter": 1, "determination": 1, "determine": 1,
  "determined": 1, "detest": 1, "deuce": 1, "devastation": 1, "develop": 1, "developed": 1,
  "device": 1, "devise": 1, "devoid": 1, "devote": 1, "devoted": 1, "devotion": 1, "devour": 1,
  "dew": 1, "dialect": 1, "dialogue": 1, "diameter": 1, "diamond": 1, "diamonds": 1, "diaper": 1,
  "diarrhea": 1, "diary": 1, "diaspora": 1, "dice": 1, "dictionary": 1, "dielectric": 1,
  "diet": 1, "differ": 1, "different": 1, "differential": 1, "differentiate": 1,
  "differently": 1, "difficult": 1, "difficulty": 1, "dig": 1, "digestion": 1, "digit": 1,
  "digital": 1, "dignity": 1, "dilemma": 1, "diligent": 1, "dim": 1, "dimension": 1,
  "diminish": 1, "din": 1, "dinner": 1, "diode": 1, "diploma": 1, "diplomacy": 1,
  "diplomatic": 1, "dire": 1, "direct": 1, "direction": 1, "director": 1, "dirt": 1, "dirty": 1,
  "disable": 1, "disagreement": 1, "disappear": 1, "disappointed": 1, "disappointment": 1,
  "disaster": 1, "discern": 1, "discharge": 1, "disciple": 1, "disciplinary": 1, "discipline": 1,
  "disclose": 1, "discography": 1, "discount": 1, "discourage": 1, "discourse": 1, "discover": 1,
  "discovery": 1, "discredit": 1, "discreet": 1, "discrepancy": 1, "discrete": 1,
  "discretion": 1, "discuss": 1, "discussion": 1, "diseased": 1, "disgrace": 1, "disgraceful": 1,
  "disguise": 1, "disgust": 1, "disgusting": 1, "dish": 1, "dishes": 1, "dishonest": 1,
  "disintegrate": 1, "disk": 1, "dislike": 1, "dismal": 1, "dismiss": 1, "disorder": 1,
  "dispatch": 1, "dispense": 1, "dispose": 1, "disposition": 1, "dispute": 1, "disputed": 1,
  "disrespectful": 1, "dissatisfied": 1, "disseminate": 1, "dissolution": 1, "distant": 1,
  "distinct": 1, "distinction": 1, "distinctive": 1, "distinctly": 1, "distinguish": 1,
  "distinguished": 1, "distraction": 1, "distress": 1, "distribute": 1, "distribution": 1,
  "district": 1, "distrust": 1, "disturb": 1, "disturbance": 1, "ditch": 1, "ditto": 1,
  "dive": 1, "diverse": 1, "diversion": 1, "diversity": 1, "divert": 1, "divide": 1,
  "dividend": 1, "divine": 1, "divinity": 1, "dizzy": 1, "docile": 1, "dock": 1, "doctor": 1,
  "doctoral": 1, "doctorate": 1, "doctrine": 1, "dodge": 1, "dog": 1, "doll": 1, "dollar": 1,
  "dolphin": 1, "domain": 1, "domestic": 1, "domination": 1, "dominion": 1, "donate": 1,
  "donation": 1, "donkey": 1, "donor": 1, "doodle": 1, "doofus": 1, "doom": 1, "doomed": 1,
  "doomsday": 1, "door": 1, "doorway": 1, "dose": 1, "dot": 1, "dotted": 1, "doubt": 1,
  "doubtful": 1, "doubtless": 1, "dough": 1, "dowager": 1, "download": 1, "downstairs": 1,
  "doze": 1, "dozen": 1, "drag": 1, "dragon": 1, "dragonfly": 1, "drain": 1, "drake": 1,
  "drama": 1, "dramatic": 1, "drastic": 1, "draw": 1, "drawer": 1, "drawing": 1, "dread": 1,
  "dreadful": 1, "dreary": 1, "dress": 1, "dressed": 1, "dried": 1, "drift": 1, "drill": 1,
  "drink": 1, "drive": 1, "dropping": 1, "drove": 1, "druid": 1, "drum": 1, "dual": 1,
  "dubious": 1, "duck": 1, "duct": 1, "duel": 1, "duke": 1, "dull": 1, "duly": 1, "dumpling": 1,
  "dune": 1, "dung": 1, "duration": 1, "dusk": 1, "dust": 1, "dusty": 1, "dwarf": 1, "dwell": 1,
  "dwelling": 1, "dynamic": 1, "dynasty": 1, "eager": 1, "eagle": 1, "ear": 1, "early": 1,
  "earn": 1, "earnest": 1, "earth": 1, "earthly": 1, "ease": 1, "easily": 1, "eastern": 1,
  "eat": 1, "eavesdrop": 1, "eccentric": 1, "echo": 1, "eclectic": 1, "eclipse": 1,
  "economic": 1, "economical": 1, "economics": 1, "economy": 1, "ecstatic": 1, "editing": 1,
  "editor": 1, "editorial": 1, "educate": 1, "education": 1, "educational": 1, "eel": 1,
  "eerie": 1, "effective": 1, "effectiveness": 1, "efficiency": 1, "efficient": 1, "egg": 1,
  "egghead": 1, "eggnog": 1, "eggplant": 1, "eighth": 1, "eject": 1, "elaborate": 1,
  "elastic": 1, "elbow": 1, "elder": 1, "elderly": 1, "elect": 1, "election": 1,
  "electricity": 1, "electron": 1, "electronic": 1, "element": 1, "elephant": 1, "elevated": 1,
  "eleventh": 1, "elf": 1, "else": 1, "email": 1, "embarrass": 1, "embarrassing": 1,
  "embassy": 1, "embed": 1, "emblem": 1, "embrace": 1, "embroidered": 1, "eminent": 1,
  "emission": 1, "emit": 1, "emperor": 1, "emphasis": 1, "empire": 1, "empirical": 1,
  "employ": 1, "employee": 1, "employment": 1, "empower": 1, "empress": 1, "enable": 1,
  "enchanted": 1, "enchantment": 1, "encompass": 1, "encore": 1, "encounter": 1, "encourage": 1,
  "encyclopedia": 1, "endeavor": 1, "endless": 1, "endurance": 1, "endure": 1, "energetic": 1,
  "energy": 1, "engaged": 1, "engagement": 1, "engineer": 1, "enhance": 1, "enigma": 1,
  "enjoy": 1, "enjoyment": 1, "enlarge": 1, "enlightened": 1, "enormous": 1, "enroll": 1,
  "ensemble": 1, "ensign": 1, "entail": 1, "enterprise": 1, "entertain": 1, "entertaining": 1,
  "enthusiasm": 1, "enthusiastic": 1, "entire": 1, "entirely": 1, "entity": 1, "entrance": 1,
  "entrepreneur": 1, "entropy": 1, "entry": 1, "envelope": 1, "envious": 1, "environment": 1,
  "envy": 1, "ephedrine": 1, "ephemeral": 1, "epiphany": 1, "episode": 1, "epsilon": 1,
  "equal": 1, "equally": 1, "equation": 1, "equator": 1, "equatorial": 1, "equinox": 1,
  "equipment": 1, "equivalent": 1, "equivocate": 1, "era": 1, "eradicate": 1, "erase": 1,
  "erect": 1, "errand": 1, "escort": 1, "esoteric": 1, "especially": 1, "espresso": 1,
  "essay": 1, "essence": 1, "essential": 1, "establish": 1, "establishment": 1, "esteem": 1,
  "eta": 1, "eternal": 1, "eternity": 1, "ethanol": 1, "ether": 1, "ethereal": 1, "ethical": 1,
  "ethnic": 1, "ethnicity": 1, "euphemism": 1, "euro": 1, "euthanasia": 1, "evaluate": 1,
  "eve": 1, "eventually": 1, "ever": 1, "everlasting": 1, "everyone": 1, "everywhere": 1,
  "evidence": 1, "evident": 1, "evidently": 1, "evil": 1, "evolution": 1, "evolutionary": 1,
  "ex": 1, "exacerbate": 1, "exact": 1, "exactly": 1, "exaggerate": 1, "exaggerated": 1,
  "examination": 1, "examine": 1, "excellent": 1, "exception": 1, "exceptional": 1, "excerpt": 1,
  "excess": 1, "excite": 1, "excited": 1, "excitement": 1, "exciting": 1, "exclude": 1,
  "excursion": 1, "execution": 1, "exempt": 1, "exercise": 1, "exhaust": 1, "exhausted": 1,
  "exhausting": 1, "exhibit": 1, "exhibition": 1, "exist": 1, "existence": 1, "existing": 1,
  "exit": 1, "expansion": 1, "expect": 1, "expectation": 1, "expedite": 1, "expedition": 1,
  "expenditure": 1, "expense": 1, "expensive": 1, "experience": 1, "experienced": 1,
  "experiment": 1, "expert": 1, "expertise": 1, "explain": 1, "explanation": 1, "explanatory": 1,
  "explicit": 1, "exploit": 1, "exploration": 1, "explore": 1, "explorer": 1, "exponential": 1,
  "expose": 1, "exposure": 1, "expression": 1, "expressive": 1, "expressly": 1, "exquisite": 1,
  "extended": 1, "extension": 1, "extensive": 1, "extensively": 1, "extent": 1, "exterminate": 1,
  "external": 1, "extra": 1, "extract": 1, "extraordinary": 1, "extreme": 1, "extremely": 1,
  "eye": 1, "eyeball": 1, "eyebrow": 1, "fable": 1, "fabric": 1, "facade": 1, "face": 1,
  "facilitate": 1, "facility": 1, "facsimile": 1, "fact": 1, "factor": 1, "factory": 1,
  "factual": 1, "faculty": 1, "fail": 1, "faint": 1, "fairly": 1, "fairy": 1, "faithful": 1,
  "fake": 1, "falcon": 1, "fallen": 1, "false": 1, "fame": 1, "familiar": 1, "family": 1,
  "famished": 1, "famous": 1, "fanatic": 1, "fancy": 1, "fanfare": 1, "fantastic": 1,
  "fantasy": 1, "farce": 1, "fare": 1, "farewell": 1, "farm": 1, "farmer": 1, "fascinating": 1,
  "fashion": 1, "fashionable": 1, "fasten": 1, "fastidious": 1, "fat": 1, "fatal": 1, "fate": 1,
  "father": 1, "fathom": 1, "fatigue": 1, "faucet": 1, "faulty": 1, "favor": 1, "favourable": 1,
  "favourite": 1, "fax": 1, "fear": 1, "fearful": 1, "feasible": 1, "feast": 1, "feather": 1,
  "feature": 1, "federation": 1, "fedora": 1, "fee": 1, "feeble": 1, "female": 1, "feminine": 1,
  "fence": 1, "fender": 1, "fern": 1, "ferret": 1, "ferry": 1, "fertile": 1, "fester": 1,
  "festival": 1, "festive": 1, "fetch": 1, "fetching": 1, "fever": 1, "fiasco": 1, "fiction": 1,
  "fiddle": 1, "field": 1, "fiend": 1, "fierce": 1, "fiercely": 1, "fifth": 1, "fifty": 1,
  "fig": 1, "fight": 1, "figment": 1, "fill": 1, "filled": 1, "filling": 1, "filter": 1,
  "filthy": 1, "fin": 1, "finalize": 1, "financial": 1, "fine": 1, "finely": 1, "finger": 1,
  "fingernail": 1, "fingerprint": 1, "finite": 1, "fir": 1, "firearm": 1, "fireman": 1,
  "fireplace": 1, "firewall": 1, "firmly": 1, "fish": 1, "fisher": 1, "fishing": 1, "fishy": 1,
  "fist": 1, "fitness": 1, "fitting": 1, "five": 1, "fixture": 1, "flag": 1, "flagship": 1,
  "flair": 1, "flake": 1, "flame": 1, "flank": 1, "flap": 1, "flashy": 1, "flask": 1, "flat": 1,
  "flatter": 1, "flattered": 1, "flaunt": 1, "flaw": 1, "flea": 1, "flee": 1, "fleece": 1,
  "fleet": 1, "fleeting": 1, "flesh": 1, "flex": 1, "flexibility": 1, "flexible": 1, "flick": 1,
  "flight": 1, "fling": 1, "flint": 1, "flip": 1, "flirt": 1, "float": 1, "flock": 1, "flood": 1,
  "floor": 1, "floppy": 1, "flora": 1, "floss": 1, "flour": 1, "flourish": 1, "flow": 1,
  "flower": 1, "flowing": 1, "flu": 1, "fluent": 1, "fluid": 1, "fluke": 1, "flute": 1,
  "flux": 1, "fly": 1, "foam": 1, "fodder": 1, "fog": 1, "foil": 1, "fold": 1, "folder": 1,
  "folding": 1, "folk": 1, "folly": 1, "fond": 1, "food": 1, "foolish": 1, "foot": 1,
  "footage": 1, "footing": 1, "forbid": 1, "forbidden": 1, "ford": 1, "fore": 1, "forecast": 1,
  "forefront": 1, "forehead": 1, "foreign": 1, "foreigner": 1, "foreman": 1, "foremost": 1,
  "forensic": 1, "foresee": 1, "forest": 1, "forever": 1, "foreword": 1, "forfeit": 1,
  "forgery": 1, "forget": 1, "forgive": 1, "forgiveness": 1, "forgotten": 1, "fork": 1,
  "form": 1, "formal": 1, "format": 1, "formerly": 1, "formidable": 1, "formula": 1,
  "forsaken": 1, "fort": 1, "forth": 1, "forthcoming": 1, "fortnight": 1, "fortress": 1,
  "fortunate": 1, "fortunately": 1, "fortune": 1, "fossil": 1, "foster": 1, "foul": 1,
  "foundation": 1, "founder": 1, "fountain": 1, "fourth": 1, "fox": 1, "foyer": 1, "fracture": 1,
  "fragile": 1, "fragrance": 1, "fragrant": 1, "framework": 1, "frank": 1, "frankly": 1,
  "frantic": 1, "freely": 1, "freeze": 1, "freight": 1, "frenzy": 1, "frequently": 1, "fresh": 1,
  "fret": 1, "friction": 1, "fried": 1, "friend": 1, "friendship": 1, "fright": 1, "frighten": 1,
  "frightened": 1, "frightening": 1, "fringe": 1, "frisky": 1, "frivolous": 1, "frog": 1,
  "frontier": 1, "frost": 1, "frown": 1, "frozen": 1, "fruit": 1, "fruitcake": 1, "fry": 1,
  "fudge": 1, "fuel": 1, "full": 1, "fully": 1, "function": 1, "functional": 1,
  "functionality": 1, "fundamental": 1, "fundamentalist": 1, "fundraiser": 1, "fundraising": 1,
  "fungus": 1, "funnel": 1, "funny": 1, "fur": 1, "furious": 1, "furlough": 1, "furnace": 1,
  "furnish": 1, "furnished": 1, "furniture": 1, "furthermore": 1, "fury": 1, "fuss": 1,
  "future": 1, "fuzz": 1, "fuzzy": 1, "gadget": 1, "gain": 1, "gala": 1, "galactic": 1,
  "galaxy": 1, "gale": 1, "gallant": 1, "galley": 1, "gallon": 1, "gallows": 1, "galore": 1,
  "game": 1, "gamma": 1, "gangrene": 1, "gap": 1, "garage": 1, "garbage": 1, "garden": 1,
  "gardener": 1, "garlic": 1, "garner": 1, "garrison": 1, "garrulous": 1, "gasket": 1,
  "gasoline": 1, "gate": 1, "gather": 1, "gathering": 1, "gauge": 1, "gavel": 1, "gaze": 1,
  "geek": 1, "gel": 1, "gelatin": 1, "gem": 1, "gemstone": 1, "gene": 1, "generally": 1,
  "generate": 1, "generic": 1, "generous": 1, "generously": 1, "genet": 1, "genie": 1,
  "genius": 1, "genre": 1, "gentle": 1, "gentleman": 1, "gently": 1, "genuine": 1, "genus": 1,
  "geography": 1, "geology": 1, "geometry": 1, "germ": 1, "gesture": 1, "ghastly": 1, "ghost": 1,
  "ghostly": 1, "giant": 1, "giddy": 1, "giggle": 1, "gill": 1, "gin": 1, "gingerbread": 1,
  "giraffe": 1, "girl": 1, "girlfriend": 1, "give": 1, "gizmo": 1, "glacier": 1, "glad": 1,
  "gladly": 1, "glance": 1, "glass": 1, "glaze": 1, "glimpse": 1, "glitter": 1, "glittering": 1,
  "gloom": 1, "gloomy": 1, "glorious": 1, "glory": 1, "gloss": 1, "glossary": 1, "glossy": 1,
  "glove": 1, "glow": 1, "glue": 1, "gluten": 1, "gnu": 1, "goal": 1, "goat": 1, "goblet": 1,
  "goblin": 1, "goddess": 1, "godfather": 1, "goggles": 1, "golden": 1, "goldfish": 1, "golf": 1,
  "goo": 1, "good": 1, "goodbye": 1, "goodness": 1, "goose": 1, "gorge": 1, "gorgeous": 1,
  "gorilla": 1, "gospel": 1, "gossip": 1, "goth": 1, "gouge": 1, "govern": 1, "governess": 1,
  "government": 1, "governor": 1, "gown": 1, "grab": 1, "graceful": 1, "gradient": 1,
  "gradual": 1, "gradually": 1, "grain": 1, "gram": 1, "grammar": 1, "grandfather": 1,
  "grandmother": 1, "grandson": 1, "granite": 1, "grant": 1, "granted": 1, "grape": 1,
  "grapefruit": 1, "graph": 1, "graphite": 1, "grasp": 1, "grass": 1, "grasshopper": 1,
  "grateful": 1, "gratitude": 1, "graveyard": 1, "gravity": 1, "gravy": 1, "gray": 1,
  "grease": 1, "greatly": 1, "greatness": 1, "greed": 1, "green": 1, "greens": 1, "greet": 1,
  "gregarious": 1, "grief": 1, "grieve": 1, "grill": 1, "grim": 1, "grin": 1, "grind": 1,
  "grip": 1, "groan": 1, "groceries": 1, "groin": 1, "groom": 1, "gross": 1, "grotesque": 1,
  "ground": 1, "grounds": 1, "group": 1, "grove": 1, "grovel": 1, "grow": 1, "growl": 1,
  "growth": 1, "grub": 1, "grudge": 1, "grumpy": 1, "grunt": 1, "guard": 1, "guardian": 1,
  "guess": 1, "guest": 1, "guide": 1, "guilty": 1, "guitar": 1, "gulf": 1, "gull": 1, "gum": 1,
  "guru": 1, "gymnasium": 1, "gymnastics": 1, "gypsy": 1, "habit": 1, "hail": 1, "hair": 1,
  "haircut": 1, "hairy": 1, "halcyon": 1, "halfway": 1, "hallelujah": 1, "hallucination": 1,
  "ham": 1, "hammer": 1, "hamster": 1, "hand": 1, "handbag": 1, "handcuff": 1, "handful": 1,
  "handiwork": 1, "handkerchief": 1, "handle": 1, "handling": 1, "handshake": 1, "handsome": 1,
  "handy": 1, "handyman": 1, "hangar": 1, "hanging": 1, "happen": 1, "happily": 1,
  "happiness": 1, "happy": 1, "harbor": 1, "hardly": 1, "hardware": 1, "hardy": 1, "hare": 1,
  "harem": 1, "harmful": 1, "harmless": 1, "harmony": 1, "harrow": 1, "hart": 1, "harvest": 1,
  "haste": 1, "hasty": 1, "hat": 1, "haunted": 1, "havoc": 1, "hawk": 1, "hay": 1, "haywire": 1,
  "hazard": 1, "hazel": 1, "head": 1, "headache": 1, "header": 1, "heading": 1, "headset": 1,
  "headstrong": 1, "heal": 1, "healing": 1, "health": 1, "healthy": 1, "heap": 1, "hear": 1,
  "hearsay": 1, "heart": 1, "heartfelt": 1, "hearth": 1, "heartless": 1, "hearts": 1,
  "hearty": 1, "heater": 1, "heathen": 1, "heating": 1, "heave": 1, "heavenly": 1, "heavens": 1,
  "heavily": 1, "heavy": 1, "hedge": 1, "heed": 1, "heel": 1, "hefty": 1, "height": 1,
  "heinous": 1, "heir": 1, "helium": 1, "helix": 1, "helm": 1, "helpful": 1, "helpless": 1,
  "hem": 1, "hemisphere": 1, "hen": 1, "hence": 1, "henceforth": 1, "hepatitis": 1, "herald": 1,
  "herb": 1, "herbicide": 1, "herd": 1, "hereby": 1, "hereditary": 1, "heresy": 1, "heritage": 1,
  "hermit": 1, "hero": 1, "heroic": 1, "heroine": 1, "heroism": 1, "heron": 1, "herring": 1,
  "hertz": 1, "hesitation": 1, "heterogeneous": 1, "heuristic": 1, "hickory": 1, "hide": 1,
  "hideous": 1, "hierarchical": 1, "hierarchy": 1, "high": 1, "highlight": 1, "highway": 1,
  "hijack": 1, "hike": 1, "hill": 1, "hind": 1, "hinder": 1, "hinge": 1, "hint": 1, "hip": 1,
  "historic": 1, "historical": 1, "history": 1, "hit": 1, "hitch": 1, "hitchhike": 1,
  "hither": 1, "hoax": 1, "hockey": 1, "hog": 1, "hoist": 1, "holder": 1, "holiday": 1,
  "holiness": 1, "holler": 1, "hollow": 1, "holly": 1, "homage": 1, "homeopathy": 1,
  "homogeneous": 1, "honest": 1, "honesty": 1, "honeymoon": 1, "honorable": 1, "honoured": 1,
  "hood": 1, "hoof": 1, "hook": 1, "hooked": 1, "hooligan": 1, "hop": 1, "hopeless": 1,
  "horde": 1, "horizon": 1, "horizontal": 1, "hormone": 1, "horn": 1, "horrible": 1, "horrid": 1,
  "horror": 1, "horse": 1, "horseback": 1, "horsepower": 1, "horseshoe": 1, "hospital": 1,
  "hospitality": 1, "hostel": 1, "hostess": 1, "hostile": 1, "hostility": 1, "hot": 1,
  "hotel": 1, "hothead": 1, "hotline": 1, "hound": 1, "hour": 1, "house": 1, "household": 1,
  "housekeeper": 1, "housewife": 1, "hover": 1, "however": 1, "howl": 1, "hub": 1, "hue": 1,
  "huff": 1, "hug": 1, "huge": 1, "huh": 1, "hulk": 1, "hum": 1, "humanities": 1, "humanity": 1,
  "humble": 1, "humbly": 1, "humid": 1, "hummingbird": 1, "humorous": 1, "humour": 1, "hump": 1,
  "hunch": 1, "hunger": 1, "hungry": 1, "hunt": 1, "hunter": 1, "hunting": 1, "hurdle": 1,
  "hurry": 1, "husband": 1, "hustle": 1, "hut": 1, "hybrid": 1, "hydraulic": 1, "hydrogen": 1,
  "hygiene": 1, "hymn": 1, "hypertext": 1, "hypothesis": 1, "hypothetical": 1, "hysteria": 1,
  "ice": 1, "icon": 1, "icy": 1, "idea": 1, "ideal": 1, "identification": 1, "identify": 1,
  "ideology": 1, "idle": 1, "idol": 1, "ignorance": 1, "ignorant": 1, "ignore": 1, "ill": 1,
  "illiterate": 1, "illuminate": 1, "illusion": 1, "illustrate": 1, "image": 1, "imaginary": 1,
  "imagination": 1, "imagine": 1, "imitate": 1, "immediate": 1, "immediately": 1, "immense": 1,
  "immensely": 1, "imminent": 1, "immortal": 1, "imp": 1, "impatient": 1, "impeccable": 1,
  "impecunious": 1, "imperfect": 1, "imperial": 1, "imperialism": 1, "impertinent": 1,
  "impetuous": 1, "implement": 1, "implementation": 1, "implicit": 1, "implied": 1, "imply": 1,
  "impolite": 1, "import": 1, "importance": 1, "important": 1, "impose": 1, "imposing": 1,
  "impossible": 1, "impressed": 1, "impression": 1, "impressive": 1, "imprisonment": 1,
  "improve": 1, "improved": 1, "improvement": 1, "impudent": 1, "impulse": 1, "inability": 1,
  "inadvertently": 1, "inception": 1, "inch": 1, "incident": 1, "inclination": 1, "inclined": 1,
  "include": 1, "income": 1, "incompatible": 1, "incomplete": 1, "incongruous": 1,
  "incredibly": 1, "incubus": 1, "incur": 1, "indemnify": 1, "independently": 1, "indicate": 1,
  "indict": 1, "indictment": 1, "indifference": 1, "indifferent": 1, "indirectly": 1,
  "individual": 1, "induce": 1, "indulge": 1, "indulgence": 1, "industrial": 1, "ineffable": 1,
  "inevitable": 1, "inevitably": 1, "inexpensive": 1, "infamous": 1, "infant": 1, "infected": 1,
  "infer": 1, "inferior": 1, "infiltrate": 1, "infinite": 1, "infinitely": 1, "inflammation": 1,
  "inflict": 1, "influence": 1, "influenza": 1, "inform": 1, "informal": 1, "informatics": 1,
  "information": 1, "informative": 1, "infringement": 1, "ingenious": 1, "ingenuity": 1,
  "inhale": 1, "inherit": 1, "inheritance": 1, "initial": 1, "initiative": 1, "injury": 1,
  "ink": 1, "inlet": 1, "inn": 1, "innate": 1, "inner": 1, "innocent": 1, "innovative": 1,
  "inquire": 1, "inquiry": 1, "insanity": 1, "inscription": 1, "insect": 1, "insight": 1,
  "insignia": 1, "insignificant": 1, "insist": 1, "insomnia": 1, "inspect": 1, "inspection": 1,
  "inspector": 1, "inspiration": 1, "instance": 1, "instant": 1, "instantly": 1, "instead": 1,
  "instinct": 1, "institution": 1, "instruct": 1, "instruction": 1, "instrument": 1,
  "instrumental": 1, "insufferable": 1, "insulation": 1, "insult": 1, "insulting": 1,
  "insure": 1, "intact": 1, "integer": 1, "integrity": 1, "intellect": 1, "intellectual": 1,
  "intelligent": 1, "intend": 1, "intense": 1, "intention": 1, "intentionally": 1,
  "interaction": 1, "interfere": 1, "interim": 1, "interior": 1, "intermittent": 1,
  "internal": 1, "international": 1, "internship": 1, "interpret": 1, "interrogate": 1,
  "interrogation": 1, "interrupt": 1, "interruption": 1, "interval": 1, "interview": 1,
  "intestine": 1, "intoxicated": 1, "intracellular": 1, "intricate": 1, "introduce": 1,
  "introduction": 1, "intrusion": 1, "intrusive": 1, "intuition": 1, "intuitive": 1,
  "invariably": 1, "invent": 1, "invented": 1, "invention": 1, "invest": 1, "investigate": 1,
  "investigation": 1, "investment": 1, "invincible": 1, "invisible": 1, "invitation": 1,
  "invite": 1, "invoice": 1, "involved": 1, "inward": 1, "iodine": 1, "ion": 1, "iris": 1,
  "ironic": 1, "irony": 1, "irrelevant": 1, "island": 1, "isolate": 1, "isolated": 1, "itch": 1,
  "item": 1, "iterative": 1, "itinerary": 1, "ivory": 1, "ivy": 1, "jackal": 1, "jackass": 1,
  "jacket": 1, "jaguar": 1, "jam": 1, "jar": 1, "jargon": 1, "jasper": 1, "jaw": 1, "jealous": 1,
  "jealousy": 1, "jeep": 1, "jelly": 1, "jellyfish": 1, "jest": 1, "jewel": 1, "jingle": 1,
  "joey": 1, "jog": 1, "join": 1, "joke": 1, "jolt": 1, "journalist": 1, "journey": 1, "joy": 1,
  "joyful": 1, "joyous": 1, "judge": 1, "judgment": 1, "judicial": 1, "jugular": 1, "juice": 1,
  "juicy": 1, "jumbo": 1, "jump": 1, "junction": 1, "jungle": 1, "juror": 1, "jury": 1,
  "justified": 1, "justify": 1, "juxtapose": 1, "juxtaposition": 1, "kangaroo": 1, "kappa": 1,
  "kay": 1, "kayak": 1, "keel": 1, "keen": 1, "keep": 1, "keeper": 1, "keepsake": 1, "ken": 1,
  "ketchup": 1, "kettle": 1, "key": 1, "keyboard": 1, "keygen": 1, "khan": 1, "kicker": 1,
  "kimono": 1, "kin": 1, "kindly": 1, "kindness": 1, "king": 1, "kiosk": 1, "kiss": 1,
  "kitchen": 1, "kite": 1, "kitten": 1, "klutz": 1, "knack": 1, "knave": 1, "knee": 1,
  "kneel": 1, "knife": 1, "knight": 1, "knit": 1, "knitted": 1, "knob": 1, "knock": 1, "knot": 1,
  "knowledge": 1, "knuckle": 1, "kudos": 1, "label": 1, "laboratory": 1, "labour": 1,
  "labyrinth": 1, "lace": 1, "lack": 1, "laconic": 1, "lacrosse": 1, "lacy": 1, "lad": 1,
  "ladder": 1, "lady": 1, "lagoon": 1, "laid": 1, "lake": 1, "lamb": 1, "lambda": 1, "lament": 1,
  "lamp": 1, "lance": 1, "landing": 1, "landslide": 1, "lane": 1, "language": 1, "lantern": 1,
  "lap": 1, "laptop": 1, "large": 1, "largely": 1, "lark": 1, "lash": 1, "last": 1, "latch": 1,
  "late": 1, "latent": 1, "later": 1, "latitude": 1, "latter": 1, "lattice": 1, "laughter": 1,
  "launch": 1, "launder": 1, "laundry": 1, "laurel": 1, "lava": 1, "lavish": 1, "law": 1,
  "lawn": 1, "lax": 1, "layer": 1, "lazy": 1, "leach": 1, "leaf": 1, "leaflet": 1, "leak": 1,
  "lean": 1, "leap": 1, "learn": 1, "lease": 1, "leash": 1, "leather": 1, "lecture": 1,
  "leech": 1, "leg": 1, "legacy": 1, "legally": 1, "legend": 1, "legendary": 1, "legislation": 1,
  "legislative": 1, "legislature": 1, "leisure": 1, "lemon": 1, "lend": 1, "lens": 1,
  "leopard": 1, "less": 1, "lessen": 1, "lesser": 1, "lesson": 1, "lettuce": 1, "lever": 1,
  "leverage": 1, "liability": 1, "liable": 1, "liaison": 1, "libel": 1, "liberal": 1,
  "liberty": 1, "license": 1, "lick": 1, "lid": 1, "lieutenant": 1, "life": 1, "lifetime": 1,
  "lift": 1, "lighter": 1, "lighthouse": 1, "lighting": 1, "lightly": 1, "lightning": 1,
  "lightspeed": 1, "likewise": 1, "lilac": 1, "lily": 1, "limb": 1, "limerick": 1, "limit": 1,
  "limitation": 1, "limited": 1, "limp": 1, "linden": 1, "lineage": 1, "linen": 1,
  "lingering": 1, "lingo": 1, "linguistic": 1, "linguistics": 1, "lion": 1, "lip": 1, "lipid": 1,
  "lipstick": 1, "liquid": 1, "listener": 1, "lit": 1, "literacy": 1, "literally": 1,
  "literary": 1, "literature": 1, "lithium": 1, "litre": 1, "litter": 1, "lively": 1, "liver": 1,
  "lizard": 1, "loathe": 1, "lobster": 1, "local": 1, "locality": 1, "locate": 1, "lockdown": 1,
  "locked": 1, "locket": 1, "locomotive": 1, "lodge": 1, "lofty": 1, "log": 1, "logic": 1,
  "logical": 1, "logically": 1, "login": 1, "lolita": 1, "lollipop": 1, "lone": 1,
  "loneliness": 1, "lonely": 1, "long": 1, "longing": 1, "longitude": 1, "look": 1, "loom": 1,
  "loose": 1, "loosen": 1, "lore": 1, "loser": 1, "lost": 1, "lot": 1, "lotion": 1, "loud": 1,
  "loudly": 1, "lout": 1, "love": 1, "lover": 1, "loving": 1, "low": 1, "lowly": 1, "loyalty": 1,
  "luck": 1, "lucky": 1, "ludicrous": 1, "lugubrious": 1, "lumber": 1, "lump": 1, "lunar": 1,
  "lunch": 1, "luncheon": 1, "lunchtime": 1, "lung": 1, "lurch": 1, "lure": 1, "lush": 1,
  "luxury": 1, "lymph": 1, "lynx": 1, "mace": 1, "machine": 1, "machinery": 1, "mackerel": 1,
  "mad": 1, "madeleine": 1, "madman": 1, "magic": 1, "magician": 1, "magistrate": 1, "magma": 1,
  "magnanimous": 1, "magnesium": 1, "magnificent": 1, "maid": 1, "maiden": 1, "main": 1,
  "mainland": 1, "mainstream": 1, "maintain": 1, "maintenance": 1, "maize": 1, "majestic": 1,
  "majesty": 1, "majority": 1, "makeup": 1, "malaria": 1, "male": 1, "malfunction": 1,
  "malice": 1, "malignant": 1, "mall": 1, "malt": 1, "mammal": 1, "mammalian": 1, "man": 1,
  "manage": 1, "manager": 1, "mandarin": 1, "mandate": 1, "mandatory": 1, "mandolin": 1,
  "maneuver": 1, "manga": 1, "mango": 1, "manifest": 1, "manifestation": 1, "manifold": 1,
  "manipulate": 1, "mankind": 1, "manner": 1, "manners": 1, "mantis": 1, "mantle": 1,
  "manual": 1, "manufacturer": 1, "manure": 1, "manuscript": 1, "map": 1, "maple": 1,
  "marble": 1, "mare": 1, "margin": 1, "marine": 1, "maritime": 1, "markup": 1, "marmalade": 1,
  "maroon": 1, "marriage": 1, "married": 1, "marry": 1, "marsh": 1, "martial": 1, "martyr": 1,
  "marvel": 1, "marvellous": 1, "marvelous": 1, "masculine": 1, "mash": 1, "mask": 1, "mason": 1,
  "masses": 1, "massive": 1, "mast": 1, "master": 1, "mastermind": 1, "masterpiece": 1, "mat": 1,
  "mate": 1, "material": 1, "math": 1, "mathematician": 1, "mathematics": 1, "maths": 1,
  "matrix": 1, "matter": 1, "mattress": 1, "maturity": 1, "maudlin": 1, "maverick": 1, "max": 1,
  "maxim": 1, "maximum": 1, "mayday": 1, "mayhem": 1, "mayonnaise": 1, "mayor": 1, "mead": 1,
  "meadow": 1, "meal": 1, "meaningless": 1, "meantime": 1, "measles": 1, "measure": 1, "meat": 1,
  "mechanic": 1, "mechanical": 1, "mechanism": 1, "medal": 1, "meddle": 1, "medical": 1,
  "medicine": 1, "medieval": 1, "mediocre": 1, "meditate": 1, "medium": 1, "medley": 1,
  "meet": 1, "melancholy": 1, "mellifluous": 1, "mellow": 1, "melody": 1, "melon": 1, "melt": 1,
  "member": 1, "membership": 1, "membrane": 1, "meme": 1, "memento": 1, "memorize": 1,
  "memory": 1, "men": 1, "mentality": 1, "mentally": 1, "mention": 1, "menu": 1, "mercenary": 1,
  "merchandise": 1, "merchant": 1, "merciful": 1, "mercury": 1, "mercy": 1, "mere": 1,
  "merely": 1, "merge": 1, "merit": 1, "mermaid": 1, "merry": 1, "mesh": 1, "mess": 1,
  "message": 1, "messenger": 1, "metadata": 1, "metallic": 1, "metaphor": 1, "meteor": 1,
  "meteorite": 1, "meter": 1, "methane": 1, "meticulous": 1, "metre": 1, "metropolis": 1,
  "mi": 1, "microscope": 1, "midget": 1, "midnight": 1, "midst": 1, "mighty": 1, "mild": 1,
  "mile": 1, "military": 1, "milk": 1, "mill": 1, "miller": 1, "million": 1, "mimic": 1,
  "mind": 1, "mindset": 1, "miner": 1, "mineral": 1, "mingle": 1, "minimal": 1, "minimum": 1,
  "ministerial": 1, "minor": 1, "minority": 1, "mint": 1, "minus": 1, "mirage": 1, "mirror": 1,
  "misbehave": 1, "miscellaneous": 1, "mischief": 1, "miserable": 1, "misery": 1,
  "misfortune": 1, "mission": 1, "missionary": 1, "mist": 1, "mistake": 1, "mistress": 1,
  "misunderstanding": 1, "mitigate": 1, "mix": 1, "mixed": 1, "mixture": 1, "moan": 1, "mob": 1,
  "mobile": 1, "mock": 1, "mode": 1, "modern": 1, "modest": 1, "modesty": 1, "modification": 1,
  "modify": 1, "moist": 1, "moisture": 1, "mole": 1, "momentum": 1, "monarch": 1, "monarchy": 1,
  "monastery": 1, "money": 1, "monkey": 1, "monopoly": 1, "monsoon": 1, "monster": 1,
  "montage": 1, "month": 1, "monthly": 1, "monument": 1, "moo": 1, "mood": 1, "moonlight": 1,
  "moor": 1, "moose": 1, "moot": 1, "mop": 1, "moral": 1, "morbid": 1, "moreover": 1,
  "morning": 1, "morrow": 1, "mortal": 1, "mortality": 1, "mortar": 1, "mortgage": 1,
  "mosquito": 1, "moss": 1, "mostly": 1, "moth": 1, "mother": 1, "motherboard": 1, "motif": 1,
  "motion": 1, "motivational": 1, "motive": 1, "motor": 1, "mound": 1, "mount": 1, "mountain": 1,
  "mourning": 1, "mouse": 1, "moustache": 1, "mouth": 1, "move": 1, "movie": 1, "mow": 1,
  "mower": 1, "mu": 1, "muck": 1, "mud": 1, "muddy": 1, "muffin": 1, "mug": 1, "mulberry": 1,
  "multicultural": 1, "multinational": 1, "multitude": 1, "mum": 1, "mumble": 1, "mummy": 1,
  "mundane": 1, "municipality": 1, "mural": 1, "muscle": 1, "muse": 1, "museum": 1, "mush": 1,
  "mushroom": 1, "music": 1, "musical": 1, "musician": 1, "mustard": 1, "muster": 1, "mute": 1,
  "mutt": 1, "mutual": 1, "mysterious": 1, "mystery": 1, "mystic": 1, "mystical": 1, "myth": 1,
  "mythology": 1, "nab": 1, "nail": 1, "naive": 1, "nameless": 1, "namely": 1, "namespace": 1,
  "narrative": 1, "narrator": 1, "narrow": 1, "nascent": 1, "nasty": 1, "nation": 1,
  "nationality": 1, "native": 1, "nativity": 1, "natural": 1, "naturally": 1, "nature": 1,
  "naughty": 1, "nautical": 1, "nautilus": 1, "naval": 1, "navigation": 1, "navy": 1, "nay": 1,
  "nearby": 1, "neat": 1, "nebula": 1, "nebulous": 1, "necessarily": 1, "necessary": 1,
  "necessity": 1, "needle": 1, "needless": 1, "needy": 1, "negative": 1, "neglect": 1,
  "neglected": 1, "negligent": 1, "negotiate": 1, "negotiation": 1, "neighborhood": 1,
  "neighboring": 1, "neighbour": 1, "neon": 1, "nephew": 1, "nerve": 1, "nervous": 1, "ness": 1,
  "nest": 1, "nestle": 1, "neutral": 1, "neutrality": 1, "neutron": 1, "never": 1,
  "nevertheless": 1, "new": 1, "newspaper": 1, "next": 1, "nexus": 1, "nice": 1, "niche": 1,
  "nickel": 1, "niece": 1, "nigh": 1, "night": 1, "nightclub": 1, "nightfall": 1,
  "nightingale": 1, "nightmare": 1, "nines": 1, "nineteenth": 1, "ninja": 1, "ninth": 1,
  "nirvana": 1, "nitrogen": 1, "nix": 1, "noble": 1, "nobody": 1, "nocturnal": 1, "nod": 1,
  "noisy": 1, "nonetheless": 1, "nonprofit": 1, "nonsense": 1, "noodle": 1, "noon": 1,
  "noose": 1, "norm": 1, "normal": 1, "north": 1, "northern": 1, "northwestern": 1, "nose": 1,
  "nosy": 1, "notable": 1, "notation": 1, "notion": 1, "notorious": 1, "nous": 1, "novel": 1,
  "novelty": 1, "nowadays": 1, "nowhere": 1, "nu": 1, "nuance": 1, "nucleus": 1, "nuisance": 1,
  "null": 1, "numerous": 1, "nurse": 1, "nut": 1, "nutrition": 1, "oak": 1, "oar": 1, "oasis": 1,
  "oath": 1, "oats": 1, "obedience": 1, "obedient": 1, "obey": 1, "obfuscate": 1, "objection": 1,
  "objectionable": 1, "objective": 1, "obligation": 1, "obliged": 1, "oblivion": 1, "obscene": 1,
  "obscure": 1, "obsequious": 1, "observation": 1, "observatory": 1, "observe": 1, "observer": 1,
  "obsolete": 1, "obstacle": 1, "obstinate": 1, "obtain": 1, "obvious": 1, "obviously": 1,
  "occasion": 1, "occasional": 1, "occasionally": 1, "occupied": 1, "occur": 1, "ocean": 1,
  "octopus": 1, "odd": 1, "offense": 1, "offensive": 1, "offering": 1, "officially": 1, "oft": 1,
  "often": 1, "ogre": 1, "oil": 1, "old": 1, "oldest": 1, "olive": 1, "ombudsman": 1, "omega": 1,
  "omelette": 1, "omen": 1, "omission": 1, "oncology": 1, "one": 1, "ongoing": 1, "onion": 1,
  "online": 1, "openly": 1, "opera": 1, "operate": 1, "opinion": 1, "opportunity": 1,
  "oppose": 1, "opposed": 1, "opposite": 1, "opposition": 1, "oppression": 1, "opt": 1,
  "optimal": 1, "optimism": 1, "optimize": 1, "oracle": 1, "orange": 1, "orbit": 1, "orchard": 1,
  "orchestra": 1, "orderly": 1, "ordinance": 1, "ordinary": 1, "ore": 1, "organ": 1,
  "organic": 1, "organism": 1, "organized": 1, "origin": 1, "originally": 1, "originate": 1,
  "ornament": 1, "orthodox": 1, "orthogonal": 1, "ostrich": 1, "otherwise": 1, "ought": 1,
  "outbreak": 1, "outer": 1, "outing": 1, "outlet": 1, "outline": 1, "outlook": 1, "outrage": 1,
  "outset": 1, "outskirts": 1, "outstanding": 1, "outward": 1, "oven": 1, "overall": 1,
  "overcome": 1, "overdue": 1, "overhaul": 1, "overhead": 1, "overlook": 1, "overnight": 1,
  "overreact": 1, "override": 1, "overthrow": 1, "overwhelming": 1, "owe": 1, "owing": 1,
  "owl": 1, "owner": 1, "ownership": 1, "ox": 1, "oxygen": 1, "oyster": 1, "ozone": 1, "pace": 1,
  "pacific": 1, "package": 1, "packed": 1, "paddy": 1, "paella": 1, "pagan": 1, "pager": 1,
  "pain": 1, "painful": 1, "painfully": 1, "paint": 1, "painter": 1, "painting": 1, "pajamas": 1,
  "palace": 1, "paladin": 1, "palanquin": 1, "palate": 1, "pale": 1, "palette": 1,
  "palliative": 1, "palm": 1, "pan": 1, "pancake": 1, "panda": 1, "pane": 1, "panel": 1,
  "panic": 1, "pant": 1, "pants": 1, "paper": 1, "paperback": 1, "parachute": 1, "parade": 1,
  "paradigm": 1, "paradise": 1, "paradox": 1, "paragon": 1, "paragraph": 1, "parallel": 1,
  "parameter": 1, "parametric": 1, "paramount": 1, "parcel": 1, "pardon": 1, "parent": 1,
  "parish": 1, "park": 1, "parliament": 1, "parliamentary": 1, "parrot": 1, "parse": 1,
  "parsley": 1, "participate": 1, "participation": 1, "particle": 1, "parting": 1, "partisan": 1,
  "partly": 1, "pass": 1, "passage": 1, "passenger": 1, "passing": 1, "passion": 1,
  "passionate": 1, "passionately": 1, "passive": 1, "passport": 1, "paste": 1, "pastry": 1,
  "pasture": 1, "pat": 1, "patch": 1, "patent": 1, "pathetic": 1, "patient": 1, "patio": 1,
  "patriotic": 1, "patriotism": 1, "patron": 1, "pause": 1, "pave": 1, "pavilion": 1, "paw": 1,
  "pay": 1, "payer": 1, "payment": 1, "pea": 1, "peace": 1, "peaceful": 1, "peacefully": 1,
  "peach": 1, "peacock": 1, "peanut": 1, "peanuts": 1, "pear": 1, "peasant": 1, "peat": 1,
  "pecan": 1, "peculiar": 1, "pedestrian": 1, "peep": 1, "peer": 1, "peg": 1, "pelican": 1,
  "pen": 1, "penance": 1, "pencil": 1, "pendulum": 1, "penetrate": 1, "penguin": 1,
  "peninsula": 1, "penny": 1, "pension": 1, "pentagon": 1, "pepper": 1, "peppermint": 1,
  "perceive": 1, "percentage": 1, "perception": 1, "perch": 1, "percussion": 1, "perennial": 1,
  "perfection": 1, "perfectly": 1, "perform": 1, "perfume": 1, "perfunctory": 1, "perilous": 1,
  "periodic": 1, "periodical": 1, "peripheral": 1, "perish": 1, "permanent": 1, "pernicious": 1,
  "perpendicular": 1, "perpetual": 1, "persecution": 1, "persist": 1, "person": 1, "personal": 1,
  "personnel": 1, "perspective": 1, "persuade": 1, "persuasive": 1, "pertinent": 1, "peso": 1,
  "pet": 1, "petty": 1, "pharmacy": 1, "phase": 1, "pheasant": 1, "phenomenon": 1, "phi": 1,
  "philosopher": 1, "philosophy": 1, "phosphorus": 1, "photograph": 1, "photography": 1,
  "phrase": 1, "physician": 1, "physicist": 1, "physics": 1, "physique": 1, "pi": 1, "pick": 1,
  "picket": 1, "picture": 1, "picturesque": 1, "pie": 1, "piece": 1, "pier": 1, "pierce": 1,
  "piercing": 1, "pig": 1, "pigeon": 1, "piglet": 1, "pigsty": 1, "pike": 1, "pile": 1,
  "pill": 1, "pillar": 1, "pillow": 1, "pilot": 1, "pimple": 1, "pin": 1, "pinch": 1,
  "pineapple": 1, "pint": 1, "pioneer": 1, "pious": 1, "pip": 1, "pipe": 1, "pirate": 1,
  "piston": 1, "pit": 1, "pitch": 1, "pitiful": 1, "pity": 1, "pivot": 1, "pivotal": 1,
  "pizza": 1, "placement": 1, "plaid": 1, "plain": 1, "plan": 1, "planet": 1, "plank": 1,
  "planned": 1, "plant": 1, "plantation": 1, "plaque": 1, "plasma": 1, "plaster": 1,
  "plastic": 1, "plate": 1, "plateau": 1, "platform": 1, "platinum": 1, "platter": 1,
  "plausible": 1, "play": 1, "playground": 1, "playwright": 1, "plaza": 1, "plead": 1,
  "pleasant": 1, "pleased": 1, "pleasing": 1, "pleasure": 1, "pledge": 1, "plenary": 1,
  "plentiful": 1, "plenty": 1, "pliers": 1, "plight": 1, "plot": 1, "plough": 1, "pluck": 1,
  "plug": 1, "plum": 1, "plume": 1, "plunge": 1, "plural": 1, "plutonium": 1, "poem": 1,
  "poetry": 1, "pointed": 1, "pointer": 1, "pointless": 1, "pole": 1, "police": 1, "policy": 1,
  "polish": 1, "polished": 1, "polite": 1, "politically": 1, "politician": 1, "politics": 1,
  "pollen": 1, "pollution": 1, "polygon": 1, "polymer": 1, "poncho": 1, "pond": 1, "ponder": 1,
  "poor": 1, "popcorn": 1, "pope": 1, "poppy": 1, "popular": 1, "popularity": 1, "population": 1,
  "porch": 1, "pork": 1, "port": 1, "portal": 1, "portion": 1, "portrait": 1, "pose": 1,
  "posh": 1, "position": 1, "possess": 1, "possession": 1, "possibility": 1, "possible": 1,
  "postcard": 1, "poster": 1, "postpone": 1, "postscript": 1, "pot": 1, "potassium": 1,
  "potato": 1, "potter": 1, "pouch": 1, "poultry": 1, "pound": 1, "pour": 1, "poverty": 1,
  "powder": 1, "power": 1, "powerful": 1, "powerhouse": 1, "practical": 1, "practically": 1,
  "practice": 1, "practicum": 1, "practise": 1, "pragmatic": 1, "prairie": 1, "praise": 1,
  "precaution": 1, "precedence": 1, "precedent": 1, "preceding": 1, "precious": 1,
  "precipitation": 1, "precisely": 1, "predict": 1, "predominant": 1, "predominantly": 1,
  "preface": 1, "prefer": 1, "preferable": 1, "preference": 1, "preferred": 1, "prefix": 1,
  "prejudice": 1, "prelude": 1, "premises": 1, "preparation": 1, "prepare": 1, "prepared": 1,
  "preposterous": 1, "prescription": 1, "presence": 1, "presentation": 1, "presently": 1,
  "preservation": 1, "preserve": 1, "president": 1, "pressing": 1, "prestige": 1,
  "presumably": 1, "presume": 1, "presumptuous": 1, "pretend": 1, "pretext": 1, "prevail": 1,
  "prevalent": 1, "prevent": 1, "previous": 1, "previously": 1, "prey": 1, "price": 1,
  "pride": 1, "priesthood": 1, "primate": 1, "primer": 1, "primitive": 1, "princess": 1,
  "principal": 1, "principle": 1, "print": 1, "printed": 1, "prior": 1, "prism": 1,
  "prisoner": 1, "pristine": 1, "private": 1, "privilege": 1, "privileged": 1, "prize": 1,
  "proactive": 1, "probability": 1, "probable": 1, "probably": 1, "problem": 1, "procedure": 1,
  "proceed": 1, "processing": 1, "procession": 1, "proclamation": 1, "procure": 1,
  "production": 1, "productivity": 1, "profession": 1, "professional": 1, "professor": 1,
  "proficient": 1, "profit": 1, "profitable": 1, "profound": 1, "profoundly": 1, "program": 1,
  "progress": 1, "prohibit": 1, "prohibition": 1, "project": 1, "prolific": 1, "prominent": 1,
  "promise": 1, "promote": 1, "promotion": 1, "promptly": 1, "pronounce": 1, "pronunciation": 1,
  "proof": 1, "propaganda": 1, "propane": 1, "propeller": 1, "properly": 1, "prophecy": 1,
  "prophet": 1, "proportion": 1, "propose": 1, "proposition": 1, "proprietary": 1,
  "proprietor": 1, "prose": 1, "prospect": 1, "prosperity": 1, "prosperous": 1, "protean": 1,
  "protect": 1, "protected": 1, "protector": 1, "protein": 1, "proton": 1, "prototype": 1,
  "proud": 1, "prove": 1, "proverb": 1, "providence": 1, "provider": 1, "province": 1,
  "provincial": 1, "provision": 1, "provoke": 1, "proximity": 1, "proxy": 1, "prudent": 1,
  "psalm": 1, "psi": 1, "psychiatrist": 1, "psychologist": 1, "psychology": 1, "pub": 1,
  "public": 1, "publication": 1, "publicly": 1, "publish": 1, "publisher": 1, "puke": 1,
  "pull": 1, "pulse": 1, "pump": 1, "pumpkin": 1, "punch": 1, "puncture": 1, "punish": 1,
  "punishment": 1, "punitive": 1, "pup": 1, "pupil": 1, "puppet": 1, "puppy": 1, "purchase": 1,
  "pure": 1, "purge": 1, "purple": 1, "purpose": 1, "purposely": 1, "purse": 1, "pursue": 1,
  "pursuit": 1, "push": 1, "pushover": 1, "put": 1, "puzzled": 1, "pyramid": 1, "quack": 1,
  "quail": 1, "quaint": 1, "qualified": 1, "qualify": 1, "quality": 1, "quantity": 1,
  "quarantine": 1, "quarrel": 1, "quarry": 1, "quart": 1, "quartz": 1, "quay": 1, "quest": 1,
  "question": 1, "questioning": 1, "queue": 1, "quiet": 1, "quietly": 1, "quill": 1, "quilt": 1,
  "quirky": 1, "quiz": 1, "quorum": 1, "quotation": 1, "quote": 1, "rabbi": 1, "rabbit": 1,
  "raccoon": 1, "race": 1, "rack": 1, "radar": 1, "radiator": 1, "radius": 1, "raffle": 1,
  "raft": 1, "rag": 1, "rage": 1, "raid": 1, "rail": 1, "railing": 1, "railway": 1, "rain": 1,
  "rainbow": 1, "raise": 1, "raisin": 1, "rake": 1, "ram": 1, "ramp": 1, "ranch": 1, "random": 1,
  "rank": 1, "rapid": 1, "rapidly": 1, "rapport": 1, "rapture": 1, "rare": 1, "rarely": 1,
  "rarity": 1, "rascal": 1, "rash": 1, "rat": 1, "ratchet": 1, "rather": 1, "ratio": 1,
  "ration": 1, "rational": 1, "ratty": 1, "raven": 1, "ravine": 1, "raw": 1, "razor": 1,
  "reaction": 1, "readable": 1, "reader": 1, "readily": 1, "ready": 1, "real": 1, "realise": 1,
  "realization": 1, "realize": 1, "realm": 1, "reap": 1, "rear": 1, "reasonable": 1,
  "reasoning": 1, "rebirth": 1, "reboot": 1, "recall": 1, "receipt": 1, "receiver": 1,
  "reception": 1, "recess": 1, "recipe": 1, "reciprocal": 1, "recital": 1, "reckon": 1,
  "recognition": 1, "recognize": 1, "recognized": 1, "recommend": 1, "reconcile": 1,
  "recorded": 1, "recorder": 1, "recording": 1, "recover": 1, "recovery": 1, "rectangle": 1,
  "rector": 1, "recycling": 1, "red": 1, "redemption": 1, "redo": 1, "reduce": 1, "reed": 1,
  "reef": 1, "reel": 1, "refer": 1, "referee": 1, "reflect": 1, "reflection": 1, "reform": 1,
  "reformation": 1, "refrain": 1, "refresh": 1, "refrigerator": 1, "refuge": 1, "refusal": 1,
  "refuse": 1, "regard": 1, "regards": 1, "reggae": 1, "regimen": 1, "regiment": 1, "region": 1,
  "regional": 1, "registration": 1, "regret": 1, "regularly": 1, "regulate": 1, "reign": 1,
  "reimburse": 1, "rein": 1, "reindeer": 1, "reinforce": 1, "reinforcement": 1, "reject": 1,
  "rejoice": 1, "relation": 1, "relational": 1, "relationship": 1, "relative": 1, "relax": 1,
  "reliable": 1, "relief": 1, "relieve": 1, "religion": 1, "religious": 1, "relish": 1,
  "reluctance": 1, "reluctant": 1, "rely": 1, "remain": 1, "remainder": 1, "remaining": 1,
  "remains": 1, "remake": 1, "remark": 1, "remarkable": 1, "remedy": 1, "remember": 1,
  "remembrance": 1, "remove": 1, "render": 1, "rendezvous": 1, "renegade": 1, "renew": 1,
  "renewal": 1, "rent": 1, "repair": 1, "repeal": 1, "repeat": 1, "repeated": 1, "repeatedly": 1,
  "repent": 1, "repentance": 1, "repetition": 1, "rephrase": 1, "replace": 1, "replacement": 1,
  "reply": 1, "report": 1, "reporter": 1, "repository": 1, "represent": 1, "representative": 1,
  "reproduce": 1, "reproduction": 1, "republic": 1, "reputation": 1, "request": 1, "require": 1,
  "requisite": 1, "rescue": 1, "research": 1, "resent": 1, "resentment": 1, "reserve": 1,
  "reservoir": 1, "reside": 1, "residence": 1, "resignation": 1, "resilient": 1, "resin": 1,
  "resist": 1, "resistance": 1, "resolution": 1, "resolve": 1, "resort": 1, "resource": 1,
  "respectable": 1, "respected": 1, "respectful": 1, "respective": 1, "respond": 1,
  "responsible": 1, "rest": 1, "restless": 1, "restoration": 1, "restore": 1, "restrain": 1,
  "restrained": 1, "result": 1, "resume": 1, "resurrection": 1, "retail": 1, "retain": 1,
  "rethink": 1, "retired": 1, "retreat": 1, "retrospect": 1, "return": 1, "reveal": 1,
  "revealing": 1, "revelation": 1, "revenge": 1, "revenue": 1, "reverence": 1, "reverend": 1,
  "reverse": 1, "revise": 1, "revive": 1, "revolt": 1, "revolutionary": 1, "revue": 1,
  "reward": 1, "rhetorical": 1, "rhyme": 1, "rhythm": 1, "rhythmic": 1, "rib": 1, "ribbon": 1,
  "rice": 1, "rid": 1, "ride": 1, "rider": 1, "ridge": 1, "ridicule": 1, "ridiculous": 1,
  "righteous": 1, "righteousness": 1, "rigid": 1, "rigorous": 1, "rim": 1, "rinse": 1, "rip": 1,
  "ripe": 1, "ripple": 1, "rise": 1, "rite": 1, "ritual": 1, "rival": 1, "rivalry": 1,
  "river": 1, "road": 1, "roadside": 1, "roam": 1, "roar": 1, "roast": 1, "robe": 1, "robin": 1,
  "robot": 1, "robust": 1, "rocket": 1, "rocky": 1, "rod": 1, "roe": 1, "rogue": 1, "romance": 1,
  "romantic": 1, "roof": 1, "rook": 1, "rooster": 1, "root": 1, "rope": 1, "rosemary": 1,
  "roster": 1, "rot": 1, "rotate": 1, "rouge": 1, "rough": 1, "roughly": 1, "round": 1,
  "roundabout": 1, "route": 1, "router": 1, "routine": 1, "row": 1, "rowing": 1, "royal": 1,
  "royalty": 1, "rub": 1, "rubber": 1, "rubbish": 1, "rubble": 1, "rudder": 1, "rude": 1,
  "rugby": 1, "rugged": 1, "ruin": 1, "rule": 1, "ruler": 1, "rumble": 1, "run": 1, "rune": 1,
  "rung": 1, "runoff": 1, "runway": 1, "rush": 1, "rushed": 1, "rust": 1, "rustic": 1, "rut": 1,
  "rye": 1, "sable": 1, "sack": 1, "sacrifice": 1, "sacrilege": 1, "sad": 1, "saddle": 1,
  "sadly": 1, "sadness": 1, "safe": 1, "safeguard": 1, "safely": 1, "safety": 1, "sage": 1,
  "sail": 1, "sailing": 1, "sailor": 1, "sake": 1, "salad": 1, "salary": 1, "salmon": 1,
  "salon": 1, "saloon": 1, "salt": 1, "salute": 1, "salvation": 1, "samurai": 1, "sand": 1,
  "sandbox": 1, "sandman": 1, "sandwich": 1, "sandy": 1, "sanguine": 1, "sanitary": 1,
  "sanitation": 1, "sanity": 1, "sap": 1, "sapphire": 1, "sarcasm": 1, "sash": 1, "satin": 1,
  "satire": 1, "satisfaction": 1, "satisfactorily": 1, "satisfactory": 1, "satisfied": 1,
  "satisfy": 1, "satisfying": 1, "sauce": 1, "sauna": 1, "sausage": 1, "savage": 1, "save": 1,
  "saving": 1, "saxophone": 1, "scale": 1, "scales": 1, "scalp": 1, "scan": 1, "scandalous": 1,
  "scapegoat": 1, "scarce": 1, "scarcely": 1, "scare": 1, "scared": 1, "scary": 1, "scatter": 1,
  "scattered": 1, "scavenger": 1, "scenario": 1, "scene": 1, "scenery": 1, "scent": 1,
  "schedule": 1, "schema": 1, "scheme": 1, "schizophrenia": 1, "school": 1, "science": 1,
  "scientific": 1, "scientifically": 1, "scissors": 1, "scold": 1, "scoop": 1, "scooter": 1,
  "scope": 1, "score": 1, "scorn": 1, "scotch": 1, "scramble": 1, "scrap": 1, "scrape": 1,
  "scratch": 1, "scrawny": 1, "scream": 1, "screen": 1, "screw": 1, "screwdriver": 1,
  "script": 1, "scripture": 1, "scrutiny": 1, "sculptor": 1, "sculpture": 1, "scum": 1,
  "scumbag": 1, "sea": 1, "seal": 1, "seaman": 1, "search": 1, "season": 1, "seat": 1,
  "secluded": 1, "secondary": 1, "secrecy": 1, "secret": 1, "secretary": 1, "secretly": 1,
  "sect": 1, "secular": 1, "secure": 1, "securely": 1, "seed": 1, "seek": 1, "seeking": 1,
  "seem": 1, "seize": 1, "seizure": 1, "seldom": 1, "selection": 1, "selfie": 1, "selfish": 1,
  "sell": 1, "senate": 1, "send": 1, "sensation": 1, "sense": 1, "sensible": 1, "sensitive": 1,
  "sentence": 1, "sentiment": 1, "sentimental": 1, "sentinel": 1, "separated": 1,
  "separately": 1, "separation": 1, "sequel": 1, "sequence": 1, "serendipity": 1, "serene": 1,
  "serenity": 1, "sergeant": 1, "serious": 1, "sermon": 1, "serpent": 1, "servant": 1,
  "serve": 1, "service": 1, "serving": 1, "setback": 1, "settle": 1, "settlement": 1,
  "seventh": 1, "sever": 1, "severe": 1, "severity": 1, "sew": 1, "sewer": 1, "shabby": 1,
  "shade": 1, "shadow": 1, "shady": 1, "shaggy": 1, "shake": 1, "shallow": 1, "shame": 1,
  "shampoo": 1, "shamrock": 1, "shank": 1, "shape": 1, "shaped": 1, "share": 1, "shared": 1,
  "shark": 1, "sharp": 1, "sharply": 1, "shatter": 1, "shave": 1, "shawl": 1, "sheath": 1,
  "shed": 1, "sheep": 1, "sheer": 1, "sheet": 1, "sheik": 1, "shell": 1, "shelter": 1,
  "shepherd": 1, "sherry": 1, "shield": 1, "shift": 1, "shilling": 1, "shin": 1, "shine": 1,
  "shining": 1, "shiny": 1, "shirt": 1, "shiver": 1, "shock": 1, "shocked": 1, "shocking": 1,
  "shoe": 1, "shoot": 1, "shop": 1, "shopper": 1, "shore": 1, "short": 1, "shortly": 1,
  "shorts": 1, "shoulder": 1, "shout": 1, "shovel": 1, "show": 1, "showcase": 1, "shredder": 1,
  "shriek": 1, "shrimp": 1, "shrine": 1, "shuffle": 1, "shun": 1, "shut": 1, "shutter": 1,
  "shuttle": 1, "shy": 1, "sic": 1, "sick": 1, "sickle": 1, "sickness": 1, "side": 1,
  "sidewalk": 1, "siege": 1, "sieve": 1, "sigh": 1, "sight": 1, "sightseeing": 1, "sigma": 1,
  "signal": 1, "significance": 1, "significant": 1, "silence": 1, "silent": 1, "silently": 1,
  "silhouette": 1, "silicon": 1, "silk": 1, "silly": 1, "similar": 1, "similarly": 1,
  "simple": 1, "simplicity": 1, "simply": 1, "simultaneous": 1, "sincere": 1, "sincerely": 1,
  "sinful": 1, "sing": 1, "singer": 1, "singing": 1, "singular": 1, "sinister": 1, "sink": 1,
  "sinner": 1, "sister": 1, "sit": 1, "situated": 1, "situation": 1, "sixth": 1, "size": 1,
  "skate": 1, "skateboard": 1, "skedaddle": 1, "skeleton": 1, "sketch": 1, "skill": 1,
  "skilled": 1, "skin": 1, "skinny": 1, "skipper": 1, "skirt": 1, "skull": 1, "sky": 1,
  "skype": 1, "slang": 1, "slant": 1, "slap": 1, "sleazy": 1, "sledgehammer": 1, "sleep": 1,
  "sleepy": 1, "sleeve": 1, "slender": 1, "slice": 1, "slide": 1, "slight": 1, "slightly": 1,
  "slim": 1, "slip": 1, "slipper": 1, "slippery": 1, "slit": 1, "slogan": 1, "slop": 1,
  "slope": 1, "slot": 1, "slow": 1, "slowly": 1, "slug": 1, "slum": 1, "slumber": 1, "small": 1,
  "smash": 1, "smear": 1, "smell": 1, "smile": 1, "smoked": 1, "smooth": 1, "smoothly": 1,
  "snail": 1, "snake": 1, "snap": 1, "snapshot": 1, "snare": 1, "snatch": 1, "sneaky": 1,
  "sneeze": 1, "snippet": 1, "snitch": 1, "snooker": 1, "snore": 1, "snort": 1, "snow": 1,
  "snowball": 1, "snowboard": 1, "snowflake": 1, "snowman": 1, "snowy": 1, "soaked": 1,
  "soap": 1, "sob": 1, "sober": 1, "socialist": 1, "society": 1, "sock": 1, "socket": 1,
  "sod": 1, "sodium": 1, "sofa": 1, "soft": 1, "soften": 1, "softly": 1, "software": 1,
  "soil": 1, "solace": 1, "solar": 1, "solder": 1, "sole": 1, "solely": 1, "solemn": 1,
  "solitary": 1, "solitude": 1, "solution": 1, "somehow": 1, "sometimes": 1, "somewhat": 1,
  "sonar": 1, "song": 1, "sonic": 1, "sonny": 1, "soon": 1, "soothe": 1, "soprano": 1,
  "sorcerer": 1, "sorcery": 1, "sore": 1, "sorrow": 1, "sounding": 1, "soup": 1, "sour": 1,
  "southeastern": 1, "southern": 1, "sovereign": 1, "soy": 1, "space": 1, "spacious": 1,
  "spade": 1, "spades": 1, "span": 1, "spank": 1, "spanking": 1, "spare": 1, "spark": 1,
  "sparkle": 1, "sparrow": 1, "spatial": 1, "speak": 1, "speaker": 1, "spear": 1, "special": 1,
  "specially": 1, "specialty": 1, "specific": 1, "specifically": 1, "speck": 1, "spectacles": 1,
  "spectator": 1, "specter": 1, "spectrum": 1, "speculation": 1, "speechless": 1, "speed": 1,
  "spell": 1, "spelling": 1, "spend": 1, "sphere": 1, "sphinx": 1, "spice": 1, "spider": 1,
  "spike": 1, "spill": 1, "spin": 1, "spiral": 1, "spirit": 1, "spirits": 1, "spiritual": 1,
  "spirituality": 1, "spit": 1, "spite": 1, "splash": 1, "splendid": 1, "splendor": 1,
  "splinter": 1, "split": 1, "spoil": 1, "spoiler": 1, "spoils": 1, "spoke": 1, "spoken": 1,
  "sponge": 1, "spontaneous": 1, "spool": 1, "spoon": 1, "sport": 1, "spouse": 1, "spray": 1,
  "spread": 1, "sprout": 1, "spruce": 1, "spur": 1, "spy": 1, "squadron": 1, "squared": 1,
  "squash": 1, "squat": 1, "squawk": 1, "squeak": 1, "squeamish": 1, "squeeze": 1, "squid": 1,
  "squire": 1, "squirm": 1, "squish": 1, "stability": 1, "stadium": 1, "stag": 1,
  "staggering": 1, "stair": 1, "staircase": 1, "stairs": 1, "stairway": 1, "stake": 1,
  "stalk": 1, "stallion": 1, "stamp": 1, "stampede": 1, "stand": 1, "standard": 1,
  "standpoint": 1, "staple": 1, "star": 1, "starch": 1, "starry": 1, "starter": 1, "startled": 1,
  "stash": 1, "statement": 1, "statesman": 1, "static": 1, "station": 1, "statistics": 1,
  "statue": 1, "stature": 1, "status": 1, "statutory": 1, "steady": 1, "steak": 1, "stealth": 1,
  "steam": 1, "steep": 1, "steer": 1, "stellar": 1, "stem": 1, "stepson": 1, "stern": 1,
  "steroid": 1, "steward": 1, "sticker": 1, "sticky": 1, "stiff": 1, "stimulate": 1, "sting": 1,
  "stink": 1, "stir": 1, "stitch": 1, "stochastic": 1, "stocking": 1, "stole": 1, "stolen": 1,
  "stomach": 1, "stomp": 1, "stone": 1, "stool": 1, "storage": 1, "store": 1, "stork": 1,
  "storm": 1, "stormy": 1, "story": 1, "storyteller": 1, "storytelling": 1, "stout": 1,
  "stove": 1, "straight": 1, "straighten": 1, "straightforward": 1, "strain": 1, "strait": 1,
  "strand": 1, "strange": 1, "stranger": 1, "straw": 1, "strawberry": 1, "stray": 1, "streak": 1,
  "stream": 1, "street": 1, "strength": 1, "strengthen": 1, "stress": 1, "stretch": 1,
  "strict": 1, "strictly": 1, "stride": 1, "strife": 1, "strike": 1, "striking": 1, "string": 1,
  "stringent": 1, "strip": 1, "stripe": 1, "strive": 1, "stroll": 1, "stroller": 1, "strong": 1,
  "stronghold": 1, "strongly": 1, "struggle": 1, "struggling": 1, "stub": 1, "stubborn": 1,
  "stuck": 1, "student": 1, "studio": 1, "stuff": 1, "stumble": 1, "stump": 1, "stunned": 1,
  "stunt": 1, "stupidity": 1, "sturdy": 1, "style": 1, "sub": 1, "subclass": 1, "sublime": 1,
  "submission": 1, "submit": 1, "subordinate": 1, "subpoena": 1, "subscribe": 1, "subsequent": 1,
  "subsequently": 1, "subset": 1, "substance": 1, "substantial": 1, "substitute": 1, "subtle": 1,
  "subtract": 1, "subway": 1, "succeed": 1, "successful": 1, "successfully": 1, "succession": 1,
  "successive": 1, "successor": 1, "sudden": 1, "suddenly": 1, "sue": 1, "suede": 1, "suffer": 1,
  "suffering": 1, "suffice": 1, "sufficient": 1, "sufficiently": 1, "suffix": 1, "sugar": 1,
  "suggest": 1, "suggestion": 1, "suit": 1, "suitable": 1, "suitcase": 1, "suite": 1,
  "sulfur": 1, "sulk": 1, "sully": 1, "sum": 1, "summarize": 1, "summary": 1, "summer": 1,
  "summit": 1, "summon": 1, "sun": 1, "sunglasses": 1, "sunlight": 1, "sunny": 1, "sunset": 1,
  "sunshine": 1, "superb": 1, "supercilious": 1, "superficial": 1, "superintendent": 1,
  "superior": 1, "superiority": 1, "supermarket": 1, "supernatural": 1, "superstition": 1,
  "superstitious": 1, "supervision": 1, "supper": 1, "support": 1, "suppose": 1, "supposedly": 1,
  "suppress": 1, "supremacy": 1, "supreme": 1, "surcharge": 1, "sure": 1, "surely": 1,
  "surge": 1, "surgical": 1, "surname": 1, "surprise": 1, "surprised": 1, "surprising": 1,
  "surrender": 1, "surround": 1, "surveillance": 1, "survive": 1, "suspended": 1, "suspense": 1,
  "suspicion": 1, "suspicious": 1, "sustain": 1, "swallow": 1, "swamp": 1, "swan": 1, "swap": 1,
  "swarm": 1, "swat": 1, "sway": 1, "swear": 1, "sweat": 1, "sweater": 1, "sweatshirt": 1,
  "sweep": 1, "sweeten": 1, "sweetheart": 1, "sweetness": 1, "swelling": 1, "swift": 1,
  "swim": 1, "swimming": 1, "swimsuit": 1, "swine": 1, "swing": 1, "swipe": 1, "swivel": 1,
  "swoop": 1, "sword": 1, "sworn": 1, "syllable": 1, "symbol": 1, "symbolic": 1, "symbolism": 1,
  "sympathetic": 1, "sympathy": 1, "synchronization": 1, "synchronize": 1, "synchronous": 1,
  "synonym": 1, "synopsis": 1, "synthetic": 1, "syringe": 1, "syrup": 1, "system": 1,
  "systematic": 1, "systemic": 1, "table": 1, "tablespoon": 1, "tacit": 1, "taciturn": 1,
  "tack": 1, "tackle": 1, "taco": 1, "tactic": 1, "tad": 1, "tail": 1, "tailor": 1, "take": 1,
  "takeover": 1, "talent": 1, "talisman": 1, "talk": 1, "tall": 1, "tally": 1, "talon": 1,
  "tame": 1, "tandem": 1, "tangible": 1, "tangle": 1, "tantamount": 1, "tap": 1, "tape": 1,
  "tapered": 1, "tapestry": 1, "tar": 1, "taste": 1, "tasty": 1, "tau": 1, "tax": 1,
  "taxation": 1, "taxi": 1, "tea": 1, "teach": 1, "teacher": 1, "teahouse": 1, "teapot": 1,
  "tease": 1, "teaser": 1, "teaspoon": 1, "technical": 1, "tedious": 1, "teenager": 1,
  "telegram": 1, "telegraph": 1, "telephone": 1, "telescope": 1, "television": 1, "temper": 1,
  "temperature": 1, "tempest": 1, "template": 1, "temporary": 1, "tempt": 1, "temptation": 1,
  "tempting": 1, "ten": 1, "tenacious": 1, "tend": 1, "tendency": 1, "tender": 1,
  "tenderness": 1, "tenner": 1, "tenor": 1, "tense": 1, "tent": 1, "tenth": 1, "terrible": 1,
  "terribly": 1, "terrific": 1, "territory": 1, "terrorism": 1, "tertiary": 1, "tesla": 1,
  "test": 1, "testimony": 1, "textbook": 1, "textile": 1, "texture": 1, "thank": 1,
  "thanksgiving": 1, "thaw": 1, "theater": 1, "theme": 1, "thence": 1, "theology": 1,
  "theoretical": 1, "therapeutic": 1, "thereby": 1, "therefore": 1, "thereof": 1,
  "thermometer": 1, "thesis": 1, "theta": 1, "thick": 1, "thigh": 1, "thin": 1, "thing": 1,
  "thingy": 1, "thirst": 1, "thirsty": 1, "thistle": 1, "thoracic": 1, "thorn": 1, "thorough": 1,
  "thoroughly": 1, "thou": 1, "thought": 1, "thoughtful": 1, "thoughtless": 1, "thousand": 1,
  "threads": 1, "threat": 1, "threaten": 1, "threatening": 1, "three": 1, "threshold": 1,
  "thrice": 1, "thrill": 1, "thrive": 1, "throne": 1, "throw": 1, "thrust": 1, "thud": 1,
  "thumb": 1, "thunder": 1, "tick": 1, "ticket": 1, "tickle": 1, "tide": 1, "tie": 1, "tiger": 1,
  "timber": 1, "timeless": 1, "timeline": 1, "timer": 1, "timestamp": 1, "timetable": 1,
  "timid": 1, "timothy": 1, "tin": 1, "tinker": 1, "tiny": 1, "tip": 1, "tired": 1, "tissue": 1,
  "titanium": 1, "title": 1, "toast": 1, "today": 1, "toddler": 1, "toe": 1, "together": 1,
  "toggle": 1, "toil": 1, "toilet": 1, "token": 1, "tolerance": 1, "tolerate": 1, "toll": 1,
  "tomato": 1, "tomb": 1, "tombstone": 1, "tomorrow": 1, "ton": 1, "tone": 1, "tongue": 1,
  "tonight": 1, "tooth": 1, "toothache": 1, "toothbrush": 1, "torch": 1, "torment": 1,
  "tornado": 1, "torpor": 1, "torque": 1, "torrent": 1, "torso": 1, "tortoise": 1, "tot": 1,
  "touch": 1, "touching": 1, "touchy": 1, "tourniquet": 1, "tout": 1, "towel": 1, "tower": 1,
  "town": 1, "toy": 1, "trace": 1, "tract": 1, "tractor": 1, "trade": 1, "trademark": 1,
  "tradition": 1, "traditional": 1, "traditionally": 1, "traffic": 1, "tragedy": 1, "trail": 1,
  "training": 1, "traitor": 1, "trajectory": 1, "tramp": 1, "tranquil": 1, "transaction": 1,
  "transcend": 1, "transcription": 1, "transfer": 1, "transform": 1, "transformation": 1,
  "transient": 1, "transit": 1, "translate": 1, "translation": 1, "translator": 1,
  "translucent": 1, "transparent": 1, "trap": 1, "trash": 1, "travel": 1, "traveller": 1,
  "travelling": 1, "tray": 1, "treacherous": 1, "tread": 1, "treasure": 1, "treasurer": 1,
  "treasury": 1, "treatment": 1, "treaty": 1, "tree": 1, "tremendous": 1, "trenchant": 1,
  "triangle": 1, "tribe": 1, "tribunal": 1, "tribute": 1, "trick": 1, "tricky": 1, "trifle": 1,
  "trilogy": 1, "trim": 1, "trinity": 1, "trip": 1, "tripe": 1, "triple": 1, "triumph": 1,
  "trivial": 1, "trombone": 1, "troops": 1, "tropical": 1, "troubled": 1, "troublemaker": 1,
  "troublesome": 1, "trough": 1, "trout": 1, "truce": 1, "truculent": 1, "truly": 1,
  "trumpet": 1, "trunk": 1, "trust": 1, "trustworthy": 1, "truth": 1, "truthful": 1, "tsar": 1,
  "tuba": 1, "tube": 1, "tuck": 1, "tulip": 1, "tumble": 1, "tuna": 1, "tundra": 1, "tune": 1,
  "tungsten": 1, "tunnel": 1, "turbine": 1, "turbulent": 1, "turkey": 1, "turmoil": 1,
  "turnover": 1, "turquoise": 1, "turtle": 1, "tutor": 1, "tweet": 1, "twelfth": 1,
  "twentieth": 1, "twenty": 1, "twice": 1, "twig": 1, "twilight": 1, "twin": 1, "twinkle": 1,
  "twirl": 1, "twist": 1, "twisted": 1, "twisting": 1, "two": 1, "typewriter": 1, "typhoon": 1,
  "typical": 1, "typo": 1, "ubiquitous": 1, "ugh": 1, "ugly": 1, "ultimate": 1, "umbrella": 1,
  "unable": 1, "unanimous": 1, "unaware": 1, "unbelievable": 1, "uncanny": 1, "uncertain": 1,
  "uncertainty": 1, "uncle": 1, "unclear": 1, "uncomfortable": 1, "unconscious": 1,
  "uncontrollable": 1, "undeniable": 1, "underdog": 1, "undermine": 1, "underneath": 1,
  "underscore": 1, "understand": 1, "undertake": 1, "undertaking": 1, "underwear": 1,
  "undoubtedly": 1, "unexpected": 1, "unexpectedly": 1, "unfair": 1, "unfinished": 1,
  "unforgivable": 1, "unfortunately": 1, "unhappy": 1, "uniform": 1, "unimportant": 1,
  "unique": 1, "unite": 1, "united": 1, "unity": 1, "universal": 1, "university": 1, "unjust": 1,
  "unknown": 1, "unleaded": 1, "unlikely": 1, "unlimited": 1, "unmarried": 1, "unnecessary": 1,
  "unpleasant": 1, "unprecedented": 1, "unreasonable": 1, "unrest": 1, "unseemly": 1,
  "unsolicited": 1, "untouched": 1, "unused": 1, "unusual": 1, "unusually": 1, "unwilling": 1,
  "upbeat": 1, "update": 1, "upper": 1, "upright": 1, "upside": 1, "upstairs": 1, "upward": 1,
  "uranium": 1, "urge": 1, "urgent": 1, "usage": 1, "usefulness": 1, "useless": 1, "usher": 1,
  "usual": 1, "usually": 1, "utmost": 1, "utter": 1, "vacancy": 1, "vacant": 1, "vaccination": 1,
  "vaccine": 1, "vacuum": 1, "vague": 1, "vain": 1, "valiant": 1, "valley": 1, "valuable": 1,
  "van": 1, "vanilla": 1, "vanity": 1, "vapor": 1, "variation": 1, "variety": 1, "various": 1,
  "varnish": 1, "vase": 1, "vast": 1, "vat": 1, "vault": 1, "veal": 1, "vector": 1,
  "vegetable": 1, "vegetation": 1, "vehicle": 1, "veil": 1, "vein": 1, "velocity": 1,
  "velvet": 1, "vendor": 1, "venerate": 1, "vengeance": 1, "venom": 1, "vent": 1,
  "ventilation": 1, "ventriloquist": 1, "venture": 1, "verb": 1, "verbal": 1, "verbatim": 1,
  "verbose": 1, "verdict": 1, "verge": 1, "verse": 1, "vertex": 1, "vertical": 1, "verve": 1,
  "vessel": 1, "vest": 1, "veterinarian": 1, "vial": 1, "vibration": 1, "vice": 1, "vicious": 1,
  "vicissitude": 1, "victory": 1, "vigorous": 1, "villa": 1, "village": 1, "villain": 1,
  "vim": 1, "vinegar": 1, "vineyard": 1, "vinyl": 1, "viola": 1, "violate": 1, "violent": 1,
  "violet": 1, "violin": 1, "viper": 1, "virtually": 1, "virtue": 1, "virtuous": 1, "visible": 1,
  "visit": 1, "visitor": 1, "visor": 1, "vital": 1, "vitamin": 1, "vivid": 1, "vixen": 1,
  "vocabulary": 1, "vocation": 1, "voice": 1, "void": 1, "volatile": 1, "volcano": 1,
  "volleyball": 1, "voluntary": 1, "volunteer": 1, "vomit": 1, "vortex": 1, "vote": 1,
  "voting": 1, "vow": 1, "voyage": 1, "vulgar": 1, "vulture": 1, "wad": 1, "wade": 1,
  "waffle": 1, "wage": 1, "wager": 1, "wagon": 1, "wait": 1, "waiter": 1, "walk": 1, "wall": 1,
  "wallpaper": 1, "walnut": 1, "walrus": 1, "wand": 1, "wander": 1, "wandering": 1, "ward": 1,
  "wardrobe": 1, "ware": 1, "warfare": 1, "warmth": 1, "warning": 1, "warp": 1, "warrant": 1,
  "warrior": 1, "wash": 1, "washer": 1, "wasp": 1, "waste": 1, "watchlist": 1, "water": 1,
  "waterfall": 1, "watermelon": 1, "watershed": 1, "wave": 1, "wavelength": 1, "wax": 1,
  "weak": 1, "weakness": 1, "wealth": 1, "wear": 1, "weary": 1, "weasel": 1, "weather": 1,
  "weave": 1, "web": 1, "wed": 1, "wee": 1, "week": 1, "weekday": 1, "weekend": 1, "weekly": 1,
  "weep": 1, "weigh": 1, "weird": 1, "weirdo": 1, "western": 1, "wet": 1, "whale": 1, "wharf": 1,
  "whatnot": 1, "whatsoever": 1, "wheat": 1, "wheel": 1, "wheelbarrow": 1, "wheelchair": 1,
  "whence": 1, "whenever": 1, "whereabouts": 1, "whereas": 1, "whereby": 1, "wherever": 1,
  "whimsical": 1, "whine": 1, "whip": 1, "whirl": 1, "whisper": 1, "whistle": 1, "white": 1,
  "whole": 1, "wholesale": 1, "whom": 1, "why": 1, "wicked": 1, "wide": 1, "widely": 1,
  "widget": 1, "width": 1, "wife": 1, "wig": 1, "wiggle": 1, "wiki": 1, "wildcat": 1,
  "wilderness": 1, "willingly": 1, "willow": 1, "wilt": 1, "win": 1, "winch": 1, "wind": 1,
  "windmill": 1, "window": 1, "windsurfing": 1, "winery": 1, "wing": 1, "wink": 1, "winter": 1,
  "wipe": 1, "wire": 1, "wireless": 1, "wisdom": 1, "wise": 1, "wit": 1, "witch": 1,
  "withdraw": 1, "withdrawn": 1, "withhold": 1, "withstand": 1, "witness": 1, "wizard": 1,
  "woe": 1, "wolf": 1, "woman": 1, "womanizer": 1, "womb": 1, "wonderful": 1, "wonderfully": 1,
  "wont": 1, "woo": 1, "wooden": 1, "woodland": 1, "wool": 1, "woozy": 1, "word": 1, "worker": 1,
  "workshop": 1, "worldly": 1, "worldwide": 1, "worm": 1, "worried": 1, "worry": 1, "worst": 1,
  "worth": 1, "worthless": 1, "worthy": 1, "wounded": 1, "wraith": 1, "wrapped": 1, "wrapper": 1,
  "wrath": 1, "wreath": 1, "wreck": 1, "wren": 1, "wrench": 1, "wrestle": 1, "wretch": 1,
  "wretched": 1, "wrinkle": 1, "wrist": 1, "write": 1, "writer": 1, "wrong": 1, "wrought": 1,
  "xi": 1, "yacht": 1, "yam": 1, "yard": 1, "yarn": 1, "yawn": 1, "ye": 1, "yearly": 1,
  "yearning": 1, "yell": 1, "yellow": 1, "yes": 1, "yesterday": 1, "yield": 1, "yoga": 1,
  "yonder": 1, "young": 1, "younger": 1, "yummy": 1, "zeal": 1, "zealous": 1, "zebra": 1,
  "zee": 1, "zenith": 1, "zephyr": 1, "zeta": 1, "zinc": 1, "zip": 1, "zoo": 1
};
