// База слов по уровням CEFR. Тестовая версия — потом расширим / заменим на API.
const WORDS = {
  A1: [
    { w: "apple", t: "яблоко", ex: "I eat an apple every day." },
    { w: "water", t: "вода", ex: "Can I have some water, please?" },
    { w: "house", t: "дом", ex: "My house is small but cozy." },
    { w: "friend", t: "друг", ex: "He is my best friend." },
    { w: "family", t: "семья", ex: "I love my family." },
    { w: "morning", t: "утро", ex: "Good morning! How are you?" },
    { w: "food", t: "еда", ex: "The food here is very good." },
    { w: "happy", t: "счастливый", ex: "She looks happy today." },
    { w: "big", t: "большой", ex: "That is a big dog!" },
    { w: "small", t: "маленький", ex: "I live in a small town." },
    { w: "run", t: "бегать", ex: "I run in the park every morning." },
    { w: "eat", t: "есть, кушать", ex: "We eat dinner at seven." },
    { w: "sleep", t: "спать", ex: "Cats sleep a lot." },
    { w: "school", t: "школа", ex: "The school is near my house." },
    { w: "sun", t: "солнце", ex: "The sun is bright today." },
    { w: "milk", t: "молоко", ex: "The cat drinks milk." },
    { w: "book", t: "книга", ex: "This book is interesting." },
    { w: "door", t: "дверь", ex: "Please close the door." },
    { w: "cold", t: "холодный", ex: "The water is cold." },
    { w: "night", t: "ночь", ex: "I read at night." },
  ],
  A2: [
    { w: "weather", t: "погода", ex: "The weather is nice today." },
    { w: "holiday", t: "отпуск, праздник", ex: "We went to Spain on holiday." },
    { w: "breakfast", t: "завтрак", ex: "I have breakfast at 8 a.m." },
    { w: "expensive", t: "дорогой", ex: "This phone is too expensive." },
    { w: "cheap", t: "дешёвый", ex: "The tickets were quite cheap." },
    { w: "journey", t: "поездка, путешествие", ex: "The journey took three hours." },
    { w: "borrow", t: "одалживать (брать)", ex: "Can I borrow your pen?" },
    { w: "arrive", t: "прибывать", ex: "The train arrives at noon." },
    { w: "dangerous", t: "опасный", ex: "It is dangerous to swim here." },
    { w: "famous", t: "знаменитый", ex: "She is a famous singer." },
    { w: "healthy", t: "здоровый, полезный", ex: "Vegetables are healthy food." },
    { w: "hungry", t: "голодный", ex: "I'm hungry — let's eat!" },
    { w: "invite", t: "приглашать", ex: "They invited us to the party." },
    { w: "luggage", t: "багаж", ex: "My luggage is very heavy." },
    { w: "neighbour", t: "сосед", ex: "Our neighbour has two cats." },
    { w: "promise", t: "обещать, обещание", ex: "I promise to call you." },
    { w: "quiet", t: "тихий", ex: "The library is a quiet place." },
    { w: "share", t: "делиться", ex: "Let's share this pizza." },
    { w: "terrible", t: "ужасный", ex: "The traffic was terrible." },
    { w: "weekend", t: "выходные", ex: "What are you doing this weekend?" },
  ],
  B1: [
    { w: "achieve", t: "достигать", ex: "You can achieve your goals." },
    { w: "advantage", t: "преимущество", ex: "Speaking English is a big advantage." },
    { w: "avoid", t: "избегать", ex: "Try to avoid mistakes." },
    { w: "behaviour", t: "поведение", ex: "His behaviour surprised everyone." },
    { w: "confident", t: "уверенный", ex: "Be confident at the interview." },
    { w: "decrease", t: "уменьшаться", ex: "Prices decreased last month." },
    { w: "environment", t: "окружающая среда", ex: "We must protect the environment." },
    { w: "experience", t: "опыт", ex: "She has a lot of work experience." },
    { w: "improve", t: "улучшать", ex: "I want to improve my English." },
    { w: "income", t: "доход", ex: "His income grew this year." },
    { w: "opportunity", t: "возможность", ex: "This is a great opportunity." },
    { w: "persuade", t: "убеждать", ex: "She persuaded me to join." },
    { w: "pollution", t: "загрязнение", ex: "Air pollution is a serious problem." },
    { w: "predict", t: "предсказывать", ex: "Nobody can predict the future." },
    { w: "purpose", t: "цель, назначение", ex: "What is the purpose of this trip?" },
    { w: "reliable", t: "надёжный", ex: "He is a reliable partner." },
    { w: "solution", t: "решение", ex: "We found a simple solution." },
    { w: "although", t: "хотя", ex: "Although it rained, we went out." },
    { w: "definitely", t: "определённо", ex: "I will definitely come." },
    { w: "curious", t: "любопытный", ex: "Cats are curious animals." },
  ],
  B2: [
    { w: "accomplish", t: "выполнять, добиваться", ex: "We accomplished the task on time." },
    { w: "ambiguous", t: "двусмысленный", ex: "His answer was ambiguous." },
    { w: "anticipate", t: "предвидеть, ожидать", ex: "We anticipate some problems." },
    { w: "assess", t: "оценивать", ex: "Teachers assess students' progress." },
    { w: "comprehensive", t: "всеобъемлющий", ex: "The report is comprehensive." },
    { w: "controversy", t: "полемика, спор", ex: "The law caused controversy." },
    { w: "deliberately", t: "намеренно", ex: "He deliberately ignored me." },
    { w: "distinguish", t: "различать", ex: "Can you distinguish these accents?" },
    { w: "emphasize", t: "подчёркивать", ex: "She emphasized the main idea." },
    { w: "inevitable", t: "неизбежный", ex: "Change is inevitable." },
    { w: "negotiate", t: "вести переговоры", ex: "They negotiated a new contract." },
    { w: "perceive", t: "воспринимать", ex: "People perceive colors differently." },
    { w: "reluctant", t: "неохотный", ex: "He was reluctant to answer." },
    { w: "significant", t: "значительный", ex: "There was a significant change." },
    { w: "subtle", t: "тонкий, едва заметный", ex: "There is a subtle difference." },
    { w: "sustain", t: "поддерживать", ex: "The land cannot sustain a city." },
    { w: "tremendous", t: "огромный", ex: "It was a tremendous success." },
    { w: "undermine", t: "подрывать", ex: "Doubts undermine confidence." },
    { w: "vague", t: "расплывчатый", ex: "His plans are still vague." },
    { w: "widespread", t: "широко распространённый", ex: "The rumor became widespread." },
  ],
  C1: [
    { w: "alleviate", t: "облегчать, смягчать", ex: "The medicine alleviates pain." },
    { w: "coherent", t: "связный, логичный", ex: "She gave a coherent explanation." },
    { w: "compelling", t: "убедительный, захватывающий", ex: "A compelling argument." },
    { w: "discrepancy", t: "расхождение", ex: "There is a discrepancy in the data." },
    { w: "feasible", t: "осуществимый", ex: "Is this plan feasible?" },
    { w: "meticulous", t: "дотошный, скрупулёзный", ex: "He is meticulous about details." },
    { w: "notorious", t: "печально известный", ex: "A notorious criminal." },
    { w: "plausible", t: "правдоподобный", ex: "A plausible excuse." },
    { w: "profound", t: "глубокий (о мысли)", ex: "A profound impact on society." },
    { w: "scrutiny", t: "тщательная проверка", ex: "The deal is under scrutiny." },
    { w: "tangible", t: "ощутимый, осязаемый", ex: "Tangible results." },
    { w: "ubiquitous", t: "вездесущий", ex: "Smartphones are ubiquitous." },
    { w: "versatile", t: "универсальный", ex: "A versatile tool." },
    { w: "advocate", t: "выступать за, защитник", ex: "She advocates for reform." },
    { w: "deteriorate", t: "ухудшаться", ex: "His health deteriorated." },
    { w: "intricate", t: "запутанный, сложный", ex: "An intricate pattern." },
    { w: "resilient", t: "стойкий, устойчивый", ex: "Children are resilient." },
    { w: "spontaneous", t: "спонтанный", ex: "A spontaneous decision." },
    { w: "paradigm", t: "парадигма, модель", ex: "A new paradigm in science." },
    { w: "endeavour", t: "попытка, начинание", ex: "A scientific endeavour." },
  ],
  C2: [
    { w: "capricious", t: "капризный, переменчивый", ex: "Capricious weather ruined the trip." },
    { w: "ephemeral", t: "мимолётный", ex: "Fame is often ephemeral." },
    { w: "gregarious", t: "общительный", ex: "A gregarious personality." },
    { w: "idiosyncrasy", t: "особенность, причуда", ex: "Everyone has their idiosyncrasies." },
    { w: "juxtaposition", t: "сопоставление", ex: "A juxtaposition of old and new." },
    { w: "magnanimous", t: "великодушный", ex: "A magnanimous gesture." },
    { w: "obfuscate", t: "запутывать, затемнять", ex: "Jargon can obfuscate meaning." },
    { w: "pernicious", t: "пагубный", ex: "A pernicious influence." },
    { w: "quintessential", t: "типичнейший, самый суть", ex: "The quintessential English village." },
    { w: "serendipity", t: "счастливая случайность", ex: "They met by pure serendipity." },
    { w: "taciturn", t: "неразговорчивый", ex: "A taciturn old man." },
    { w: "vicissitude", t: "превратность (судьбы)", ex: "The vicissitudes of life." },
    { w: "esoteric", t: "эзотерический, понятный немногим", ex: "An esoteric subject." },
    { w: "laconic", t: "лаконичный", ex: "A laconic reply." },
    { w: "zealous", t: "рьяный, усердный", ex: "A zealous supporter." },
    { w: "obsequious", t: "подобострастный", ex: "An obsequious waiter." },
  ],
};

const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Примерный прирост словарного запаса на каждом уровне
const LEVEL_VOCAB_SIZE = { A1: 500, A2: 500, B1: 1000, B2: 2000, C1: 4000, C2: 8000 };

const LEVEL_NAMES = {
  A1: "Начинающий",
  A2: "Элементарный",
  B1: "Средний",
  B2: "Выше среднего",
  C1: "Продвинутый",
  C2: "Свободное владение",
};
