// Словообразование — задания формата ОГЭ и ЕГЭ.
//
// В экзамене это выглядит так: предложение с пропуском, а справа от него
// ЗАГЛАВНЫМИ исходное слово. Нужно поставить его в правильную форму —
// сменить часть речи, добавить приставку или суффикс.
//
// Почему отдельным файлом, а не внутри words.js. Это не словарь: здесь
// у каждой записи есть предложение, исходное слово, ответ и разбор.
// Плюс файл грузится только тем, кто дошёл до этих упражнений
// (ensureWordForms в js/util.js), а это ещё 30 КБ.
//
// Поля записи:
//   s     предложение, пропуск обозначен ___
//   base  исходное слово (в интерфейсе показывается ЗАГЛАВНЫМИ)
//   a     правильный ответ
//   alt   другие принимаемые ответы (необязательно)
//   ru    перевод предложения — ученик должен понимать, что переводит
//   why   разбор: почему именно эта форма
//   lvl   A2 | B1 | B2
//   grp   тип преобразования — по нему собираются подборки
//
// ВАЖНО про ответы: сверка идёт без учёта регистра и лишних пробелов,
// но форма должна быть точной. Где допустимы два варианта (realise /
// realize), второй лежит в alt.

const WORD_FORMS = [

  // ---------- -er / -or: кто делает ----------
  { s: "My sister wants to be a ___ at a primary school.", base: "TEACH", a: "teacher",
    ru: "Моя сестра хочет быть учителем в начальной школе.",
    why: "Нужен человек по действию: teach (учить) + -er = teacher.", lvl: "A2", grp: "agent" },
  { s: "He is a famous ___ — you have seen him in three films.", base: "ACT", a: "actor",
    ru: "Он известный актёр — ты видел его в трёх фильмах.",
    why: "От глаголов на латинской основе деятель чаще на -or: act → actor.", lvl: "A2", grp: "agent" },
  { s: "Every ___ to the museum gets a free map.", base: "VISIT", a: "visitor",
    ru: "Каждый посетитель музея получает бесплатную карту.",
    why: "visit → visitor: тот, кто посещает.", lvl: "A2", grp: "agent" },
  { s: "The ___ of this book lives in Canada.", base: "WRITE", a: "writer",
    ru: "Автор этой книги живёт в Канаде.",
    why: "write → writer. Немая -e перед -er уходит.", lvl: "A2", grp: "agent" },
  { s: "She is the best ___ in our swimming club.", base: "SWIM", a: "swimmer",
    ru: "Она лучшая пловчиха в нашем клубе плавания.",
    why: "Короткий слог с одной гласной — согласная удваивается: swim → swimmer.", lvl: "B1", grp: "agent" },
  { s: "The ___ said the train would arrive at six.", base: "ANNOUNCE", a: "announcer",
    ru: "Диктор сказал, что поезд прибудет в шесть.",
    why: "announce → announcer, немая -e перед -er уходит.", lvl: "B2", grp: "agent" },
  { s: "A good ___ listens more than he speaks.", base: "LEAD", a: "leader",
    ru: "Хороший руководитель слушает больше, чем говорит.",
    why: "lead → leader: тот, кто ведёт.", lvl: "B1", grp: "agent" },
  { s: "The ___ of the company signed the letter herself.", base: "DIRECT", a: "director",
    ru: "Директор компании подписала письмо сама.",
    why: "direct → director, деятель на -or.", lvl: "B1", grp: "agent" },

  // ---------- -ist ----------
  { s: "My brother is an ___ and paints every weekend.", base: "ART", a: "artist",
    ru: "Мой брат художник и рисует каждые выходные.",
    why: "art → artist: занятие человека через -ist.", lvl: "A2", grp: "ist" },
  { s: "The ___ explained her experiment to the students.", base: "SCIENCE", a: "scientist",
    ru: "Учёная объяснила свой эксперимент студентам.",
    why: "science → scientist, конечная -ce меняется на -t перед -ist.", lvl: "B1", grp: "ist" },
  { s: "A ___ from the local paper asked me three questions.", base: "JOURNAL", a: "journalist",
    ru: "Журналист местной газеты задал мне три вопроса.",
    why: "journal → journalist.", lvl: "B1", grp: "ist" },
  { s: "The ___ played for two hours without a break.", base: "PIANO", a: "pianist",
    ru: "Пианист играл два часа без перерыва.",
    why: "piano → pianist, конечная -o уходит.", lvl: "B1", grp: "ist" },

  // ---------- -ment ----------
  { s: "The ___ of the new park took two years.", base: "DEVELOP", a: "development",
    ru: "Строительство нового парка заняло два года.",
    why: "После артикля нужно существительное: develop + -ment.", lvl: "B1", grp: "ment" },
  { s: "We came to an ___ after a long talk.", base: "AGREE", a: "agreement",
    ru: "Мы пришли к соглашению после долгого разговора.",
    why: "agree → agreement: -ment превращает глагол в существительное.", lvl: "B1", grp: "ment" },
  { s: "His ___ was clear: finish the work by Friday.", base: "ARGUE", a: "argument",
    ru: "Его довод был ясен: закончить работу к пятнице.",
    why: "argue → argument. Внимание: немая -e здесь исчезает.", lvl: "B2", grp: "ment" },
  { s: "The film was pure ___ — nothing to think about.", base: "ENTERTAIN", a: "entertainment",
    ru: "Фильм был чистым развлечением — думать не о чем.",
    why: "entertain → entertainment.", lvl: "B2", grp: "ment" },
  { s: "Her ___ in the school play was a surprise to us.", base: "INVOLVE", a: "involvement",
    ru: "Её участие в школьном спектакле было для нас неожиданностью.",
    why: "involve → involvement, немая -e сохраняется.", lvl: "B2", grp: "ment" },
  { s: "Read the ___ before you switch the machine on.", base: "INSTRUCT", a: "instructions",
    alt: ["instruction"],
    ru: "Прочитай инструкцию, прежде чем включать машину.",
    why: "instruct → instruction. Здесь чаще множественное: instructions.", lvl: "B1", grp: "tion" },

  // ---------- -tion / -sion / -ation ----------
  { s: "___ is free in our country until the age of eighteen.", base: "EDUCATE", a: "education",
    ru: "Образование в нашей стране бесплатное до восемнадцати лет.",
    why: "educate → education: -ate меняется на -ation.", lvl: "B1", grp: "tion" },
  { s: "The ___ was difficult, but she made it quickly.", base: "DECIDE", a: "decision",
    ru: "Решение было трудным, но она приняла его быстро.",
    why: "decide → decision: -de переходит в -sion.", lvl: "B1", grp: "tion" },
  { s: "Thank you for the ___ to your birthday party.", base: "INVITE", a: "invitation",
    ru: "Спасибо за приглашение на твой день рождения.",
    why: "invite → invitation.", lvl: "A2", grp: "tion" },
  { s: "The ___ of the city is about two million.", base: "POPULATE", a: "population",
    ru: "Население города — около двух миллионов.",
    why: "populate → population.", lvl: "B1", grp: "tion" },
  { s: "His ___ of the rules was completely wrong.", base: "EXPLAIN", a: "explanation",
    ru: "Его объяснение правил было совершенно неверным.",
    why: "explain → explanation: -ai- сокращается до -a-.", lvl: "B1", grp: "tion" },
  { s: "We need more ___ before we can answer.", base: "INFORM", a: "information",
    ru: "Нам нужно больше информации, прежде чем мы сможем ответить.",
    why: "inform → information. Слово неисчисляемое: без -s.", lvl: "A2", grp: "tion" },
  { s: "The ___ between the two schools started last year.", base: "COMPETE", a: "competition",
    ru: "Соревнование между двумя школами началось в прошлом году.",
    why: "compete → competition.", lvl: "B1", grp: "tion" },
  { s: "Her ___ to the team made everyone happier.", base: "ADD", a: "addition",
    ru: "Её появление в команде обрадовало всех.",
    why: "add → addition.", lvl: "B2", grp: "tion" },
  { s: "The ___ of the film takes place in Paris.", base: "ACT", a: "action",
    ru: "Действие фильма происходит в Париже.",
    why: "act → action.", lvl: "A2", grp: "tion" },
  { s: "There was no ___ from the audience at all.", base: "REACT", a: "reaction",
    ru: "От зала не было вообще никакой реакции.",
    why: "react → reaction.", lvl: "B1", grp: "tion" },

  // ---------- -ness ----------
  { s: "Her ___ was clear from the first minute.", base: "HAPPY", a: "happiness",
    ru: "Её счастье было заметно с первой минуты.",
    why: "happy → happiness: -y после согласной переходит в -i-.", lvl: "A2", grp: "ness" },
  { s: "In the ___ I could not find the door.", base: "DARK", a: "darkness",
    ru: "В темноте я не смог найти дверь.",
    why: "dark → darkness: прилагательное становится существительным.", lvl: "A2", grp: "ness" },
  { s: "His ___ kept him at home for a week.", base: "ILL", a: "illness",
    ru: "Болезнь продержала его дома неделю.",
    why: "ill → illness.", lvl: "B1", grp: "ness" },
  { s: "Thank you for your ___ — I will not forget it.", base: "KIND", a: "kindness",
    ru: "Спасибо за твою доброту — я этого не забуду.",
    why: "kind → kindness.", lvl: "A2", grp: "ness" },
  { s: "The ___ of the mountain surprised the climbers.", base: "STEEP", a: "steepness",
    ru: "Крутизна горы удивила альпинистов.",
    why: "steep → steepness.", lvl: "B2", grp: "ness" },
  { s: "I admire her ___ in difficult moments.", base: "CALM", a: "calmness",
    ru: "Я восхищаюсь её спокойствием в трудные минуты.",
    why: "calm → calmness.", lvl: "B1", grp: "ness" },

  // ---------- -ity ----------
  { s: "There is a ___ that it will rain tomorrow.", base: "POSSIBLE", a: "possibility",
    ru: "Есть вероятность, что завтра пойдёт дождь.",
    why: "possible → possibility: -le меняется на -ility.", lvl: "B1", grp: "ity" },
  { s: "Physical ___ is important at any age.", base: "ACTIVE", a: "activity",
    ru: "Физическая активность важна в любом возрасте.",
    why: "active → activity.", lvl: "B1", grp: "ity" },
  { s: "The ___ of this song surprised even the singer.", base: "POPULAR", a: "popularity",
    ru: "Популярность этой песни удивила даже певца.",
    why: "popular → popularity.", lvl: "B1", grp: "ity" },
  { s: "Everyone has the ___ to learn a language.", base: "ABLE", a: "ability",
    ru: "У каждого есть способность выучить язык.",
    why: "able → ability.", lvl: "B1", grp: "ity" },
  { s: "The ___ of the water here is very good.", base: "PURE", a: "purity",
    ru: "Чистота воды здесь очень хорошая.",
    why: "pure → purity.", lvl: "B2", grp: "ity" },

  // ---------- -ance / -ence ----------
  { s: "The ___ of sleep is often forgotten.", base: "IMPORTANT", a: "importance",
    ru: "О важности сна часто забывают.",
    why: "important → importance: -ant меняется на -ance.", lvl: "B1", grp: "ance" },
  { s: "I see no ___ between these two answers.", base: "DIFFERENT", a: "difference",
    ru: "Я не вижу разницы между этими двумя ответами.",
    why: "different → difference: -ent меняется на -ence.", lvl: "A2", grp: "ance" },
  { s: "Her ___ at the meeting was noticed by everybody.", base: "PRESENT", a: "presence",
    ru: "Её присутствие на встрече заметили все.",
    why: "present → presence.", lvl: "B2", grp: "ance" },
  { s: "The ___ from home to school is two kilometres.", base: "DISTANT", a: "distance",
    ru: "Расстояние от дома до школы — два километра.",
    why: "distant → distance.", lvl: "A2", grp: "ance" },
  { s: "Thank you for your ___ with the heavy bags.", base: "ASSIST", a: "assistance",
    ru: "Спасибо за помощь с тяжёлыми сумками.",
    why: "assist → assistance.", lvl: "B2", grp: "ance" },

  // ---------- -ful ----------
  { s: "Be ___ — the plate is very hot.", base: "CARE", a: "careful",
    ru: "Будь осторожен — тарелка очень горячая.",
    why: "care + -ful = «полный чего-то»: careful.", lvl: "A2", grp: "ful" },
  { s: "This map will be ___ on your trip.", base: "USE", a: "useful",
    ru: "Эта карта будет полезна в твоей поездке.",
    why: "use → useful.", lvl: "A2", grp: "ful" },
  { s: "The garden looked ___ in the morning light.", base: "BEAUTY", a: "beautiful",
    ru: "Сад выглядел прекрасно в утреннем свете.",
    why: "beauty → beautiful: -y переходит в -i-.", lvl: "A2", grp: "ful" },
  { s: "She was ___ to everyone who helped her.", base: "THANK", a: "thankful",
    ru: "Она была благодарна всем, кто ей помог.",
    why: "thank → thankful.", lvl: "B1", grp: "ful" },
  { s: "It was a ___ day — nothing went wrong.", base: "PEACE", a: "peaceful",
    ru: "Это был спокойный день — ничего не пошло не так.",
    why: "peace → peaceful.", lvl: "B1", grp: "ful" },
  { s: "The dog is ___ of thunder.", base: "FEAR", a: "fearful",
    ru: "Собака боится грома.",
    why: "fear → fearful.", lvl: "B2", grp: "ful" },

  // ---------- -less ----------
  { s: "This old phone is ___ — it does not switch on.", base: "USE", a: "useless",
    ru: "Этот старый телефон бесполезен — он не включается.",
    why: "use + -less = «без чего-то»: useless.", lvl: "A2", grp: "less" },
  { s: "He was ___ and broke the window.", base: "CARE", a: "careless",
    ru: "Он был невнимателен и разбил окно.",
    why: "care → careless: суффикс -less отнимает качество.", lvl: "A2", grp: "less" },
  { s: "The night was ___ and very quiet.", base: "CLOUD", a: "cloudless",
    ru: "Ночь была безоблачной и очень тихой.",
    why: "cloud → cloudless.", lvl: "B1", grp: "less" },
  { s: "Do not be ___ — everything can be fixed.", base: "HOPE", a: "hopeless",
    ru: "Не отчаивайся — всё можно исправить.",
    why: "hope → hopeless.", lvl: "B1", grp: "less" },
  { s: "The task turned out to be ___ — nobody needed it.", base: "POINT", a: "pointless",
    ru: "Задание оказалось бессмысленным — оно никому не понадобилось.",
    why: "point → pointless.", lvl: "B2", grp: "less" },

  // ---------- -able / -ible ----------
  { s: "This chair is not very ___ for long work.", base: "COMFORT", a: "comfortable",
    ru: "Этот стул не очень удобен для долгой работы.",
    why: "comfort → comfortable.", lvl: "B1", grp: "able" },
  { s: "Your writing is not ___ — please write bigger.", base: "READ", a: "readable",
    ru: "Твой почерк неразборчив — пиши крупнее, пожалуйста.",
    why: "read → readable: «который можно прочитать».", lvl: "B1", grp: "able" },
  { s: "He is a ___ friend — he never lets me down.", base: "RELY", a: "reliable",
    ru: "Он надёжный друг — он никогда меня не подводит.",
    why: "rely → reliable: -y переходит в -i-.", lvl: "B1", grp: "able" },
  { s: "The teacher is ___ for thirty students.", base: "RESPONSE", a: "responsible",
    ru: "Учитель отвечает за тридцать учеников.",
    why: "response → responsible — исключение, суффикс -ible.", lvl: "B1", grp: "able" },
  { s: "The change was hardly ___ to the eye.", base: "NOTICE", a: "noticeable",
    ru: "Изменение было едва заметно глазу.",
    why: "notice → noticeable: -e сохраняется, чтобы c читалась как [s].", lvl: "B2", grp: "able" },

  // ---------- -ous ----------
  { s: "Swimming here is ___ — the current is strong.", base: "DANGER", a: "dangerous",
    ru: "Плавать здесь опасно — течение сильное.",
    why: "danger → dangerous.", lvl: "A2", grp: "ous" },
  { s: "She became ___ after her first film.", base: "FAME", a: "famous",
    ru: "Она стала знаменитой после первого фильма.",
    why: "fame → famous: немая -e уходит.", lvl: "A2", grp: "ous" },
  { s: "He is very ___ about his little brother.", base: "NERVE", a: "nervous",
    ru: "Он очень переживает за младшего брата.",
    why: "nerve → nervous.", lvl: "B1", grp: "ous" },
  { s: "Be ___ about the dog — it does not know you.", base: "CAUTION", a: "cautious",
    ru: "Будь осторожен с собакой — она тебя не знает.",
    why: "caution → cautious.", lvl: "B2", grp: "ous" },
  { s: "The trip was full of ___ moments.", base: "HUMOUR", a: "humorous",
    ru: "Поездка была полна забавных моментов.",
    why: "humour → humorous: -our сокращается до -or-.", lvl: "B2", grp: "ous" },

  // ---------- -ive ----------
  { s: "She has a very ___ mind — always new ideas.", base: "CREATE", a: "creative",
    ru: "У неё очень творческий ум — всегда новые идеи.",
    why: "create → creative.", lvl: "B1", grp: "ive" },
  { s: "Try to be more ___ during the lesson.", base: "ACT", a: "active",
    ru: "Постарайся быть активнее на уроке.",
    why: "act → active.", lvl: "A2", grp: "ive" },
  { s: "This method is more ___ than the old one.", base: "EFFECT", a: "effective",
    ru: "Этот метод эффективнее старого.",
    why: "effect → effective.", lvl: "B1", grp: "ive" },
  { s: "The medicine had a ___ effect on his health.", base: "PROTECT", a: "protective",
    ru: "Лекарство оказало защитное действие на его здоровье.",
    why: "protect → protective.", lvl: "B2", grp: "ive" },
  { s: "He gave a very ___ answer — too many details.", base: "DESCRIBE", a: "descriptive",
    ru: "Он дал очень описательный ответ — слишком много подробностей.",
    why: "describe → descriptive: -be меняется на -ptive.", lvl: "B2", grp: "ive" },

  // ---------- -al ----------
  { s: "This is a ___ way to keep food fresh.", base: "NATURE", a: "natural",
    ru: "Это естественный способ сохранить еду свежей.",
    why: "nature → natural: немая -e уходит.", lvl: "B1", grp: "al" },
  { s: "She goes to a ___ school and plays the violin.", base: "MUSIC", a: "musical",
    ru: "Она ходит в музыкальную школу и играет на скрипке.",
    why: "music → musical.", lvl: "A2", grp: "al" },
  { s: "The ___ museum is next to the park.", base: "HISTORY", a: "historical",
    ru: "Исторический музей находится рядом с парком.",
    why: "history → historical.", lvl: "B1", grp: "al" },
  { s: "It was a ___ mistake, not a serious one.", base: "PERSON", a: "personal",
    ru: "Это была личная ошибка, не серьёзная.",
    why: "person → personal.", lvl: "B1", grp: "al" },
  { s: "The ___ team won the championship.", base: "NATION", a: "national",
    ru: "Национальная сборная выиграла чемпионат.",
    why: "nation → national.", lvl: "B1", grp: "al" },

  // ---------- -y ----------
  { s: "It was a ___ day, so we stayed at home.", base: "RAIN", a: "rainy",
    ru: "День был дождливый, поэтому мы остались дома.",
    why: "rain → rainy.", lvl: "A2", grp: "y" },
  { s: "The weather is ___ today — take your hat.", base: "SUN", a: "sunny",
    ru: "Погода сегодня солнечная — возьми шляпу.",
    why: "sun → sunny: короткий слог, согласная удваивается.", lvl: "A2", grp: "y" },
  { s: "The room was ___ after the party.", base: "DIRT", a: "dirty",
    ru: "Комната была грязной после вечеринки.",
    why: "dirt → dirty.", lvl: "A2", grp: "y" },
  { s: "The street was too ___ to talk on the phone.", base: "NOISE", a: "noisy",
    ru: "На улице было слишком шумно, чтобы говорить по телефону.",
    why: "noise → noisy: немая -e уходит.", lvl: "B1", grp: "y" },

  // ---------- -ly (наречия) ----------
  { s: "He answered the question ___ and sat down.", base: "QUICK", a: "quickly",
    ru: "Он быстро ответил на вопрос и сел.",
    why: "Действие описывает наречие: quick → quickly.", lvl: "A2", grp: "ly" },
  { s: "She looked at the map ___ before choosing.", base: "CAREFUL", a: "carefully",
    ru: "Она внимательно посмотрела на карту, прежде чем выбрать.",
    why: "careful → carefully.", lvl: "A2", grp: "ly" },
  { s: "The dog ran ___ across the road.", base: "SUDDEN", a: "suddenly",
    ru: "Собака внезапно перебежала дорогу.",
    why: "sudden → suddenly.", lvl: "B1", grp: "ly" },
  { s: "He speaks English ___ well for his age.", base: "SURPRISE", a: "surprisingly",
    ru: "Он говорит по-английски удивительно хорошо для своего возраста.",
    why: "surprise → surprising → surprisingly.", lvl: "B2", grp: "ly" },
  { s: "___ , nobody was hurt in the accident.", base: "LUCK", a: "luckily",
    ru: "К счастью, в аварии никто не пострадал.",
    why: "luck → lucky → luckily: -y переходит в -i-.", lvl: "B1", grp: "ly" },
  { s: "The child slept ___ all night.", base: "PEACE", a: "peacefully",
    ru: "Ребёнок мирно спал всю ночь.",
    why: "peace → peaceful → peacefully.", lvl: "B1", grp: "ly" },

  // ---------- un- / in- / im- / dis- / ir- ----------
  { s: "She looked ___ after the bad news.", base: "HAPPY", a: "unhappy",
    ru: "Она выглядела несчастной после плохих новостей.",
    why: "Отрицание через un-: unhappy.", lvl: "A2", grp: "neg" },
  { s: "It is ___ to be in two places at once.", base: "POSSIBLE", a: "impossible",
    ru: "Невозможно быть в двух местах одновременно.",
    why: "Перед p, b, m ставится im-: impossible.", lvl: "B1", grp: "neg" },
  { s: "I ___ with you, and here is why.", base: "AGREE", a: "disagree",
    ru: "Я с тобой не согласен, и вот почему.",
    why: "Обратное действие через dis-: disagree.", lvl: "A2", grp: "neg" },
  { s: "His answer was ___ — it had nothing to do with the question.", base: "RELEVANT", a: "irrelevant",
    ru: "Его ответ был неуместен — он не имел отношения к вопросу.",
    why: "Перед r ставится ir-: irrelevant.", lvl: "B2", grp: "neg" },
  { s: "The information turned out to be ___ .", base: "CORRECT", a: "incorrect",
    ru: "Информация оказалась неверной.",
    why: "Перед c обычно in-: incorrect.", lvl: "B1", grp: "neg" },
  { s: "Do not be ___ — you can do this task.", base: "PATIENT", a: "impatient",
    ru: "Не будь нетерпеливым — ты справишься с этим заданием.",
    why: "Перед p ставится im-: impatient.", lvl: "B1", grp: "neg" },
  { s: "The old bridge is ___ for heavy trucks.", base: "SAFE", a: "unsafe",
    ru: "Старый мост небезопасен для тяжёлых грузовиков.",
    why: "safe → unsafe.", lvl: "B1", grp: "neg" },
  { s: "Snow in May is quite ___ for this region.", base: "USUAL", a: "unusual",
    ru: "Снег в мае довольно необычен для этого региона.",
    why: "usual → unusual.", lvl: "B1", grp: "neg" },

  // ---------- -en / -ise (глаголы) ----------
  { s: "They plan to ___ the road next summer.", base: "WIDE", a: "widen",
    ru: "Они планируют расширить дорогу следующим летом.",
    why: "Суффикс -en делает из прилагательного глагол: wide → widen.", lvl: "B2", grp: "verb" },
  { s: "Exercise helps to ___ your muscles.", base: "STRONG", a: "strengthen",
    ru: "Упражнения помогают укрепить мышцы.",
    why: "strong → strength → strengthen.", lvl: "B2", grp: "verb" },
  { s: "I did not ___ how late it was.", base: "REAL", a: "realise", alt: ["realize"],
    ru: "Я не осознавал, как поздно.",
    why: "real → realise. В американском варианте пишут realize — оба верны.", lvl: "B1", grp: "verb" },
  { s: "The sun will ___ the water in the pool by noon.", base: "WARM", a: "warm",
    ru: "К полудню солнце нагреет воду в бассейне.",
    why: "warm — и прилагательное, и глагол. Такие слова тоже спрашивают: "
       + "менять форму не нужно, нужно узнать, что менять нечего.", lvl: "B2", grp: "verb" },

  // ---------- неправильные пары ----------
  { s: "What is the ___ of this room?", base: "LONG", a: "length",
    ru: "Какова длина этой комнаты?",
    why: "long → length: гласная меняется, суффикс -th.", lvl: "B1", grp: "irr" },
  { s: "The ___ of the door is ninety centimetres.", base: "WIDE", a: "width",
    ru: "Ширина двери — девяносто сантиметров.",
    why: "wide → width.", lvl: "B1", grp: "irr" },
  { s: "His ___ is one metre eighty.", base: "HIGH", a: "height",
    ru: "Его рост — метр восемьдесят.",
    why: "high → height. Пишется через -eigh-.", lvl: "B1", grp: "irr" },
  { s: "She showed great ___ during the illness.", base: "STRONG", a: "strength",
    ru: "Она проявила большую силу во время болезни.",
    why: "strong → strength.", lvl: "B1", grp: "irr" },
  { s: "The ___ of the lake is about ten metres.", base: "DEEP", a: "depth",
    ru: "Глубина озера — около десяти метров.",
    why: "deep → depth.", lvl: "B2", grp: "irr" },

  // ---------- смешанные, на выбор части речи ----------
  { s: "The ___ of the experiment surprised everyone.", base: "SUCCEED", a: "success",
    ru: "Успех эксперимента всех удивил.",
    why: "succeed → success: перед артиклем нужно существительное.", lvl: "B1", grp: "mix" },
  { s: "He is a very ___ student.", base: "SUCCEED", a: "successful",
    ru: "Он очень успешный ученик.",
    why: "Перед существительным нужно прилагательное: successful.", lvl: "B1", grp: "mix" },
  { s: "She finished the task ___ .", base: "SUCCEED", a: "successfully",
    ru: "Она успешно завершила задание.",
    why: "Действие описывает наречие: successfully.", lvl: "B2", grp: "mix" },
  { s: "There is a big ___ between the two cities.", base: "DIFFER", a: "difference",
    ru: "Между двумя городами большая разница.",
    why: "differ → difference — существительное после артикля.", lvl: "B1", grp: "mix" },
  { s: "The two brothers are completely ___ .", base: "DIFFER", a: "different",
    ru: "Два брата совершенно разные.",
    why: "После глагола-связки нужно прилагательное: different.", lvl: "A2", grp: "mix" },
  { s: "Her ___ helped the whole team.", base: "DECIDE", a: "decision",
    ru: "Её решение помогло всей команде.",
    why: "decide → decision.", lvl: "B1", grp: "mix" },
  { s: "He is a ___ person — he knows what he wants.", base: "DECIDE", a: "decisive",
    ru: "Он решительный человек — он знает, чего хочет.",
    why: "decide → decisive, прилагательное.", lvl: "B2", grp: "mix" },
  { s: "The ___ of the room took all day.", base: "CLEAN", a: "cleaning",
    ru: "Уборка комнаты заняла весь день.",
    why: "Действие как существительное: -ing.", lvl: "B1", grp: "mix" },
  { s: "Nobody knew about his ___ to leave.", base: "DECIDE", a: "decision",
    ru: "Никто не знал о его решении уехать.",
    why: "После притяжательного местоимения нужно существительное.", lvl: "B1", grp: "mix" },
  { s: "This is the ___ book I have ever read.", base: "GOOD", a: "best",
    ru: "Это лучшая книга, которую я когда-либо читал.",
    why: "good → best: превосходная степень, форма неправильная.", lvl: "A2", grp: "mix" },
  { s: "Today the weather is ___ than yesterday.", base: "BAD", a: "worse",
    ru: "Сегодня погода хуже, чем вчера.",
    why: "bad → worse: сравнительная степень, форма неправильная.", lvl: "A2", grp: "mix" },
];
