// База слов по уровням CEFR.
// w — слово, t — перевод, ex — пример, exr — перевод примера,
// def — определение по-английски, cat — категория (для «лишнего» и сортировки).
const WORDS = {
  A1: [
    { w: "apple", t: "яблоко", ex: "I eat an apple every day.", exr: "Я ем яблоко каждый день.", def: "a round fruit with red or green skin", cat: "food" },
    { w: "water", t: "вода", ex: "Can I have some water, please?", exr: "Можно мне воды, пожалуйста?", def: "the clear liquid that we drink", cat: "food" },
    { w: "milk", t: "молоко", ex: "The cat drinks milk.", exr: "Кот пьёт молоко.", def: "a white drink that comes from cows", cat: "food" },
    { w: "food", t: "еда", ex: "The food here is very good.", exr: "Еда здесь очень хорошая.", def: "things that people and animals eat", cat: "food" },
    { w: "house", t: "дом", ex: "My house is small but cozy.", exr: "Мой дом маленький, но уютный.", def: "a building where people live", cat: "home" },
    { w: "door", t: "дверь", ex: "Please close the door.", exr: "Пожалуйста, закрой дверь.", def: "you open it to enter a room", cat: "home" },
    { w: "book", t: "книга", ex: "This book is interesting.", exr: "Эта книга интересная.", def: "pages with words that you read", cat: "objects" },
    { w: "school", t: "школа", ex: "The school is near my house.", exr: "Школа рядом с моим домом.", def: "a place where children learn", cat: "places" },
    { w: "sun", t: "солнце", ex: "The sun is bright today.", exr: "Солнце сегодня яркое.", def: "the star that gives us light and heat", cat: "nature" },
    { w: "night", t: "ночь", ex: "I read at night.", exr: "Я читаю по ночам.", def: "the dark time of the day", cat: "time" },
    { w: "morning", t: "утро", ex: "Good morning! How are you?", exr: "Доброе утро! Как дела?", def: "the early part of the day", cat: "time" },
    { w: "cold", t: "холодный", ex: "The water is cold.", exr: "Вода холодная.", def: "with a low temperature, not warm", cat: "qualities" },
    { w: "big", t: "большой", ex: "That is a big dog!", exr: "Вот это большая собака!", def: "large in size, not small", cat: "qualities" },
    { w: "small", t: "маленький", ex: "I live in a small town.", exr: "Я живу в маленьком городе.", def: "little in size, not big", cat: "qualities" },
    { w: "happy", t: "счастливый", ex: "She looks happy today.", exr: "Она сегодня выглядит счастливой.", def: "feeling good and smiling", cat: "feelings" },
    { w: "friend", t: "друг", ex: "He is my best friend.", exr: "Он мой лучший друг.", def: "a person you like and know well", cat: "people" },
    { w: "family", t: "семья", ex: "I love my family.", exr: "Я люблю свою семью.", def: "parents, children and relatives", cat: "people" },
    { w: "run", t: "бегать", ex: "I run in the park every morning.", exr: "Я бегаю в парке каждое утро.", def: "to move very fast on your legs", cat: "actions" },
    { w: "eat", t: "есть, кушать", ex: "We eat dinner at seven.", exr: "Мы ужинаем в семь.", def: "to put food in your mouth", cat: "actions" },
    { w: "sleep", t: "спать", ex: "Cats sleep a lot.", exr: "Кошки много спят.", def: "to rest with your eyes closed at night", cat: "actions" },
  ],
  A2: [
    { w: "weather", t: "погода", ex: "The weather is nice today.", exr: "Погода сегодня хорошая.", def: "sun, rain, wind and temperature outside", cat: "nature" },
    { w: "holiday", t: "отпуск, праздник", ex: "We went to Spain on holiday.", exr: "Мы ездили в отпуск в Испанию.", def: "time when you do not work and can travel", cat: "travel" },
    { w: "breakfast", t: "завтрак", ex: "I have breakfast at 8 a.m.", exr: "Я завтракаю в 8 утра.", def: "the meal you eat in the morning", cat: "food" },
    { w: "expensive", t: "дорогой", ex: "This phone is too expensive.", exr: "Этот телефон слишком дорогой.", def: "costing a lot of money", cat: "qualities" },
    { w: "cheap", t: "дешёвый", ex: "The tickets were quite cheap.", exr: "Билеты были довольно дешёвые.", def: "costing little money", cat: "qualities" },
    { w: "journey", t: "поездка, путешествие", ex: "The journey took three hours.", exr: "Поездка заняла три часа.", def: "travelling from one place to another", cat: "travel" },
    { w: "borrow", t: "одалживать (брать)", ex: "Can I borrow your pen?", exr: "Можно одолжить твою ручку?", def: "to take something and give it back later", cat: "actions" },
    { w: "arrive", t: "прибывать", ex: "The train arrives at noon.", exr: "Поезд прибывает в полдень.", def: "to get to a place", cat: "travel" },
    { w: "dangerous", t: "опасный", ex: "It is dangerous to swim here.", exr: "Здесь опасно плавать.", def: "able to hurt or harm you", cat: "qualities" },
    { w: "famous", t: "знаменитый", ex: "She is a famous singer.", exr: "Она знаменитая певица.", def: "known by many people", cat: "qualities" },
    { w: "healthy", t: "здоровый, полезный", ex: "Vegetables are healthy food.", exr: "Овощи — полезная еда.", def: "good for your body", cat: "qualities" },
    { w: "hungry", t: "голодный", ex: "I'm hungry — let's eat!", exr: "Я голоден — давай поедим!", def: "wanting to eat", cat: "feelings" },
    { w: "invite", t: "приглашать", ex: "They invited us to the party.", exr: "Они пригласили нас на вечеринку.", def: "to ask someone to come to an event", cat: "communication" },
    { w: "luggage", t: "багаж", ex: "My luggage is very heavy.", exr: "Мой багаж очень тяжёлый.", def: "bags you take when you travel", cat: "travel" },
    { w: "neighbour", t: "сосед", ex: "Our neighbour has two cats.", exr: "У нашего соседа два кота.", def: "a person who lives next to you", cat: "people" },
    { w: "promise", t: "обещать, обещание", ex: "I promise to call you.", exr: "Обещаю тебе позвонить.", def: "to say you will surely do something", cat: "communication" },
    { w: "quiet", t: "тихий", ex: "The library is a quiet place.", exr: "Библиотека — тихое место.", def: "with little or no noise", cat: "qualities" },
    { w: "share", t: "делиться", ex: "Let's share this pizza.", exr: "Давай разделим эту пиццу.", def: "to give a part of something to others", cat: "actions" },
    { w: "terrible", t: "ужасный", ex: "The traffic was terrible.", exr: "Пробки были ужасные.", def: "very bad", cat: "qualities" },
    { w: "weekend", t: "выходные", ex: "What are you doing this weekend?", exr: "Что ты делаешь в эти выходные?", def: "Saturday and Sunday", cat: "time" },
  ],
  B1: [
    { w: "achieve", t: "достигать", ex: "You can achieve your goals.", exr: "Ты можешь достичь своих целей.", def: "to succeed in doing something after effort", cat: "actions" },
    { w: "advantage", t: "преимущество", ex: "Speaking English is a big advantage.", exr: "Знание английского — большое преимущество.", def: "something that helps you be more successful", cat: "mind" },
    { w: "avoid", t: "избегать", ex: "Try to avoid mistakes.", exr: "Старайся избегать ошибок.", def: "to stay away from something", cat: "actions" },
    { w: "behaviour", t: "поведение", ex: "His behaviour surprised everyone.", exr: "Его поведение всех удивило.", def: "the way a person acts", cat: "character" },
    { w: "confident", t: "уверенный", ex: "Be confident at the interview.", exr: "Будь уверенным на собеседовании.", def: "sure about yourself and your abilities", cat: "character" },
    { w: "decrease", t: "уменьшаться", ex: "Prices decreased last month.", exr: "Цены снизились в прошлом месяце.", def: "to become smaller in number or size", cat: "change" },
    { w: "environment", t: "окружающая среда", ex: "We must protect the environment.", exr: "Мы должны защищать окружающую среду.", def: "the natural world around us", cat: "nature" },
    { w: "experience", t: "опыт", ex: "She has a lot of work experience.", exr: "У неё большой опыт работы.", def: "knowledge you get by doing things", cat: "mind" },
    { w: "improve", t: "улучшать", ex: "I want to improve my English.", exr: "Я хочу улучшить свой английский.", def: "to make something better", cat: "change" },
    { w: "income", t: "доход", ex: "His income grew this year.", exr: "Его доход вырос в этом году.", def: "money that you earn", cat: "money" },
    { w: "opportunity", t: "возможность", ex: "This is a great opportunity.", exr: "Это отличная возможность.", def: "a chance to do something good", cat: "mind" },
    { w: "persuade", t: "убеждать", ex: "She persuaded me to join.", exr: "Она убедила меня присоединиться.", def: "to make someone agree by giving reasons", cat: "communication" },
    { w: "pollution", t: "загрязнение", ex: "Air pollution is a serious problem.", exr: "Загрязнение воздуха — серьёзная проблема.", def: "dirty air, water or land", cat: "nature" },
    { w: "predict", t: "предсказывать", ex: "Nobody can predict the future.", exr: "Никто не может предсказать будущее.", def: "to say what will happen before it happens", cat: "mind" },
    { w: "purpose", t: "цель, назначение", ex: "What is the purpose of this trip?", exr: "Какова цель этой поездки?", def: "the reason why you do something", cat: "mind" },
    { w: "reliable", t: "надёжный", ex: "He is a reliable partner.", exr: "Он надёжный партнёр.", def: "someone you can trust and depend on", cat: "character" },
    { w: "solution", t: "решение", ex: "We found a simple solution.", exr: "Мы нашли простое решение.", def: "an answer to a problem", cat: "mind" },
    { w: "although", t: "хотя", ex: "Although it rained, we went out.", exr: "Хотя шёл дождь, мы пошли гулять.", def: "a word meaning 'despite the fact that'", cat: "linkers" },
    { w: "definitely", t: "определённо", ex: "I will definitely come.", exr: "Я определённо приду.", def: "certainly, without any doubt", cat: "linkers" },
    { w: "curious", t: "любопытный", ex: "Cats are curious animals.", exr: "Кошки — любопытные животные.", def: "wanting to know or learn things", cat: "character" },
  ],
  B2: [
    { w: "accomplish", t: "выполнять, добиваться", ex: "We accomplished the task on time.", exr: "Мы выполнили задачу вовремя.", def: "to finish something successfully", cat: "actions" },
    { w: "ambiguous", t: "двусмысленный", ex: "His answer was ambiguous.", exr: "Его ответ был двусмысленным.", def: "having more than one possible meaning", cat: "communication" },
    { w: "anticipate", t: "предвидеть, ожидать", ex: "We anticipate some problems.", exr: "Мы ожидаем некоторых проблем.", def: "to expect that something will happen", cat: "mind" },
    { w: "assess", t: "оценивать", ex: "Teachers assess students' progress.", exr: "Учителя оценивают прогресс учеников.", def: "to judge the quality or value of something", cat: "mind" },
    { w: "comprehensive", t: "всеобъемлющий", ex: "The report is comprehensive.", exr: "Отчёт всеобъемлющий.", def: "including everything that is needed", cat: "qualities" },
    { w: "controversy", t: "полемика, спор", ex: "The law caused controversy.", exr: "Закон вызвал полемику.", def: "a public disagreement about something", cat: "society" },
    { w: "deliberately", t: "намеренно", ex: "He deliberately ignored me.", exr: "Он намеренно игнорировал меня.", def: "done on purpose, not by accident", cat: "linkers" },
    { w: "distinguish", t: "различать", ex: "Can you distinguish these accents?", exr: "Ты можешь различить эти акценты?", def: "to see the difference between things", cat: "mind" },
    { w: "emphasize", t: "подчёркивать", ex: "She emphasized the main idea.", exr: "Она подчеркнула главную мысль.", def: "to show that something is important", cat: "communication" },
    { w: "inevitable", t: "неизбежный", ex: "Change is inevitable.", exr: "Перемены неизбежны.", def: "impossible to avoid or prevent", cat: "change" },
    { w: "negotiate", t: "вести переговоры", ex: "They negotiated a new contract.", exr: "Они договорились о новом контракте.", def: "to discuss in order to reach an agreement", cat: "communication" },
    { w: "perceive", t: "воспринимать", ex: "People perceive colors differently.", exr: "Люди воспринимают цвета по-разному.", def: "to notice or understand something", cat: "mind" },
    { w: "reluctant", t: "неохотный", ex: "He was reluctant to answer.", exr: "Он отвечал неохотно.", def: "not wanting to do something", cat: "character" },
    { w: "significant", t: "значительный", ex: "There was a significant change.", exr: "Произошло значительное изменение.", def: "large or important enough to matter", cat: "qualities" },
    { w: "subtle", t: "тонкий, едва заметный", ex: "There is a subtle difference.", exr: "Есть тонкое различие.", def: "not obvious, hard to notice", cat: "qualities" },
    { w: "sustain", t: "поддерживать", ex: "The land cannot sustain a city.", exr: "Эта земля не может прокормить город.", def: "to keep something going over time", cat: "change" },
    { w: "tremendous", t: "огромный", ex: "It was a tremendous success.", exr: "Это был огромный успех.", def: "extremely large or great", cat: "qualities" },
    { w: "undermine", t: "подрывать", ex: "Doubts undermine confidence.", exr: "Сомнения подрывают уверенность.", def: "to make something weaker step by step", cat: "change" },
    { w: "vague", t: "расплывчатый", ex: "His plans are still vague.", exr: "Его планы всё ещё расплывчаты.", def: "not clear or exact", cat: "communication" },
    { w: "widespread", t: "широко распространённый", ex: "The rumor became widespread.", exr: "Слух широко распространился.", def: "existing in many places or among many people", cat: "society" },
  ],
  C1: [
    { w: "alleviate", t: "облегчать, смягчать", ex: "The medicine alleviates pain.", exr: "Лекарство облегчает боль.", def: "to make pain or a problem less severe", cat: "change" },
    { w: "coherent", t: "связный, логичный", ex: "She gave a coherent explanation.", exr: "Она дала связное объяснение.", def: "clear, logical and well organized", cat: "communication" },
    { w: "compelling", t: "убедительный, захватывающий", ex: "A compelling argument.", exr: "Убедительный аргумент.", def: "so strong or interesting you cannot ignore it", cat: "communication" },
    { w: "discrepancy", t: "расхождение", ex: "There is a discrepancy in the data.", exr: "В данных есть расхождение.", def: "a difference between things that should match", cat: "mind" },
    { w: "feasible", t: "осуществимый", ex: "Is this plan feasible?", exr: "Этот план осуществим?", def: "possible to do or achieve", cat: "mind" },
    { w: "meticulous", t: "дотошный, скрупулёзный", ex: "He is meticulous about details.", exr: "Он дотошен в деталях.", def: "very careful and precise", cat: "character" },
    { w: "notorious", t: "печально известный", ex: "A notorious criminal.", exr: "Печально известный преступник.", def: "famous for something bad", cat: "character" },
    { w: "plausible", t: "правдоподобный", ex: "A plausible excuse.", exr: "Правдоподобное оправдание.", def: "seeming likely to be true", cat: "mind" },
    { w: "profound", t: "глубокий (о мысли)", ex: "A profound impact on society.", exr: "Глубокое влияние на общество.", def: "very deep, strong or serious", cat: "qualities" },
    { w: "scrutiny", t: "тщательная проверка", ex: "The deal is under scrutiny.", exr: "Сделка находится под пристальным вниманием.", def: "careful and detailed examination", cat: "society" },
    { w: "tangible", t: "ощутимый, осязаемый", ex: "Tangible results.", exr: "Ощутимые результаты.", def: "real and possible to see, touch or measure", cat: "qualities" },
    { w: "ubiquitous", t: "вездесущий", ex: "Smartphones are ubiquitous.", exr: "Смартфоны повсюду.", def: "seeming to be everywhere", cat: "qualities" },
    { w: "versatile", t: "универсальный", ex: "A versatile tool.", exr: "Универсальный инструмент.", def: "useful for many different purposes", cat: "qualities" },
    { w: "advocate", t: "выступать за, защитник", ex: "She advocates for reform.", exr: "Она выступает за реформу.", def: "to publicly support an idea or plan", cat: "society" },
    { w: "deteriorate", t: "ухудшаться", ex: "His health deteriorated.", exr: "Его здоровье ухудшилось.", def: "to become worse over time", cat: "change" },
    { w: "intricate", t: "запутанный, сложный", ex: "An intricate pattern.", exr: "Замысловатый узор.", def: "very detailed and complicated", cat: "qualities" },
    { w: "resilient", t: "стойкий, устойчивый", ex: "Children are resilient.", exr: "Дети быстро восстанавливаются.", def: "able to recover quickly from difficulties", cat: "character" },
    { w: "spontaneous", t: "спонтанный", ex: "A spontaneous decision.", exr: "Спонтанное решение.", def: "done suddenly, without planning", cat: "character" },
    { w: "paradigm", t: "парадигма, модель", ex: "A new paradigm in science.", exr: "Новая парадигма в науке.", def: "a typical model or way of thinking", cat: "mind" },
    { w: "endeavour", t: "попытка, начинание", ex: "A scientific endeavour.", exr: "Научное начинание.", def: "a serious attempt to do something", cat: "actions" },
  ],
  C2: [
    { w: "capricious", t: "капризный, переменчивый", ex: "Capricious weather ruined the trip.", exr: "Переменчивая погода испортила поездку.", def: "changing suddenly without reason", cat: "character" },
    { w: "ephemeral", t: "мимолётный", ex: "Fame is often ephemeral.", exr: "Слава часто мимолётна.", def: "lasting for a very short time", cat: "time" },
    { w: "gregarious", t: "общительный", ex: "A gregarious personality.", exr: "Общительный характер.", def: "enjoying the company of other people", cat: "character" },
    { w: "idiosyncrasy", t: "особенность, причуда", ex: "Everyone has their idiosyncrasies.", exr: "У каждого свои причуды.", def: "an unusual habit typical of one person", cat: "character" },
    { w: "juxtaposition", t: "сопоставление", ex: "A juxtaposition of old and new.", exr: "Сопоставление старого и нового.", def: "placing things side by side to compare them", cat: "mind" },
    { w: "magnanimous", t: "великодушный", ex: "A magnanimous gesture.", exr: "Великодушный жест.", def: "generous and kind, especially to a rival", cat: "character" },
    { w: "obfuscate", t: "запутывать, затемнять", ex: "Jargon can obfuscate meaning.", exr: "Жаргон может затемнять смысл.", def: "to make something unclear on purpose", cat: "communication" },
    { w: "pernicious", t: "пагубный", ex: "A pernicious influence.", exr: "Пагубное влияние.", def: "very harmful, often in a hidden way", cat: "qualities" },
    { w: "quintessential", t: "типичнейший, воплощение", ex: "The quintessential English village.", exr: "Типичнейшая английская деревня.", def: "being a perfect example of something", cat: "qualities" },
    { w: "serendipity", t: "счастливая случайность", ex: "They met by pure serendipity.", exr: "Они встретились по счастливой случайности.", def: "finding something good by lucky chance", cat: "mind" },
    { w: "taciturn", t: "неразговорчивый", ex: "A taciturn old man.", exr: "Неразговорчивый старик.", def: "saying very little, quiet by nature", cat: "character" },
    { w: "vicissitude", t: "превратность (судьбы)", ex: "The vicissitudes of life.", exr: "Превратности жизни.", def: "an unexpected change in life or fortune", cat: "change" },
    { w: "esoteric", t: "понятный немногим", ex: "An esoteric subject.", exr: "Тема, понятная немногим.", def: "understood by only a small group of experts", cat: "mind" },
    { w: "laconic", t: "лаконичный", ex: "A laconic reply.", exr: "Лаконичный ответ.", def: "using very few words", cat: "communication" },
    { w: "zealous", t: "рьяный, усердный", ex: "A zealous supporter.", exr: "Рьяный сторонник.", def: "full of energy and enthusiasm for a cause", cat: "character" },
    { w: "obsequious", t: "подобострастный", ex: "An obsequious waiter.", exr: "Подобострастный официант.", def: "too eager to please or obey someone", cat: "character" },
  ],
};

const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Примерный прирост словарного запаса на каждом уровне
const LEVEL_VOCAB_SIZE = { A1: 500, A2: 500, B1: 1000, B2: 2000, C1: 4000, C2: 8000 };

const LEVEL_NAMES = {
  A1: "Начинающий",
  A2: "Элементарный",
  B1: "Средний",
  B2: "Выше среднего",
  C1: "Продвинутый",
  C2: "Свободное владение",
};

const CATEGORY_NAMES = {
  food: "Еда", home: "Дом", objects: "Вещи", places: "Места", nature: "Природа",
  time: "Время", qualities: "Качества", feelings: "Чувства", people: "Люди",
  actions: "Действия", travel: "Дорога и отдых", communication: "Общение",
  mind: "Мышление", character: "Характер", change: "Изменения",
  money: "Деньги и работа", society: "Общество", linkers: "Слова-связки",
};

// Устойчивые сочетания (Collocation Matching) — пары подобраны так,
// чтобы перекрёстные комбинации были ошибочными
const COLLOCATIONS = [
  { h: "make", tl: "a decision" },
  { h: "do", tl: "homework" },
  { h: "take", tl: "a photo" },
  { h: "have", tl: "breakfast" },
  { h: "pay", tl: "attention" },
  { h: "tell", tl: "the truth" },
  { h: "keep", tl: "a secret" },
  { h: "catch", tl: "a cold" },
];

// Синонимы и антонимы
const SYNONYMS = [
  { w: "big", syn: "large", ant: "small" },
  { w: "happy", syn: "glad", ant: "sad" },
  { w: "cold", syn: "chilly", ant: "hot" },
  { w: "cheap", syn: "inexpensive", ant: "expensive" },
  { w: "dangerous", syn: "risky", ant: "safe" },
  { w: "famous", syn: "well-known", ant: "unknown" },
  { w: "quiet", syn: "silent", ant: "noisy" },
  { w: "terrible", syn: "awful", ant: "wonderful" },
  { w: "improve", syn: "get better", ant: "worsen" },
  { w: "reliable", syn: "dependable", ant: "unreliable" },
  { w: "significant", syn: "important", ant: "minor" },
  { w: "vague", syn: "unclear", ant: "precise" },
  { w: "tremendous", syn: "huge", ant: "tiny" },
  { w: "inevitable", syn: "unavoidable", ant: "avoidable" },
  { w: "feasible", syn: "doable", ant: "impossible" },
  { w: "meticulous", syn: "thorough", ant: "careless" },
  { w: "ubiquitous", syn: "everywhere", ant: "rare" },
  { w: "taciturn", syn: "reserved", ant: "talkative" },
  { w: "ephemeral", syn: "short-lived", ant: "permanent" },
  { w: "gregarious", syn: "sociable", ant: "shy" },
];
