// База слов по уровням CEFR.
// w — слово, t — перевод, ex — пример, exr — перевод примера,
// def — определение по-английски, cat — категория (для «лишнего» и сортировки).
const WORDS = {
  A1: [
    { w: "apple", t: "яблоко", ex: "I eat an apple every day.", exr: "Я ем яблоко каждый день.", def: "a round fruit with red or green skin", cat: "food" },
    { w: "water", t: "вода", ex: "Can I have some water, please?", exr: "Можно мне воды, пожалуйста?", def: "the clear liquid that we drink", cat: "food" },
    { w: "milk", t: "молоко", ex: "The cat drinks milk.", exr: "Кот пьёт молоко.", def: "a white drink that comes from cows", cat: "food" },
    { w: "food", t: "еда", ex: "The food here is very good.", exr: "Еда здесь очень хорошая.", def: "things that people and animals eat", cat: "food" },
    { w: "house", t: "дом", ex: "My house is small but cozy.", exr: "Мой дом маленький, но уютный.", def: "a building where people live", cat: "home" },
    { w: "door", t: "дверь", ex: "Please close the door.", exr: "Пожалуйста, закрой дверь.", def: "you open it to enter a room", cat: "home" },
    { w: "book", t: "книга", ex: "This book is interesting.", exr: "Эта книга интересная.", def: "pages with words that you read", cat: "objects" },
    { w: "school", t: "школа", ex: "The school is near my house.", exr: "Школа рядом с моим домом.", def: "a place where children learn", cat: "places" },
    { w: "sun", t: "солнце", ex: "The sun is bright today.", exr: "Солнце сегодня яркое.", def: "the star that gives us light and heat", cat: "nature" },
    { w: "night", t: "ночь", ex: "I read at night.", exr: "Я читаю по ночам.", def: "the dark time of the day", cat: "time" },
    { w: "morning", t: "утро", ex: "Good morning! How are you?", exr: "Доброе утро! Как дела?", def: "the early part of the day", cat: "time" },
    { w: "cold", t: "холодный", ex: "The water is cold.", exr: "Вода холодная.", def: "with a low temperature, not warm", cat: "qualities" },
    { w: "big", t: "большой", ex: "That is a big dog!", exr: "Вот это большая собака!", def: "large in size, not small", cat: "qualities" },
    { w: "small", t: "маленький", ex: "I live in a small town.", exr: "Я живу в маленьком городе.", def: "little in size, not big", cat: "qualities" },
    { w: "happy", t: "счастливый", ex: "She looks happy today.", exr: "Она сегодня выглядит счастливой.", def: "feeling good and smiling", cat: "feelings" },
    { w: "friend", t: "друг", ex: "He is my best friend.", exr: "Он мой лучший друг.", def: "a person you like and know well", cat: "people" },
    { w: "family", t: "семья", ex: "I love my family.", exr: "Я люблю свою семью.", def: "parents, children and relatives", cat: "people" },
    { w: "run", t: "бегать", ex: "I run in the park every morning.", exr: "Я бегаю в парке каждое утро.", def: "to move very fast on your legs", cat: "actions" },
    { w: "eat", t: "есть, кушать", ex: "We eat dinner at seven.", exr: "Мы ужинаем в семь.", def: "to put food in your mouth", cat: "actions" },
    { w: "sleep", t: "спать", ex: "Cats sleep a lot.", exr: "Кошки много спят.", def: "to rest with your eyes closed at night", cat: "actions" },
    { w: "bread", t: "хлеб", ex: "We buy fresh bread every morning.", exr: "Мы покупаем свежий хлеб каждое утро.", def: "food made from flour and baked", cat: "food" },
    { w: "egg", t: "яйцо", ex: "There is one egg left in the fridge.", exr: "В холодильнике осталось одно яйцо.", def: "round food that comes from birds", cat: "food" },
    { w: "cheese", t: "сыр", ex: "The mouse found a piece of cheese.", exr: "Мышь нашла кусочек сыра.", def: "yellow food made from milk", cat: "food" },
    { w: "tea", t: "чай", ex: "Grandma drinks tea with lemon.", exr: "Бабушка пьёт чай с лимоном.", def: "hot drink made with leaves and water", cat: "food" },
    { w: "banana", t: "банан", ex: "The monkey is eating a banana.", exr: "Обезьяна ест банан.", def: "long yellow fruit", cat: "food" },
    { w: "cake", t: "торт, пирожное", ex: "There are ten candles on the cake.", exr: "На торте десять свечей.", def: "sweet food for birthdays and parties", cat: "food" },
    { w: "meat", t: "мясо", ex: "My brother does not eat meat.", exr: "Мой брат не ест мясо.", def: "food that comes from animals", cat: "food" },
    { w: "rice", t: "рис", ex: "We had chicken with rice for dinner.", exr: "На ужин у нас была курица с рисом.", def: "small white grains you cook and eat", cat: "food" },
    { w: "soup", t: "суп", ex: "This soup is too hot to eat.", exr: "Этот суп слишком горячий, чтобы его есть.", def: "hot liquid food eaten with a spoon", cat: "food" },
    { w: "mother", t: "мама, мать", ex: "My mother works at a hospital.", exr: "Моя мама работает в больнице.", def: "woman who has a child", cat: "family" },
    { w: "father", t: "папа, отец", ex: "My father drives me to school.", exr: "Папа отвозит меня в школу.", def: "man who has a child", cat: "family" },
    { w: "sister", t: "сестра", ex: "My little sister is five years old.", exr: "Моей младшей сестре пять лет.", def: "girl with the same parents as you", cat: "family" },
    { w: "brother", t: "брат", ex: "My brother plays football every Sunday.", exr: "Мой брат играет в футбол каждое воскресенье.", def: "boy with the same parents as you", cat: "family" },
    { w: "baby", t: "малыш, младенец", ex: "The baby is sleeping, be quiet.", exr: "Малыш спит, веди себя тихо.", def: "very young child", cat: "family" },
    { w: "grandmother", t: "бабушка", ex: "My grandmother makes the best pies.", exr: "Моя бабушка печёт самые вкусные пироги.", def: "mother of your mother or father", cat: "family" },
    { w: "cat", t: "кот, кошка", ex: "Our cat sleeps on my bed.", exr: "Наш кот спит на моей кровати.", def: "small furry animal that says meow", cat: "animals" },
    { w: "dog", t: "собака", ex: "The dog runs after the ball.", exr: "Собака бежит за мячом.", def: "animal that barks and helps people", cat: "animals" },
    { w: "bird", t: "птица", ex: "A bird is singing outside my window.", exr: "За моим окном поёт птица.", def: "animal with wings that can fly", cat: "animals" },
    { w: "horse", t: "лошадь", ex: "I want to ride a horse someday.", exr: "Когда-нибудь я хочу покататься на лошади.", def: "big animal that people ride", cat: "animals" },
    { w: "cow", t: "корова", ex: "The cow gives us fresh milk.", exr: "Корова даёт нам свежее молоко.", def: "big farm animal that gives milk", cat: "animals" },
    { w: "fish", t: "рыба", ex: "Three fish swim in my aquarium.", exr: "В моём аквариуме плавают три рыбки.", def: "animal that lives and swims in water", cat: "animals" },
    { w: "rabbit", t: "кролик", ex: "A white rabbit ran into the grass.", exr: "Белый кролик убежал в траву.", def: "small animal with long ears", cat: "animals" },
    { w: "red", t: "красный", ex: "She is wearing a red dress.", exr: "На ней красное платье.", def: "colour of blood and tomatoes", cat: "qualities" },
    { w: "blue", t: "синий, голубой", ex: "The sky is blue today.", exr: "Небо сегодня голубое.", def: "colour of the clear sky", cat: "qualities" },
    { w: "green", t: "зелёный", ex: "My favourite colour is green.", exr: "Мой любимый цвет — зелёный.", def: "colour of grass and leaves", cat: "qualities" },
    { w: "yellow", t: "жёлтый", ex: "He drew a big yellow sun.", exr: "Он нарисовал большое жёлтое солнце.", def: "colour of lemons and the sun", cat: "qualities" },
    { w: "black", t: "чёрный", ex: "My cat is black with white paws.", exr: "Мой кот чёрный с белыми лапками.", def: "darkest colour, like night", cat: "qualities" },
    { w: "white", t: "белый", ex: "Snow is white and very cold.", exr: "Снег белый и очень холодный.", def: "colour of milk and snow", cat: "qualities" },
    { w: "good", t: "хороший", ex: "That was a really good film.", exr: "Это был по-настоящему хороший фильм.", def: "of high quality, not bad", cat: "qualities" },
    { w: "bad", t: "плохой", ex: "I had a bad day at school.", exr: "У меня был плохой день в школе.", def: "not good, not nice", cat: "qualities" },
    { w: "hot", t: "горячий, жаркий", ex: "Be careful, the tea is hot.", exr: "Осторожно, чай горячий.", def: "with a high temperature, not cold", cat: "qualities" },
    { w: "new", t: "новый", ex: "I got a new bike yesterday.", exr: "Вчера мне подарили новый велосипед.", def: "made or bought a short time ago", cat: "qualities" },
    { w: "one", t: "один", ex: "I have only one question.", exr: "У меня только один вопрос.", def: "number that comes before two", cat: "school" },
    { w: "two", t: "два", ex: "We have two dogs at home.", exr: "У нас дома две собаки.", def: "number that comes after one", cat: "school" },
    { w: "three", t: "три", ex: "The lesson starts in three minutes.", exr: "Урок начинается через три минуты.", def: "number between two and four", cat: "school" },
    { w: "five", t: "пять", ex: "Give me five more minutes, please.", exr: "Дай мне ещё пять минут, пожалуйста.", def: "number of fingers on one hand", cat: "school" },
    { w: "ten", t: "десять", ex: "Count from one to ten.", exr: "Посчитай от одного до десяти.", def: "number that comes after nine", cat: "school" },
    { w: "pen", t: "ручка", ex: "My pen does not write any more.", exr: "Моя ручка больше не пишет.", def: "you write with it using ink", cat: "school" },
    { w: "pencil", t: "карандаш", ex: "Draw the line with a pencil first.", exr: "Сначала начерти линию карандашом.", def: "thin wooden thing for writing and drawing", cat: "school" },
    { w: "teacher", t: "учитель", ex: "Our English teacher is very funny.", exr: "Наш учитель английского очень весёлый.", def: "person whose job is to teach", cat: "school" },
    { w: "ruler", t: "линейка", ex: "Draw a straight line with a ruler.", exr: "Начерти прямую линию линейкой.", def: "flat thing for measuring and drawing lines", cat: "school" },
    { w: "hand", t: "рука, кисть руки", ex: "He raised his hand to answer.", exr: "Он поднял руку, чтобы ответить.", def: "part of your body with five fingers", cat: "body" },
    { w: "leg", t: "нога", ex: "My leg hurts after the long walk.", exr: "У меня болит нога после долгой прогулки.", def: "part of your body for walking", cat: "body" },
    { w: "foot", t: "ступня", ex: "I hurt my foot playing football.", exr: "Я повредил ступню, играя в футбол.", def: "part of your body inside a shoe", cat: "body" },
    { w: "nose", t: "нос", ex: "The cat touched my nose with its paw.", exr: "Кот тронул мой нос лапой.", def: "part of your face for smelling", cat: "body" },
    { w: "ear", t: "ухо", ex: "My ear hurts when I swim.", exr: "У меня болит ухо, когда я плаваю.", def: "part of your body for hearing", cat: "body" },
    { w: "mouth", t: "рот", ex: "Do not talk with a full mouth.", exr: "Не разговаривай с полным ртом.", def: "part of your face for eating and speaking", cat: "body" },
    { w: "tooth", t: "зуб", ex: "My little brother lost a tooth today.", exr: "Мой младший брат сегодня потерял зуб.", def: "hard white thing inside your mouth", cat: "body" },
    { w: "shirt", t: "рубашка", ex: "Dad is ironing his white shirt.", exr: "Папа гладит свою белую рубашку.", def: "clothes for the top of your body", cat: "clothes" },
    { w: "shoe", t: "ботинок, туфля", ex: "I cannot find my other shoe.", exr: "Я не могу найти второй ботинок.", def: "you wear it on your foot", cat: "clothes" },
    { w: "hat", t: "шапка, шляпа", ex: "Put on a hat, it is cold.", exr: "Надень шапку, на улице холодно.", def: "you wear it on your head", cat: "clothes" },
    { w: "dress", t: "платье", ex: "She bought a long blue dress.", exr: "Она купила длинное синее платье.", def: "one-piece clothes that women wear", cat: "clothes" },
    { w: "coat", t: "пальто", ex: "Hang your coat on the hook.", exr: "Повесь пальто на крючок.", def: "warm clothes you wear outside", cat: "clothes" },
    { w: "sock", t: "носок", ex: "One sock is always missing.", exr: "Один носок вечно куда-то пропадает.", def: "soft thing you wear inside a shoe", cat: "clothes" },
    { w: "chair", t: "стул", ex: "Pull your chair closer to the table.", exr: "Придвинь стул поближе к столу.", def: "you sit on it", cat: "home" },
    { w: "bed", t: "кровать", ex: "Make your bed before you leave.", exr: "Заправь кровать, прежде чем уйти.", def: "you sleep on it at night", cat: "home" },
    { w: "window", t: "окно", ex: "Open the window, it is hot here.", exr: "Открой окно, здесь жарко.", def: "glass opening in a wall", cat: "home" },
    { w: "kitchen", t: "кухня", ex: "Mum is cooking in the kitchen.", exr: "Мама готовит на кухне.", def: "room where people cook food", cat: "home" },
    { w: "key", t: "ключ", ex: "I lost the key to my flat.", exr: "Я потерял ключ от квартиры.", def: "small metal thing that opens locks", cat: "objects" },
    { w: "rain", t: "дождь", ex: "We stayed home because of the rain.", exr: "Мы остались дома из-за дождя.", def: "water that falls from clouds", cat: "weather" },
    { w: "snow", t: "снег", ex: "Snow covered the whole garden last night.", exr: "Ночью снег засыпал весь сад.", def: "soft white water that falls in winter", cat: "weather" },
    { w: "wind", t: "ветер", ex: "The wind took my hat away.", exr: "Ветер унёс мою шапку.", def: "air that moves outside", cat: "weather" },
    { w: "cloud", t: "облако, туча", ex: "A grey cloud is coming this way.", exr: "Серая туча движется сюда.", def: "white or grey shape in the sky", cat: "weather" },
    { w: "tree", t: "дерево", ex: "A bird built a nest in our tree.", exr: "Птица свила гнездо на нашем дереве.", def: "tall plant with a trunk and leaves", cat: "nature" },
    { w: "flower", t: "цветок", ex: "He gave his mum a yellow flower.", exr: "Он подарил маме жёлтый цветок.", def: "colourful part of a plant", cat: "nature" },
    { w: "sea", t: "море", ex: "We swim in the sea every summer.", exr: "Каждое лето мы купаемся в море.", def: "very big area of salty water", cat: "nature" },
    { w: "mountain", t: "гора", ex: "There is snow on the mountain.", exr: "На горе лежит снег.", def: "very high hill of rock", cat: "nature" },
    { w: "walk", t: "ходить пешком, гулять", ex: "I walk to school every day.", exr: "Я хожу в школу пешком каждый день.", def: "to move slowly on your legs", cat: "actions" },
    { w: "swim", t: "плавать", ex: "Can you swim without any help?", exr: "Ты умеешь плавать без посторонней помощи?", def: "to move through water with your body", cat: "actions" },
    { w: "jump", t: "прыгать", ex: "The cat can jump onto the table.", exr: "Кот умеет запрыгивать на стол.", def: "to push yourself up into the air", cat: "actions" },
    { w: "sit", t: "сидеть, садиться", ex: "Come and sit next to me.", exr: "Иди сюда и сядь рядом со мной.", def: "to rest on a chair", cat: "actions" },
    { w: "stand", t: "стоять", ex: "We had to stand on the bus.", exr: "Нам пришлось стоять в автобусе.", def: "to be on your feet", cat: "actions" },
    { w: "write", t: "писать", ex: "Write your name at the top.", exr: "Напиши своё имя сверху.", def: "to make words with a pen", cat: "actions" },
    { w: "drink", t: "пить", ex: "You should drink more water.", exr: "Тебе стоит пить больше воды.", def: "to take liquid into your mouth", cat: "actions" },
    { w: "sing", t: "петь", ex: "We sing this song every lesson.", exr: "Мы поём эту песню на каждом уроке.", def: "to make music with your voice", cat: "actions" },
    { w: "dance", t: "танцевать", ex: "My sister loves to dance.", exr: "Моя сестра обожает танцевать.", def: "to move your body to music", cat: "actions" },
    { w: "sad", t: "грустный", ex: "Why do you look so sad?", exr: "Почему у тебя такой грустный вид?", def: "not happy, wanting to cry", cat: "feelings" },
    { w: "angry", t: "сердитый, злой", ex: "Dad was angry about the broken window.", exr: "Папа был сердит из-за разбитого окна.", def: "feeling very cross with someone", cat: "feelings" },
    { w: "tired", t: "уставший", ex: "I am too tired to study.", exr: "Я слишком устал, чтобы заниматься.", def: "needing to rest or sleep", cat: "feelings" },
    { w: "love", t: "любить", ex: "I love my dog very much.", exr: "Я очень люблю свою собаку.", def: "to like someone very much", cat: "feelings" },
  ],
  A2: [
    { w: "weather", t: "погода", ex: "The weather is nice today.", exr: "Погода сегодня хорошая.", def: "sun, rain, wind and temperature outside", cat: "nature" },
    { w: "holiday", t: "отпуск, праздник", ex: "We went to Spain on holiday.", exr: "Мы ездили в отпуск в Испанию.", def: "time when you do not work and can travel", cat: "travel" },
    { w: "breakfast", t: "завтрак", ex: "I have breakfast at 8 a.m.", exr: "Я завтракаю в 8 утра.", def: "the meal you eat in the morning", cat: "food" },
    { w: "expensive", t: "дорогой", ex: "This phone is too expensive.", exr: "Этот телефон слишком дорогой.", def: "costing a lot of money", cat: "qualities" },
    { w: "cheap", t: "дешёвый", ex: "The tickets were quite cheap.", exr: "Билеты были довольно дешёвые.", def: "costing little money", cat: "qualities" },
    { w: "journey", t: "поездка, путешествие", ex: "The journey took three hours.", exr: "Поездка заняла три часа.", def: "travelling from one place to another", cat: "travel" },
    { w: "borrow", t: "одалживать (брать)", ex: "Can I borrow your pen?", exr: "Можно одолжить твою ручку?", def: "to take something and give it back later", cat: "actions" },
    { w: "arrive", t: "прибывать", ex: "The train arrives at noon.", exr: "Поезд прибывает в полдень.", def: "to get to a place", cat: "travel" },
    { w: "dangerous", t: "опасный", ex: "It is dangerous to swim here.", exr: "Здесь опасно плавать.", def: "able to hurt or harm you", cat: "qualities" },
    { w: "famous", t: "знаменитый", ex: "She is a famous singer.", exr: "Она знаменитая певица.", def: "known by many people", cat: "qualities" },
    { w: "healthy", t: "здоровый, полезный", ex: "Vegetables are healthy food.", exr: "Овощи — полезная еда.", def: "good for your body", cat: "qualities" },
    { w: "hungry", t: "голодный", ex: "I'm hungry — let's eat!", exr: "Я голоден — давай поедим!", def: "wanting to eat", cat: "feelings" },
    { w: "invite", t: "приглашать", ex: "They invited us to the party.", exr: "Они пригласили нас на вечеринку.", def: "to ask someone to come to an event", cat: "communication" },
    { w: "luggage", t: "багаж", ex: "My luggage is very heavy.", exr: "Мой багаж очень тяжёлый.", def: "bags you take when you travel", cat: "travel" },
    { w: "neighbour", t: "сосед", ex: "Our neighbour has two cats.", exr: "У нашего соседа два кота.", def: "a person who lives next to you", cat: "people" },
    { w: "promise", t: "обещать, обещание", ex: "I promise to call you.", exr: "Обещаю тебе позвонить.", def: "to say you will surely do something", cat: "communication" },
    { w: "quiet", t: "тихий", ex: "The library is a quiet place.", exr: "Библиотека — тихое место.", def: "with little or no noise", cat: "qualities" },
    { w: "share", t: "делиться", ex: "Let's share this pizza.", exr: "Давай разделим эту пиццу.", def: "to give a part of something to others", cat: "actions" },
    { w: "terrible", t: "ужасный", ex: "The traffic was terrible.", exr: "Пробки были ужасные.", def: "very bad", cat: "qualities" },
    { w: "weekend", t: "выходные", ex: "What are you doing this weekend?", exr: "Что ты делаешь в эти выходные?", def: "Saturday and Sunday", cat: "time" },
    { w: "supermarket", t: "супермаркет", ex: "We buy fruit at the supermarket on Fridays.", exr: "Мы покупаем фрукты в супермаркете по пятницам.", def: "big shop that sells food and drinks", cat: "city" },
    { w: "receipt", t: "чек", ex: "Keep the receipt in case it breaks.", exr: "Сохрани чек на случай, если сломается.", def: "paper that shows what you paid", cat: "money" },
    { w: "price", t: "цена", ex: "The price of milk went up again.", exr: "Цена на молоко снова выросла.", def: "money you must pay for something", cat: "money" },
    { w: "spend", t: "тратить", ex: "Don't spend all your money on games.", exr: "Не трать все деньги на игры.", def: "to use money to buy things", cat: "money" },
    { w: "earn", t: "зарабатывать", ex: "You can earn money by washing cars.", exr: "Можно заработать деньги, моя машины.", def: "to get money for work you do", cat: "money" },
    { w: "wallet", t: "кошелёк", ex: "He left his wallet on the bus.", exr: "Он забыл кошелёк в автобусе.", def: "small flat case for money and cards", cat: "objects" },
    { w: "bank", t: "банк", ex: "The bank closes at six on Saturdays.", exr: "Банк закрывается в шесть по субботам.", def: "place where people keep their money", cat: "money" },
    { w: "ticket", t: "билет", ex: "She showed her ticket to the driver.", exr: "Она показала билет водителю.", def: "paper that lets you travel or enter", cat: "travel" },
    { w: "station", t: "станция, вокзал", ex: "Meet me at the station at seven.", exr: "Встретимся на вокзале в семь.", def: "place where trains stop for passengers", cat: "travel" },
    { w: "bicycle", t: "велосипед", ex: "My bicycle has a flat tyre again.", exr: "У моего велосипеда снова спустило колесо.", def: "vehicle with two wheels that you pedal", cat: "travel" },
    { w: "taxi", t: "такси", ex: "We took a taxi because of the rain.", exr: "Мы взяли такси из-за дождя.", def: "car with driver you pay to use", cat: "travel" },
    { w: "passenger", t: "пассажир", ex: "Every passenger must show a ticket.", exr: "Каждый пассажир должен показать билет.", def: "person travelling in a car, bus or plane", cat: "travel" },
    { w: "airport", t: "аэропорт", ex: "Our plane leaves from the old airport.", exr: "Наш самолёт вылетает из старого аэропорта.", def: "place where planes take off and land", cat: "travel" },
    { w: "traffic", t: "дорожное движение, пробки", ex: "There was heavy traffic on the bridge.", exr: "На мосту были большие пробки.", def: "cars and buses moving on the road", cat: "city" },
    { w: "seat", t: "место, сиденье", ex: "Is this seat free?", exr: "Это место свободно?", def: "place where you sit down", cat: "objects" },
    { w: "drive", t: "водить, вести машину", ex: "He learned to drive last summer.", exr: "Он научился водить прошлым летом.", def: "to make a car move and control it", cat: "actions" },
    { w: "bridge", t: "мост", ex: "We walked across the old wooden bridge.", exr: "Мы прошли по старому деревянному мосту.", def: "road built over a river or road", cat: "city" },
    { w: "road", t: "дорога", ex: "Look both ways before crossing the road.", exr: "Посмотри по сторонам, прежде чем переходить дорогу.", def: "hard way for cars between places", cat: "city" },
    { w: "building", t: "здание", ex: "Her office is in that tall building.", exr: "Её офис в том высоком здании.", def: "structure with walls and roof, like house", cat: "city" },
    { w: "museum", t: "музей", ex: "The museum is free on the first Sunday.", exr: "Музей бесплатный в первое воскресенье.", def: "place where you can see old interesting things", cat: "city" },
    { w: "hotel", t: "отель, гостиница", ex: "We stayed in a small hotel near the sea.", exr: "Мы жили в маленьком отеле у моря.", def: "building where travellers pay to sleep", cat: "travel" },
    { w: "hospital", t: "больница", ex: "Grandpa spent three days in hospital.", exr: "Дедушка провёл три дня в больнице.", def: "place where doctors help sick people", cat: "health" },
    { w: "headache", t: "головная боль", ex: "I have a bad headache today.", exr: "У меня сегодня сильно болит голова.", def: "pain inside your head", cat: "health" },
    { w: "temperature", t: "температура", ex: "The nurse took my temperature twice.", exr: "Медсестра дважды измерила мне температуру.", def: "how hot or cold something is", cat: "health" },
    { w: "ill", t: "больной", ex: "She was ill and missed the trip.", exr: "Она болела и пропустила поездку.", def: "not healthy, having a sickness", cat: "health" },
    { w: "heart", t: "сердце", ex: "My heart beats fast when I run.", exr: "Моё сердце быстро бьётся, когда я бегу.", def: "organ that pumps blood in your body", cat: "body" },
    { w: "nurse", t: "медсестра, медбрат", ex: "The nurse gave me a glass of water.", exr: "Медсестра дала мне стакан воды.", def: "person who cares for sick people", cat: "health" },
    { w: "jacket", t: "куртка, пиджак", ex: "Take a jacket — it's cold outside.", exr: "Возьми куртку — на улице холодно.", def: "short coat that you wear outside", cat: "clothes" },
    { w: "scarf", t: "шарф", ex: "She wrapped a warm scarf around her neck.", exr: "Она обмотала тёплый шарф вокруг шеи.", def: "long piece of cloth for your neck", cat: "clothes" },
    { w: "gloves", t: "перчатки", ex: "I can't find my gloves anywhere.", exr: "Я нигде не могу найти свои перчатки.", def: "things you wear to keep hands warm", cat: "clothes" },
    { w: "boots", t: "ботинки, сапоги", ex: "Wear your boots — the street is muddy.", exr: "Надень ботинки — на улице грязь.", def: "strong shoes that cover your ankles", cat: "clothes" },
    { w: "wear", t: "носить (одежду)", ex: "What are you going to wear tomorrow?", exr: "Что ты наденешь завтра?", def: "to have clothes on your body", cat: "actions" },
    { w: "guitar", t: "гитара", ex: "He plays the guitar in a school band.", exr: "Он играет на гитаре в школьной группе.", def: "music instrument with six strings", cat: "art" },
    { w: "paint", t: "рисовать красками", ex: "She likes to paint flowers and cats.", exr: "Она любит рисовать красками цветы и кошек.", def: "to make pictures with colours and brush", cat: "art" },
    { w: "draw", t: "рисовать (карандашом)", ex: "Can you draw a map for me?", exr: "Можешь нарисовать мне карту?", def: "to make pictures with pencil or pen", cat: "art" },
    { w: "win", t: "выигрывать", ex: "We can win if we play well.", exr: "Мы можем выиграть, если хорошо сыграем.", def: "to finish first or beat others", cat: "sports" },
    { w: "chess", t: "шахматы", ex: "Grandpa taught me to play chess.", exr: "Дедушка научил меня играть в шахматы.", def: "board game with kings and horses", cat: "sports" },
    { w: "fishing", t: "рыбалка", ex: "Dad goes fishing early on Sundays.", exr: "Папа ходит на рыбалку рано по воскресеньям.", def: "activity of catching fish for fun", cat: "sports" },
    { w: "gym", t: "спортзал", ex: "She goes to the gym twice a week.", exr: "Она ходит в спортзал два раза в неделю.", def: "place with machines for doing sport", cat: "sports" },
    { w: "alarm", t: "будильник", ex: "My alarm didn't ring this morning.", exr: "Мой будильник сегодня утром не прозвонил.", def: "clock or sound that wakes you up", cat: "time" },
    { w: "shower", t: "душ", ex: "I take a shower before breakfast.", exr: "Я принимаю душ перед завтраком.", def: "washing under water falling from above", cat: "home" },
    { w: "wash", t: "мыть, стирать", ex: "Wash your hands before you eat.", exr: "Помой руки перед едой.", def: "to clean something with water and soap", cat: "actions" },
    { w: "mirror", t: "зеркало", ex: "He looked in the mirror and smiled.", exr: "Он посмотрел в зеркало и улыбнулся.", def: "glass where you see yourself", cat: "home" },
    { w: "umbrella", t: "зонт", ex: "Take an umbrella, it may rain later.", exr: "Возьми зонт, позже может пойти дождь.", def: "thing you hold to stay dry", cat: "objects" },
    { w: "clock", t: "часы (настенные)", ex: "The clock in the kitchen is slow.", exr: "Часы на кухне отстают.", def: "machine on wall showing the time", cat: "objects" },
    { w: "cook", t: "готовить", ex: "I can cook soup and pasta.", exr: "Я умею готовить суп и макароны.", def: "to make food ready by heating", cat: "food" },
    { w: "lunch", t: "обед", ex: "We have lunch at half past one.", exr: "Мы обедаем в половине второго.", def: "meal you eat in the middle of day", cat: "food" },
    { w: "keyboard", t: "клавиатура", ex: "My keyboard is full of crumbs.", exr: "Моя клавиатура вся в крошках.", def: "part of computer with letter buttons", cat: "tech" },
    { w: "headphones", t: "наушники", ex: "He wears headphones on the bus every day.", exr: "Он каждый день едет в автобусе в наушниках.", def: "things you wear to listen to sound", cat: "tech" },
    { w: "camera", t: "фотоаппарат, камера", ex: "She took an old camera to the lake.", exr: "Она взяла на озеро старый фотоаппарат.", def: "machine for taking photos or video", cat: "tech" },
    { w: "battery", t: "батарея, аккумулятор", ex: "My phone battery died during the film.", exr: "У телефона села батарея во время фильма.", def: "thing that gives power to devices", cat: "tech" },
    { w: "message", t: "сообщение", ex: "Send me a message when you arrive.", exr: "Напиши мне сообщение, когда приедешь.", def: "short words you send to someone", cat: "communication" },
    { w: "afraid", t: "испуганный", ex: "My little sister is afraid of dogs.", exr: "Моя младшая сестра боится собак.", def: "feeling fear about something", cat: "feelings" },
    { w: "surprised", t: "удивлённый", ex: "We were surprised by his new haircut.", exr: "Мы удивились его новой стрижке.", def: "feeling something you did not expect", cat: "feelings" },
    { w: "worried", t: "обеспокоенный", ex: "Mum looks worried about the exam.", exr: "Мама выглядит обеспокоенной из-за экзамена.", def: "thinking that something bad may happen", cat: "feelings" },
    { w: "excited", t: "взволнованный, воодушевлённый", ex: "The kids are excited about the trip.", exr: "Дети в предвкушении поездки.", def: "very happy about something that will happen", cat: "feelings" },
    { w: "boring", t: "скучный", ex: "The film was long and really boring.", exr: "Фильм был длинным и очень скучным.", def: "not interesting at all", cat: "qualities" },
    { w: "lazy", t: "ленивый", ex: "My cat is too lazy to play.", exr: "Мой кот слишком ленивый, чтобы играть.", def: "not wanting to work or move", cat: "character" },
    { w: "polite", t: "вежливый", ex: "He is always polite to older people.", exr: "Он всегда вежлив со старшими.", def: "behaving in nice, respectful way", cat: "character" },
    { w: "funny", t: "смешной, забавный", ex: "Your story about the goat is funny.", exr: "Твоя история про козу смешная.", def: "making people laugh or smile", cat: "qualities" },
    { w: "cloudy", t: "облачный, пасмурный", ex: "It was cloudy all day yesterday.", exr: "Вчера весь день было пасмурно.", def: "with many clouds in the sky", cat: "weather" },
    { w: "storm", t: "гроза, буря", ex: "A storm broke the tree in our yard.", exr: "Гроза сломала дерево у нас во дворе.", def: "very bad weather with wind and rain", cat: "weather" },
    { w: "always", t: "всегда", ex: "She always drinks tea after dinner.", exr: "Она всегда пьёт чай после ужина.", def: "every time, at all times", cat: "linkers" },
    { w: "never", t: "никогда", ex: "I never eat fish for breakfast.", exr: "Я никогда не ем рыбу на завтрак.", def: "not at any time", cat: "linkers" },
    { w: "often", t: "часто", ex: "We often walk home through the park.", exr: "Мы часто идём домой через парк.", def: "many times, again and again", cat: "linkers" },
    { w: "sometimes", t: "иногда", ex: "Sometimes I forget my keys at home.", exr: "Иногда я забываю ключи дома.", def: "at some times, not always", cat: "linkers" },
    { w: "usually", t: "обычно", ex: "I usually get up at seven.", exr: "Обычно я встаю в семь.", def: "most of the time, as normal", cat: "linkers" },
    { w: "early", t: "рано, ранний", ex: "The bus came ten minutes early.", exr: "Автобус пришёл на десять минут раньше.", def: "before the usual or planned time", cat: "time" },
    { w: "late", t: "поздно, поздний", ex: "Sorry, I'm late — the bus broke down.", exr: "Извини, я опоздал — автобус сломался.", def: "after the usual or planned time", cat: "time" },
    { w: "busy", t: "занятой, занятый", ex: "She is busy with her homework now.", exr: "Она сейчас занята домашней работой.", def: "having many things to do", cat: "qualities" },
  ],
  B1: [
    { w: "achieve", t: "достигать", ex: "You can achieve your goals.", exr: "Ты можешь достичь своих целей.", def: "to succeed in doing something after effort", cat: "actions" },
    { w: "advantage", t: "преимущество", ex: "Speaking English is a big advantage.", exr: "Знание английского — большое преимущество.", def: "something that helps you be more successful", cat: "mind" },
    { w: "avoid", t: "избегать", ex: "Try to avoid mistakes.", exr: "Старайся избегать ошибок.", def: "to stay away from something", cat: "actions" },
    { w: "behaviour", t: "поведение", ex: "His behaviour surprised everyone.", exr: "Его поведение всех удивило.", def: "the way a person acts", cat: "character" },
    { w: "confident", t: "уверенный", ex: "Be confident at the interview.", exr: "Будь уверенным на собеседовании.", def: "sure about yourself and your abilities", cat: "character" },
    { w: "decrease", t: "уменьшаться", ex: "Prices decreased last month.", exr: "Цены снизились в прошлом месяце.", def: "to become smaller in number or size", cat: "change" },
    { w: "environment", t: "окружающая среда", ex: "We must protect the environment.", exr: "Мы должны защищать окружающую среду.", def: "the natural world around us", cat: "nature" },
    { w: "experience", t: "опыт", ex: "She has a lot of work experience.", exr: "У неё большой опыт работы.", def: "knowledge you get by doing things", cat: "mind" },
    { w: "improve", t: "улучшать", ex: "I want to improve my English.", exr: "Я хочу улучшить свой английский.", def: "to make something better", cat: "change" },
    { w: "income", t: "доход", ex: "His income grew this year.", exr: "Его доход вырос в этом году.", def: "money that you earn", cat: "money" },
    { w: "opportunity", t: "возможность", ex: "This is a great opportunity.", exr: "Это отличная возможность.", def: "a chance to do something good", cat: "mind" },
    { w: "persuade", t: "убеждать", ex: "She persuaded me to join.", exr: "Она убедила меня присоединиться.", def: "to make someone agree by giving reasons", cat: "communication" },
    { w: "pollution", t: "загрязнение", ex: "Air pollution is a serious problem.", exr: "Загрязнение воздуха — серьёзная проблема.", def: "dirty air, water or land", cat: "nature" },
    { w: "predict", t: "предсказывать", ex: "Nobody can predict the future.", exr: "Никто не может предсказать будущее.", def: "to say what will happen before it happens", cat: "mind" },
    { w: "purpose", t: "цель, назначение", ex: "What is the purpose of this trip?", exr: "Какова цель этой поездки?", def: "the reason why you do something", cat: "mind" },
    { w: "reliable", t: "надёжный", ex: "He is a reliable partner.", exr: "Он надёжный партнёр.", def: "someone you can trust and depend on", cat: "character" },
    { w: "solution", t: "решение", ex: "We found a simple solution.", exr: "Мы нашли простое решение.", def: "an answer to a problem", cat: "mind" },
    { w: "although", t: "хотя", ex: "Although it rained, we went out.", exr: "Хотя шёл дождь, мы пошли гулять.", def: "a word meaning 'despite the fact that'", cat: "linkers" },
    { w: "definitely", t: "определённо", ex: "I will definitely come.", exr: "Я определённо приду.", def: "certainly, without any doubt", cat: "linkers" },
    { w: "curious", t: "любопытный", ex: "Cats are curious animals.", exr: "Кошки — любопытные животные.", def: "wanting to know or learn things", cat: "character" },
    { w: "colleague", t: "коллега", ex: "A colleague of mine speaks five languages.", exr: "Один мой коллега говорит на пяти языках.", def: "someone who works with you", cat: "work" },
    { w: "employer", t: "работодатель", ex: "My employer lets us work from home on Fridays.", exr: "Мой работодатель разрешает нам по пятницам работать из дома.", def: "person or company that pays you to work", cat: "work" },
    { w: "salary", t: "зарплата", ex: "She left the job for a higher salary.", exr: "Она ушла с работы ради более высокой зарплаты.", def: "money you get regularly for your job", cat: "money" },
    { w: "apply", t: "подавать заявку, устраиваться", ex: "I'm applying for a summer job at the café.", exr: "Я устраиваюсь на летнюю работу в кафе.", def: "to ask officially for a job or place", cat: "work" },
    { w: "interview", t: "собеседование", ex: "The interview lasted only ten minutes.", exr: "Собеседование длилось всего десять минут.", def: "meeting where someone asks you questions for work", cat: "work" },
    { w: "career", t: "карьера", ex: "My sister is starting a career in medicine.", exr: "Моя сестра начинает карьеру в медицине.", def: "work you do over many years", cat: "work" },
    { w: "skill", t: "навык, умение", ex: "Cooking is a useful skill to have.", exr: "Умение готовить — полезный навык.", def: "ability to do something well", cat: "work" },
    { w: "deadline", t: "крайний срок", ex: "The deadline for the essay is Friday.", exr: "Крайний срок сдачи эссе — пятница.", def: "last time when work must be finished", cat: "work" },
    { w: "manage", t: "справляться, руководить", ex: "Somehow I managed to finish everything on time.", exr: "Как-то я умудрился закончить всё вовремя.", def: "to succeed in doing something difficult", cat: "work" },
    { w: "afford", t: "позволить себе (по деньгам)", ex: "We can't afford a new car this year.", exr: "В этом году мы не можем позволить себе новую машину.", def: "to have enough money for something", cat: "money" },
    { w: "degree", t: "диплом, учёная степень", ex: "She has a degree in computer science.", exr: "У неё диплом по информатике.", def: "qualification you get at university", cat: "school" },
    { w: "essay", t: "сочинение, эссе", ex: "I still haven't started my essay on Shakespeare.", exr: "Я до сих пор не начал сочинение о Шекспире.", def: "short piece of writing about one topic", cat: "school" },
    { w: "graduate", t: "оканчивать (учёбу)", ex: "My brother graduates from university in June.", exr: "Мой брат оканчивает университет в июне.", def: "to finish studies at school or university", cat: "school" },
    { w: "attend", t: "посещать (занятия)", ex: "Students must attend at least ten lectures.", exr: "Студенты обязаны посетить не меньше десяти лекций.", def: "to go to lessons or meetings", cat: "school" },
    { w: "progress", t: "прогресс, успехи", ex: "You're making real progress with your speaking.", exr: "Ты делаешь настоящие успехи в разговорной речи.", def: "movement forward or getting better", cat: "school" },
    { w: "knowledge", t: "знания", ex: "His knowledge of history really surprised me.", exr: "Его знание истории меня по-настоящему удивило.", def: "information you have learned and understand", cat: "mind" },
    { w: "concentrate", t: "сосредоточиться", ex: "I can't concentrate with the TV on.", exr: "Я не могу сосредоточиться, когда включён телевизор.", def: "to give all attention to one thing", cat: "mind" },
    { w: "memorize", t: "заучивать наизусть", ex: "We had to memorize the whole poem.", exr: "Нам пришлось выучить наизусть всё стихотворение.", def: "to learn something so you remember exactly", cat: "mind" },
    { w: "attitude", t: "отношение, настрой", ex: "A positive attitude helps in difficult times.", exr: "Позитивный настрой помогает в трудные времена.", def: "way you think and feel about something", cat: "mind" },
    { w: "realize", t: "осознавать, понимать", ex: "I suddenly realized I had left my keys inside.", exr: "Я вдруг понял, что оставил ключи внутри.", def: "to suddenly understand something", cat: "mind" },
    { w: "consider", t: "обдумывать, рассматривать", ex: "We're considering moving to another city.", exr: "Мы обдумываем переезд в другой город.", def: "to think carefully before deciding", cat: "mind" },
    { w: "doubt", t: "сомнение; сомневаться", ex: "I have serious doubts about his story.", exr: "У меня серьёзные сомнения насчёт его истории.", def: "feeling that something may not be true", cat: "mind" },
    { w: "schedule", t: "расписание, график", ex: "My schedule is completely full this week.", exr: "На этой неделе у меня совершенно забито расписание.", def: "plan showing when things will happen", cat: "time" },
    { w: "postpone", t: "откладывать (на потом)", ex: "They postponed the match because of rain.", exr: "Матч отложили из-за дождя.", def: "to move something to a later time", cat: "time" },
    { w: "arrange", t: "организовать, договориться", ex: "I've arranged to meet Anna after school.", exr: "Я договорился встретиться с Аней после школы.", def: "to plan and organize something in advance", cat: "actions" },
    { w: "deserve", t: "заслуживать", ex: "After all that work you deserve a break.", exr: "После всей этой работы ты заслуживаешь перерыв.", def: "to have earned something by your actions", cat: "actions" },
    { w: "suggest", t: "предлагать (идею)", ex: "She suggested taking the early train.", exr: "Она предложила поехать на раннем поезде.", def: "to tell someone your idea about something", cat: "communication" },
    { w: "complain", t: "жаловаться", ex: "He complains about the food every single day.", exr: "Он жалуется на еду каждый божий день.", def: "to say you are not happy", cat: "communication" },
    { w: "admit", t: "признавать", ex: "He admitted that he had broken the window.", exr: "Он признал, что разбил окно.", def: "to agree that something bad is true", cat: "communication" },
    { w: "apologize", t: "извиняться", ex: "You should apologize to your sister.", exr: "Тебе стоит извиниться перед сестрой.", def: "to say sorry for something", cat: "communication" },
    { w: "discuss", t: "обсуждать", ex: "We discussed the plan for over an hour.", exr: "Мы обсуждали план больше часа.", def: "to talk about something with others", cat: "communication" },
    { w: "argue", t: "спорить", ex: "My parents rarely argue about money.", exr: "Мои родители редко спорят из-за денег.", def: "to disagree with someone in words", cat: "communication" },
    { w: "remind", t: "напоминать", ex: "Remind me to buy bread on the way home.", exr: "Напомни мне купить хлеб по дороге домой.", def: "to make someone remember something", cat: "communication" },
    { w: "mention", t: "упоминать", ex: "She mentioned your name at dinner.", exr: "Она упомянула твоё имя за ужином.", def: "to say something quickly without details", cat: "communication" },
    { w: "however", t: "однако", ex: "The film was long; however, it was never boring.", exr: "Фильм был длинный, однако он ни разу не наскучил.", def: "word used to add an opposite idea", cat: "linkers" },
    { w: "therefore", t: "поэтому, следовательно", ex: "It was raining, therefore we stayed at home.", exr: "Шёл дождь, поэтому мы остались дома.", def: "for that reason, as a result", cat: "linkers" },
    { w: "instead", t: "вместо этого", ex: "Let's take the bus instead.", exr: "Давай вместо этого поедем на автобусе.", def: "in place of something else", cat: "linkers" },
    { w: "actually", t: "на самом деле", ex: "Actually, I've never been to London.", exr: "На самом деле я никогда не был в Лондоне.", def: "used to say what is really true", cat: "linkers" },
    { w: "eventually", t: "в конце концов", ex: "Eventually he found a job he really liked.", exr: "В конце концов он нашёл работу, которая ему по-настоящему нравилась.", def: "in the end, after a long time", cat: "linkers" },
    { w: "relationship", t: "отношения", ex: "They have a very close relationship.", exr: "У них очень близкие отношения.", def: "way two people connect and treat each other", cat: "people" },
    { w: "trust", t: "доверять; доверие", ex: "I trust her completely with my secrets.", exr: "Я полностью доверяю ей свои секреты.", def: "to believe someone is honest and safe", cat: "people" },
    { w: "support", t: "поддерживать; поддержка", ex: "My family supported me during the exams.", exr: "Семья поддерживала меня во время экзаменов.", def: "to help someone who needs it", cat: "people" },
    { w: "generous", t: "щедрый", ex: "He's so generous — he always pays for everyone.", exr: "Он такой щедрый — всегда за всех платит.", def: "happy to give money, time or help", cat: "character" },
    { w: "patient", t: "терпеливый", ex: "Be patient, the bus will come.", exr: "Потерпи, автобус придёт.", def: "able to wait calmly without anger", cat: "character" },
    { w: "selfish", t: "эгоистичный", ex: "It was selfish to take the last piece.", exr: "Было эгоистично взять последний кусок.", def: "caring only about yourself", cat: "character" },
    { w: "honest", t: "честный", ex: "Be honest — did you like the present?", exr: "Скажи честно: тебе понравился подарок?", def: "always telling the truth", cat: "character" },
    { w: "jealous", t: "ревнивый, завистливый", ex: "She was jealous of her friend's new phone.", exr: "Она завидовала новому телефону подруги.", def: "unhappy because someone has what you want", cat: "feelings" },
    { w: "embarrassed", t: "смущённый", ex: "I was so embarrassed when I forgot her name.", exr: "Мне было так неловко, когда я забыл её имя.", def: "feeling uncomfortable in front of other people", cat: "feelings" },
    { w: "disappointed", t: "разочарованный", ex: "We were disappointed by the ending of the film.", exr: "Мы были разочарованы концовкой фильма.", def: "sad because something was worse than expected", cat: "feelings" },
    { w: "proud", t: "гордый", ex: "My parents are proud of my results.", exr: "Родители гордятся моими результатами.", def: "pleased about something good you did", cat: "feelings" },
    { w: "lonely", t: "одинокий", ex: "He felt lonely in the new city.", exr: "Он чувствовал себя одиноко в новом городе.", def: "unhappy because you are alone", cat: "feelings" },
    { w: "device", t: "устройство", ex: "This device measures your heart rate.", exr: "Это устройство измеряет пульс.", def: "machine or tool made for one job", cat: "tech" },
    { w: "download", t: "скачивать", ex: "It took ages to download the film.", exr: "Фильм скачивался целую вечность.", def: "to copy files from the internet", cat: "tech" },
    { w: "software", t: "программное обеспечение", ex: "The school installed new software on every computer.", exr: "Школа установила новые программы на каждый компьютер.", def: "programs that make computers work", cat: "tech" },
    { w: "update", t: "обновлять; обновление", ex: "I keep forgetting to update the app.", exr: "Я всё время забываю обновить приложение.", def: "to add the newest version or information", cat: "tech" },
    { w: "charge", t: "заряжать", ex: "My phone died — I need to charge it.", exr: "Телефон сел, надо его зарядить.", def: "to put electricity into a battery", cat: "tech" },
    { w: "compete", t: "соревноваться", ex: "Twenty teams competed in the tournament.", exr: "В турнире соревновались двадцать команд.", def: "to try to win against others", cat: "sports" },
    { w: "coach", t: "тренер", ex: "Our coach makes us run every morning.", exr: "Наш тренер заставляет нас бегать каждое утро.", def: "person who trains a sports team", cat: "sports" },
    { w: "score", t: "забивать; счёт", ex: "He scored twice in the second half.", exr: "Он забил дважды во втором тайме.", def: "to get a point or goal", cat: "sports" },
    { w: "athlete", t: "спортсмен", ex: "Olympic athletes train six hours a day.", exr: "Олимпийские спортсмены тренируются по шесть часов в день.", def: "person who is very good at sport", cat: "sports" },
    { w: "injury", t: "травма", ex: "A knee injury kept him out of the game.", exr: "Травма колена не пустила его на игру.", def: "damage to your body from an accident", cat: "health" },
    { w: "exhausted", t: "измотанный", ex: "After eight hours of walking I was exhausted.", exr: "После восьми часов ходьбы я был вымотан.", def: "extremely tired with no energy left", cat: "health" },
    { w: "recycle", t: "перерабатывать (вторсырьё)", ex: "We recycle all our plastic bottles.", exr: "Мы сдаём на переработку все наши пластиковые бутылки.", def: "to use old materials to make new things", cat: "nature" },
    { w: "waste", t: "тратить впустую; отходы", ex: "Don't waste water while brushing your teeth.", exr: "Не трать зря воду, пока чистишь зубы.", def: "to use something badly or pointlessly", cat: "nature" },
    { w: "energy", t: "энергия", ex: "Wind and sun give us clean energy.", exr: "Ветер и солнце дают нам чистую энергию.", def: "power that makes machines and people work", cat: "nature" },
    { w: "climate", t: "климат", ex: "The climate here is mild and wet.", exr: "Климат здесь мягкий и влажный.", def: "usual weather of a place over years", cat: "weather" },
    { w: "protect", t: "защищать", ex: "Trees protect the soil from wind.", exr: "Деревья защищают почву от ветра.", def: "to keep someone or something safe", cat: "nature" },
    { w: "increase", t: "увеличиваться, расти", ex: "The number of students increased this year.", exr: "Число учеников в этом году выросло.", def: "to become bigger in number or size", cat: "change" },
  ],
  B2: [
    { w: "accomplish", t: "выполнять, добиваться", ex: "We accomplished the task on time.", exr: "Мы выполнили задачу вовремя.", def: "to finish something successfully", cat: "actions" },
    { w: "ambiguous", t: "двусмысленный", ex: "His answer was ambiguous.", exr: "Его ответ был двусмысленным.", def: "having more than one possible meaning", cat: "communication" },
    { w: "anticipate", t: "предвидеть, ожидать", ex: "We anticipate some problems.", exr: "Мы ожидаем некоторых проблем.", def: "to expect that something will happen", cat: "mind" },
    { w: "assess", t: "оценивать", ex: "Teachers assess students' progress.", exr: "Учителя оценивают прогресс учеников.", def: "to judge the quality or value of something", cat: "mind" },
    { w: "comprehensive", t: "всеобъемлющий", ex: "The report is comprehensive.", exr: "Отчёт всеобъемлющий.", def: "including everything that is needed", cat: "qualities" },
    { w: "controversy", t: "полемика, спор", ex: "The law caused controversy.", exr: "Закон вызвал полемику.", def: "a public disagreement about something", cat: "society" },
    { w: "deliberately", t: "намеренно", ex: "He deliberately ignored me.", exr: "Он намеренно игнорировал меня.", def: "done on purpose, not by accident", cat: "linkers" },
    { w: "distinguish", t: "различать", ex: "Can you distinguish these accents?", exr: "Ты можешь различить эти акценты?", def: "to see the difference between things", cat: "mind" },
    { w: "emphasize", t: "подчёркивать", ex: "She emphasized the main idea.", exr: "Она подчеркнула главную мысль.", def: "to show that something is important", cat: "communication" },
    { w: "inevitable", t: "неизбежный", ex: "Change is inevitable.", exr: "Перемены неизбежны.", def: "impossible to avoid or prevent", cat: "change" },
    { w: "negotiate", t: "вести переговоры", ex: "They negotiated a new contract.", exr: "Они договорились о новом контракте.", def: "to discuss in order to reach an agreement", cat: "communication" },
    { w: "perceive", t: "воспринимать", ex: "People perceive colors differently.", exr: "Люди воспринимают цвета по-разному.", def: "to notice or understand something", cat: "mind" },
    { w: "reluctant", t: "неохотный", ex: "He was reluctant to answer.", exr: "Он отвечал неохотно.", def: "not wanting to do something", cat: "character" },
    { w: "significant", t: "значительный", ex: "There was a significant change.", exr: "Произошло значительное изменение.", def: "large or important enough to matter", cat: "qualities" },
    { w: "subtle", t: "тонкий, едва заметный", ex: "There is a subtle difference.", exr: "Есть тонкое различие.", def: "not obvious, hard to notice", cat: "qualities" },
    { w: "sustain", t: "поддерживать", ex: "The land cannot sustain a city.", exr: "Эта земля не может прокормить город.", def: "to keep something going over time", cat: "change" },
    { w: "tremendous", t: "огромный", ex: "It was a tremendous success.", exr: "Это был огромный успех.", def: "extremely large or great", cat: "qualities" },
    { w: "undermine", t: "подрывать", ex: "Doubts undermine confidence.", exr: "Сомнения подрывают уверенность.", def: "to make something weaker step by step", cat: "change" },
    { w: "vague", t: "расплывчатый", ex: "His plans are still vague.", exr: "Его планы всё ещё расплывчаты.", def: "not clear or exact", cat: "communication" },
    { w: "widespread", t: "широко распространённый", ex: "The rumor became widespread.", exr: "Слух широко распространился.", def: "existing in many places or among many people", cat: "society" },
    { w: "justify", t: "оправдывать, обосновывать", ex: "Nothing can justify lying to your parents.", exr: "Ничто не может оправдать ложь родителям.", def: "to give a good reason for something", cat: "mind" },
    { w: "assume", t: "предполагать", ex: "Don't assume everyone agrees with you.", exr: "Не думай, что все с тобой согласны.", def: "to think something is true without proof", cat: "mind" },
    { w: "conclude", t: "делать вывод", ex: "The study concluded that sleep affects grades.", exr: "Исследование пришло к выводу, что сон влияет на оценки.", def: "to decide something after looking at facts", cat: "mind" },
    { w: "evidence", t: "доказательства", ex: "There is no evidence that the plan works.", exr: "Нет доказательств, что план работает.", def: "facts that show something is true", cat: "mind" },
    { w: "bias", t: "предвзятость", ex: "The article shows a clear bias against teenagers.", exr: "В статье видна явная предвзятость к подросткам.", def: "unfair opinion for or against someone", cat: "mind" },
    { w: "flaw", t: "изъян, недостаток", ex: "There is one serious flaw in your argument.", exr: "В твоём аргументе есть один серьёзный изъян.", def: "weak point that spoils something otherwise good", cat: "mind" },
    { w: "outcome", t: "итог, исход", ex: "The outcome of the vote surprised everyone.", exr: "Итог голосования всех удивил.", def: "final result of an action or event", cat: "mind" },
    { w: "analyse", t: "анализировать", ex: "We analysed the results for a whole week.", exr: "Мы анализировали результаты целую неделю.", def: "to study something carefully to understand it", cat: "mind" },
    { w: "estimate", t: "оценивать (приблизительно)", ex: "Scientists estimate the ice will melt by 2050.", exr: "По оценкам учёных, лёд растает к 2050 году.", def: "to guess an amount using what you know", cat: "mind" },
    { w: "phenomenon", t: "явление", ex: "Fake news is a worrying modern phenomenon.", exr: "Фейковые новости — тревожное явление нашего времени.", def: "something that happens and can be studied", cat: "mind" },
    { w: "observe", t: "наблюдать", ex: "She observed how the crowd reacted to the speech.", exr: "Она наблюдала, как толпа реагирует на речь.", def: "to watch carefully in order to learn", cat: "mind" },
    { w: "imply", t: "подразумевать, намекать", ex: "Are you implying that I copied the answers?", exr: "Ты намекаешь, что я списал ответы?", def: "to suggest something without saying it directly", cat: "communication" },
    { w: "contradict", t: "противоречить", ex: "His story contradicts the photos on his phone.", exr: "Его рассказ противоречит фотографиям в его телефоне.", def: "to say the opposite of something else", cat: "communication" },
    { w: "clarify", t: "прояснять, уточнять", ex: "Could you clarify what you mean by that?", exr: "Можешь уточнить, что ты этим хочешь сказать?", def: "to make something easier to understand", cat: "communication" },
    { w: "acknowledge", t: "признавать", ex: "He finally acknowledged that he was wrong.", exr: "Он наконец признал, что был неправ.", def: "to accept that something is true", cat: "communication" },
    { w: "claim", t: "утверждать", ex: "The company claims its product is completely safe.", exr: "Компания утверждает, что её продукт совершенно безопасен.", def: "to say something is true without proving it", cat: "communication" },
    { w: "summarize", t: "кратко излагать", ex: "Can you summarize the article in three sentences?", exr: "Можешь кратко изложить статью в трёх предложениях?", def: "to give main points in short form", cat: "communication" },
    { w: "outline", t: "обрисовать в общих чертах", ex: "The teacher outlined the plan for the term.", exr: "Учитель обрисовал план на четверть.", def: "to describe main ideas without the details", cat: "communication" },
    { w: "objection", t: "возражение", ex: "Does anyone have an objection to this idea?", exr: "У кого-нибудь есть возражения против этой идеи?", def: "reason why you disagree with something", cat: "communication" },
    { w: "consequently", t: "следовательно, вследствие этого", ex: "He missed the bus and consequently arrived late.", exr: "Он опоздал на автобус и вследствие этого пришёл поздно.", def: "as a result of what came before", cat: "linkers" },
    { w: "nevertheless", t: "тем не менее", ex: "The film was long; nevertheless, nobody left.", exr: "Фильм был длинный; тем не менее никто не ушёл.", def: "in spite of that, but still true", cat: "linkers" },
    { w: "moreover", t: "более того", ex: "The flat is cheap; moreover, it is near school.", exr: "Квартира дешёвая; более того, она рядом со школой.", def: "used to add one more supporting point", cat: "linkers" },
    { w: "whereas", t: "тогда как", ex: "My brother loves maths, whereas I prefer history.", exr: "Мой брат обожает математику, тогда как я предпочитаю историю.", def: "used to compare two different facts", cat: "linkers" },
    { w: "regardless", t: "независимо от, невзирая", ex: "We will go regardless of the weather.", exr: "Мы поедем независимо от погоды.", def: "without caring about what could stop you", cat: "linkers" },
    { w: "somewhat", t: "отчасти, довольно", ex: "The results were somewhat surprising.", exr: "Результаты оказались отчасти неожиданными.", def: "slightly, but not very much", cat: "linkers" },
    { w: "inequality", t: "неравенство", ex: "Inequality between rich and poor keeps growing.", exr: "Неравенство между богатыми и бедными продолжает расти.", def: "unfair difference between groups of people", cat: "society" },
    { w: "poverty", t: "бедность", ex: "Millions of people still live in poverty.", exr: "Миллионы людей всё ещё живут в бедности.", def: "state of being very poor", cat: "society" },
    { w: "discrimination", t: "дискриминация", ex: "The law bans discrimination at work.", exr: "Закон запрещает дискриминацию на работе.", def: "treating some people unfairly because they differ", cat: "society" },
    { w: "authority", t: "власть, органы власти", ex: "The local authorities closed the old bridge.", exr: "Местные власти закрыли старый мост.", def: "power to give orders and make decisions", cat: "society" },
    { w: "democracy", t: "демократия", ex: "In a democracy, people choose their leaders.", exr: "При демократии люди сами выбирают своих руководителей.", def: "system where people vote for their government", cat: "society" },
    { w: "campaign", t: "кампания", ex: "They started a campaign against plastic bags.", exr: "Они начали кампанию против пластиковых пакетов.", def: "planned actions to reach a political goal", cat: "society" },
    { w: "protest", t: "протест, протестовать", ex: "Students protested against the new school rules.", exr: "Ученики протестовали против новых школьных правил.", def: "to show publicly that you disagree", cat: "society" },
    { w: "reform", t: "реформа, реформировать", ex: "The government promised to reform education.", exr: "Правительство пообещало реформировать образование.", def: "to change a system to make it better", cat: "society" },
    { w: "welfare", t: "благополучие, соцобеспечение", ex: "The charity works for the welfare of children.", exr: "Фонд заботится о благополучии детей.", def: "health, comfort and support of people", cat: "society" },
    { w: "minority", t: "меньшинство", ex: "Only a small minority supported the idea.", exr: "Идею поддержало лишь небольшое меньшинство.", def: "smaller part of a larger group", cat: "society" },
    { w: "corruption", t: "коррупция", ex: "Corruption slows down the country's development.", exr: "Коррупция тормозит развитие страны.", def: "using power dishonestly for money or favours", cat: "society" },
    { w: "urban", t: "городской", ex: "Urban life is faster and much noisier.", exr: "Городская жизнь быстрее и намного шумнее.", def: "connected with towns and cities", cat: "city" },
    { w: "budget", t: "бюджет", ex: "Our family budget is tight this month.", exr: "В этом месяце наш семейный бюджет ограничен.", def: "plan of how much money you can spend", cat: "money" },
    { w: "investment", t: "вложение, инвестиция", ex: "Education is the best investment in your future.", exr: "Образование — лучшее вложение в твоё будущее.", def: "money put into something to gain more later", cat: "money" },
    { w: "profit", t: "прибыль", ex: "The café made a small profit last year.", exr: "Кафе получило небольшую прибыль в прошлом году.", def: "money left after all costs are paid", cat: "money" },
    { w: "debt", t: "долг", ex: "He is still paying off his student debt.", exr: "Он всё ещё выплачивает студенческий долг.", def: "money that you owe to someone", cat: "money" },
    { w: "wealth", t: "богатство", ex: "Wealth does not always bring happiness.", exr: "Богатство не всегда приносит счастье.", def: "large amount of money and property", cat: "money" },
    { w: "consumer", t: "потребитель", ex: "Consumers want clear information about products.", exr: "Потребители хотят ясной информации о товарах.", def: "person who buys and uses goods", cat: "money" },
    { w: "shortage", t: "нехватка, дефицит", ex: "There is a shortage of doctors in small towns.", exr: "В маленьких городах не хватает врачей.", def: "situation when there is not enough", cat: "money" },
    { w: "unemployment", t: "безработица", ex: "Unemployment fell for the third month in a row.", exr: "Безработица снижается третий месяц подряд.", def: "situation when people cannot find jobs", cat: "money" },
    { w: "wage", t: "заработная плата", ex: "The workers asked for a higher wage.", exr: "Рабочие попросили повысить зарплату.", def: "money paid regularly for work done", cat: "money" },
    { w: "currency", t: "валюта", ex: "The local currency lost value overnight.", exr: "Местная валюта обесценилась за одну ночь.", def: "money used in a particular country", cat: "money" },
    { w: "innovation", t: "нововведение, инновация", ex: "The company is famous for its innovations.", exr: "Компания знаменита своими нововведениями.", def: "new idea or method that changes things", cat: "tech" },
    { w: "breakthrough", t: "прорыв", ex: "Scientists made a breakthrough in battery technology.", exr: "Учёные совершили прорыв в технологии аккумуляторов.", def: "important discovery after a lot of effort", cat: "tech" },
    { w: "artificial", t: "искусственный", ex: "This drink is full of artificial flavours.", exr: "Этот напиток полон искусственных ароматизаторов.", def: "made by people, not by nature", cat: "qualities" },
    { w: "conduct", t: "проводить (исследование)", ex: "The team conducted a survey among teenagers.", exr: "Команда провела опрос среди подростков.", def: "to organize and carry out an activity", cat: "actions" },
    { w: "accurate", t: "точный", ex: "Her description of the man was surprisingly accurate.", exr: "Её описание мужчины оказалось на удивление точным.", def: "exactly right, without mistakes", cat: "qualities" },
    { w: "relevant", t: "уместный, относящийся к делу", ex: "Please keep your questions relevant to the topic.", exr: "Пожалуйста, задавайте вопросы, относящиеся к теме.", def: "connected with what is being discussed", cat: "qualities" },
    { w: "sufficient", t: "достаточный", ex: "We didn't have sufficient time to finish the test.", exr: "У нас не было достаточно времени, чтобы закончить тест.", def: "as much as is needed", cat: "qualities" },
    { w: "crucial", t: "решающий, крайне важный", ex: "The next two weeks are crucial for the project.", exr: "Следующие две недели решающие для проекта.", def: "extremely important for the final result", cat: "qualities" },
    { w: "beneficial", t: "полезный, благотворный", ex: "Walking every day is beneficial for your heart.", exr: "Ежедневные прогулки полезны для сердца.", def: "having a good effect on something", cat: "qualities" },
    { w: "moderate", t: "умеренный", ex: "The plan got moderate support in our class.", exr: "План получил умеренную поддержку в нашем классе.", def: "not too much and not too little", cat: "qualities" },
    { w: "diverse", t: "разнообразный", ex: "Our class is diverse: seven nationalities in one room.", exr: "Наш класс разнообразный: семь национальностей в одном кабинете.", def: "made of many different types", cat: "qualities" },
    { w: "gradual", t: "постепенный", ex: "There has been a gradual rise in prices.", exr: "Произошёл постепенный рост цен.", def: "happening slowly over a long time", cat: "change" },
    { w: "drastic", t: "резкий, радикальный", ex: "The city took drastic measures against traffic jams.", exr: "Город принял радикальные меры против пробок.", def: "extreme and sudden, with strong effect", cat: "change" },
  ],
  C1: [
    { w: "alleviate", t: "облегчать, смягчать", ex: "The medicine alleviates pain.", exr: "Лекарство облегчает боль.", def: "to make pain or a problem less severe", cat: "change" },
    { w: "coherent", t: "связный, логичный", ex: "She gave a coherent explanation.", exr: "Она дала связное объяснение.", def: "clear, logical and well organized", cat: "communication" },
    { w: "compelling", t: "убедительный, захватывающий", ex: "A compelling argument.", exr: "Убедительный аргумент.", def: "so strong or interesting you cannot ignore it", cat: "communication" },
    { w: "discrepancy", t: "расхождение", ex: "There is a discrepancy in the data.", exr: "В данных есть расхождение.", def: "a difference between things that should match", cat: "mind" },
    { w: "feasible", t: "осуществимый", ex: "Is this plan feasible?", exr: "Этот план осуществим?", def: "possible to do or achieve", cat: "mind" },
    { w: "meticulous", t: "дотошный, скрупулёзный", ex: "He is meticulous about details.", exr: "Он дотошен в деталях.", def: "very careful and precise", cat: "character" },
    { w: "notorious", t: "печально известный", ex: "A notorious criminal.", exr: "Печально известный преступник.", def: "famous for something bad", cat: "character" },
    { w: "plausible", t: "правдоподобный", ex: "A plausible excuse.", exr: "Правдоподобное оправдание.", def: "seeming likely to be true", cat: "mind" },
    { w: "profound", t: "глубокий (о мысли)", ex: "A profound impact on society.", exr: "Глубокое влияние на общество.", def: "very deep, strong or serious", cat: "qualities" },
    { w: "scrutiny", t: "тщательная проверка", ex: "The deal is under scrutiny.", exr: "Сделка находится под пристальным вниманием.", def: "careful and detailed examination", cat: "society" },
    { w: "tangible", t: "ощутимый, осязаемый", ex: "Tangible results.", exr: "Ощутимые результаты.", def: "real and possible to see, touch or measure", cat: "qualities" },
    { w: "ubiquitous", t: "вездесущий", ex: "Smartphones are ubiquitous.", exr: "Смартфоны повсюду.", def: "seeming to be everywhere", cat: "qualities" },
    { w: "versatile", t: "универсальный", ex: "A versatile tool.", exr: "Универсальный инструмент.", def: "useful for many different purposes", cat: "qualities" },
    { w: "advocate", t: "выступать за, защитник", ex: "She advocates for reform.", exr: "Она выступает за реформу.", def: "to publicly support an idea or plan", cat: "society" },
    { w: "deteriorate", t: "ухудшаться", ex: "His health deteriorated.", exr: "Его здоровье ухудшилось.", def: "to become worse over time", cat: "change" },
    { w: "intricate", t: "запутанный, сложный", ex: "An intricate pattern.", exr: "Замысловатый узор.", def: "very detailed and complicated", cat: "qualities" },
    { w: "resilient", t: "стойкий, устойчивый", ex: "Children are resilient.", exr: "Дети быстро восстанавливаются.", def: "able to recover quickly from difficulties", cat: "character" },
    { w: "spontaneous", t: "спонтанный", ex: "A spontaneous decision.", exr: "Спонтанное решение.", def: "done suddenly, without planning", cat: "character" },
    { w: "paradigm", t: "парадигма, модель", ex: "A new paradigm in science.", exr: "Новая парадигма в науке.", def: "a typical model or way of thinking", cat: "mind" },
    { w: "endeavour", t: "попытка, начинание", ex: "A scientific endeavour.", exr: "Научное начинание.", def: "a serious attempt to do something", cat: "actions" },
    { w: "inherent", t: "присущий, неотъемлемый", ex: "There is an inherent risk in every startup.", exr: "В любом стартапе есть неотъемлемый риск.", def: "existing as a natural, permanent part of something", cat: "qualities" },
    { w: "cumbersome", t: "громоздкий, неудобный", ex: "The old system was slow and cumbersome.", exr: "Старая система была медленной и громоздкой.", def: "big, heavy or complicated and hard to use", cat: "qualities" },
    { w: "redundant", t: "избыточный, лишний", ex: "Half of these slides are redundant.", exr: "Половина этих слайдов лишние.", def: "not needed because it repeats something else", cat: "qualities" },
    { w: "futile", t: "тщетный, бесполезный", ex: "Arguing with him turned out to be futile.", exr: "Спорить с ним оказалось бесполезно.", def: "having no chance of success", cat: "qualities" },
    { w: "mundane", t: "будничный, приземлённый", ex: "Her day is full of mundane tasks.", exr: "Её день полон будничных дел.", def: "ordinary, boring and not exciting", cat: "qualities" },
    { w: "robust", t: "прочный, крепкий", ex: "These boots are robust enough for the mountains.", exr: "Эти ботинки достаточно прочные для гор.", def: "strong and not easily damaged or broken", cat: "qualities" },
    { w: "arbitrary", t: "произвольный", ex: "The deadline felt completely arbitrary.", exr: "Дедлайн казался совершенно произвольным.", def: "chosen without a clear reason or system", cat: "mind" },
    { w: "constraint", t: "ограничение", ex: "Our only real constraint is time.", exr: "Наше единственное настоящее ограничение — время.", def: "something that limits what you can do", cat: "mind" },
    { w: "entail", t: "влечь за собой, подразумевать", ex: "The job entails a lot of travelling.", exr: "Работа предполагает много поездок.", def: "to involve something as a necessary part", cat: "mind" },
    { w: "premise", t: "предпосылка, исходное утверждение", ex: "The whole argument rests on a false premise.", exr: "Весь аргумент строится на ложной предпосылке.", def: "idea you accept as true to build arguments on", cat: "mind" },
    { w: "criterion", t: "критерий", ex: "Price was not our main criterion here.", exr: "Цена не была здесь нашим главным критерием.", def: "standard you use to judge or decide something", cat: "mind" },
    { w: "mitigate", t: "смягчать, снижать", ex: "Nothing can mitigate the damage now.", exr: "Теперь ничто не может смягчить ущерб.", def: "to reduce the harm or risk of something", cat: "change" },
    { w: "exacerbate", t: "усугублять, обострять", ex: "Shouting only exacerbated the conflict.", exr: "Крики лишь усугубили конфликт.", def: "to make a bad situation even worse", cat: "change" },
    { w: "obsolete", t: "устаревший", ex: "Fax machines became obsolete years ago.", exr: "Факсы устарели много лет назад.", def: "no longer used because something newer exists", cat: "change" },
    { w: "proliferate", t: "стремительно распространяться, множиться", ex: "Fake accounts proliferate on social media.", exr: "Фейковые аккаунты стремительно множатся в соцсетях.", def: "to increase quickly in number", cat: "change" },
    { w: "reconcile", t: "примирять, согласовывать", ex: "It's hard to reconcile these two figures.", exr: "Трудно согласовать эти две цифры.", def: "to make two different things or people agree", cat: "change" },
    { w: "foster", t: "способствовать, развивать", ex: "Good teachers foster curiosity in their students.", exr: "Хорошие учителя развивают в учениках любознательность.", def: "to help something good grow or develop", cat: "change" },
    { w: "pragmatic", t: "прагматичный", ex: "Let's take a pragmatic approach to this.", exr: "Давай подойдём к этому прагматично.", def: "dealing with things in a practical, realistic way", cat: "character" },
    { w: "candid", t: "откровенный, прямой", ex: "Thank you for being so candid with me.", exr: "Спасибо, что был со мной так откровенен.", def: "honest and open, even about difficult things", cat: "character" },
    { w: "sceptical", t: "скептический, недоверчивый", ex: "I'm sceptical about his promises.", exr: "Я скептически отношусь к его обещаниям.", def: "doubting that something is true or will work", cat: "character" },
    { w: "complacent", t: "самодовольный, беспечный", ex: "One win, and the team got complacent.", exr: "Одна победа — и команда расслабилась.", def: "too satisfied with yourself to keep trying", cat: "character" },
    { w: "impartial", t: "беспристрастный", ex: "A judge must stay impartial at all times.", exr: "Судья обязан всегда оставаться беспристрастным.", def: "not favouring one side over another", cat: "character" },
    { w: "nuance", t: "нюанс, тонкий оттенок", ex: "Every nuance of her voice mattered.", exr: "Каждый оттенок её голоса имел значение.", def: "very small difference in meaning or feeling", cat: "communication" },
    { w: "articulate", t: "чётко выражать (мысли)", ex: "She can articulate complex ideas very simply.", exr: "Она умеет очень просто выражать сложные идеи.", def: "to express thoughts in clear words", cat: "communication" },
    { w: "convey", t: "передавать (смысл, чувство)", ex: "Words cannot convey how grateful I am.", exr: "Словами не передать, как я благодарен.", def: "to make an idea or feeling known to others", cat: "communication" },
    { w: "concede", t: "признавать, уступать", ex: "He finally conceded that I was right.", exr: "Он наконец признал, что я был прав.", def: "to admit something is true after arguing", cat: "communication" },
    { w: "lucrative", t: "прибыльный, доходный", ex: "Tutoring turned out to be lucrative.", exr: "Репетиторство оказалось прибыльным.", def: "bringing in a lot of money", cat: "money" },
    { w: "incentive", t: "стимул, поощрение", ex: "Bonuses are a strong incentive to work harder.", exr: "Премии — сильный стимул работать усерднее.", def: "something that makes you want to do something", cat: "money" },
    { w: "deficit", t: "дефицит, нехватка", ex: "The city faces a huge budget deficit.", exr: "Город столкнулся с огромным дефицитом бюджета.", def: "amount by which money or supply is too small", cat: "money" },
    { w: "allocate", t: "распределять, выделять", ex: "We allocated most of the budget to marketing.", exr: "Мы выделили большую часть бюджета на маркетинг.", def: "to give money or time to a particular purpose", cat: "money" },
    { w: "legitimate", t: "законный, обоснованный", ex: "That's actually a legitimate question.", exr: "Это, вообще-то, обоснованный вопрос.", def: "allowed by law, or fair and reasonable", cat: "society" },
    { w: "consensus", t: "консенсус, общее согласие", ex: "The group reached a consensus after an hour.", exr: "Через час группа пришла к общему согласию.", def: "opinion that everyone in a group agrees on", cat: "society" },
    { w: "endorse", t: "одобрять, публично поддерживать", ex: "Two famous athletes endorsed the campaign.", exr: "Два известных спортсмена поддержали кампанию.", def: "to say publicly that you support someone or something", cat: "society" },
    { w: "loophole", t: "лазейка (в законе, правилах)", ex: "Their lawyers found a loophole in the contract.", exr: "Их юристы нашли лазейку в договоре.", def: "small mistake in rules that lets you avoid them", cat: "society" },
    { w: "daunting", t: "пугающий, устрашающий", ex: "Learning four thousand words sounds daunting.", exr: "Выучить четыре тысячи слов звучит пугающе.", def: "seeming so difficult that you lose courage", cat: "feelings" },
    { w: "resent", t: "возмущаться, затаить обиду", ex: "She still resents being left out.", exr: "Она всё ещё обижена, что её не позвали.", def: "to feel angry about something unfair", cat: "feelings" },
    { w: "apprehensive", t: "тревожный, опасающийся", ex: "I felt apprehensive before the interview.", exr: "Перед собеседованием мне было тревожно.", def: "worried that something bad may happen", cat: "feelings" },
    { w: "exhilarating", t: "будоражащий, захватывающий", ex: "The first jump was absolutely exhilarating.", exr: "Первый прыжок был абсолютно захватывающим.", def: "making you feel excited and full of energy", cat: "feelings" },
    { w: "imminent", t: "неминуемый, надвигающийся", ex: "Everyone knew a strike was imminent.", exr: "Все знали, что забастовка вот-вот начнётся.", def: "going to happen very soon", cat: "time" },
    { w: "unprecedented", t: "беспрецедентный, небывалый", ex: "The team had unprecedented success this year.", exr: "В этом году у команды был небывалый успех.", def: "never having happened before", cat: "time" },
    { w: "milestone", t: "веха, важный этап", ex: "Her first solo concert was a real milestone.", exr: "Её первый сольный концерт стал настоящей вехой.", def: "important event in a life or project", cat: "time" },
    { w: "nonetheless", t: "тем не менее", ex: "The plan is risky; nonetheless, I support it.", exr: "План рискованный; тем не менее я его поддерживаю.", def: "in spite of what was just said", cat: "linkers" },
    { w: "hence", t: "следовательно, отсюда", ex: "He missed the train, hence the delay.", exr: "Он опоздал на поезд — отсюда и задержка.", def: "for this reason, as a result", cat: "linkers" },
    { w: "conversely", t: "напротив, наоборот", ex: "Cats hate water; conversely, dogs love it.", exr: "Кошки ненавидят воду; собаки, наоборот, её обожают.", def: "used to introduce the opposite situation", cat: "linkers" },
    { w: "arguably", t: "пожалуй, можно утверждать", ex: "This is arguably his best film.", exr: "Это, пожалуй, его лучший фильм.", def: "used when something can probably be proved", cat: "linkers" },
    { w: "adhere", t: "придерживаться, соблюдать", ex: "All students must adhere to these rules.", exr: "Все ученики обязаны соблюдать эти правила.", def: "to follow a rule or plan exactly", cat: "actions" },
    { w: "streamline", t: "оптимизировать, упрощать", ex: "The new app streamlines the whole process.", exr: "Новое приложение упрощает весь процесс.", def: "to make a process simpler and faster", cat: "work" },
    { w: "depict", t: "изображать, описывать", ex: "The painting depicts a busy winter market.", exr: "Картина изображает оживлённый зимний рынок.", def: "to show something in a picture or story", cat: "art" },
  ],
  C2: [
    { w: "capricious", t: "капризный, переменчивый", ex: "Capricious weather ruined the trip.", exr: "Переменчивая погода испортила поездку.", def: "changing suddenly without reason", cat: "character" },
    { w: "ephemeral", t: "мимолётный", ex: "Fame is often ephemeral.", exr: "Слава часто мимолётна.", def: "lasting for a very short time", cat: "time" },
    { w: "gregarious", t: "общительный", ex: "A gregarious personality.", exr: "Общительный характер.", def: "enjoying the company of other people", cat: "character" },
    { w: "idiosyncrasy", t: "особенность, причуда", ex: "Everyone has their idiosyncrasies.", exr: "У каждого свои причуды.", def: "an unusual habit typical of one person", cat: "character" },
    { w: "juxtaposition", t: "сопоставление", ex: "A juxtaposition of old and new.", exr: "Сопоставление старого и нового.", def: "placing things side by side to compare them", cat: "mind" },
    { w: "magnanimous", t: "великодушный", ex: "A magnanimous gesture.", exr: "Великодушный жест.", def: "generous and kind, especially to a rival", cat: "character" },
    { w: "obfuscate", t: "запутывать, затемнять", ex: "Jargon can obfuscate meaning.", exr: "Жаргон может затемнять смысл.", def: "to make something unclear on purpose", cat: "communication" },
    { w: "pernicious", t: "пагубный", ex: "A pernicious influence.", exr: "Пагубное влияние.", def: "very harmful, often in a hidden way", cat: "qualities" },
    { w: "quintessential", t: "типичнейший, воплощение", ex: "The quintessential English village.", exr: "Типичнейшая английская деревня.", def: "being a perfect example of something", cat: "qualities" },
    { w: "serendipity", t: "счастливая случайность", ex: "They met by pure serendipity.", exr: "Они встретились по счастливой случайности.", def: "finding something good by lucky chance", cat: "mind" },
    { w: "taciturn", t: "неразговорчивый", ex: "A taciturn old man.", exr: "Неразговорчивый старик.", def: "saying very little, quiet by nature", cat: "character" },
    { w: "vicissitude", t: "превратность (судьбы)", ex: "The vicissitudes of life.", exr: "Превратности жизни.", def: "an unexpected change in life or fortune", cat: "change" },
    { w: "esoteric", t: "понятный немногим", ex: "An esoteric subject.", exr: "Тема, понятная немногим.", def: "understood by only a small group of experts", cat: "mind" },
    { w: "laconic", t: "лаконичный", ex: "A laconic reply.", exr: "Лаконичный ответ.", def: "using very few words", cat: "communication" },
    { w: "zealous", t: "рьяный, усердный", ex: "A zealous supporter.", exr: "Рьяный сторонник.", def: "full of energy and enthusiasm for a cause", cat: "character" },
    { w: "obsequious", t: "подобострастный", ex: "An obsequious waiter.", exr: "Подобострастный официант.", def: "too eager to please or obey someone", cat: "character" },
    { w: "ineffable", t: "невыразимый, неописуемый", ex: "She felt an ineffable sadness she could not name.", exr: "Она чувствовала невыразимую грусть, которую не могла назвать.", def: "too great or beautiful to describe in words", cat: "qualities" },
    { w: "lugubrious", t: "мрачный, скорбный", ex: "He announced the news in a lugubrious voice.", exr: "Он сообщил новость мрачным, скорбным голосом.", def: "looking or sounding very sad and gloomy", cat: "feelings" },
    { w: "perfunctory", t: "небрежный, формальный", ex: "The waiter gave the table a perfunctory wipe.", exr: "Официант небрежно, для галочки протёр стол.", def: "done quickly and without care or interest", cat: "qualities" },
    { w: "recalcitrant", t: "непокорный, строптивый", ex: "The recalcitrant pupil refused to sit down.", exr: "Строптивый ученик отказался сесть.", def: "refusing to obey rules or accept authority", cat: "character" },
    { w: "truculent", t: "задиристый, агрессивный", ex: "He became truculent after losing the argument.", exr: "Он стал задиристым после проигранного спора.", def: "eager to argue or fight, aggressive in manner", cat: "character" },
    { w: "inexorable", t: "неумолимый, неотвратимый", ex: "Nothing stopped the inexorable rise of the sea.", exr: "Ничто не остановило неумолимый подъём моря.", def: "impossible to stop or change by any effort", cat: "change" },
    { w: "mellifluous", t: "сладкозвучный, медоточивый", ex: "The narrator's mellifluous voice filled the hall.", exr: "Сладкозвучный голос чтеца заполнил зал.", def: "sounding smooth, sweet and pleasant to hear", cat: "communication" },
    { w: "ostensible", t: "мнимый, показной", ex: "The ostensible reason for his visit was business.", exr: "Мнимой причиной его визита были дела.", def: "stated as true but probably not the real one", cat: "qualities" },
    { w: "protean", t: "многоликий, изменчивый", ex: "Her protean talent moved easily between styles.", exr: "Её многоликий талант легко переходил от стиля к стилю.", def: "able to change form or role very easily", cat: "change" },
    { w: "sanguine", t: "оптимистичный, бодро настроенный", ex: "He stayed sanguine even as the deadline slipped.", exr: "Он оставался оптимистичным, даже когда сроки поехали.", def: "cheerful and hopeful about a difficult situation", cat: "character" },
    { w: "tenuous", t: "зыбкий, шаткий", ex: "The link between the two events is tenuous.", exr: "Связь между этими двумя событиями зыбкая.", def: "very weak, thin or easily doubted", cat: "qualities" },
    { w: "venerate", t: "почитать, благоговеть", ex: "The villagers still venerate the old oak.", exr: "Жители деревни до сих пор почитают старый дуб.", def: "to respect and honour someone or something deeply", cat: "actions" },
    { w: "assiduous", t: "усердный, прилежный", ex: "Years of assiduous practice made him a soloist.", exr: "Годы усердных занятий сделали его солистом.", def: "working hard and with constant careful attention", cat: "character" },
    { w: "cacophony", t: "какофония, разноголосица", ex: "A cacophony of horns rose from the street.", exr: "С улицы поднималась какофония автомобильных гудков.", def: "loud, harsh mixture of unpleasant sounds", cat: "communication" },
    { w: "ebullient", t: "кипучий, брызжущий энергией", ex: "Ebullient fans sang all the way home.", exr: "Брызжущие энергией болельщики пели всю дорогу домой.", def: "full of cheerful energy and excitement", cat: "feelings" },
    { w: "fastidious", t: "привередливый, щепетильный", ex: "She is fastidious about how the table is laid.", exr: "Она привередлива в том, как накрыт стол.", def: "very hard to please, caring about small details", cat: "character" },
    { w: "garrulous", t: "болтливый", ex: "Our garrulous taxi driver talked for an hour.", exr: "Наш болтливый таксист говорил целый час.", def: "talking too much, especially about small things", cat: "character" },
    { w: "hackneyed", t: "избитый, затасканный", ex: "The film ends with a hackneyed speech about hope.", exr: "Фильм заканчивается избитой речью о надежде.", def: "used so often that it is no longer interesting", cat: "communication" },
    { w: "impecunious", t: "безденежный, нуждающийся", ex: "As an impecunious student, he lived on tea.", exr: "Будучи безденежным студентом, он жил на одном чае.", def: "having very little money, usually for a long time", cat: "money" },
    { w: "maudlin", t: "слезливо-сентиментальный", ex: "After two glasses he became maudlin and tearful.", exr: "После двух бокалов он стал слезливо-сентиментальным.", def: "sad and sentimental in a silly, tearful way", cat: "feelings" },
    { w: "nebulous", t: "туманный, неопределённый", ex: "His plans for the future remain nebulous.", exr: "Его планы на будущее остаются туманными.", def: "unclear in shape or meaning, hard to define", cat: "mind" },
    { w: "opulent", t: "роскошный", ex: "They dined in an opulent hall of mirrors.", exr: "Они ужинали в роскошном зеркальном зале.", def: "expensive, rich and impressive to look at", cat: "qualities" },
    { w: "supercilious", t: "надменный, высокомерный", ex: "The clerk answered with a supercilious smile.", exr: "Клерк ответил с надменной улыбкой.", def: "behaving as if you are better than other people", cat: "character" },
    { w: "trenchant", t: "резкий, меткий", ex: "Her trenchant review left the author speechless.", exr: "Её резкая рецензия лишила автора дара речи.", def: "sharp, clear and forceful in criticism", cat: "communication" },
    { w: "wistful", t: "тоскливо-мечтательный, грустный", ex: "He gave his old bicycle a wistful look.", exr: "Он с грустной нежностью взглянул на свой старый велосипед.", def: "sadly wishing for something that is gone", cat: "feelings" },
    { w: "anachronism", t: "анахронизм", ex: "A wooden plough here is a charming anachronism.", exr: "Деревянный плуг здесь — милый анахронизм.", def: "something that belongs to another period of time", cat: "time" },
    { w: "bucolic", t: "пасторальный, деревенски-идиллический", ex: "The painting shows a bucolic scene with sheep.", exr: "На картине изображена пасторальная сцена с овцами.", def: "about pleasant, peaceful life in the countryside", cat: "nature" },
    { w: "clandestine", t: "тайный, подпольный", ex: "They held clandestine meetings in the back room.", exr: "Они проводили тайные встречи в задней комнате.", def: "kept secret because it is not allowed", cat: "society" },
    { w: "incongruous", t: "неуместный, несуразный", ex: "The piano looked incongruous in the tiny kitchen.", exr: "Рояль смотрелся неуместно в крошечной кухне.", def: "strange because it does not fit its surroundings", cat: "qualities" },
    { w: "ostracize", t: "подвергать остракизму, изгонять", ex: "The whole class ostracized him after the incident.", exr: "Весь класс подверг его остракизму после того случая.", def: "to refuse to let someone belong to a group", cat: "society" },
    { w: "vitriolic", t: "язвительный, злобный", ex: "The debate turned vitriolic within a few minutes.", exr: "Дебаты за считанные минуты стали язвительными и злыми.", def: "full of cruel, bitter and angry words", cat: "communication" },
    { w: "halcyon", t: "безмятежный, счастливый", ex: "He remembers the halcyon days before the war.", exr: "Он вспоминает безмятежные дни перед войной.", def: "peaceful and happy, usually about the past", cat: "time" },
    { w: "inscrutable", t: "непроницаемый, загадочный", ex: "The judge kept an inscrutable expression throughout.", exr: "Судья всё время сохранял непроницаемое выражение лица.", def: "impossible to understand from the outside", cat: "character" },
    { w: "torpor", t: "оцепенение, вялость", ex: "The afternoon heat sank the village into torpor.", exr: "Послеполуденная жара погрузила деревню в оцепенение.", def: "state of being slow, sleepy and inactive", cat: "feelings" },
    { w: "equivocate", t: "уклоняться от прямого ответа", ex: "Stop equivocating and tell me what happened.", exr: "Хватит увиливать — расскажи, что случилось.", def: "to speak unclearly to avoid telling the truth", cat: "communication" },
    { w: "myopic", t: "недальновидный", ex: "Cutting the science budget was a myopic decision.", exr: "Урезать бюджет на науку было недальновидным решением.", def: "unable to see what will matter in the future", cat: "mind" },
    { w: "seminal", t: "основополагающий", ex: "Her seminal paper changed the whole field.", exr: "Её основополагающая статья изменила всю область.", def: "very important and influencing later work", cat: "mind" },
    { w: "nascent", t: "зарождающийся", ex: "The country's nascent film industry needs money.", exr: "Зарождающейся киноиндустрии страны нужны деньги.", def: "just beginning to exist and still developing", cat: "change" },
    { w: "wanderlust", t: "тяга к странствиям", ex: "Her wanderlust took her to three continents.", exr: "Тяга к странствиям привела её на три континента.", def: "strong wish to travel and see the world", cat: "travel" },
    { w: "tantamount", t: "равносильный", ex: "Silence here is tantamount to agreement.", exr: "Молчание здесь равносильно согласию.", def: "having the same effect as something else", cat: "linkers" },
  ],
};

const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// Примерный прирост словарного запаса на каждом уровне
const LEVEL_VOCAB_SIZE = { A1: 500, A2: 500, B1: 1000, B2: 2000, C1: 4000, C2: 8000 };

const LEVEL_NAMES = {
  A1: "Начинающий",
  A2: "Элементарный",
  B1: "Средний",
  B2: "Выше среднего",
  C1: "Продвинутый",
  C2: "Свободное владение",
};

const CATEGORY_NAMES = {
  food: "Еда", home: "Дом", objects: "Вещи", places: "Места", nature: "Природа",
  time: "Время", qualities: "Качества", feelings: "Чувства", people: "Люди",
  actions: "Действия", travel: "Дорога и отдых", communication: "Общение",
  mind: "Мышление", character: "Характер", change: "Изменения",
  money: "Деньги и работа", society: "Общество", linkers: "Слова-связки",
};

// Устойчивые сочетания (Collocation Matching) — пары подобраны так,
// чтобы перекрёстные комбинации были ошибочными
const COLLOCATIONS = [
  { h: "make", tl: "a decision" },
  { h: "do", tl: "homework" },
  { h: "take", tl: "a photo" },
  { h: "have", tl: "breakfast" },
  { h: "pay", tl: "attention" },
  { h: "tell", tl: "the truth" },
  { h: "keep", tl: "a secret" },
  { h: "catch", tl: "a cold" },
];

// Синонимы и антонимы
const SYNONYMS = [
  { w: "big", syn: "large", ant: "small" },
  { w: "happy", syn: "glad", ant: "sad" },
  { w: "cold", syn: "chilly", ant: "hot" },
  { w: "cheap", syn: "inexpensive", ant: "expensive" },
  { w: "dangerous", syn: "risky", ant: "safe" },
  { w: "famous", syn: "well-known", ant: "unknown" },
  { w: "quiet", syn: "silent", ant: "noisy" },
  { w: "terrible", syn: "awful", ant: "wonderful" },
  { w: "improve", syn: "get better", ant: "worsen" },
  { w: "reliable", syn: "dependable", ant: "unreliable" },
  { w: "significant", syn: "important", ant: "minor" },
  { w: "vague", syn: "unclear", ant: "precise" },
  { w: "tremendous", syn: "huge", ant: "tiny" },
  { w: "inevitable", syn: "unavoidable", ant: "avoidable" },
  { w: "feasible", syn: "doable", ant: "impossible" },
  { w: "meticulous", syn: "thorough", ant: "careless" },
  { w: "ubiquitous", syn: "everywhere", ant: "rare" },
  { w: "taciturn", syn: "reserved", ant: "talkative" },
  { w: "ephemeral", syn: "short-lived", ant: "permanent" },
  { w: "gregarious", syn: "sociable", ant: "shy" },
];
