// Сгенерировано tools/build_images.py — руками не править.
// Только список слов, у которых есть фотография: имя файла всегда
// img/words/<слово>.webp. Значение не несёт смысла, важен сам ключ.
// Лицензии и авторы — img/words/manifest.json и credits.html.
const WORD_PHOTOS = {
  "aircraft": 1, "airport": 1, "alarm": 1, "alley": 1, "ambulance": 1, "anger": 1,
  "animal": 1, "applause": 1, "apple": 1, "architecture": 1, "archive": 1, "art": 1,
  "artist": 1, "autumn": 1, "baby": 1, "baker": 1, "banana": 1, "bank": 1,
  "barn": 1, "barrel": 1, "basket": 1, "basketball": 1, "bat": 1, "battery": 1,
  "bay": 1, "bed": 1, "bee": 1, "belt": 1, "bicycle": 1, "bike": 1,
  "biker": 1, "biotechnology": 1, "bird": 1, "birthday": 1, "blackberry": 1, "boat": 1,
  "bone": 1, "book": 1, "boots": 1, "bottle": 1, "branch": 1, "bread": 1,
  "breakfast": 1, "brick": 1, "bridge": 1, "buffalo": 1, "bus": 1, "bush": 1,
  "butterfly": 1, "buyer": 1, "cake": 1, "calendar": 1, "camera": 1, "candle": 1,
  "car": 1, "cardboard": 1, "cargo": 1, "carpet": 1, "carrot": 1, "cashier": 1,
  "cat": 1, "cauldron": 1, "cave": 1, "chain": 1, "chair": 1, "champagne": 1,
  "chapel": 1, "cheese": 1, "cherry": 1, "chess": 1, "chest": 1, "childhood": 1,
  "cinnamon": 1, "city": 1, "classroom": 1, "cliff": 1, "clock": 1, "cloud": 1,
  "coal": 1, "coast": 1, "coffee": 1, "coin": 1, "cold": 1, "college": 1,
  "column": 1, "construction": 1, "cook": 1, "corn": 1, "cottage": 1, "couch": 1,
  "cow": 1, "coyote": 1, "crane": 1, "crate": 1, "cricket": 1, "crowd": 1,
  "crystal": 1, "cure": 1, "daisy": 1, "dam": 1, "dance": 1, "date": 1,
  "deer": 1, "delivery": 1, "desk": 1, "detail": 1, "dictionary": 1, "dinner": 1,
  "discount": 1, "dishwasher": 1, "doctor": 1, "dog": 1, "dress": 1, "drive": 1,
  "dump": 1, "eagle": 1, "egg": 1, "energy": 1, "face": 1, "family": 1,
  "farm": 1, "father": 1, "fax": 1, "fence": 1, "festival": 1, "fever": 1,
  "film": 1, "finger": 1, "fish": 1, "fishing": 1, "flag": 1, "flashlight": 1,
  "floor": 1, "flower": 1, "fly": 1, "food": 1, "forest": 1, "fort": 1,
  "fruit": 1, "galaxy": 1, "gallery": 1, "garbage": 1, "garden": 1, "gate": 1,
  "gloves": 1, "golf": 1, "grain": 1, "grandfather": 1, "grass": 1, "gravel": 1,
  "guitar": 1, "gym": 1, "gymnastics": 1, "hammer": 1, "headphones": 1, "heather": 1,
  "hill": 1, "horn": 1, "horse": 1, "hospital": 1, "hotel": 1, "hourglass": 1,
  "house": 1, "hug": 1, "ice": 1, "ink": 1, "inn": 1, "inspector": 1,
  "instrument": 1, "interview": 1, "jacket": 1, "jockey": 1, "judge": 1, "juice": 1,
  "jump": 1, "jungle": 1, "key": 1, "keyboard": 1, "king": 1, "kitchen": 1,
  "knife": 1, "lake": 1, "lantern": 1, "laptop": 1, "laser": 1, "lawn": 1,
  "leaf": 1, "leather": 1, "lecture": 1, "lemon": 1, "leopard": 1, "lightning": 1,
  "lily": 1, "log": 1, "luggage": 1, "mall": 1, "mannequin": 1, "marmalade": 1,
  "marry": 1, "mask": 1, "mason": 1, "massage": 1, "menu": 1, "mercury": 1,
  "microscope": 1, "milk": 1, "mobile": 1, "money": 1, "morning": 1, "motorcycle": 1,
  "mountain": 1, "mouse": 1, "mud": 1, "museum": 1, "necklace": 1, "needle": 1,
  "negotiate": 1, "neighborhood": 1, "night": 1, "nightclub": 1, "nose": 1, "notebook": 1,
  "notepad": 1, "nurse": 1, "nutmeg": 1, "observatory": 1, "oil": 1, "olive": 1,
  "orange": 1, "orchid": 1, "paint": 1, "pants": 1, "park": 1, "passenger": 1,
  "passport": 1, "pavement": 1, "payment": 1, "pear": 1, "pen": 1, "pencil": 1,
  "photographer": 1, "pig": 1, "pillow": 1, "pine": 1, "pineapple": 1, "pizza": 1,
  "planet": 1, "plate": 1, "plum": 1, "pollution": 1, "port": 1, "porter": 1,
  "portfolio": 1, "pot": 1, "potato": 1, "pouch": 1, "pub": 1, "pump": 1,
  "rabbit": 1, "railway": 1, "rain": 1, "rest": 1, "rice": 1, "river": 1,
  "road": 1, "roof": 1, "rope": 1, "ruler": 1, "run": 1, "sailing": 1,
  "salmon": 1, "sand": 1, "sandwich": 1, "sashimi": 1, "sauce": 1, "scaffold": 1,
  "scarf": 1, "school": 1, "sea": 1, "seed": 1, "shark": 1, "shirt": 1,
  "shoe": 1, "shoelace": 1, "shop": 1, "sieve": 1, "sing": 1, "sleep": 1,
  "snow": 1, "sock": 1, "soil": 1, "soup": 1, "spoon": 1, "stadium": 1,
  "stand": 1, "station": 1, "storm": 1, "stream": 1, "street": 1, "student": 1,
  "sugar": 1, "summer": 1, "sun": 1, "supermarket": 1, "surf": 1, "surgeon": 1,
  "surveillance": 1, "swim": 1, "taco": 1, "tattoo": 1, "taxi": 1, "tea": 1,
  "telephone": 1, "television": 1, "temperature": 1, "ten": 1, "tennis": 1, "tent": 1,
  "tiger": 1, "toad": 1, "toast": 1, "toe": 1, "toilet": 1, "tongue": 1,
  "tornado": 1, "tower": 1, "traffic": 1, "treasure": 1, "tree": 1, "tunnel": 1,
  "umbrella": 1, "valley": 1, "van": 1, "vehicle": 1, "vendor": 1, "villa": 1,
  "village": 1, "volunteer": 1, "wallet": 1, "walnut": 1, "walrus": 1, "wash": 1,
  "water": 1, "webcam": 1, "whistle": 1, "window": 1, "winter": 1, "wizard": 1,
  "woman": 1, "wood": 1, "woodpecker": 1, "workshop": 1, "yarn": 1, "yogurt": 1,
  "zoo": 1
};
