"""Список-семя для трёх наборов фраз: фразовые глаголы, идиомы, коллокации.

Почему список курируемый, а не «взять Category:English phrasal verbs целиком».

  1. Безопасность. В категории Wiktionary «English idioms» около 9000 статей, и
     заметная их часть — про алкоголь, смерть, драки и секс («kick the bucket»,
     «hit the bottle», «bite the dust»). Фильтр примеров такое ловит, но фильтр
     работает по СЛОВАМ, а идиома опасна ЗНАЧЕНИЕМ: «kick the bucket» состоит из
     трёх безобидных слов. Единственный надёжный барьер — выбирать фразы руками.

  2. Перевод. У фразового глагола перевод почти всегда зависит от значения:
     take off — и «взлетать», и «снимать», и «иметь успех». Робот выберет первый
     блок переводов Wiktionary и с большой вероятностью ошибётся. Поэтому русский
     перевод здесь — часть исходных данных, а Wiktionary используется как
     ПРОВЕРКА (см. build_phrases.py: расхождение попадает в отчёт).

  3. Буквальный перевод (literal) машине взять неоткуда вовсе: ни в одном
     словаре нет поля «как это звучит, если переводить по словам».

Что берёт на себя машина: английское определение (Wiktionary REST), пример с
русским переводом (Tatoeba) и весь контентный фильтр.

Формат записи:
    (фраза, русский перевод, буквальный перевод, категория, уровень, запасное
     определение по-английски)

  * буквальный перевод — только для phrasal и idiom (для коллокаций он совпадает
    с настоящим и упражнению не нужен);
  * запасное определение используется, только если Wiktionary статьи не дал;
    у коллокаций статьи нет почти никогда, поэтому там оно заполнено всегда.

Категории — те же, что в js/words.js, новых не вводим.
Уровень — по двум признакам: частотность и «выводится ли значение из частей».
"""

# --- Фразовые глаголы -----------------------------------------------------
# Разделяемые (turn the light off) помечать не нужно: подстановщик примеров
# в phrases.py допускает вставку дополнения между частями.

PHRASAL = [
    # A1–A2: буквальные, значение видно из частей
    ("get up", "вставать, подниматься", "взять вверх", "actions", "A1", "to rise from bed"),
    ("sit down", "садиться", "сидеть вниз", "actions", "A1", "to take a seat"),
    ("stand up", "вставать на ноги", "стоять вверх", "actions", "A1", "to rise to your feet"),
    ("wake up", "просыпаться, будить", "проснуться вверх", "actions", "A1", "to stop sleeping"),
    ("come in", "входить", "прийти внутрь", "actions", "A1", "to enter a room"),
    ("go out", "выходить, гулять", "идти наружу", "actions", "A1", "to leave the house"),
    ("come back", "возвращаться", "прийти назад", "actions", "A1", "to return to a place"),
    ("go back", "возвращаться", "идти назад", "travel", "A1", "to return to where you were"),
    ("put on", "надевать", "положить на", "clothes", "A1", "to dress yourself in something"),
    ("turn on", "включать", "повернуть на", "tech", "A1", "to make a machine start working"),
    ("turn off", "выключать", "повернуть прочь", "tech", "A1", "to make a machine stop working"),
    ("look at", "смотреть на", "смотреть у", "actions", "A1", "to direct your eyes at something"),
    ("take off", "снимать (одежду); взлетать", "взять прочь", "clothes", "A2", "to remove a piece of clothing"),
    ("look for", "искать", "смотреть для", "actions", "A2", "to try to find something"),
    ("give up", "сдаваться, бросать", "дать вверх", "actions", "A2", "to stop trying"),
    ("hurry up", "поторопиться", "спешить вверх", "time", "A2", "to move or act faster"),
    ("get in", "садиться (в машину), входить", "взять внутрь", "travel", "A2", "to enter a car or small space"),
    ("get out", "выходить, вылезать", "взять наружу", "travel", "A2", "to leave a car or a place"),
    ("get on", "садиться (в автобус, поезд)", "взять на", "travel", "A2", "to board a bus or train"),
    ("get off", "выходить (из автобуса, поезда)", "взять прочь", "travel", "A2", "to leave a bus or train"),
    ("put down", "класть, опускать", "положить вниз", "actions", "A2", "to place something on a surface"),
    ("pick up", "поднимать; забирать", "поднять вверх", "actions", "A2", "to lift something from the ground"),
    ("write down", "записывать", "писать вниз", "school", "A2", "to write something on paper"),
    ("clean up", "убирать, наводить порядок", "чистить вверх", "home", "A2", "to make a place tidy and clean"),
    ("wash up", "мыть посуду", "мыть вверх", "home", "A2", "to wash the plates after a meal"),
    ("try on", "примерять", "пробовать на", "clothes", "A2", "to put clothes on to see if they fit"),
    ("throw away", "выбрасывать", "бросить прочь", "home", "A2", "to get rid of something you do not need"),
    ("run away", "убегать", "бежать прочь", "actions", "A2", "to leave a place quickly to escape"),
    ("grow up", "расти, взрослеть", "расти вверх", "people", "A2", "to become an adult"),
    ("find out", "узнавать, выяснять", "найти наружу", "mind", "A2", "to learn a fact"),
    ("look after", "присматривать, ухаживать", "смотреть после", "family", "A2", "to take care of someone"),
    ("go on", "продолжать; происходить", "идти на", "actions", "A2", "to continue doing something"),
    ("come on", "давай, ну же", "прийти на", "communication", "A2", "used to tell someone to hurry or try"),
    ("put away", "убирать на место", "положить прочь", "home", "A2", "to put something back where it belongs"),
    ("eat out", "есть в кафе, ужинать вне дома", "есть наружу", "food", "A2", "to have a meal in a restaurant"),
    ("get back", "возвращаться; получить обратно", "взять назад", "travel", "A2", "to return to a place"),
    ("call back", "перезвонить", "звонить назад", "communication", "A2", "to telephone someone again"),
    ("switch on", "включать", "переключить на", "tech", "A2", "to turn a device on"),
    ("switch off", "выключать", "переключить прочь", "tech", "A2", "to turn a device off"),
    ("give back", "возвращать (вещь)", "дать назад", "actions", "A2", "to return something to its owner"),
    ("tidy up", "прибираться", "прибрать вверх", "home", "A2", "to make a place neat"),
    ("sit up", "сесть прямо; не ложиться спать", "сидеть вверх", "actions", "B1", "to move into a sitting position"),

    # B1: значение уже не складывается из частей, но фразы очень частотные
    ("turn up", "прибавить (звук); объявиться", "повернуть вверх", "tech", "B1", "to increase the volume"),
    ("turn down", "убавить (звук); отказать", "повернуть вниз", "tech", "B1", "to reduce the volume"),
    ("move in", "въезжать (в новое жильё)", "двигаться внутрь", "home", "B1", "to start living in a new home"),
    ("move out", "съезжать (с квартиры)", "двигаться наружу", "home", "B1", "to leave the home you lived in"),
    ("hang up", "вешать трубку", "вешать вверх", "communication", "B1", "to end a telephone call"),
    ("fill in", "заполнять (бланк)", "наполнять внутрь", "work", "B1", "to write information in a form"),
    ("hand in", "сдавать (работу учителю)", "рука внутрь", "school", "B1", "to give work to a teacher"),
    ("hand out", "раздавать", "рука наружу", "school", "B1", "to give something to each person"),
    ("carry on", "продолжать", "нести на", "actions", "B1", "to continue"),
    ("put off", "откладывать на потом", "положить прочь", "time", "B1", "to move something to a later time"),
    ("take care of", "заботиться о", "взять заботу о", "family", "B1", "to look after someone or something"),
    ("look forward to", "с нетерпением ждать", "смотреть вперёд к", "feelings", "B1", "to wait for something with pleasure"),
    ("get along", "ладить, уживаться", "взять вдоль", "people", "B1", "to have a friendly relationship"),
    ("break down", "ломаться (о технике)", "ломать вниз", "tech", "B1", "to stop working"),
    ("work out", "тренироваться; получаться", "работать наружу", "sports", "B1", "to do physical exercise"),
    ("figure out", "разобраться, понять", "фигура наружу", "mind", "B1", "to understand after thinking"),
    ("point out", "указывать, отмечать", "указать наружу", "communication", "B1", "to make someone notice something"),
    ("set up", "устанавливать, организовывать", "ставить вверх", "work", "B1", "to build or start something"),
    ("take part in", "участвовать в", "взять часть в", "society", "B1", "to join an activity"),
    ("deal with", "иметь дело с, решать", "сделка с", "work", "B1", "to handle a problem or a person"),
    ("bring up", "воспитывать; поднимать (тему)", "принести вверх", "family", "B1", "to raise a child"),
    ("call off", "отменять", "звать прочь", "work", "B1", "to cancel an event"),
    ("check in", "регистрироваться (в гостинице, на рейс)", "проверить внутрь", "travel", "B1", "to report your arrival at a hotel or airport"),
    ("check out", "выписываться из гостиницы", "проверить наружу", "travel", "B1", "to pay and leave a hotel"),
    ("come across", "наткнуться, случайно найти", "прийти поперёк", "mind", "B1", "to find something by chance"),
    ("cut down", "сократить (потребление)", "резать вниз", "health", "B1", "to use less of something"),
    ("keep on", "продолжать делать", "держать на", "actions", "B1", "to continue doing something"),
    ("give in", "уступить, сдаться", "дать внутрь", "feelings", "B1", "to stop resisting"),
    ("go over", "просматривать, повторять", "идти над", "school", "B1", "to look at something again carefully"),
    ("hold on", "подождать; держаться", "держать на", "communication", "B1", "to wait for a short time"),
    ("look up", "искать (в словаре, справочнике)", "смотреть вверх", "school", "B1", "to search for information in a book"),
    ("put together", "собирать, составлять", "положить вместе", "actions", "B1", "to make something from parts"),
    ("show up", "появляться, приходить", "показать вверх", "people", "B1", "to arrive somewhere"),
    ("sort out", "разобраться, уладить", "сортировать наружу", "work", "B1", "to solve a problem or organise things"),
    ("take up", "заняться (новым делом)", "взять вверх", "sports", "B1", "to start a new hobby"),
    ("warm up", "разогреваться, разминаться", "греть вверх", "sports", "B1", "to prepare your body for exercise"),
    ("slow down", "замедляться", "медленно вниз", "actions", "B1", "to go more slowly"),
    ("speed up", "ускоряться", "скорость вверх", "actions", "B1", "to go faster"),
    ("break up", "расставаться; распадаться", "ломать вверх", "feelings", "B1", "to end a relationship"),
    ("make up", "мириться; выдумывать", "делать вверх", "feelings", "B1", "to become friends again after a quarrel"),
    ("get over", "оправиться, пережить", "взять над", "feelings", "B1", "to recover from something bad"),
    ("turn into", "превращаться в", "повернуть в", "change", "B1", "to become something different"),
    ("put up", "вешать, размещать", "положить вверх", "home", "B1", "to fix something to a wall"),
    ("take back", "забирать назад; брать слова обратно", "взять назад", "communication", "B1", "to return something to a shop"),
    ("leave out", "пропускать, не включать", "оставить наружу", "school", "B1", "to not include something"),
    ("join in", "присоединяться", "присоединиться внутрь", "society", "B1", "to take part with other people"),
    ("save up", "копить деньги", "сберечь вверх", "money", "B1", "to keep money for something you want"),
    ("pay back", "возвращать долг", "платить назад", "money", "B1", "to return money you borrowed"),
    ("try out", "испытывать, пробовать", "пробовать наружу", "actions", "B1", "to test something new"),
    ("put back", "класть на место", "положить назад", "home", "B1", "to return something to its place"),
    ("set off", "отправляться в путь", "ставить прочь", "travel", "B1", "to begin a journey"),
    ("take down", "снимать (со стены); записывать", "взять вниз", "actions", "B1", "to remove something that is fixed up"),
    ("work on", "работать над", "работать на", "work", "B1", "to spend time improving something"),
    ("drop off", "подвезти и высадить; задремать", "уронить прочь", "travel", "B1", "to take someone to a place and leave them"),
    ("hold up", "задерживать; поддерживать", "держать вверх", "time", "B1", "to delay someone or something"),
    ("run out of", "исчерпать запас, остаться без", "выбежать из", "change", "B1", "to have no more of something"),

    # B2: значение из частей уже не выводится
    ("put up with", "терпеть, мириться с", "положить вверх с", "feelings", "B2", "to accept something unpleasant without complaining"),
    ("look up to", "уважать, брать пример", "смотреть вверх к", "people", "B2", "to admire someone"),
    ("look down on", "смотреть свысока", "смотреть вниз на", "people", "B2", "to think you are better than someone"),
    ("get away with", "сойти с рук", "взять прочь с", "society", "B2", "to do something wrong and not be punished"),
    ("come up with", "придумать, предложить", "прийти вверх с", "mind", "B2", "to think of an idea or plan"),
    ("take after", "быть похожим (на родителя)", "взять после", "family", "B2", "to look or behave like an older relative"),
    ("bring about", "вызывать, приводить к", "принести около", "change", "B2", "to make something happen"),
    ("carry out", "выполнять, проводить", "нести наружу", "work", "B2", "to do a task or a plan"),
    ("catch up with", "догонять", "поймать вверх с", "actions", "B2", "to reach someone who is ahead"),
    ("cut back on", "сокращать (расходы, потребление)", "резать назад на", "money", "B2", "to spend or use less"),
    ("fall behind", "отставать", "падать позади", "school", "B2", "to make less progress than others"),
    ("get by", "обходиться, перебиваться", "взять мимо", "money", "B2", "to manage with what you have"),
    ("give away", "отдавать даром; выдавать (секрет)", "дать прочь", "society", "B2", "to give something without asking for money"),
    ("go through", "переживать (трудное); просматривать", "идти сквозь", "feelings", "B2", "to experience something difficult"),
    ("keep up with", "успевать за, поспевать", "держать вверх с", "school", "B2", "to move or learn as fast as others"),
    ("live up to", "оправдывать (ожидания)", "жить вверх к", "society", "B2", "to be as good as expected"),
    ("make up for", "компенсировать, возмещать", "делать вверх для", "change", "B2", "to do something good to balance something bad"),
    ("stand up for", "заступаться за", "стоять вверх за", "society", "B2", "to defend a person or an idea"),
    ("stand out", "выделяться", "стоять наружу", "qualities", "B2", "to be easy to notice"),
    ("take over", "брать управление на себя", "взять над", "work", "B2", "to take control of something"),
    ("turn out", "оказаться, выйти в итоге", "повернуть наружу", "change", "B2", "to happen in a particular way"),
    # rely on здесь не место: буквальный перевод («полагаться на») совпадает с
    # настоящим, и упражнению на контраст такая запись ничего не даёт.
    ("count on", "рассчитывать на", "считать на", "people", "B2", "to depend on someone"),
    ("bring in", "приносить (доход); привлекать", "принести внутрь", "money", "B2", "to earn money"),
    ("call for", "требовать, предусматривать", "звать для", "work", "B2", "to need something"),
    ("come down with", "заболевать (простудой)", "прийти вниз с", "health", "B2", "to catch a common illness"),
    ("cut off", "отрезать; отключать", "резать прочь", "tech", "B2", "to stop the supply of something"),
    ("draw up", "составлять (документ, план)", "тянуть вверх", "work", "B2", "to prepare a written plan"),
    ("drop by", "заглянуть в гости", "уронить мимо", "people", "B2", "to visit for a short time"),
    ("drop out", "бросить учёбу", "уронить наружу", "school", "B2", "to leave a course before finishing"),
    ("end up", "в итоге оказаться", "конец вверх", "change", "B2", "to be in a place or state at last"),
    ("fill out", "заполнять (анкету)", "наполнять наружу", "work", "B2", "to write information in a form"),
    ("get down to", "приниматься за", "взять вниз к", "work", "B2", "to start working seriously"),
    ("get through", "дозвониться; справиться", "взять сквозь", "communication", "B2", "to reach someone by phone"),
    ("give out", "раздавать; иссякать", "дать наружу", "change", "B2", "to give something to many people"),
    ("hold back", "сдерживать", "держать назад", "feelings", "B2", "to stop yourself showing a feeling"),
    ("look into", "изучать, разбираться", "смотреть внутрь", "mind", "B2", "to examine a matter carefully"),
    ("pass on", "передавать дальше", "пройти на", "communication", "B2", "to give information to another person"),
    ("pick out", "выбирать, выделять", "поднять наружу", "actions", "B2", "to choose one from a group"),
    ("put forward", "выдвигать (идею)", "положить вперёд", "mind", "B2", "to suggest an idea for discussion"),
    ("run into", "случайно встретить", "бежать в", "people", "B2", "to meet someone by chance"),
    ("see off", "провожать", "видеть прочь", "travel", "B2", "to go with someone to their point of departure"),
    ("set aside", "откладывать (время, деньги)", "ставить в сторону", "money", "B2", "to keep something for later use"),
    ("settle down", "остепениться; успокоиться", "осесть вниз", "people", "B2", "to start living a calm settled life"),
    ("sign up", "записаться, зарегистрироваться", "подписать вверх", "school", "B2", "to put your name on a list to join"),
    ("take on", "брать на себя; нанимать", "взять на", "work", "B2", "to accept a task or a job"),
    ("tell off", "отчитывать, ругать", "сказать прочь", "school", "B2", "to speak angrily to someone who did wrong"),
    ("think over", "обдумывать", "думать над", "mind", "B2", "to consider carefully"),
    ("turn around", "развернуться; изменить к лучшему", "повернуть вокруг", "change", "B2", "to face the other way"),
    ("wear off", "проходить (об эффекте)", "носить прочь", "change", "B2", "to slowly disappear"),
    ("wear out", "изнашивать(ся); выматывать", "носить наружу", "change", "B2", "to become old and unusable"),
    ("own up", "признаваться", "владеть вверх", "communication", "B2", "to admit that you did something"),
    ("back up", "поддержать; сделать копию", "назад вверх", "tech", "B2", "to make a copy of computer files"),
    ("call on", "обращаться к, призывать", "звать на", "communication", "B2", "to ask someone publicly to do something"),
    ("come around", "заглянуть; прийти в себя", "прийти вокруг", "people", "B2", "to visit someone at their home"),

    # C1: книжные и деловые, значение полностью переносное
    ("bank on", "рассчитывать на, надеяться на", "банк на", "mind", "C1", "to depend on something happening"),
    ("brush aside", "отмахнуться от", "смахнуть в сторону", "communication", "C1", "to refuse to consider something"),
    ("gloss over", "замалчивать, обходить стороной", "глянец над", "communication", "C1", "to avoid mentioning a problem"),
    ("iron out", "сглаживать, устранять (шероховатости)", "утюжить наружу", "work", "C1", "to solve small problems"),
    ("mull over", "обмозговывать", "размышлять над", "mind", "C1", "to think about something for a long time"),
    ("phase out", "постепенно сворачивать", "фаза наружу", "change", "C1", "to stop using something gradually"),
    ("rope in", "втягивать, привлекать", "верёвка внутрь", "society", "C1", "to persuade someone to help"),
    ("shore up", "укреплять, подпирать", "берег вверх", "work", "C1", "to support something that may fail"),
    ("tone down", "смягчать, приглушать", "тон вниз", "communication", "C1", "to make something less strong"),
    ("weigh up", "взвешивать (варианты)", "взвешивать вверх", "mind", "C1", "to compare things before deciding"),
    ("wade through", "продираться сквозь (текст)", "брести сквозь", "school", "C1", "to read something long and dull"),
    ("whittle down", "постепенно сокращать", "строгать вниз", "change", "C1", "to reduce something little by little"),
    ("bear out", "подтверждать", "нести наружу", "mind", "C1", "to show that something is true"),
    ("hinge on", "зависеть от", "петля на", "mind", "C1", "to depend completely on something"),
    ("stave off", "предотвращать, отсрочивать", "отражать прочь", "change", "C1", "to keep something bad away for a time"),
    ("tide over", "помочь продержаться", "прилив над", "money", "C1", "to help someone through a difficult period"),
    ("wind up", "в итоге оказаться; сворачивать (дело)", "заводить вверх", "change", "C1", "to end in a particular situation"),
    ("egg on", "подначивать, подстрекать", "яйцо на", "people", "C1", "to encourage someone to do something silly"),
    ("reel off", "тараторить, выпаливать списком", "катушка прочь", "communication", "C1", "to say a list quickly from memory"),
    ("spell out", "разъяснять по пунктам", "произносить по буквам наружу", "communication", "C1", "to explain something in a very clear way"),
    ("branch out", "расширять дело, пробовать новое", "ветвь наружу", "work", "C1", "to start doing something new"),
]

# --- Идиомы ---------------------------------------------------------------
# Чего здесь принципиально нет: алкоголь, смерть, драки, оружие, секс, деньги
# «на взятку». Такие идиомы частотны, но детской базе не нужны.

IDIOMS = [
    ("a piece of cake", "проще простого", "кусок торта", "qualities", "B1", "something very easy to do"),
    ("once in a blue moon", "очень редко, раз в сто лет", "однажды в голубую луну", "time", "B1", "very rarely"),
    ("break the ice", "растопить лёд, начать разговор", "разбить лёд", "communication", "B1", "to make people feel less shy at a first meeting"),
    ("hit the books", "засесть за учёбу", "бить книги", "school", "B1", "to start studying hard"),
    ("under the weather", "неважно себя чувствовать", "под погодой", "health", "B1", "feeling slightly unwell"),
    ("keep an eye on", "присматривать за", "держать глаз на", "family", "B1", "to watch someone or something carefully"),
    ("cost an arm and a leg", "стоить целое состояние", "стоить руку и ногу", "money", "B1", "to be very expensive"),
    ("feel blue", "грустить, хандрить", "чувствовать синий", "feelings", "B1", "to feel sad"),
    ("be all ears", "внимательно слушать", "быть весь уши", "communication", "B1", "to be listening very carefully"),
    ("on cloud nine", "на седьмом небе от счастья", "на облаке девять", "feelings", "B1", "extremely happy"),
    ("rain cats and dogs", "лить как из ведра", "дождить кошками и собаками", "weather", "B1", "to rain very heavily"),
    ("hit the road", "отправиться в путь", "бить дорогу", "travel", "B1", "to start a journey"),
    ("break a leg", "ни пуха ни пера", "сломать ногу", "communication", "B1", "used to wish someone good luck"),
    ("better late than never", "лучше поздно, чем никогда", "лучше поздно, чем никогда", "time", "A2", "it is better to arrive late than not at all"),
    ("practice makes perfect", "повторение — мать учения", "практика делает совершенным", "school", "A2", "you get better at something by doing it often"),
    ("time flies", "время летит", "время летит", "time", "A2", "time passes very quickly"),
    ("never mind", "неважно, не бери в голову", "никогда не думай", "communication", "A2", "used to say that something is not important"),
    ("take your time", "не торопись", "возьми своё время", "time", "B1", "used to tell someone not to hurry"),
    ("no big deal", "ничего страшного", "не большая сделка", "communication", "B1", "not important, not a problem"),
    ("now and then", "время от времени", "сейчас и тогда", "time", "B1", "sometimes but not often"),
    ("so far so good", "пока всё идёт хорошо", "так далеко так хорошо", "change", "B1", "everything is fine up to now"),
    ("keep it up", "так держать", "держи это вверх", "school", "B1", "used to tell someone to continue doing well"),
    ("it's a small world", "мир тесен", "это маленький мир", "society", "B1", "used when you meet someone you know in an unexpected place"),
    ("actions speak louder than words", "судят по делам, а не по словам", "действия говорят громче слов", "society", "B1", "what you do matters more than what you say"),
    ("the early bird catches the worm", "кто рано встаёт, тому бог подаёт", "ранняя птица ловит червяка", "time", "B1", "the person who starts early gets the best result"),
    ("don't judge a book by its cover", "не суди по внешности", "не суди книгу по обложке", "qualities", "B1", "do not judge people by how they look"),
    ("two heads are better than one", "одна голова хорошо, а две лучше", "две головы лучше одной", "mind", "B1", "two people solve a problem better than one"),
    ("money doesn't grow on trees", "деньги на дороге не валяются", "деньги не растут на деревьях", "money", "B1", "money is not easy to get"),
    ("give someone a hand", "помочь кому-то", "дать кому-то руку", "people", "B1", "to help someone"),
    ("lend a hand", "подсобить, помочь", "одолжить руку", "people", "B1", "to help with a task"),
    ("keep your fingers crossed", "держать кулачки за кого-то", "держать пальцы скрещёнными", "feelings", "B1", "to hope that something good will happen"),
    ("know something by heart", "знать наизусть", "знать что-то сердцем", "school", "B1", "to remember something perfectly"),
    ("a couch potato", "лежебока, домосед", "диванная картошка", "people", "B1", "a person who watches a lot of television"),
    ("an early bird", "ранняя пташка, жаворонок", "ранняя птица", "people", "B1", "a person who gets up early"),
    ("a night owl", "сова, полуночник", "ночная сова", "people", "B1", "a person who stays awake late"),
    ("butterflies in your stomach", "бабочки в животе, волнение", "бабочки в животе", "feelings", "B1", "a nervous feeling before something important"),
    ("once and for all", "раз и навсегда", "однажды и навсегда", "time", "B1", "finally and completely"),

    ("a hot potato", "щекотливая тема", "горячая картошка", "society", "B2", "a subject that people find hard to discuss"),
    ("the ball is in your court", "теперь твой ход", "мяч на твоей половине корта", "communication", "B2", "it is your turn to act"),
    ("call it a day", "закончить на сегодня", "назвать это днём", "work", "B2", "to stop working for the day"),
    ("a blessing in disguise", "не было бы счастья, да несчастье помогло", "благословение в маскировке", "change", "B2", "something bad that turns out to be good"),
    ("every cloud has a silver lining", "нет худа без добра", "у каждой тучи серебряная подкладка", "feelings", "B2", "every bad situation has something good in it"),
    ("it's not rocket science", "это не бином Ньютона", "это не ракетная наука", "mind", "B2", "it is not difficult to understand"),
    ("get cold feet", "струсить в последний момент", "получить холодные ноги", "feelings", "B2", "to become afraid to do something planned"),
    ("from scratch", "с нуля", "с царапины", "actions", "B2", "from the very beginning, with nothing ready"),
    ("in a nutshell", "вкратце, в двух словах", "в ореховой скорлупе", "communication", "B2", "said in a very short way"),
    ("off the top of my head", "навскидку, не задумываясь", "с верхушки моей головы", "mind", "B2", "without checking or thinking long"),
    ("hit the nail on the head", "попасть в точку", "ударить по гвоздю по шляпке", "communication", "B2", "to say exactly the right thing"),
    ("beat around the bush", "ходить вокруг да около", "бить вокруг куста", "communication", "B2", "to avoid saying the main thing"),
    ("spill the beans", "проболтаться", "рассыпать бобы", "communication", "B2", "to tell a secret"),
    ("let the cat out of the bag", "выдать секрет", "выпустить кота из мешка", "communication", "B2", "to reveal a secret by accident"),
    ("the last straw", "последняя капля", "последняя соломинка", "feelings", "B2", "the last small problem that makes you give up"),
    ("a drop in the ocean", "капля в море", "капля в океане", "qualities", "B2", "a very small part of what is needed"),
    ("the tip of the iceberg", "верхушка айсберга", "кончик айсберга", "qualities", "B2", "the small visible part of a big problem"),
    ("see eye to eye", "сходиться во взглядах", "видеть глаз в глаз", "people", "B2", "to agree with someone"),
    ("pull someone's leg", "разыгрывать, подшучивать", "тянуть кого-то за ногу", "communication", "B2", "to tell someone something untrue as a joke"),
    ("break the news", "сообщить новость", "сломать новость", "communication", "B2", "to tell someone important news"),
    ("get the hang of", "приноровиться, освоить", "схватить свисание", "school", "B2", "to learn how to do something"),
    ("hang in there", "держись, не сдавайся", "висеть там", "feelings", "B2", "used to tell someone not to give up"),
    ("in the same boat", "в одной лодке", "в той же лодке", "society", "B2", "in the same difficult situation"),
    ("jump to conclusions", "делать поспешные выводы", "прыгать к выводам", "mind", "B2", "to decide too quickly without facts"),
    ("keep your chin up", "не вешать нос", "держи подбородок вверх", "feelings", "B2", "used to tell someone to stay cheerful"),
    ("miss the boat", "упустить момент", "пропустить лодку", "time", "B2", "to be too late for a chance"),
    ("on the same page", "понимать друг друга одинаково", "на той же странице", "communication", "B2", "agreeing about what is happening"),
    ("out of the blue", "как гром среди ясного неба", "из синевы", "change", "B2", "completely unexpectedly"),
    ("over the moon", "на седьмом небе", "над луной", "feelings", "B2", "very pleased about something"),
    ("pull yourself together", "взять себя в руки", "стянуть себя вместе", "feelings", "B2", "to become calm and in control again"),
    ("put yourself in someone's shoes", "поставить себя на чьё-то место", "встать в чужие ботинки", "mind", "B2", "to imagine how another person feels"),
    ("ring a bell", "что-то напоминать, казаться знакомым", "звонить в колокол", "mind", "B2", "to sound familiar"),
    ("under your nose", "под самым носом", "под твоим носом", "mind", "B2", "very close but not noticed"),
    ("up in the air", "ещё не решено, висит в воздухе", "вверху в воздухе", "change", "B2", "not decided yet"),
    ("a walk in the park", "плёвое дело", "прогулка в парке", "qualities", "B2", "something very easy"),
    ("you can say that again", "вот именно, полностью согласен", "ты можешь сказать это снова", "communication", "B2", "used to strongly agree"),
    ("save for a rainy day", "откладывать на чёрный день", "беречь на дождливый день", "money", "B2", "to keep money for a future need"),
    ("tighten your belt", "затянуть пояс потуже", "затянуть ремень", "money", "B2", "to spend less money than before"),
    ("make ends meet", "сводить концы с концами", "заставить концы встретиться", "money", "B2", "to have just enough money to live"),
    ("break the bank", "влететь в копеечку", "разорить банк", "money", "B2", "to cost more than you can afford"),
    ("worth its weight in gold", "на вес золота", "стоит своего веса в золоте", "qualities", "B2", "extremely useful or valuable"),
    ("a golden opportunity", "прекрасная возможность", "золотая возможность", "change", "B2", "a very good chance"),
    ("the best of both worlds", "и то и другое сразу", "лучшее из обоих миров", "qualities", "B2", "the advantages of two different things at once"),
    ("get down to business", "перейти к делу", "спуститься к делу", "work", "B2", "to start the serious work"),
    ("in the long run", "в конечном счёте", "в долгом беге", "time", "B2", "over a long period of time"),
    ("read between the lines", "читать между строк", "читать между строк", "mind", "B2", "to understand what is not said directly"),
    ("blow off steam", "выпустить пар", "выпустить пар", "feelings", "B2", "to get rid of anger in a harmless way"),
    ("cry over spilt milk", "плакать над пролитым молоком", "плакать над пролитым молоком", "feelings", "B2", "to be upset about something you cannot change"),
    ("get out of hand", "выйти из-под контроля", "выйти из руки", "change", "B2", "to become impossible to control"),
    ("lose track of time", "не замечать времени", "потерять след времени", "time", "B2", "to forget what time it is"),
    ("on the tip of my tongue", "вертится на языке", "на кончике моего языка", "communication", "B2", "almost remembered but not quite"),
    ("once in a lifetime", "раз в жизни", "однажды за жизнь", "time", "B2", "happening only once in your whole life"),
    ("out of the question", "исключено, не обсуждается", "вне вопроса", "communication", "B2", "completely impossible"),
    ("pick up the pace", "ускориться, поднажать", "поднять темп", "sports", "B2", "to start moving or working faster"),
    ("play with fire", "играть с огнём", "играть с огнём", "mind", "B2", "to do something risky"),
    ("rain or shine", "при любой погоде", "дождь или солнце", "weather", "B2", "whatever the weather is"),
    ("sleep on it", "утро вечера мудренее", "поспать на этом", "mind", "B2", "to wait until tomorrow before deciding"),
    ("speak your mind", "говорить прямо, что думаешь", "говорить свой разум", "communication", "B2", "to say your opinion openly"),
    ("the icing on the cake", "вишенка на торте", "глазурь на торте", "qualities", "B2", "an extra good thing added to something already good"),
    ("think outside the box", "мыслить нестандартно", "думать вне коробки", "mind", "B2", "to find new and unusual ideas"),
    ("when pigs fly", "когда рак на горе свистнет", "когда свиньи полетят", "time", "B2", "never"),
    ("easier said than done", "легче сказать, чем сделать", "легче сказано, чем сделано", "qualities", "B2", "harder to do than it sounds"),
    ("give it a go", "попробовать, рискнуть", "дать этому ход", "actions", "B2", "to try something"),
    ("go with the flow", "плыть по течению", "идти с потоком", "mind", "B2", "to accept things as they happen"),
    ("have a lot on your plate", "быть загруженным делами", "иметь много на тарелке", "work", "B2", "to have many things to do"),
    ("hold your horses", "не гони, погоди", "придержи лошадей", "communication", "B2", "used to tell someone to wait"),
    ("in the blink of an eye", "в мгновение ока", "в моргание глаза", "time", "B2", "extremely quickly"),
    ("keep a cool head", "сохранять хладнокровие", "держать холодную голову", "feelings", "B2", "to stay calm in a hard moment"),
    ("last but not least", "и наконец, что не менее важно", "последний, но не наименьший", "communication", "B2", "used before the last item, which is also important"),
    ("lose your temper", "выйти из себя", "потерять свой характер", "feelings", "B2", "to suddenly become angry"),
    ("mind your own business", "не лезь не в своё дело", "занимайся своим делом", "communication", "B2", "used to tell someone not to interfere"),
    ("on second thought", "если подумать, пожалуй", "по второй мысли", "mind", "B2", "after thinking about it again"),
    ("out of the ordinary", "необычный, из ряда вон", "вне обычного", "qualities", "B2", "different from what is usual"),
    ("the sky is the limit", "предела нет", "небо — предел", "change", "B2", "there is no limit to what is possible"),
    ("back to square one", "снова к началу", "назад на клетку номер один", "change", "B2", "back to the start with no progress"),
    ("a bird's eye view", "вид с высоты птичьего полёта", "вид птичьего глаза", "places", "B2", "a view from high above"),
    ("child's play", "детская забава, пустяк", "детская игра", "qualities", "B2", "something very easy to do"),
    ("a change of heart", "перемена во взглядах", "смена сердца", "feelings", "B2", "a change in your opinion or feelings"),
    ("second nature", "вторая натура, привычка", "вторая природа", "character", "B2", "something you do easily without thinking"),
    ("in good hands", "в надёжных руках", "в хороших руках", "people", "B2", "being cared for by someone you can trust"),

    ("once bitten, twice shy", "обжёгшись на молоке, дуешь на воду", "раз укушен — дважды пуглив", "mind", "C1", "after a bad experience you become careful"),
    ("burn the midnight oil", "работать допоздна", "жечь полуночное масло", "work", "C1", "to work or study late into the night"),
    ("bite off more than you can chew", "переоценить свои силы", "откусить больше, чем можешь прожевать", "mind", "C1", "to take on more than you can manage"),
    ("face the music", "отвечать за последствия", "встретить музыку", "society", "C1", "to accept the results of what you did"),
    ("learn the ropes", "войти в курс дела", "выучить верёвки", "work", "C1", "to learn how a job is done"),
    ("to make a long story short", "короче говоря", "чтобы сделать длинную историю короткой", "communication", "C1", "used before giving only the main point"),
    ("play it by ear", "действовать по обстоятельствам", "играть на слух", "mind", "C1", "to decide as the situation develops"),
    ("sit on the fence", "занимать выжидательную позицию", "сидеть на заборе", "mind", "C1", "to avoid choosing a side"),
    ("take it with a grain of salt", "относиться с недоверием", "принять с крупинкой соли", "mind", "C1", "to not fully believe something"),
    ("the tables have turned", "ситуация перевернулась", "столы повернулись", "change", "C1", "the situation has reversed"),
    ("wrap your head around", "уложить в голове, осознать", "обернуть голову вокруг", "mind", "C1", "to manage to understand something difficult"),
    ("add fuel to the fire", "подливать масла в огонь", "добавить топлива в огонь", "society", "C1", "to make a bad situation worse"),
    ("a storm in a teacup", "буря в стакане воды", "шторм в чашке чая", "society", "C1", "a lot of noise about something unimportant"),
    ("clear the air", "разрядить обстановку", "очистить воздух", "communication", "C1", "to talk openly and remove bad feeling"),
    ("cut corners", "халтурить, делать наспех", "срезать углы", "work", "C1", "to do something the quick cheap way"),
    ("go the extra mile", "сделать больше, чем требуется", "пройти лишнюю милю", "work", "C1", "to make more effort than expected"),
    ("put all your eggs in one basket", "ставить всё на одну карту", "положить все яйца в одну корзину", "mind", "C1", "to risk everything on one plan"),
    ("take the bull by the horns", "взять быка за рога", "взять быка за рога", "actions", "C1", "to deal with a hard problem directly"),
    ("the writing on the wall", "тревожные признаки", "надпись на стене", "mind", "C1", "clear signs that something will fail"),
    ("throw in the towel", "сдаться, выбросить полотенце", "бросить полотенце", "sports", "C1", "to admit that you have lost"),
    ("touch base", "связаться, свериться", "коснуться базы", "work", "C1", "to make short contact with someone"),
    ("bend over backwards", "из кожи вон лезть", "гнуться назад", "people", "C1", "to try extremely hard to help"),
    ("by the skin of your teeth", "еле-еле, чудом", "кожей своих зубов", "change", "C1", "only just, very narrowly"),
    ("hit the ground running", "сразу взяться за дело", "коснуться земли уже на бегу", "work", "C1", "to start a new task at full speed"),
    ("keep a low profile", "держаться в тени", "держать низкий профиль", "people", "C1", "to avoid attention"),
    ("let sleeping dogs lie", "не буди лихо, пока тихо", "пусть спящие собаки лежат", "mind", "C1", "to leave a settled problem alone"),
    ("make a mountain out of a molehill", "делать из мухи слона", "делать гору из кротовой кучки", "mind", "C1", "to treat a small problem as a big one"),
    ("pay through the nose", "платить втридорога", "платить через нос", "money", "C1", "to pay far too much"),
    ("second to none", "непревзойдённый, лучше всех", "второй ни для кого", "qualities", "C1", "better than all the others"),
    ("take a rain check", "перенести на другой раз", "взять дождевой талон", "time", "C1", "to refuse an invitation but ask for a later one"),
    ("through thick and thin", "и в горе, и в радости", "сквозь толстое и тонкое", "family", "C1", "in good times and bad times alike"),
    ("under your belt", "за плечами (об опыте)", "под ремнём", "work", "C1", "already achieved and kept as experience"),
    ("up to scratch", "на должном уровне", "до царапины", "qualities", "C1", "good enough to meet the standard"),
    ("water under the bridge", "дело прошлое", "вода под мостом", "time", "C1", "something past that no longer matters"),
    ("a whole new ball game", "совсем другое дело", "совсем новая игра в мяч", "change", "C1", "a completely different situation"),
    ("wear many hats", "совмещать много ролей", "носить много шляп", "work", "C1", "to do several different jobs at once"),
    ("with flying colours", "с блеском, на отлично", "с летящими флагами", "school", "C1", "with great success"),
    ("your guess is as good as mine", "понятия не имею, как и ты", "твоя догадка не хуже моей", "communication", "C1", "I do not know any more than you do"),
    ("cross that bridge when you come to it", "решим, когда дойдём", "перейти этот мост, когда до него дойдёшь", "mind", "C1", "to deal with a problem only when it happens"),
    ("don't count your chickens before they hatch", "цыплят по осени считают", "не считай цыплят, пока не вылупились", "mind", "C1", "do not plan on something before it is certain"),
    ("leave no stone unturned", "перепробовать все способы", "не оставить ни одного камня неперевёрнутым", "actions", "C1", "to try every possible way"),
    ("at the drop of a hat", "по первому же поводу, мгновенно", "при падении шляпы", "time", "C1", "immediately, without needing a reason"),
    ("break new ground", "открывать новые горизонты", "ломать новую землю", "work", "C1", "to do something no one has done before"),
    ("to make matters worse", "что ещё хуже", "чтобы сделать дела хуже", "communication", "C1", "used to add another bad thing"),
    ("word of mouth", "сарафанное радио", "слово рта", "communication", "C1", "information passed from person to person"),
    ("you name it", "и чего только нет", "ты назови это", "communication", "C1", "used to say that everything is included"),
    ("draw the line", "провести черту, установить предел", "провести линию", "mind", "C1", "to set a limit you will not pass"),
]

# --- Устойчивые сочетания -------------------------------------------------
# Здесь важна не идиоматичность, а сочетаемость: по-русски «сильный дождь», а
# по-английски именно heavy rain, а не strong rain. Ошибка в выборе глагола
# (do/make/take/have) — самая частая у русскоязычных школьников.

COLLOC = [
    ("do homework", "делать домашнее задание", "", "school", "A1", "to do the school work given for home"),
    ("do the dishes", "мыть посуду", "", "home", "A2", "to wash the plates and cups after a meal"),
    ("do the shopping", "делать покупки", "", "home", "A2", "to buy the food and things a home needs"),
    ("do exercise", "заниматься спортом", "", "sports", "A2", "to move your body to stay healthy"),
    ("make the bed", "заправлять кровать", "", "home", "A2", "to make a bed tidy after sleeping"),
    ("make a cake", "печь торт", "", "food", "A1", "to prepare and bake a cake"),
    ("make a mistake", "сделать ошибку", "", "school", "A2", "to do something wrong by accident"),
    ("make friends", "заводить друзей", "", "people", "A2", "to start new friendships"),
    ("make noise", "шуметь", "", "home", "A2", "to produce loud sounds"),
    ("take a photo", "фотографировать", "", "art", "A1", "to use a camera to make a picture"),
    ("take a shower", "принимать душ", "", "home", "A1", "to wash yourself under a shower"),
    ("take a bus", "ехать на автобусе", "", "travel", "A1", "to travel by bus"),
    ("take a seat", "присесть, занять место", "", "communication", "A2", "to sit down"),
    ("take a break", "сделать перерыв", "", "work", "A2", "to stop working for a short time"),
    ("have breakfast", "завтракать", "", "food", "A1", "to eat the first meal of the day"),
    ("have lunch", "обедать", "", "food", "A1", "to eat the midday meal"),
    ("have dinner", "ужинать", "", "food", "A1", "to eat the evening meal"),
    ("have a good time", "хорошо провести время", "", "feelings", "A2", "to enjoy yourself"),
    ("have a look", "взглянуть", "", "actions", "A2", "to look at something quickly"),
    ("have a rest", "отдохнуть", "", "health", "A2", "to stop and relax for a while"),
    ("have a party", "устроить праздник", "", "society", "A2", "to invite people and celebrate"),
    ("watch television", "смотреть телевизор", "", "home", "A1", "to look at television programmes"),
    ("play football", "играть в футбол", "", "sports", "A1", "to take part in a game of football"),
    ("play the piano", "играть на пианино", "", "art", "A1", "to make music on a piano"),
    ("play a game", "играть в игру", "", "sports", "A1", "to take part in a game"),
    ("ride a bike", "кататься на велосипеде", "", "sports", "A1", "to travel on a bicycle"),
    ("go shopping", "ходить по магазинам", "", "city", "A1", "to go out to buy things"),
    ("go swimming", "ходить плавать", "", "sports", "A1", "to go somewhere to swim"),
    ("go for a walk", "пойти погулять", "", "health", "A1", "to walk somewhere for pleasure"),
    ("go to bed", "ложиться спать", "", "home", "A1", "to get into bed to sleep"),
    ("brush your teeth", "чистить зубы", "", "health", "A1", "to clean your teeth with a brush"),
    ("wash your hands", "мыть руки", "", "health", "A1", "to clean your hands with water and soap"),
    ("tell a story", "рассказывать историю", "", "communication", "A1", "to say a story to someone"),
    ("tell the truth", "говорить правду", "", "communication", "A2", "to say what is really true"),
    ("tell a joke", "рассказать шутку", "", "communication", "A2", "to say something funny"),
    ("ask a question", "задать вопрос", "", "school", "A1", "to say something you want answered"),
    ("give an answer", "дать ответ", "", "school", "A2", "to say the answer to a question"),
    ("get dressed", "одеваться", "", "clothes", "A1", "to put your clothes on"),
    ("get ready", "собираться, готовиться", "", "time", "A1", "to prepare for something"),
    ("catch a bus", "успеть на автобус", "", "travel", "A2", "to get on a bus before it leaves"),
    ("keep a promise", "сдержать обещание", "", "character", "A2", "to do what you promised"),
    ("break a promise", "нарушить обещание", "", "character", "A2", "to fail to do what you promised"),
    ("set the table", "накрывать на стол", "", "home", "A2", "to put plates and forks on a table"),
    ("feed the cat", "кормить кота", "", "animals", "A1", "to give food to a cat"),
    ("fast food", "фастфуд, быстрая еда", "", "food", "A2", "food that is cooked and served very quickly"),
    ("best friend", "лучший друг", "", "people", "A2", "the friend you like most"),
    ("free time", "свободное время", "", "time", "A2", "time when you have nothing you must do"),
    ("good news", "хорошие новости", "", "communication", "A2", "news that makes people happy"),
    ("long way", "далеко, долгий путь", "", "travel", "A2", "a big distance"),
    ("loud voice", "громкий голос", "", "communication", "A2", "a voice that is easy to hear"),

    ("make a decision", "принять решение", "", "mind", "B1", "to decide something"),
    ("make a plan", "составить план", "", "mind", "B1", "to decide what you will do"),
    ("make progress", "делать успехи", "", "school", "B1", "to get better at something"),
    ("make an excuse", "придумать оправдание", "", "communication", "B1", "to give a reason for not doing something"),
    ("make a suggestion", "внести предложение", "", "communication", "B1", "to say an idea for others to consider"),
    ("do your best", "стараться изо всех сил", "", "character", "B1", "to try as hard as you can"),
    ("do research", "проводить исследование", "", "school", "B1", "to study a subject carefully"),
    ("do a favour", "оказать услугу", "", "people", "B1", "to do something kind for someone"),
    ("take notes", "делать записи, конспектировать", "", "school", "B1", "to write down what you hear or read"),
    ("take part", "принимать участие", "", "society", "B1", "to join an activity with others"),
    ("take place", "происходить, состояться", "", "time", "B1", "to happen"),
    ("take care", "беречь себя, быть осторожным", "", "health", "B1", "to be careful"),
    ("take a risk", "рисковать", "", "mind", "B1", "to do something that may go wrong"),
    ("take an exam", "сдавать экзамен", "", "school", "B1", "to do an official test"),
    ("take advice", "прислушаться к совету", "", "mind", "B1", "to do what someone advises"),
    ("pay attention", "обращать внимание", "", "mind", "B1", "to listen and watch carefully"),
    ("pay a visit", "нанести визит", "", "people", "B1", "to go and see someone"),
    ("keep a secret", "хранить секрет", "", "character", "B1", "to not tell other people something"),
    ("keep calm", "сохранять спокойствие", "", "feelings", "B1", "to stay calm"),
    ("keep in touch", "поддерживать связь", "", "communication", "B1", "to go on writing or calling someone"),
    ("give advice", "давать совет", "", "communication", "B1", "to tell someone what you think they should do"),
    ("give a speech", "выступать с речью", "", "communication", "B1", "to speak in front of a group"),
    ("give permission", "дать разрешение", "", "society", "B1", "to allow someone to do something"),
    ("give an example", "привести пример", "", "school", "B1", "to name one case that shows an idea"),
    ("save time", "экономить время", "", "time", "B1", "to use less time than usual"),
    ("save money", "копить деньги", "", "money", "B1", "to keep money instead of spending it"),
    ("waste time", "тратить время впустую", "", "time", "B1", "to use time badly"),
    ("spend money", "тратить деньги", "", "money", "B1", "to use money to buy things"),
    ("earn money", "зарабатывать деньги", "", "money", "B1", "to get money for your work"),
    ("lose weight", "худеть", "", "health", "B1", "to become lighter"),
    ("gain weight", "набирать вес", "", "health", "B1", "to become heavier"),
    ("catch a cold", "простудиться", "", "health", "B1", "to get a cold"),
    ("get a job", "устроиться на работу", "", "work", "B1", "to start working somewhere"),
    ("get married", "жениться, выходить замуж", "", "family", "B1", "to become husband and wife"),
    ("get lost", "заблудиться", "", "travel", "B1", "to stop knowing where you are"),
    ("get in touch", "связаться", "", "communication", "B1", "to contact someone"),
    ("change your mind", "передумать", "", "mind", "B1", "to make a different decision"),
    ("solve a problem", "решать задачу, решать проблему", "", "mind", "B1", "to find an answer to a problem"),
    ("follow the rules", "соблюдать правила", "", "society", "B1", "to do what the rules say"),
    ("follow instructions", "следовать инструкции", "", "school", "B1", "to do exactly what you are told"),
    ("offer help", "предложить помощь", "", "people", "B1", "to say you are ready to help"),
    ("heavy rain", "сильный дождь", "", "weather", "B1", "rain that falls hard and fast"),
    ("heavy traffic", "плотное движение на дорогах", "", "city", "B1", "many cars moving slowly"),
    ("strong coffee", "крепкий кофе", "", "food", "B1", "coffee with a lot of taste"),
    ("strong wind", "сильный ветер", "", "weather", "B1", "wind that blows hard"),
    ("close friend", "близкий друг", "", "people", "B1", "a friend you trust a lot"),
    ("hard work", "тяжёлый труд", "", "work", "B1", "work that needs a lot of effort"),
    ("bright idea", "блестящая идея", "", "mind", "B1", "a very clever idea"),
    ("high price", "высокая цена", "", "money", "B1", "a price that is a lot of money"),
    ("deep sleep", "глубокий сон", "", "health", "B1", "sleep from which it is hard to wake"),
    ("bad habit", "дурная привычка", "", "character", "B1", "something bad that you often do"),
    ("hard time", "трудный период", "", "feelings", "B1", "a difficult time in your life"),
    ("main reason", "главная причина", "", "mind", "B1", "the most important reason"),
    ("warm welcome", "тёплый приём", "", "people", "B1", "a friendly greeting"),
    ("deep breath", "глубокий вдох", "", "health", "B1", "a big amount of air taken in"),
    ("busy street", "оживлённая улица", "", "city", "B1", "a street with many people and cars"),

    ("make an effort", "приложить усилие", "", "character", "B2", "to try hard to do something"),
    ("make an impression", "произвести впечатление", "", "people", "B2", "to make people notice and remember you"),
    ("make a difference", "изменить положение к лучшему", "", "society", "B2", "to have a real effect on something"),
    ("make sense", "иметь смысл", "", "mind", "B2", "to be clear and reasonable"),
    ("make a living", "зарабатывать на жизнь", "", "money", "B2", "to earn enough money to live"),
    ("take responsibility", "брать на себя ответственность", "", "character", "B2", "to accept that something is your duty"),
    ("take advantage of", "воспользоваться (случаем)", "", "mind", "B2", "to use a chance well"),
    ("take action", "принимать меры", "", "society", "B2", "to start doing something about a problem"),
    ("take into account", "принимать во внимание", "", "mind", "B2", "to think about something when deciding"),
    ("take steps", "предпринимать шаги", "", "work", "B2", "to do the things needed to reach a goal"),
    ("reach an agreement", "прийти к соглашению", "", "society", "B2", "to agree after talking"),
    ("reach a decision", "прийти к решению", "", "mind", "B2", "to decide after thinking"),
    ("meet a deadline", "уложиться в срок", "", "work", "B2", "to finish work in time"),
    ("meet the requirements", "соответствовать требованиям", "", "work", "B2", "to have everything that is asked for"),
    ("meet expectations", "оправдать ожидания", "", "work", "B2", "to be as good as people hoped"),
    ("raise a question", "поднять вопрос", "", "communication", "B2", "to bring up something to discuss"),
    ("raise awareness", "привлечь внимание к проблеме", "", "society", "B2", "to make people know about something"),
    ("raise money", "собрать деньги", "", "money", "B2", "to collect money for a purpose"),
    ("draw a conclusion", "сделать вывод", "", "mind", "B2", "to decide what the facts show"),
    ("draw attention", "привлечь внимание", "", "communication", "B2", "to make people notice something"),
    ("set a goal", "поставить цель", "", "mind", "B2", "to decide what you want to achieve"),
    ("set an example", "подать пример", "", "character", "B2", "to behave so that others can copy you"),
    ("set a record", "установить рекорд", "", "sports", "B2", "to do better than anyone before"),
    ("break a record", "побить рекорд", "", "sports", "B2", "to do better than the best result so far"),
    ("break a habit", "избавиться от привычки", "", "character", "B2", "to stop doing something you often do"),
    ("break the rules", "нарушать правила", "", "society", "B2", "to do what the rules forbid"),
    ("gain experience", "набираться опыта", "", "work", "B2", "to slowly learn by doing something"),
    ("gain confidence", "обрести уверенность", "", "feelings", "B2", "to start believing in yourself"),
    ("lose patience", "терять терпение", "", "feelings", "B2", "to stop being patient"),
    ("lose interest", "терять интерес", "", "feelings", "B2", "to stop caring about something"),
    ("run a business", "вести дело, управлять бизнесом", "", "work", "B2", "to be in charge of a company"),
    ("run a risk", "идти на риск", "", "mind", "B2", "to put yourself in a risky position"),
    ("hold a meeting", "проводить встречу", "", "work", "B2", "to organise and lead a meeting"),
    ("hold your breath", "задержать дыхание", "", "sports", "B2", "to stop breathing for a moment"),
    ("play a role", "играть роль", "", "society", "B2", "to have a part in something"),
    ("bear in mind", "иметь в виду", "", "mind", "B2", "to remember something important"),
    ("express an opinion", "высказать мнение", "", "communication", "B2", "to say what you think"),
    ("share an opinion", "поделиться мнением", "", "communication", "B2", "to tell others what you think"),
    ("face a problem", "столкнуться с проблемой", "", "change", "B2", "to have to deal with a problem"),
    ("cause a problem", "создавать проблему", "", "change", "B2", "to make a problem happen"),
    ("provide support", "оказывать поддержку", "", "society", "B2", "to give help to someone"),
    ("accept an offer", "принять предложение", "", "work", "B2", "to say yes to what is offered"),
    ("keep track of", "отслеживать, держать на контроле", "", "work", "B2", "to know what is happening with something"),
    ("common sense", "здравый смысл", "", "mind", "B2", "the normal ability to think sensibly"),
    ("wide range", "широкий выбор, широкий спектр", "", "qualities", "B2", "many different kinds of something"),
    ("key factor", "ключевой фактор", "", "mind", "B2", "the most important cause of a result"),
    ("major change", "серьёзное изменение", "", "change", "B2", "a big and important change"),
    ("significant difference", "существенная разница", "", "qualities", "B2", "a difference that matters"),
    ("valuable experience", "ценный опыт", "", "work", "B2", "experience that is worth a lot"),
    ("serious mistake", "серьёзная ошибка", "", "school", "B2", "a mistake with big results"),
    ("strong argument", "веский довод", "", "communication", "B2", "a reason that is hard to answer"),
    ("clear evidence", "явное доказательство", "", "mind", "B2", "facts that plainly show something"),
    ("urgent need", "насущная необходимость", "", "society", "B2", "a need that must be met at once"),
    ("tight schedule", "плотный график", "", "time", "B2", "a plan with very little spare time"),

    ("strike a balance", "найти равновесие", "", "mind", "C1", "to find a fair middle between two things"),
    ("take the initiative", "взять инициативу на себя", "", "character", "C1", "to act first without being asked"),
    ("exceed expectations", "превзойти ожидания", "", "work", "C1", "to be better than people hoped"),
    ("pose a threat", "представлять угрозу", "", "society", "C1", "to be a possible danger"),
    ("bridge the gap", "устранить разрыв", "", "society", "C1", "to bring two different things closer"),
    ("lay the foundation", "заложить основу", "", "work", "C1", "to prepare the base for something bigger"),
    ("shed light on", "пролить свет на", "", "mind", "C1", "to make something easier to understand"),
    ("draw a distinction", "проводить различие", "", "mind", "C1", "to show how two things differ"),
    # «draw the line» отсюда убрано: это идиома (значение из частей не выводится),
    # и живёт она в списке IDIOMS — там у неё есть буквальный перевод.
    ("gain momentum", "набирать обороты", "", "change", "C1", "to grow faster and stronger"),
    ("broaden your horizons", "расширять кругозор", "", "mind", "C1", "to learn about new things and places"),
    ("meet a challenge", "справиться с трудной задачей", "", "work", "C1", "to deal well with a hard task"),
    ("voice concerns", "выразить озабоченность", "", "communication", "C1", "to say openly that you are worried"),
    ("reach a compromise", "прийти к компромиссу", "", "society", "C1", "to agree by both sides giving up something"),
    ("set a precedent", "создать прецедент", "", "society", "C1", "to do something that later cases will follow"),
    ("take precedence", "иметь приоритет", "", "work", "C1", "to be more important than something else"),
    ("bear responsibility", "нести ответственность", "", "society", "C1", "to be the one who must answer for something"),
    ("come to terms with", "смириться с", "", "feelings", "C1", "to accept something difficult"),
    ("raise the bar", "поднять планку", "", "work", "C1", "to set a higher standard"),
]

SETS = [("phrasal", PHRASAL), ("idiom", IDIOMS), ("colloc", COLLOC)]
