"""Сгенерировано tools/wikidata_picks.py — руками не править.

Слово -> файл P18 сущности Викиданных, у которой английская
подпись равна слову, а русская совпала по основе с переводом
из базы. Приоритет ниже picks_auto и ручного PICKS."""

AUTO_PICKS2 = {
    'acquaintance': ('file:Reunion of 3 Secret Service agents.jpg',),
    'addition': ('file:AdditionShapes.svg',),
    'anachronism': ('file:2016-07-23 15-54-17 reconstit-belfort.jpg',),
    'analysis': ("file:Adriaen Van Ostade - L'Analyse - PDUT921 - Musée des Beaux-Arts de la ville de Paris.jpg",),
    'anonymous': ('file:Image of none.svg',),
    'antigen': ('file:Antibody.svg',),
    'antiquarian': ('file:Johann Bauer Antiquitätenhändler.jpg',),
    'archipelago': ('file:Galapagos archipelago 250m.jpg',),
    'article': ('file:New York Times 1918-08-19.jpg',),
    'astrology': ('file:Astro signs.svg',),
    'athlete': ('file:1500finalM1.JPG',),
    'auction': ('file:Crosby Garrett Helmet on auction at Christies.jpg',),
    'authority': ('file:AuthorityOfLaw.JPG',),
    'baseball': ('file:Zack Greinke on July 29, 2009.jpg',),
    'bathroom': ('file:Restaurant bathroom with two-way mirror.jpg',),
    'beam': ('file:Balken.jpg',),
    'bear': ('file:Coat of Arms of Yaroslavl (1995, mono).png',),
    'bedroom': ('file:Berlin Villa Borsig Tegel asv2019-08 img09.jpg',),
    'bell': ('file:Church bell cutaway.png',),
    'biology': ('file:Biology-0001.jpg',),
    'black': ('file:Color icon black.svg',),
    'blackmail': ('file:Capon-Minerbo Blackmail Note.jpg',),
    'blade': ('file:Whale knife hg.jpg',),
    'blanket': ('file:Filmmaking of "Black Thursday" on ulica Świętojańska in Gdynia - 24.jpg',),
    'blindfold': ('file:Blind Justice (2830780815).jpg',),
    'blog': ('file:BlogActive.com Screenshot 2004.jpg',),
    'blue': ('file:Color icon blue.svg',),
    'body': ('file:The human body and health - an elementary text-book of essential anatomy, applied physiology and practical hygiene for schools (1908) (14586547287).jpg',),
    'border': ('file:Finnish border sign Kilpisjarvi.JPG',),
    'bowl': ('file:Ancient Roman clay bowl.jpg',),
    'box': ('file:Elaborate wood box Tom Tanaka.JPG',),
    'boy': ('file:Giulio del Torre Zwei Kartenspieler.jpg',),
    'brother': ('file:Brothers.jpg',),
    'brown': ('file:Color icon brown.svg',),
    'bubble': ('file:Soda bubbles macro.jpg',),
    'budget': ('file:Brooklyn Museum - Comme Sisyphe - Honoré Daumier.jpg',),
    'burn': ('file:Brandwond-graad2.JPG',),
    'cabbage': ('file:Aesthetic Cabage.jpg',),
    'cabinet': ('file:Schrank2.jpg',),
    'campus': ('file:Aerial View BITS Pilani, 2014.png',),
    'canoe': ('file:Boat on Euphrates.jpg',),
    'challenge': ('file:Balancing on great white balls.jpg',),
    'championship': ('file:Secondo scudetto schio.jpg',),
    'channel': ('file:Comm Channel.svg',),
    'chemistry': ('file:Chemicals in flasks.jpg',),
    'chimney': ('file:Bytom EC Szombierki chimney E 2023.jpg',),
    'circus': ('file:Circus Ronaldo door Dirk Annemans.jpg',),
    'clan': ('file:Clan Chattan lands affected by Earldoms circa 17th century.jpg',),
    'coach': ('file:Dogos Waterpolo equipo Hot Dogos en el mundial IGLA+ 2024.jpg',),
    'collector': ('file:Largest collection of Converse All-Stars.JPG',),
    'color': ('file:Colouring pencils.jpg',),
    'comedy': ('file:Comedyicon PL.png',),
    'community': ('file:Bigdayout crowd2.jpg',),
    'company': ('file:Carlos Luis Michel Fumero - Equipo de Aducarga.jpg',),
    'computer': ('file:Apple II Plus, Museum of the Moving Image.jpg',),
    'consent': ('file:Oberlin Consent Initiative.jpg',),
    'consumer': ('file:People are buying fruits.jpg',),
    'contempt': ('file:Pavel Fedotov - The fresh cavalier - Google Art Project.jpg',),
    'controversy': ('file:Meggendorfer Wenn Gelehrte streiten.jpg',),
    'conversation': ('file:PManeg 0720-10 B Oudenaarde.jpg',),
    'corporation': ('file:Ralph Allen making a speech to the Corporation of Bath. Wellcome V0011283.jpg',),
    'costume': ('file:Audrey Hepburn My Fair Lady Dress.jpg',),
    'country': ('file:CIA WorldFactBook-Political world.png',),
    'courage': ('file:Raevsky saltanovka.jpg',),
    'courthouse': ('file:Vue du palais de justice de Bruxelles.jpg',),
    'cowboy': ('file:Music of the Plains (mural study, Kilgore, Texas Post Office) SAAM-1974.28.333 1.jpg',),
    'cup': ('file:Kaffeetasse halbhoch Golddekor 05, KPM.jpg',),
    'cushion': ('file:Cushions.jpg',),
    'cut': ('file:Schnittwunden.JPG',),
    'danger': ('file:Ravak Turbo cleaner GHS labelling.jpg',),
    'data': ('file:Sonar tracking of tungsten ball underneath research vessel for calibration (16824332958).jpg',),
    'debt': ('file:1979 $10,000 Treasury Bond .jpg',),
    'desire': ('file:Jacob Jordaens - Susanna and the Elders - Google Art Project.jpg',),
    'dialogue': ("file:Plato and Aristotle dialectics by Luca della Robbia-Museo dell'Opera del Duomo-Florence.jpg",),
    'dictation': ('file:Il dettato.jpg',),
    'diet': ('file:FoodSourcesOfMagnesium.jpg',),
    'differential': ('file:NonSynchronousGearBoxSF.jpg',),
    'disk': ('file:Disko.png',),
    'doubt': ('file:Rae, Henrietta - Doubts - 1886.jpg',),
    'earth': ('file:Alchemical earth symbol (fixed width).svg',),
    'economy': ('file:Grand-Bazaar Shop.jpg',),
    'education': ('file:1887 Bettannier Der Schwarze Fleck anagoria.jpg',),
    'elephant': ('file:178 Male African bush elephant in Etosha National Park Photo by Giles Laurent.jpg',),
    'elite': ('file:The Royal Feast of Belshazzar Blaine and the Money Kings (1884).jpg',),
    'empire': ('file:Roman Empire Trajan 117AD.png',),
    'engagement': ('file:Love Zambia.jpg',),
    'ensemble': ('file:John Galliano ensemble. Dress of the Year, 1987.jpg',),
    'enterprise': ('file:Wolfsburg VW-Werk.jpg',),
    'envelope': ('file:Briefumschlag (fcm).jpg',),
    'equipment': ('file:Electronics workbench.jpg',),
    'essay': ('file:An Essay on the Principle of Population.jpg',),
    'ethics': ('file:Rage-and-anger-fresco.jpg',),
    'etiquette': ('file:Cinema etiquette title card.jpg',),
    'euthanasia': ('file:Intracardial-injection-rat.JPG',),
    'evacuation': ('file:Rita evacuees from Houston Texas September 21 2005.jpg',),
    'evolution': ("file:L'origine de l'évolution.jpg",),
    'explorer': ('file:Landing of Columbus (2).jpg',),
    'eye': ('file:201405 eye.png',),
    'fact': ('file:FACTS ubt 2.JPG',),
    'factory': ('file:Workers in the fuse factory Woolwich Arsenal Flickr 4615367952 d40a18ec24 o.jpg',),
    'fairy': ('file:Falero Luis Ricardo Lily Fairy 1888.jpg',),
    'farmer': ('file:Ueberladewagen.jpg',),
    'fashion': ('file:E1266601 (5398889640).jpg',),
    'female': ('file:Venus symbol.svg',),
    'fiction': ('file:Alice par John Tenniel 30.png',),
    'field': ('file:VFPt charges plus minus thumb.svg',),
    'filter': ('file:FilterDiagram.svg',),
    'fingerprint': ('file:Fingerprintforcriminologystubs.jpg',),
    'fist': ('file:Human fist from three sides.jpg',),
    'float': ('file:Mechanical float switch waterpool.jpg',),
    'friend': ('file:H. Magnus Olsson, Jens O. Z. Ehrs & Emil Eikner 2005.jpg',),
    'fuel': ('file:Fire, Fireplace, Rostov-on-Don, Russia.jpg',),
    'function': ('file:Exp re.png',),
    'fundamental': ('file:Root of a major chord on C.png',),
    'game': ('file:Les joueurs de cartes de P. Cézanne (Fondation Vuitton, Paris) (33568651718).jpg',),
    'gene': ('file:Gene structure eukaryote 2 annotated.svg',),
    'genius': ('file:Vindobona Hoher Markt-92.JPG',),
    'giant': ('file:DnD Giant.png',),
    'girl': ('file:Anita Rée - Kopf eines Mädchens.jpg',),
    'glass': ('file:Drinkware.jpg',),
    'goal': ('file:Millennium Development Goals, UN Headquarters, New York City, New York - 20080501.jpg',),
    'gossip': ('file:Eugene de Blaas The Friendly Gossips.jpg',),
    'government': ("file:De ministers die deel uitmaken van het derde kabinet Van Agt op de trappen van Paleis Huis ten Bosch in 's-Gravenhage. D - SFA001009248.jpg",),
    'graffiti': ('file:Kartu Chufu01.JPG',),
    'gray': ('file:Grey eye G5wCD.jpg',),
    'green': ('file:Color icon green.svg',),
    'group': ('file:Rubiks revenge tilt.jpg',),
    'hair': ('file:Borsten ausgewachsenes Mangalitza-Schwein.JPG',),
    'health': ('file:Star of life2.svg',),
    'heavy': ('file:Martian Moon Orbiting the Red Planet.jpg',),
    'helmet': ('file:1581heaumeLambrequinsBARA.PNG',),
    'history': ('file:Nikolaos Gyzis - Historia.jpg',),
    'hockey': ('file:Floorball game.jpg',),
    'holiday': ('file:Carnaval 2014 - Rio de Janeiro (12973844805).jpg',),
    'hood': ('file:Bonnet raised Saab 9-5.JPG',),
    'horoscope': ('file:Astro3.png',),
    'hour': ('file:AnalogClockAnimation1 2hands 1h in 6sec.gif',),
    'household': ('file:Aime Pez Familienidylle 1839.jpg',),
    'housewife': ('file:HOUSEWIFE IN THE KITCHEN OF HER MOBILE HOME IN ONE OF THE TRAILER PARKS. THE TWO PARKS WERE CREATED IN RESPONSE TO... - NARA - 558298.jpg',),
    'husband': ('file:Prince Manga Bell and favorite wives.jpg',),
    'idea': ('file:Pictofigo - Idea.png',),
    'immigration': ('file:Inmigrantes europeos llegando a Argentina.jpg',),
    'inequality': ('file:Linear Programming Feasible Region.svg',),
    'information': ('file:Structure of the Universe.jpg',),
    'institution': ('file:RISW Building.jpg',),
    'intellectual': ('file:Goethe (Stieler 1828).jpg',),
    'interior': ('file:Haringrokerij - 335312 - onroerenderfgoed.jpg',),
    'interpreter': ('file:Interpreters (01113765) (9840848393).jpg',),
    'inventor': ('file:Dave Warren with BlackBox Prototype.jpg',),
    'investment': ('file:Norblin Factory Redevelopment under construction, 8.jpg',),
    'jazz': ('file:Louis Armstrong restored.jpg',),
    'jury': ('file:The Jury (1861).jpg',),
    'kilt': ('file:Plaid Kilt Nontraditional.jpg',),
    'kiss': ('file:El Beso (Pinacoteca de Brera, Milán, 1859).jpg',),
    'lamp': ('file:Oil and electric lamp.jpg',),
    'large': ('file:Brach humerus.jpg',),
    'lavender': ('file:Solid lavender.svg',),
    'lead': ('file:Lead electrolytic and 1cm3 cube.jpg',),
    'legislation': ('file:Constitution of the United States - DPLA - 9ca804144bd5965e992ae3528bc3c6a3 (page 1).jpg',),
    'legislature': ('file:Palace of Westminster, London - Feb 2007.jpg',),
    'lesson': ('file:Estamos en el salón.jpg',),
    'lever': ('file:Hefboom.jpg',),
    'libertarian': ('file:Anarchist placard, 2011.jpg',),
    'liver': ('file:Leber Schaf.jpg',),
    'logic': ('file:Discourse-into-the-night.jpg',),
    'loneliness': ('file:Asylbewerber03.jpg',),
    'luck': ('file:A postcard illustrating a soldier sending good luck and wish Wellcome V0016596.jpg',),
    'lung': ('file:Thorax Lung 3d from ct scans.jpg',),
    'lyrics': ('file:Song lyrics about Namazu, the giant catfish who causes earthquakes (13470133804).jpg',),
    'map': ('file:Btv1b530849639 plan du port et de la ville de Brest 1855 restored.jpg',),
    'mathematics': ('file:Mathematics.png',),
    'mayor': ('file:Femme Maire 2.jpg',),
    'medication': ('file:VariousPills.jpg',),
    'memory': ('file:Ripa - Iconologie - 1643 - p. 107- memoire.jpg',),
    'merchant': ('file:A merchant making up the account.jpg',),
    'mermaid': ('file:Mermaid (Heraldry).svg',),
    'message': ('file:Mere, The Walnut Tree Inn, Sign of the times - geograph.org.uk - 6638836.jpg',),
    'messiah': ('file:Cristo Aurea Solar.jpg',),
    'metaphor': ('file:Puck magazine cover 2 May 1894 - In the cyclone cellar, waiting for fair weather.jpg',),
    'monster': ('file:A fantastic monster; a cyclops with multiple heads and arms Wellcome V0007455.jpg',),
    'motion': ('file:Simple harmonic oscillator.gif',),
    'music': ('file:Op27 1 seg mov.png',),
    'noon': ('file:Big Ben um 12 Uhr.jpg',),
    'normal': ('file:Normal vectors2.svg',),
    'north': ('file:CompassRose (mul) 16 blue N.svg',),
    'ocean': ('file:Ocean beach at low tide against the sun.jpg',),
    'opposition': ('file:Positional astronomy.svg',),
    'organism': ('file:E. coli Bacteria (7316101966).jpg',),
    'paddle': ('file:Double bentshaft paddle wood.jpg',),
    'panel': ('file:Pannåer från Beckers - SKANM.0139639A-I.jpg',),
    'papaya': ('file:Owoce Papaja.jpg',),
    'paper': ('file:Scattered white paper (Unsplash).jpg',),
    'paradise': ('file:Jan Brueghel de Oude en Peter Paul Rubens - Het aards paradijs met de zondeval van Adam en Eva.jpg',),
    'parliament': ('file:Swiss Federal Assembly session, with spectators gallery.jpg',),
    'patience': ('file:Pacientia or Patience.jpg',),
    'peace': ('file:Peace dove.svg',),
    'pension': ('file:DNB visitor centre - ritirement pension.jpg',),
    'perry': ('file:Perry bottled in Normandy.jpg',),
    'pharmacy': ('file:Inneres einer historischen Apotheke.jpg',),
    'philosophy': ('file:Hortus Deliciarum, Philosophy and the seven liberal arts (cropped).jpg',),
    'phoenix': ('file:The Making of Harry Potter 29-05-2012 (Fawkes).jpg',),
    'physician': ('file:Auscultation of a women.jpg',),
    'plan': ('file:Aftakking KW linie 07.jpg',),
    'player': ("file:Ernest Cadine pratiquant un exercice d'haltérophilie, Agence Rol, btv1b53098358j.jpg",),
    'pleasure': ('file:EdisonDelights1905.jpg',),
    'poet': ('file:Portrait of John Ceiriog Hughes (4674472).jpg',),
    'police': ('file:HH Polizeihauptmeister MZ.jpg',),
    'politics': ('file:24.09.2024 - Abertura do Debate Geral da 79ª Sessão da Assembleia Geral das Nações Unidas (54018866744).jpg',),
    'poncho': ('file:Chilean Man Chile Chamanto Poncho.JPG',),
    'portrait': ('file:Dama z gronostajem.jpg',),
    'power': ('file:Politischer Aschermittwoch 06.jpg',),
    'president': ('file:President George W. Bush Meets with Former Presidents George H. W. Bush, Bill Clinton and Jimmy Carter and President-Elect Barack Obama in the Oval Office of the White House - DPLA - 8f2f33d64f72a6eb1b0471ba20da87f6.jpg',),
    'price': ('file:Wireless in-store price display at a clothing retailer in NJ.jpg',),
    'princess': ('file:Schloss Glücksburg - Prinzessin Kris vor dem Wasserschloss - panoramio.jpg',),
    'prisoner': ('file:Prison scrubs 1.jpg',),
    'professor': ('file:Laurentius de Voltolina 001.jpg',),
    'province': ('file:Map of country subdivisions (provinces).svg',),
    'psychology': ('file:Greek uc psi icon.svg',),
    'pulse': ('file:Pulse evaluation.JPG',),
    'question': ('file:Question mark.svg',),
    'race': ('file:Silly - Grand Prix Criquielion, 15 mai 2016, départ (C07).JPG',),
    'rally': ('file:Demonstration during the 2011-2012 Russian protests in Nizhny Novgorod (10 December 2011).jpg',),
    'ranch': ('file:Grant-Kohrs Ranch.jpg',),
    'reception': ('file:Délégation vénitienne à Damas (musée du Louvre) (6358418295).jpg',),
    'red': ('file:Color icon red.svg',),
    'reed': ('file:Albufera 2010 Roseaux.jpg',),
    'region': ('file:Mediterranian Sea Carthago location.JPG',),
    'regret': ('file:Hans Thoma - Der verlorene Sohn.jpg',),
    'religion': ('file:16 religionist symbols.png',),
    'republic': ('file:Forms of government.svg',),
    'rescue': ('file:Gebirgstrage02 Patient Seilsicherung.jpg',),
    'research': ('file:Mitarbeiterin der EMPA in St-Gallen.jpg',),
    'rhythm': ('file:8beat example 01.jpg',),
    'roommate': ('file:Roommates (3218131407).jpg',),
    'rooster': ('file:Complete Guide to Heraldry Fig468.png',),
    'root': ('file:Mangroves.jpg',),
    'sail': ('file:Рисунки к статье «Паруса». Военная энциклопедия Сытина (Санкт-Петербург, 1911-1915).jpg',),
    'salad': ('file:Salad platter.jpg',),
    'salt': ('file:Ammonium-cerium(IV)-sulfate-sample.jpg',),
    'science': ('file:Stylised atom with three Bohr model orbits and stylised nucleus (encircled).svg',),
    'score': ('file:Bowling (19548528996).jpg',),
    'screw': ('file:Cast-iron bookbinding screw press.jpg',),
    'secretary': ('file:Office and Administrative Support Workers - DPLA - 244c999905681bac485868640d9a6270.jpg',),
    'serve': ('file:Serve during volleyball match 4.jpg',),
    'server': ('file:Floridaserversfront1.jpg',),
    'shame': ('file:Monasterio viejo de San Juan de la Peña (RPS 19-04-2019) capitel representando la vergüenza.png',),
    'shamrock': ('file:Irish clover.jpg',),
    'shelf': ('file:Shelve.jpg',),
    'shelter': ('file:Réunion Maïdo kiosque pique-nique.JPG',),
    'shoulder': ('file:Photo of male right shoulder, combined with an anatomical drawing from Leonardo da Vinci.jpg',),
    'shuttle': ('file:Boat shuttle Tapiola 14AUG2026 01.jpg',),
    'signature': ('file:Autograph of Benjamin Franklin.svg',),
    'skirt': ('file:Peasant skirt 1435043608.jpg',),
    'skull': ('file:A2613-Museum Geologi-Fosil Tengkorak.jpg',),
    'sky': ('file:Sky over Munich 02.jpg',),
    'small': ('file:Smallcrane.jpg',),
    'smile': ('file:HD@DH.nrw Strichfigur 22.svg',),
    'smiley': ('file:Smiley.svg',),
    'snapshot': ('file:Snapper root list screenshot.png',),
    'solidarity': ('file:Abramowski-braterstwo-solidarnosc-wspoldzialanie-okladka.png',),
    'space': ('file:3D coordinate system.svg',),
    'sport': ('file:Youth-soccer-indiana.jpg',),
    'stomach': ('file:Sobo 1906 370.png',),
    'studio': ('file:619 Western 06.jpg',),
    'suit': ('file:Suit.jpg',),
    'superhero': ('file:Gotham City Saviour (2430422247).jpg',),
    'surprise': ('file:Grandville Cent Proverbes page129.png',),
    'symbol': ('file:ReligijneSymbole.svg',),
    'syntax': ('file:Syntax tree - Affirmation (1a).png',),
    'system': ('file:Primäres System.png',),
    'table': ('file:Parsons Table.jpg',),
    'tape': ('file:Masking-tape.png',),
    'taste': ('file:Tongue-bitter.jpg',),
    'teacher': ('file:Classroom at a seconday school in Pendembu Sierra Leone.jpg',),
    'technical': ("file:Niger, Mélèk (N'Gourti)(10) (cropped).jpg",),
    'thirst': ('file:William-Adolphe Bouguereau (1825-1905) - Thirst (1886).jpg',),
    'throw': ('file:Sambo at the 2015 European Games.jpg',),
    'toolbar': ('file:Application toolbar.png',),
    'toy': ('file:Child playing with a toy cart and horse. -front- (9726037522).jpg',),
    'trade': ('file:Fredmeyer edit 1.jpg',),
    'troll': ('file:Internet Troll velu ill artlibre jnl.jpg',),
    'trust': ('file:Faith (3).jpg',),
    'twin': ('file:A cross-section of a pregnant uterus containing twins. Engra Wellcome V0014950.jpg',),
    'unusual': ('file:Geisteswissenschaften.png',),
    'vampire': ('file:Les vampires.jpg',),
    'void': ('file:Galaxy superclusters and galaxy voids.png',),
    'vomiting': ('file:Vomiting.jpg',),
    'vulnerable': ('file:Status iucn3.1 VU-ca.svg',),
    'wall': ('file:2015 Zakład Karny w Kłodzku 02.JPG',),
    'warning': ('file:Avertissement marches piscine - Cité Miroir.jpg',),
    'warrior': ('file:Cagayan Warrior.png',),
    'wealth': ('file:Massysm Quentin — The Moneylender and his Wife — 1514.jpg',),
    'wedge': ('file:Geometric wedge.png',),
    'week': ('file:First Day of Week World Map.svg',),
    'wheel': ('file:Hub (PSF).png',),
    'white': ('file:Color icon white.svg',),
    'wife': ('file:William-Adolphe Bouguereau (1825-1905) - The Proposal (1872).jpg',),
    'wind': ('file:Bundesarchiv Bild 183-1990-0206-324, Berlin, Passanten im Wind.jpg',),
    'wing': ('file:Duerer wing of a blue roller.jpg',),
    'winner': ('file:Boxkampf 11.jpg',),
    'witch': ('file:Albert Joseph Pénot - Départ pour le Sabbat.png',),
    'worker': ('file:WomanFactory1940s.jpg',),
    'writer': ('file:Leonid Pasternak - The Passion of creation (1).jpg',),
    'yellow': ('file:Color icon yellow.svg',),
    'zebra': ('file:Plains Zebra Equus quagga.jpg',),
    'zoology': ('file:Animal diversity.jpg',),
}
