"""Сгенерировано tools/commons_cat_picks.py — руками не править.

Слово -> до трёх крупнейших JPEG из категории Commons (P373)
сущности, прошедшей смысловую проверку по русской подписи.
Приоритет ниже всех остальных списков."""

AUTO_PICKS3 = {
    'addition': ('file:Addition with cookies.JPG', 'file:6 + 8 LCCN98514560.jpg', 'file:6 plus 8 = 14 sad penguins, WPA poster, ca. 1938.jpg'),
    'allegro': ('file:Anna Bon di Venezia, Flöten-Sonate IV- Andante und Anfang Allegro assai1Untitled3.jpg', 'file:Archive-ugent-be-0B4371EA-DD2B-11E1-8693-E85B8375B242 DS-5 (cropped).jpg'),
    'anachronism': ('file:2019-09-14 15-56-10 fete-chateau-hericourt.jpg', 'file:2018-07-21 12-56-58 reconst-histo-belfort.jpg', 'file:2017-07-23 12-21-46 reconst-histo-belfort.jpg'),
    'analysis': ('file:Diane Urnick and Lily Cason collecting from their kick seine (4977011627).jpg', 'file:Diane Urnick and Ann McGhee checking their dip stick (4977609524).jpg', 'file:Diane Urnick and Ann McGhee checking their D-nets (4977624790).jpg'),
    'anonymous': ('file:Ann - Mer de Glace - Switzerland-Anon-Grimm-98741-Verso.jpg', 'file:Anon - Devil’s Glen, County of Wicklow - early 19th century - Ireland-98297.jpg', 'file:Anon - Mer de Glace - Switzerland-Anon-Grimm-98741.jpg'),
    'antigen': ('file:Blood Types.jpg', 'file:Brucella Agglutination Test.jpg', 'file:Test de compatibilité croisée Luminex.jpg'),
    'antiquarian': ("file:Siġar Antiki fil-Ġonna ta' San Anton 2.jpg", "file:Siġar Antiki fil-Ġonna ta' San Anton 4.jpg", "file:Siġar Antiki fil-Ġonna ta' San Anton 1.jpg"),
    'apathy': ('file:Tibori Szabó Zoltán.JPG', 'file:Anekaksn100.jpg', 'file:Sarah Bernhardt, par Nadar, 1864.jpg'),
    'astrology': ('file:Astrorum Uraniae Cursus, Variosque Recursus, Oculis Notans, Futura Mente Praevidet.jpg', 'file:9.8.19 1 Lipnice 05 (48498723502).jpg', 'file:Circle of 9 and 12.jpg'),
    'athlete': ('file:Arsen Karen Harutyunyan(ARM).jpg', 'file:20190704064457 IMG 4362.jpg', 'file:2018-10-14 Lee vs Yairegpie (Group stage Boys Wrestling Freestyle 80kg) at 2018 Summer Youth Olympics by Sandro Halank–028.jpg'),
    'attention': ('file:Die Gartenlaube (1891) 453.jpg', 'file:Russian POW being lowered into a bath. Wellcome L0034665.jpg', 'file:Directing Attention.jpg'),
    'bandit': ('file:Portret van Toolsee, een bandiet die gevangen zit in Jabalpur Toolsee. Hindoo dacait. Jubbulpoor (titel op object), RP-F-2001-7-1122G-20.jpg', 'file:Thomas Rowlandson - Banditti - Google Art Project.jpg', 'file:019 Festa Major de Gràcia 2022 (Barcelona), carrer de Verdi.jpg'),
    'base': ('file:Well water spout garden element Gibberd Garden Harlow Essex England 01.jpg', 'file:Base of two pillars at Viborg Katedralskole.jpg', 'file:Architectural column plinth Gibberd Garden Essex England 03.JPG'),
    'bathroom': ('file:A modern styled hotel bathroom.jpg', 'file:Badezimmer auf Segelschiff.jpg', 'file:A washroom in Auschwitz.JPG'),
    'beam': ('file:Baldwin Wallace Homecoming (48869333111).jpg', 'file:Baldwin Wallace Homecoming (48869676157).jpg', 'file:Baldwin Wallace Homecoming (48869528052).jpg'),
    'bear': ('file:JPG – CSD in Hof (Saale) 2024 HOF9130 RAW-Export.jpg', 'file:JPG – CSD in Hof (Saale) 2024 HOF8866 RAW-Export crop.jpg', 'file:JPG – CSD in Hof (Saale) 2024 HOF9787 RAW-Export crop.jpg'),
    'bedroom': ('file:Building a desk.jpg', 'file:Bekah Russom 2017-04-02 (Unsplash).jpg', 'file:At Sudbury Hall 2023 003.jpg'),
    'bell': ('file:9-11 Commemoration Wreath-Laying Ceremony at the Pentagon Group Burial Marker in Section 64 at Arlington National Cemetery, Arlington, Virginia, Sept. 11, 2024 - 5.jpg', 'file:20171102 115019 Wanfried ev.-Stadtkirche-Wanfried Glocke.jpg', 'file:1910 to 1915 photo of William Crooks steam locomotive (cropped).jpg'),
    'biology': ('file:Group of shield bugs Dolycoris baccarum feeding on host plant leaves in Dnipropetrovsk Oblast Ukraine by baby-bear.org Natalka Ukraine 02.jpg', 'file:Ecological still life with Helix pomatia snail and fallen apple under Ribes nigrum bush in Dnipropetrovsk Oblast Ukraine by baby-bear org Natalka Ukraine.jpg', 'file:Emulgieren hoch u niedermol Emulgator Micelle.jpg'),
    'black': ('file:Black Palette Graphic Created by Trisorn Triboon.jpg', 'file:Children Expression.jpg', 'file:Black22z.jpg'),
    'blade': ('file:Messer mit Elfenbeingriff.jpg', 'file:Kanger Stainless Knife.jpg', 'file:Hoe blades at blacksmithing workshop, Ghiny (Sabon Sarki).jpg'),
    'blanket': ('file:Industries of War - Blankets - MANUFACTURING ARMY BLANKETS. Cutting and stamping blankets in plant of J.P. Stevens and Co., New York City - NARA - 31486037.jpg', 'file:Homemade Blanket - Flickr - andymudrak.jpg', 'file:Chinese Coffin with blanket.jpg'),
    'blog': ('file:Sunday (Unsplash).jpg', 'file:Monetize blog 2017.jpg', 'file:1ºAniversário Becas no Mundo.jpg'),
    'blue': ('file:032F Nizza (15626054919).jpg', 'file:20131003 Schoeningen Palaeon DSC08394 PtrQs.jpg', 'file:2013, Atrium Hotel Pool - panoramio.jpg'),
    'body': ('file:Il cuore.jpg', 'file:MAS S.jpg', 'file:Body spots in Acid fast stain of slit skin smear.jpg'),
    'border': ('file:Part of the boundary between the United States and Texas, north of Sabine River from the 72nd mile mound to Red River (NYPL b20643881-5422739).jpg', 'file:The San Juan award (NYPL b20767366-5452679).jpg', 'file:DSC 1499-1 (14289951711).jpg'),
    'bowl': ('file:At La Palma 2021 0058.jpg', 'file:A Golden teapot and iron plate with table wares in Lung Dim Sum.jpg', 'file:20151003최광모RX10DSC03005.JPG'),
    'box': ('file:A Spring onions on the poly boxes.jpg', 'file:20150331최광모101.jpg', 'file:American Library Association - Dispatch - Service of the American Library Association to the boats of the U.S. Shipping Board. Collections arranged at the Dispatch Office of Newport News, VA - NARA - 17342934.jpg'),
    'boy': ('file:Boy drinks water from glass in a cozy home environment.jpg', 'file:A young boy dressed in overalls engages with a vintage typewriter.jpg', "file:Arba'een In Mehran City 2016 - Iran (Black And White Photography-Mostafa Meraji) اربعین در مهران- ایران- عکس های سیاه و سفید 31.jpg"),
    'brother': ('file:Air Force brothers reunited after 15 years (6509538).jpg', 'file:Brothers Dean W. Hodges and William S. Hodges, Jr. - U-Boat Victims - Lusitania (165-WW-537F-32) - DPLA - 1fa548f71eeb0a0e50a5ac8f72885feb (cropped).jpg', 'file:Couple on the sand beach (Unsplash).jpg'),
    'brown': ('file:Brown Palette Graphic Created by Trisorn Triboon.jpg', 'file:Abstract (33527372480).jpg', 'file:(HMM) Planet Eggs (32442357494).jpg'),
    'budget': ('file:AUTOVÍA MADRID-IRÚN 08.jpg', 'file:Cuaderno de notas minería Pachuca 1845-1846 48.jpg', 'file:120124-N-TH437-002 (6867436099).jpg'),
    'cabinet': ('file:At Salisbury 2023 057.jpg', 'file:Cabinet of Sánchez Cerén.jpg', 'file:Case with candles - Snowshill Manor - Gloucestershire, England - DSC09559.jpg'),
    'campus': ('file:04 UVA by Husos FOTOMONT.jpg', 'file:Aerial view of Mays Business School, Texas A&M University.jpg', 'file:Aerial shot of UCA Campus in Khorog.jpg'),
    'class': ('file:Everyday class 2 - Copy.jpg', 'file:Clase de guion.jpg', 'file:AaaaaG 0054 (36883702605).jpg'),
    'coach': ('file:Allegheny vs. Baldwin Wallace Lacrosse - 49599435546.jpg', 'file:Anton Kadushin.jpg', 'file:Coach Mohammad Thunibat.jpg'),
    'collector': ('file:Richard Stout Annual Fall Show.jpg', 'file:Grand Seiko & Tirta BambangWirawan at Soehanna Hall Energy Building.jpg', 'file:Mesin jahit lawas.jpg'),
    'comedy': ("file:3 Gerry Cottle's Circus - The Loonies in Colour.jpg", "file:2 Gerry Cottle's Circus - The Loonies.jpg", "file:1 Gerry Cottle's Circus - The Loonies in Make Up.jpg"),
    'component': ('file:TWAM Ref- TWCMS-M4414 (21624377145).jpg', 'file:TWAM Ref- TWCMS-M4424 (21613295362).jpg', 'file:MITRPAK aluminum alloy housing 2.jpg'),
    'conference': ('file:302-R (412).jpg', 'file:20221026 GOSH2022-day1 by-Laura-Olalde-CC BY-SA 2.0 (125) 03.jpg', 'file:20221026 GOSH2022-day1 by-Laura-Olalde-CC BY-SA 2.0 (125) 02.jpg'),
    'connection': ('file:Spans of Padma Multipurpose Bridge in 2020.jpg', 'file:Heavy span of the Padma Bridge.jpg', 'file:2019年版到着！365日繋がっているカレンダー。めくらなくて良いし、見るだけで幸せになるデザインも嬉しい。 Nov 5, 2018. @kototoicalendar http kototoi.com (45733231611).jpg'),
    'consultant': ('file:Silvana Mero, Consultor de Proyectos.jpg', 'file:Jai Chabria.jpg', 'file:United States Institute of Peace and Conciliation Resources hosted a discussion of “Still Time to Talk- Adaptation and Innovation in Peace Mediation” on 31 October 2024 - 4.jpg'),
    'consumer': ('file:Looking at Food Labels (098) (7396780726).jpg', 'file:Nutrition Labeling (FDA 157) (8212211574).jpg', 'file:Consumption (33933848254).jpg'),
    'contempt': ('file:Peter James Middlebrook.jpg', 'file:Pavel Fedotov - The fresh cavalier - Google Art Project.jpg', "file:Le Crainte, Le Mépris, La Frayeur (from Caractères des passions, gravés sur les desseins de l'illustre Monsieur le Brun) MET DP854049.jpg"),
    'controversy': ('file:Anti article 13 template grafitti near a bus station (2022-12-30) 2.jpg', 'file:Anti article 13 template grafitti near a bus station (2022-12-30) 1.jpg', 'file:Romney - Taking Tikanga To The World.jpg'),
    'conversation': ('file:A woman with curly hair is speaking on a red rotary telephone.jpg', 'file:2024-06-15 Museumsfest DMM Bruchsal 022.jpg', 'file:2024-04-20 HCC Einweihungsfeier 062.jpg'),
    'copyright': ('file:AUCS - VÍAS PRIMARIAS.jpg', 'file:2015-365-52 Copyright As An Act of Encouragement of Learning (16420135640).jpg', 'file:Copyright card game image.jpg'),
    'corporation': ('file:Mission Vision Values.jpg', 'file:The Eye of Evil.jpg', 'file:Protect people over corporate profit.jpg'),
    'counter': ('file:Digital counter signals.jpg', "file:Fonctionnement d'un compteur (décompteur), schématique.jpg"),
    'courage': ('file:Brandon Harris courage.jpg', 'file:Courage to do more.jpg', 'file:All for the sake of Jack (NYPL Hades-447647-1153743).jpg'),
    'cowboy': ('file:1877 Chico Basin Roundup At The HOP Ranch.jpg', 'file:Cine Cowboy, Austin, Tx (29472104435).jpg', 'file:Camille Pissarro Llanero.jpg'),
    'cup': ('file:2025-04-26 Brauereifest Rheinfelden AG 067.jpg', 'file:2024-09-15 Eroeffnungswochenende AMB 002.jpg', 'file:Bunny on the moon.jpg'),
    'cushion': ('file:Dülmen, Kirchspiel, Marienkapelle Visbeck, Bestuhlung -- 2022 -- 4145.jpg', 'file:Hand-knitted cushions for kneeling down for prayer in church. (51416435809).jpg', 'file:Candlelight at By The Sea Recovery sober living 03.jpg'),
    'custom': ('file:"Afo tsy maty" - Rova d\'Ambohidrabiby - Mars 2024.jpg', 'file:A traditional outfit alongside a modern suit outfit.jpg', 'file:A Celebration of Luxurious Detail 06.jpg'),
    'damage': ('file:AT&T large cylinder copper wire damage - August 2026.jpg', 'file:Bache en la pista de la av. José Galvez cdra 5 en La Victoria.jpg', 'file:Clearing Debris on Rt. 626 (7797525794).jpg'),
    'dean': ('file:Dodela zlatnih povelja zasluznim profesorima u penziji povodom 50 godina FDU 2.jpg', 'file:Dodela zlatnih povelja zaslužnim profesorima u penziji povodom 50 godina FDU 1.jpg', 'file:Ljiljana Mrkic Popovic dekan FDU 1996 - 2002.jpg'),
    'debt': ('file:Geschrift Lucy Weguelin.jpg', 'file:Minneapolis Critical Mass August 29, 2008 (2813535826).jpg', 'file:230227 Government obligation of 1915.jpg'),
    'designer': ('file:Bocetaje a la medida.jpg', 'file:Amowa Design.jpg', 'file:Cycling World Europe 2025, Meerbusch (File1236-2).jpg'),
    'desire': ('file:That Obscure Object of Desire.jpg', 'file:Before I Die. . . (8068344863).jpg', 'file:やきとりが食べたい キリンラガー (4450929158).jpg'),
    'device': ('file:Airfield damage- repaired and ready at Atlantic Trident 25 (9124538).jpg', 'file:1-8IN Raven during LFX (7180064).jpg', 'file:Airfield damage- repaired and ready at Atlantic Trident 25 (9124545).jpg'),
    'diagnosis': ('file:Chordoma brachyury immunohistochemistry.jpg', 'file:The abioSCOPE and the IVD CAPSULE PSP.jpg', 'file:Diagnosis result.jpg'),
    'dialogue': ('file:Come And Go With Empty Hand.jpg', 'file:Kreisfeuerwehrverband Limburg-Weilburg 1.Hessischer Feuerwehrpreis Ehrungsveranstaltung 2023-12-08.jpg', 'file:Kreisfeuerwehrverband Limburg-Weilburg 1.Hessischer Feuerwehrpreis 2023-12-08.jpg'),
    'dictation': ('file:Aanvankelijk spellen.jpg', 'file:Fête du Tour 2026, Bergerac 19.jpg'),
    'documentary': ('file:Alby Mangels in Cleo Magazine (Australia).jpg', 'file:An Unquiet Mind of.jpg', 'file:31012017-IMG 6138.jpg'),
    'doubt': ('file:Onzeker.jpg', 'file:Singer-songwriter-RJ-Thompson-promo-shot-diner-6.jpg', 'file:"Blasts" from The Ram\'s Horn (1902) (14597969520).jpg'),
    'earth': ('file:NSBEPosterwiki.jpg',),
    'economy': ('file:Federación Económica de Formosa 02.jpg', 'file:Federación Económica de Formosa 01.jpg', 'file:Francisco Ruiz Díaz López.jpg'),
    'editor': ('file:Ascencio Esteban abril 2025. Foto Margarita Mayen.jpg', 'file:Cross section of participants at the Wikimedia Awareness in Nile University of Nigeria.jpg', 'file:A participant creating wikipedia account.jpg'),
    'education': ('file:Analiză urme.jpg', 'file:Alin Cosmin Popescu - Rector USVT.jpg', 'file:ATU-2025.jpg'),
    'efficiency': ('file:Efficiency in the Mill (5943464735).jpg', 'file:"WORK CLOTHES FOR SAFEY & EFFICIENCY" - NARA - 516184.jpg', 'file:Daylight efficiency of artificial illuminants (1909) (14774145251).jpg'),
    'elder': ('file:2 Londoners - A Lived in Face.jpg', 'file:2025 counter anti-migrants protest in Sydney, speakers give speeches and elderly and children watch.jpg', 'file:An elderly man with a warm expression stands next to a rustic door, holding a small container in a peaceful countryside.jpg'),
    'elephant': ('file:2023 Family Category Entry 10- The Zoo (c1191e6f-d1c2-45ec-bbf4-56f89c6a91cd).jpg', 'file:Dzanga Bai forest clearing with African forest elephants, Central African Republic.jpg', 'file:Dzanga Bai at sunrise, Central African Republic.jpg'),
    'empire': ('file:Adler Frauenfreude - Knöpfe mit tief liegenden Nahfaden - Reichspatent - um 1910 - Deutsches Reich.jpg', 'file:Empire88Tower.jpg', 'file:Negri Hardt L9991646.jpg'),
    'encounter': ('file:Two Tuareg nomads meet on the way.jpg', 'file:“Encounters” with 21st Century Phoenix Mule Deer, Lauren Strohacker, 2013 - panoramio.jpg', "file:Lets Eat at Bill Johnson's Big Apple, 2013 - panoramio.jpg"),
    'engagement': ('file:Claddagh ring.jpg', 'file:Beautiful couple at there engagement eve.jpg', 'file:Engagement gifts basket (01).jpg'),
    'enlightenment': ('file:We grow wiser as we grow older - K. LCCN2010651404.jpg', 'file:PuckMagazine1May1901.jpg', 'file:Heinrich Josefson handwriting.jpg'),
    'essay': ('file:Antigua Stamps and Postal History The E. V. Toeg Collection.jpg', 'file:Bartlomiejczyk Essay 1917.jpg'),
    'ethics': ('file:Consent in Data Policies.jpg', 'file:A doctor who writes books of sexual advice talking Wellcome L0034920.jpg', 'file:Code of ethics and professional conduct.jpg'),
    'evacuation': ('file:09 02 2020 - Operação Regresso (50828920877).jpg', 'file:09 02 2020 - Operação Regresso (50828920777).jpg', 'file:09 02 2020 - Operação Regresso (50828920192).jpg'),
    'evaluation': ('file:140825-A-HE359-015 (14875837727).jpg', 'file:131104-N-PO203-050 (10699087426).jpg', 'file:131104-N-PO203-046 (10699242003).jpg'),
    'evolution': ('file:1-s2.0-S0042682215000859-gr2 lrg.jpg', 'file:Ceratites evolution.jpg', "file:Chaisson's figure2.jpg"),
    'exit': ('file:Millenniumi kiállítás, Ős-Budavára. - Budapest XIV. Fortepan 82791.jpg', 'file:Milstat13 vhod-freske-cerkev.jpg', 'file:Airlock Avshalom Cave Exit.jpg'),
    'explanation': ('file:Rembrandt (workshop) - A young Scholar and his Tutor (Getty Center).jpg', 'file:Decommissioned-lego-moulds.jpg', 'file:Ranger Terrance explains the mechanics of geysers, while a "grand" example erupts in the background (7f443bed-fa44-49d2-856b-d711d2a736f5).jpg'),
    'explorer': ('file:Sexy view of explorer (52604387154).jpg', "file:Let's explore.jpg", 'file:探洞工廠.jpg'),
    'factory': ('file:Metal frames are stacked at a construction site during the day under clear skies with visible sunlight shining down.jpg', 'file:Machine working in a factory while cutting material on a production line in the workshop.jpg', 'file:Glass sheets are cut and processed in a workshop during midday hours for various construction projects.jpg'),
    'fairy': ('file:My home is a tiny Walnut.JPG', 'file:Flickr - Laenulfean - fairy forest.jpg', 'file:Brique da Redenção, Porto Alegre, Brasil.JPG'),
    'farmer': ('file:An elderly man with a warm expression stands next to a rustic door, holding a small container in a peaceful countryside.jpg', 'file:An elderly man in a blue jacket interacts with chickens in a simple farm environment.jpg', 'file:Arrival of Monsoon in Maharashtra Western Ghats.jpg'),
    'fashion': ('file:2021-02-07 Busayo Olupona.jpg', 'file:Azerbaijan Fashion Week 7.jpg', 'file:Afri Art Model 2023.jpg'),
    'fiction': ('file:Chuck Greaves.jpg', 'file:Arwen Elys Dayton office desk.jpg', 'file:Eric Alterman @ BBF (8024099379).jpg'),
    'field': ('file:2001078 007 70 094 010ac (20633057993).jpg', 'file:A depressed young girl stands quietly in a vast field, looking at a vibrant sunset.jpg', 'file:2 Rehe im Wald 7.jpg'),
    'fingerprint': ('file:Een aantal politiefunctionarissen die naar een op diascherm geprojecteerde vingerafdruk kijken ca.19 GN15827.jpeg', 'file:4293029656 a631180184 bPlaqueIdentificationAcide.jpg', 'file:Deel van een envelop met een vingerafdruk, RP-F-2001-7-117-41.jpg'),
    'fist': ('file:-OccupyHart - Stop the Shutdown Protest (45939453915).jpg', "file:Baby's closed fist.jpg", 'file:Breaking Plateau.jpg'),
    'form': ('file:Imprenta de Franklin Court-2023 04.jpg', 'file:Presse à bras Alauzet (48611527426).jpg', 'file:Historic Cherokee printing press typesetting at New Echota in Gordon County, Georgia (7e537a2e-7307-420e-ba11-3ec25f4bfaf4).JPG'),
    'game': ('file:A boy lies on a comfortable sofa, focused on playing with a smartphone.jpg', 'file:27 03 2019 Elm günündə institutda gənclərlə görüş (4).jpg', 'file:2 Presentation jeu complet fond blanc vertical.jpg'),
    'gene': ('file:Another KIAA0090 Conceptual Translation.jpg', 'file:Alteracions descrites al gen NR3C1.jpg', 'file:Antigenic Drift of the Flu Virus (5102830852).jpg'),
    'girl': ('file:2369D - 01, Acervo do Museu Paulista da USP.jpg', 'file:4972D - 01, Acervo do Museu Paulista da USP.jpg', 'file:2588D - 01, Acervo do Museu Paulista da USP.jpg'),
    'gossip': ('file:There are two sides to a story (NYPL Hades-608963-1947027).jpg', 'file:There are two sides to a story (NYPL Hades-608963-1947025).jpg', 'file:There are two sides to a story (NYPL Hades-608963-1947024).jpg'),
    'government': ('file:Andrés Hidalgo Leiva.jpg', 'file:BanderaVilcabamba.jpg', 'file:Council ruling on Wampage March 1679.jpg'),
    'graffiti': ('file:-96wiki.jpg', 'file:-122wiki.jpg', 'file:2016-Shibuya-graffiti-in-the-street.jpg'),
    'green': ('file:2023-08-25 - grapes on the vine - 3 strands dangling side by side - (HiRes focus stack).jpg', 'file:2022-10-28 multiple folds of green table cloth (focus stack - HiRes).jpg', 'file:2022-10-23 grapes on the vine (focus stack - HiRes).jpg'),
    'ground': ('file:Bullock ploughing sowing groundnut blackeyed peas Raichur Karnataka India.jp.jpg', 'file:Drought bshsjd.jpg', 'file:Dirt and Mud 008 - Mud.jpg'),
    'guest': ('file:Le Christ chez Marthe et Marie - Joos Goemaere.jpg', 'file:Karim La Joie.jpg', 'file:Bon Echo Inn Water Tower (30480701001).jpg'),
    'habit': ('file:Casa y Habitante de Cuetzalan, Puebla.jpg', 'file:Umusaza uri kunywa igikamba.jpg', 'file:Berenice Lopez mexikar Domusantua Elorrion2022.11.01.jpg'),
    'hair': ('file:Abdiel Ibarra 2016 (Unsplash).jpg', 'file:Galeopsis tetrahit (5202210018).jpg', 'file:Elaeagnus angustifolia (5001548377).jpg'),
    'handle': ('file:取っ手付き紙コップ 手袋着用 (32184306565).jpg', 'file:Griff einer Geldkassette.jpg', 'file:China-beijing-forbidden-city-P1000178.jpg'),
    'health': ("file:Teddy bear receives a health checkup with mask and test swab in a child's room.jpg", "file:Caregiver checks child's temperature with thermometer in a warm indoor setting during a health routine.jpg", 'file:A health monitoring device is seen attached to a hand, showing vital sign readings.jpg'),
    'history': ('file:Original Town Gate of Brody (Formerly Pförten).jpg', "file:Plaque commémorative Jeanne d'arc provins.jpg", "file:Jeanne d'arc église de Provins.jpg"),
    'holiday': ('file:The cozy indoor space is adorned with vibrant holiday decorations.jpg', 'file:A child joyfully holds a sparkler, illuminating the surroundings with bright sparks.jpg', 'file:Gift exchange at a cozy gathering during the holiday season with friends and family celebrating together.jpg'),
    'homework': ('file:Parent helps child with homework during afternoon study session at home.jpg', 'file:Chem hw.jpg', 'file:Technical drawing, homework, calipers, ink guide Fortepan 61283.jpg'),
    'horoscope': ('file:Helix, v.4, no.5, Aug. 29, 1968 - DPLA - 841a1a68f4295fee3a912baf0c87caaa (page 5).jpg', 'file:Kunstkammer-Wallenstein-Horoskop-Amulett DSC9125.jpg', 'file:1940 Horrorscope New Masses.jpg'),
    'hour': ('file:Tower Bridge (16814228371).jpg', 'file:St Pauls Cathedral (16608019397).jpg', 'file:Güneş saati, Sultanahmet.jpg'),
    'household': ('file:Johannes Rach and Odvardt Helmoldt von Lode - Household Goods - NMK.2021.0112.038 - National Museum of Art, Architecture and Design.jpg', 'file:Aime Pez Familienidylle 1839.jpg', 'file:Adolf Eberle Musikalische Unterhaltung auf der Alm.jpg'),
    'housewife': ('file:1. Mai 1907 – Frau als Allegorie der Neuen Gesellschaft.jpg', 'file:Big Sandy Housing Camp. Mines at Big Sandy closed and housing now occupied by Exeter Miners. Mrs. Beulah Wady, wife... - NARA - 540710.jpg', 'file:Dillard Eldridge, his wife and children, at supper in the four room house for which they pay $9 monthly. This is one... - NARA - 541209.jpg'),
    'husband': ('file:Zentralbibliothek Zürich - Börse. Glasgemälde No. 118, 4 Mannesalter - 991040989239705501.jpg', "file:I've got a wife!, artist unknown, c. 1882, from the Digital Commonwealth - commonwealth 3f462g969.jpg", 'file:Park bench plaque - Flickr - antmoose.jpg'),
    'idea': ('file:"I Got an Idea^ If it\'s Good...I\'ll Cash In" - NARA - 514560 - retouched.jpg', 'file:Chapters Dialogue I, board with questions, ideas, problems and point of views, Chapters Dialogue I, wmcon14 berlin.jpg', 'file:Chapters Dialogue I, board with questions, ideas, problems and point of views, Chapters Dialogue I, wmcon14 berlin-009.jpg'),
    'immigration': ('file:1909-04-15 Immigrant Bldg, New York City A.jpg', 'file:Alexander More keynote address.jpg', 'file:Be Good buttons.jpg'),
    'improvisation': ('file:干し毛布 (53116213295).jpg', 'file:Paul Timings.jpg', 'file:Improvised Hanukkah menora.jpg'),
    'innovation': ('file:Alan Zettelmann - Innovation Management Expert and Author.jpg', 'file:Creation Center Berlin.jpg', 'file:Consolas sala Labco.jpg'),
    'interpreter': ("file:1863 Meeting of Settlers and Maoris at Hawke's Bay, New Zealand.jpg", 'file:Chief of the "Friendly" Yuma Indians, John Townsend, and the interpreter, Poncho Lachero, ca.1900 (CHS-3457).jpg', 'file:Adobe house belonging to the Pima Indian interpreter, Gila Crossing, ca.1900 (CHS-3557).jpg'),
    'jazz': ('file:Chrome Valley (Mahogany L. Browne and Sean Mason Album).jpg', 'file:The Jazz Hounds Still.jpg', 'file:Emmett Miller.jpg'),
    'jury': ('file:AssembleHouseOfThePeople1.jpg', 'file:John G. Mac Harty, fils, Lewis Mac Harty, juré du procès Sacco - Vanzetti, Pacific - btv1b531883303.jpg', 'file:TikTok Short Film Competition Jury.jpg'),
    'kilt': ('file:Designer Kilt - 2020 gefertigt aus biologischen und naturbelassenen ungefärbten Leinen - Herstellung in Lübbenau Spreewald - mit handgeschmiedeter Fibel aus 800.er Silber.jpg', 'file:Scottish dress and cheongsam.jpg', 'file:Pete Rees LOC npcc.10328.jpg'),
    'kiss': ('file:Evangel Pentecostal Church Quebec City 05.jpg', 'file:Couple Kissing Pix 1949 SLNSW FL9316675.jpg', 'file:CAC CC 001 18 29 0000 2842.jpg'),
    'lavender': ('file:Agarbatti - Lavender fragrance.jpg', 'file:Blue coral - Indonesia, 2012 (12).JPG', 'file:Flor de lavanda.jpg'),
    'lead': ('file:Candlesticks made of lead and tin; Germany.jpg', 'file:Hüven - Hüvener Mühle - Mühlenpark - Mühle 24 ies.jpg', 'file:Hüven - Hüvener Mühle - Mühlenpark - Mühle 23 ies.jpg'),
    'legislature': ('file:Salon Azul, Legislative Assembly of El Salvador.jpg', 'file:Legislatura de la provincia de Jujuy - Argentina.jpg', 'file:Charlotte Amalie 2fer.JPG'),
    'lesson': ('file:Akshata Murty hosts Young Enterprise Lessons at 10 Downing Street on 17 November 2023 - 7.jpg', 'file:Akshata Murty hosts Young Enterprise Lessons at 10 Downing Street on 17 November 2023 - 5.jpg', 'file:Akshata Murty hosts Young Enterprise Lessons at 10 Downing Street on 17 November 2023 - 4.jpg'),
    'lever': ('file:Elevator lever, Holyoke Masonic Temple (Mount Tom Lodge A. F. & A. M.), Holyoke, Massachusetts.jpg', 'file:Interboot 2023, Friedrichshafen (P1120387).jpg', 'file:CP 2400 Interior 05.jpg'),
    'license': ('file:2023 Krótkofalarska licencja nasłuchowa.jpg', 'file:Business Licence in a tea shop in Suzhou.jpg', 'file:Switzerland Neuchâtel 1929 permit to purchase arsenic.jpg'),
    'liver': ('file:Hematopoietic stem cell niche in fetal liver versus bone marrow.jpg', 'file:Livartil P-FG-ES-03290.jpg', "file:Bottle of 'Chologestin', United States, 1890-1930 Wellcome L0058557.jpg"),
    'logic': ('file:KJL02617.jpg', 'file:ABC.VI.1913.01.jpg', 'file:Leonid Vasilyevich Rutkowski short biography, 1907.jpg'),
    'loneliness': ("file:L'intimité de la côte pointe noire et les pontonnegrais (habitants de la ville de pointe noire).jpg", 'file:In the Dragster, getting ready for start, Kaukana, Wisconsin, 1970.jpg', 'file:American Herring Gull Larus smithsonianus Vancouver Island 7197.jpg'),
    'loser': ('file:Wall of Skulls 2 (4386998093).jpg', 'file:Losers @ Akiba.jpg'),
    'luck': ('file:Dülmen, Kirchspiel, Börnste, BMW Mini -- 2019 -- 7207-13.jpg', 'file:Lucky time —- — Love life.jpg', 'file:Lucky Penny scam in Biloxi MS.jpg'),
    'lung': ('file:1D53EE7 image.jpg', 'file:A Three Pig Lungs.jpg', 'file:Journal of morphology (1893) (14596056270).jpg'),
    'lyrics': ('file:Ein figurales Gedicht über Frauen in der Kirche.jpg', 'file:0Z5A9120.jpg', "file:Ik heb goede tabak in mijn snuifdoos J'ai du bon tabac dans ma tabatière (titel op object), RP-P-OB-201.098.jpg"),
    'mandarin': ('file:Musée Salies - Figurine 02.jpg', 'file:Mandarin statures at Khai Dinh Tomb (25627003877).jpg', 'file:Mandarin statues at Khai Dinh Tomb (38687497000).jpg'),
    'map': ('file:Житомирські трамвайні маршрути.jpg', 'file:Кичкірівська волость.ЦДАВО ф.5оп.1 спр.339.ст.50.jpg', 'file:Возера Сермеж (Сірмеж) і рака Сермеж (Сірмеж) на карце 1865-1874 гг..jpg'),
    'material': ('file:Children engage in a crafting session, sharing various colorful materials.jpg', 'file:Closeup of Weathered FRP Panel Texture.jpg', 'file:Fotos-7.jpg'),
    'medication': ('file:-13wiki.jpg', 'file:Bucharest Municipal Museum - medicine box, circa 1900.jpg', 'file:Different medicins.jpg'),
    'member': ('file:Wikimedia Community User Group members-Kenya.jpg', 'file:MEMBERS ONLY jacket tag.jpg', 'file:IMG-20230104-WA0104.jpg'),
    'memory': ('file:CZ Trebic Zborów1264.jpg', 'file:Dongen skulptur i Solheim Borettslag.jpg', 'file:Almásfüzitői Timföldgyár, épület15, 78.jpg'),
    'merchant': ('file:Habit of a wealthy merchant of London in 1588. Riche marchand de Londres (NYPL b14140320-1638225).jpg', 'file:Habit of a merchant of Misnia in 1577. Marchand de Misnie (NYPL b14140320-1638178).jpg', 'file:Habit of a Russian merchant in 1577. Marchand Russe (NYPL b14140320-1638199).jpg'),
    'mermaid': ('file:Ex libris du Vicomte de Nettine.jpg', 'file:Habsburger Wappenbuch Fisch saa-V4-1985 000 Vr.jpg', 'file:Cambados, San Benito 04-24g.JPG'),
    'message': ('file:Hinatazaka46 (52650827255).jpg', 'file:BTOK6E.jpg', 'file:I一言カード 目安箱 (29505930768).jpg'),
    'metaphor': ('file:Mein Porsche und Audi ... Mein Haus .... mit der Frau ... das Alles gehört der Bank - Bildimpression eines Straßenfotografen.jpg', 'file:Where’s the beef - Irish Black Angus Beef from Cork - Image impression of a street photographer - III.jpg', 'file:My Porsche ... my House.... my Wife... all this belongs to the Bank - Picture 001.jpg'),
    'ministry': ('file:Arch. Okoduwa-1439.jpg', 'file:Ministry in Pakse.jpg', "file:Sortie du Ministère du développement et de la coordination de l'action gouvernementale.jpg"),
    'minute': ('file:Sign-1330335, Wainuiomata, Wellington, New Zealand.jpg', 'file:Sign-1330329, Wainuiomata, Wellington, New Zealand.jpg', 'file:ルミナリエ会場 およそ90分 (3174235518).jpg'),
    'monopoly': ('file:Take the Next Car - 1883 US political cartoon.jpg', 'file:塩が専売制だった時代の鑑札 - 江戸東京たてもの園で撮影 - Pcs34560 IMG1288.jpg', 'file:Streichhölzer BW 2017-07-26 17-32-21.jpg'),
    'monster': ('file:Letter-G-Monsters.jpg',),
    'mutation': ('file:Dreigliedriger Daumen.jpg', 'file:CCR5 Delta mutation.jpg', 'file:Deformed, dead chicks, Unknown Location-Lake Michigan Federation-epa.gov.jpg'),
    'noon': ('file:At Clock museum, Vienna 2025 011.jpg', 'file:Clouds in sky 2.jpg', 'file:Clouds in sky 1.jpg'),
    'north': ('file:Первый день лета в Арктике.jpg', 'file:Arewa.jpg', 'file:Murals at Kungri Gompha Monastery - India.jpg'),
    'ocean': ('file:Pantai Cibuaya, Kabupaten Sukabumi, Kepiting.jpg', 'file:Spinner dolphin.jpg', 'file:Plage à Sassandra.jpg'),
    'opinion': ('file:まわれ右脳！展 (37877883554).jpg', 'file:Havriin Bayar 2007 official message.jpg', 'file:Flickr - europeanpeoplesparty - EPP Political Assembly 4-5 February 2010 (42).jpg'),
    'opposition': ('file:Mars at its brightest, in opposition to the Sun. Spring (2016, 21 of May) Italy.jpg', 'file:Jupiter and Red Spot, Ganymede (and transit), Io, Europa, and Callisto, taken with Nikon P900 - 2020-07-24.jpg', 'file:Oposición y Mínima Distancia.jpg'),
    'outcome': ('file:Coin tossing.JPG',),
    'paddle': ('file:DEGAN Gabin ( the canoe of these schoolchildren ).jpg', "file:3 great holiday numbers, Dec. 15, 22, 29, '95. For sale here. LCCN2014649568.jpg", 'file:Aboriginal paddles (29233602173).jpg'),
    'papaya': ('file:At Icod de los Vinos 2022 071.jpg', 'file:Drvo papaje, Zanzibar.jpg', 'file:Au cœur du goût.jpg'),
    'paradigm': ('file:LongWavesThreeParadigms.jpg', 'file:Parafoveal magnification paradigm.jpg'),
    'paradise': ('file:Trail Crew - 29389862847.jpg', 'file:Oskar Laske Paradies 1913.jpg', 'file:Paradisstien-FrederiksvaerkDenmark RomanDeckert06082022.jpg'),
    'parliament': ('file:A perspective view of the Parliament House & Exchequer LCCN2003680064.jpg', 'file:Asaf Bartov, explaining the benefit of open knowledge at the Senate partnership meeting with Wikimedia Team.jpg', 'file:Asaf Bartov speaking at the Senate.jpg'),
    'patience': ('file:由布島の水牛は精神論で人を渡します (15957703301).jpg', 'file:The Hunter.jpg', 'file:Fly fishing on the Metolius River, Oregon (3386413872).jpg'),
    'peace': ('file:At La Orotava 2022 055.jpg', 'file:"Lets make Pakistan beautiful".jpg', 'file:Assisi peace installation 2304-1056.jpg'),
    'perry': ('file:Halmstad Cider i en butikkhylle.jpg', 'file:Sidro di pere casalingo.jpg', 'file:Sidro di pere (lattina e bottiglia).jpg'),
    'pharmacy': ('file:Mizzan pharmacy and via Torino (2).jpg', 'file:A la pharmacie IRANZI.jpg', 'file:Karunya Pharmacy Thycaud.jpg'),
    'philosophy': ('file:Bautista Aguirre.jpg', 'file:Bonding Agents-2.jpg', "file:Andrea di bonaiuto, apoteosi di san tommaso d'aquino, scienze ed arti 03 Filosofia e Aristotele 2.jpg"),
    'phoenix': ('file:Brandende feniks, RP-P-1982-1374.jpg', 'file:Fabel van de feniks, RP-P-OB-5266.jpg', 'file:Château de Bussy Rabutin-Phœnix-20160228.jpg'),
    'physician': ('file:Doctor (Kusakabe Kimbei).jpg', 'file:Doctor scientist holding a plastic tube in the laboratory closeup.jpg', 'file:Child enjoys fruit while adult smiles and offers plate.jpg'),
    'pleasure': ('file:Bersahabat dengan pandemi.jpg', 'file:Amber Lee Ettinger (7483783144).jpg', 'file:Mary N. Crawford, shown sitting next to blackboard (3321962495).jpg'),
    'poet': ('file:1904 January 24 Ashton Stevens Interviews George Sterling, Poet.jpg', 'file:Aditya Tiwari. jpg.jpg', 'file:Alessandro Angelelli.jpg'),
    'police': ('file:20190327-FS-Sandia-AM-01.jpg', 'file:01.MTPD.FoggyBottom.GWU.WDC.13April2023.jpg', 'file:Bomb-disposal unit.jpg'),
    'poncho': ('file:Georgia Mooney.jpg', 'file:Colourful poncho(s).jpg', 'file:Artesano de Ponchos en La Paz.jpg'),
    'portrait': ('file:5 Eolo-Perfido-Portraits.jpg (1).jpg', 'file:20250208 Raoul-5.jpg', 'file:A happy artist.jpg'),
    'princess': ('file:Swedish princess dresses at the royal castle of Stockholm 2015.JPG', 'file:HER EXCELLENCY AND ROYAL HIGHNESS PRINCESS AMANDA OF BRONG-AHAFO AND ASHANTI KINGDOMS.jpg', 'file:Juego de té 2.jpg'),
    'principle': ('file:FAIR data principles (Interoperable).jpg', 'file:FAIR data principles (Accessible).jpg', 'file:FAIR data principles (Reusable).jpg'),
    'problem': ('file:Discovering the real problem.jpg', 'file:Problem and Solution.jpg', 'file:Toward the real problem.jpg'),
    'professor': ('file:Anita-Layton-in-Davis-Centre.jpg', 'file:20201125-22-volle-groesse.jpg', 'file:2013 Leroy Lowe Nova Scotia Community College.jpg'),
    'project': ('file:Project start up.jpg', 'file:Digital Dera 26 SP Pakpattan.jpg', 'file:Pic in 2016.jpg'),
    'promise': ('file:Chinese-Promises-1-CR.jpg', 'file:Fresh thyme paper.jpg'),
    'province': ('file:Savusavu.jpg', 'file:Captaincy of São José do Rio Negro (1755-1821).jpg'),
    'public': ('file:Humanities.jpg', 'file:Petrol pamp stand Tampu line.jpg', 'file:Delegates.jpg'),
    'pulse': ('file:A treatise on the pulse published by Wang Wellcome L0031716.jpg', 'file:Characteristic pulse of mitral insufficiency Wellcome M0011301.jpg', 'file:Le Médecin de Chiens (36685027234).jpg'),
    'quality': ('file:Lean wastes - with examples.jpg', 'file:Kisosansen Winter Illumination - panoramio (3).jpg', 'file:Kisosansen Winter Illumination - panoramio.jpg'),
    'question': ('file:Eingang Oper Köln Rekonstruktion 1.jpg', 'file:Are You a Woman NOLA.jpg', 'file:27 Oct 2007 Seattle Demo 56.jpg'),
    'ranch': ('file:End Livestock At Large Road Sign.jpg', 'file:八重山石垣牧場.jpg', 'file:八重山石垣牧場 (96232).jpg'),
    'red': ('file:A collection of glasses filled with red sparkling drinks is arranged neatly on a wooden table.jpg', 'file:(Wü)stenrot, U4 center Meidling.jpg', 'file:(Wüsten)rot, U4 center Meidling.jpg'),
    'reed': ('file:2016-12 reeds and fence in snow.jpg', 'file:12-10-23 Einafjorden PermaLiv 01.jpg', 'file:2017-07-29 Kufstein Hechtsee9 Seerosen.jpg'),
    'regret': ("file:You miss 100% of the shots you don't take - Okanagan Hockey Academy white board.jpg", 'file:2017.02.12 Signs of Regret (of the dying) Brookland Neighborhood, Washington, DC USA 00604.jpg', 'file:Regret facial expression.jpg'),
    'regulation': ('file:REGULATOR LINER SYSTEM - DPLA - 9acf89b186bf1897ce08ab5f251f3f42.jpg', 'file:Sound Police are Ready - EXHIBIT CLOSED due to Show Floor Sound Level Policy Violation - 2015 NAMM Show.jpg', 'file:Fishing regulations BC Virginia State Parks (16569575760).jpg'),
    'religion': ('file:148368 jerusalem - agron street PikiWiki Israel.jpg', 'file:147139 safed - a corner at the entrance to the yeshiva in PikiWiki Israel.jpg', 'file:139484 golan heights-navi hazuri PikiWiki Israel.jpg'),
    'republic': ('file:Homenaje a Juana Capdevielle (Rábade).jpg', 'file:Captain marvel.jpg'),
    'research': ('file:4science dspace cris-or2019-hamburg.jpg', 'file:Atlantic Shark Institute.jpg', 'file:Building at Tezpur University.jpg'),
    'rhythm': ('file:Conga tumbao.jpg',),
    'rooster': ('file:Wappen Anton Leonard von Verbeek.jpg', "file:3893 - Milano - Palazzo della Ragione - Affresco di banco dei magistrati - Foto Giovanni Dall'Orto 9-July.2007.jpg", 'file:Nuremberg chronicles - Genealogy of Charlemagne (CLXXXVIIr).jpg'),
    'root': ('file:2021-09-26-Wurzel Siebengebirge-4653.jpg', 'file:Au - Halbinsel 2015-09-26 16-33-22.JPG', 'file:Au - Halbinsel 2015-09-26 16-32-08.JPG'),
    'rule': ('file:Former Infirmary At Greet House guardians.jpg', 'file:Bar billiards rules cross scythes sheffield 2020-02-09.jpg', 'file:Ellsworth W. Allen Park td (2019-06-28) 023 - Gary Karp Memorial Playground.jpg'),
    'safety': ('file:"Keep Out of Reach of Children" (FDA 114) (8205498879).jpg', 'file:Cloud Super Stainless Safety Razor Blade (13968651134).jpg', 'file:159th SOC Provides Much Needed Safety DVIDS293455.jpg'),
    'sail': ('file:74-Gun Ship - Detail of Sails, No. 1 - NARA - 68865644.jpg', 'file:74-Gun Ship - Detail of Sails, No. 3 - NARA - 68865648.jpg', 'file:74-Gun Ship - Detail of Sails, No. 2 - NARA - 68865646.jpg'),
    'salad': ('file:2023 - Corporate Innovation Summit key event HMZ 3897 (53330185725).jpg', 'file:27-關山二分地民宿早餐 (28896710393).jpg', 'file:Steak and chips at The Red Lyon in Slinfold, West Sussex, England 01.jpg'),
    'salt': ('file:Tulekeeris Igor.jpg', 'file:Erinevate soolade leegid.jpg', 'file:ORT saches.JPG'),
    'screw': ('file:Aprilscherz File-NIK 1064.jpg', 'file:A bolt through the heart... - Flickr - Kate^2112.jpg', 'file:Boulons et vices dans des petits paniers.jpg'),
    'search': ('file:Buskando ur-biltegia 01.jpg', 'file:151121-M-GM943-069 (22838986834).jpg', 'file:2012.01.16.HebronGilbertCheckpoint.1.JPG'),
    'secretary': ('file:20240715 NP SPP ANA GLENDA TAGER FOTOGRAFÍAS CON PERSONAL ADMINISTRATIVO 017.jpg', 'file:Portret van Willem Elinck, RP-P-1905-184.jpg', 'file:The boss and the secretary.jpg'),
    'servant': ('file:"8 Marzo 1973" (Lotta Femminista Poster for International Women\'s Day).jpg', 'file:"Di chi è la pancia di questa donna?" (To whom does the body of this woman belong?).jpg', 'file:"1 Maggio 1975" (1975 Mayday Protest for Wages for Housework in Mestre, Italy).jpg'),
    'service': ('file:Kumbh Mela 2019 - GBPSSI Kumbh Seva Mitra and Military.jpg', 'file:Service sign (Unsplash).jpg', 'file:Taj Continental Kabul Afghanistan.jpg'),
    'shame': ('file:Baudouin, Pierre Antoine - The Honest Model - 1769.jpg', 'file:Shame at 2026 SXSW London 05.jpg', 'file:Shame at 2026 SXSW London 03.jpg'),
    'shamrock': ('file:"Erin Go Braugh. St. Patrick\'s Greetings.".jpg', 'file:"Erin Go Braugh. St. Patricks Day Greetings.".jpg', 'file:Enda Kenny speaks to Barack Obama in the Oval Office 2012.jpg'),
    'shape': ('file:2014-365-342 Geometries (15793709978).jpg', 'file:Christening sweets and their reflections.jpg', 'file:Lines and Shapes (7503673518).jpg'),
    'shoulder': ('file:The Horse BHL18225894.jpg', 'file:Lengchum Saapa - gesture of making shoulders - one of the Hakchaang Saapa (Laipou Khutthek) group of gestures of creating human body - in Lai Haraoba classical dance & music ritualistic performances.jpg'),
    'signal': ('file:-Civil War View- MET DP248312.jpg', 'file:Bridge (5490022387).jpg', 'file:Golden Jubilee Needle Saint Hélyi Jèrri Janvyi 2010 c.jpg'),
    'signature': ('file:2023 Comprehensive Test-Ban Treaty Article XIV Conference - 53212625634.jpg', 'file:1855-11-23 Wilhelm von Borries Urkunde "de jure" Hannoverscher Künstlerverein.jpg', 'file:12080--1910-Adalbert Pokorny Oberstabsgfr.-Brück & Sohn Kunstverlag.jpg'),
    'size': ('file:5-8 vs 5-8 003.jpg', 'file:Pige utilisée pour contrôler la taille des coquilles Saint-Jacques (Ifremer 00527-63859 - 31807).jpg', 'file:Pige utilisée pour contrôler la taille des coquilles Saint-Jacques (Ifremer 00527-63859 - 31806).jpg'),
    'skill': ('file:Hikoban (1920).jpg', 'file:In person management training session for employees.jpg', 'file:Graduate Assistant Appointment.jpg'),
    'skirt': ('file:Blusa y Falda Monek.jpg', 'file:Causal style for women.jpg', 'file:A woman causal style in spring 2021.jpg'),
    'skull': ('file:Skull on a Pole (34919146016).jpg', 'file:Sticker goldener-totenkopf.jpg', 'file:Crâne hérisson 02.jpg'),
    'smile': ('file:Couple enjoys time together at home.jpg', 'file:Couple enjoys coffee together in a cozy setting.jpg', 'file:Couple enjoys coffee together at home.jpg'),
    'smiley': ('file:2013 Woodstock 001 pole namiotowe.jpg', 'file:AUS Brisbane, St Lucia, University of Queensland 0013.jpg', 'file:2008 Children’s Group 3rd Place Winner photo 1 (c32a3656-1dd8-b71b-0b47-f0bd634bd33f).JPG'),
    'solidarity': ('file:A+F-Stickers.jpg', 'file:Bochum Langendreer - Wallbaumweg 03 ies.jpg', 'file:11th March 2019.jpg'),
    'space': ('file:The moon through telescope.jpg', 'file:PIA05437 - Saturn in Red.jpg', 'file:Styx jpg.jpg'),
    'speed': ('file:CH.ZH.Affoltern-am-Albis 2024-03-30 road-bike-racing 2727.jpg', 'file:CH.ZH.Affoltern-am-Albis 2024-03-30 Biker.jpg', 'file:速力 標準表 (7390303886).jpg'),
    'stomach': ('file:Cavidad gástrica.jpg', 'file:Abdominal pain.jpg', 'file:Layers of stomach.jpg'),
    'storage': ('file:Bermondsey Climate Controlled unit.jpg', 'file:20150427최광모101.JPG', 'file:20150331최광모108.jpg'),
    'strategy': ('file:Focus Graphic Recordings, wmcon14 berlin-004.jpg', 'file:Mission Vision Values.jpg', 'file:Hand drawing boxes - garalt.jpg'),
    'suit': ('file:William Owen - Portrait of a man - Google Art Project.jpg', 'file:Businessman-fashion-suit-jacket (24300754036).jpg', 'file:A82I5066.jpg'),
    'superhero': ('file:From wrenches to gloves- 86th AMXS Airman fights his way to success (9447691).jpg', 'file:Sergeant-Joe-Omaha-Guide-Aug4-1945.jpg', 'file:BESC Blood Donation Camp.jpg'),
    'surprise': ('file:Five year old girl in a state of excitement and agitation, listening to trance music at a trance music party.jpg', 'file:Surprise (42495212).jpeg'),
    'suspect': ('file:A member of the Somali security services stands guard over suspected al Shabab militants during a joint night operation with AMISOM forces in Mogadishu, Somalia, on May 4. AU UN IST PHOTO - Tobin (13926966779).jpg', 'file:Members of the Ugandan Special Forces, as part of the African Union Mission in Somalia, sit in the back of an armored vehicle before embarking on a night operation in Mogadishu, Somalia, to capture (14133657353).jpg', 'file:Suspected al Shabab militants are placed in a vehicle before being taken away for further questioning during a joint night operation between the Somali security services and AMISOM forces in (14133691963).jpg'),
    'symbol': ('file:Acrobatics Bannar.jpg', 'file:A painting encapsulating Ewe symbols.jpg', 'file:ATAMAGUI (Ewe symbol).jpg'),
    'symptom': ('file:Lipoathropia semicircularis.jpg', 'file:Lightning injury.jpg', 'file:Jammed ring finger day 2.jpg'),
    'system': ('file:Learning Hubs Sociocratic Structure Update.jpg', 'file:+DSC 0063.jpg', 'file:Danphone system 2.jpg'),
    'taste': ('file:Les cinq sens - Boilly.jpg', 'file:Alie & Georgia at 2015 Taste Awards.jpg', 'file:JOH 0249 (6078916657).jpg'),
    'technique': ('file:Illustrating proper method of throw hand grenades - DPLA - bde67ad0de34b2119454daf25fab70c5.jpg', 'file:COAF SMART Mechanics Program.jpg', 'file:Домкра́т.jpg'),
    'theme': ('file:Fischer Ariadne Editionsvergleich Präludium c-Moll.jpg',),
    'thirst': ('file:Warsaw Lindley Filters 2016 P30 rapid sand filters Thirst relief.jpg', 'file:Save it before you have to save yourself.jpg', 'file:Jesus, kali Ghat.jpg'),
    'torpor': ('file:Virginia big-eared bat (C.t. virginianus).JPG', 'file:Delias nigrina Common jezebels immobile on frosty morning beneath Allocasuarina litoralis infested with Amyema congenener 7th Brigade Park Chermside P1060591.jpg', 'file:Delias nigrina Common jezebels immobile on frosty morning beneath Allocasuarina litoralis infested with Amyema congenener 7th Brigade Park Chermside P1060590.jpg'),
    'toy': ("file:2025-06-01 11 48 09 The Motion Machine at the Bucks County Children's Museum in New Hope, Bucks County, Pennsylvania.jpg", 'file:2025-05-08 12 49 37 Toys in the interior of Playpad Bucks in Middletown Township, Bucks County, Pennsylvania.jpg', 'file:2025-05-08 12 47 52 Toys in the interior of Playpad Bucks in Middletown Township, Bucks County, Pennsylvania.jpg'),
    'trade': ('file:HUA-216555-Plattegronden opstanden en doorsneden van het ontwerp voor een korenbeurs tussen de bebouwing van de Neude en de Ganzenmarkt te UtrechtMet indeling en.jpg', 'file:Hand Made African-Print Bag.jpg', 'file:De la costa a la cordillera con mis cochayuyos.jpg'),
    'trailer': ('file:Jochen Claussen-Finks hfg ulm history 2014.jpg', 'file:Juarez 1939 Title.jpg'),
    'transmission': ('file:Algoritmo Flanger.jpg', 'file:Aircraft-recognition-and-tracking-by-dsp-based-signal-processing.jpg', 'file:Signal créneau symétrique.jpg'),
    'trap': ('file:Pinchout.jpg',),
    'troll': ('file:Virginia Motor Sport Club (VMSC) at RIR (26054406685).jpg', 'file:Troll-Collect.jpg', 'file:No Trolls wanted here.jpg'),
    'ultimatum': ('file:Ultimatum on the Oregon question 1846 cartoon crop.jpg', 'file:German ultimatum of 1914.JPG', 'file:Ultimatum Defuisseaux - 26 mai 1887.jpg'),
    'unemployment': ('file:If I only had a job (NYPL Hades-609941-1802325).jpg', 'file:If I only had a job (NYPL Hades-609941-1802324).jpg', 'file:If I only had a job (NYPL Hades-609941-1802323).jpg'),
    'vampire': ('file:MercyBrownGravestone.jpg', 'file:MercyBrownGravestone (bearb Sp).jpg'),
    'vice': ('file:Israel Broadcasting service at Shaarei Tsedek 17.jpg', "file:4336 - Venezia - Palazzo ducale - Capitello 33 - Foto Giovanni Dall'Orto, 30-Jul-2008.jpg", 'file:Frailties breed false beleifs.jpg'),
    'victory': ('file:Jessica Podium.jpg', 'file:Millstatt Benediktinerstift Kreuzgang Treppe zur Moenchspforte 20042015 2365.jpg', 'file:Millstatt Benediktinerstift Kreuzgang Moenchspforte Saeulenbasis rechts Skulptur 20042015 2356.jpg'),
    'vomiting': ('file:Een financieel debâcle, RP-T-1932-18.jpg', 'file:嘔吐 罰金 2万円 (54368068879).jpg', 'file:BombBag Inhalt.jpg'),
    'vulnerable': ('file:Dried Ashoka flower (Saraca asoca) 01.jpg', 'file:Displaying the IUCN Red List awareness.jpg', 'file:Dried Ashoka flower (Saraca asoca).jpg'),
    'warrior': ('file:Neues Reich. Dynastie XIX. Theben (Thebes). Memnonia (Ramesseum). Tempel Ramses II. Erster Pylon. Westseite, Nordhälfte. Blatt A (NYPL b14291191-38326).jpg', 'file:"Armed Ngoni Warriors, Livingstonia" Malawi, ca.1910 (imp-cswc-GB-237-CSWC47-LS4-1-006).jpg', 'file:A happy warrior during the Nom Bajju 2026 Annual Cultural Festival.jpg'),
    'wealth': ('file:Extemporaneous remarks at Harve, Montana - NARA - 197750.jpg', 'file:Svenska millionärer.jpg', 'file:Wealth Inequality in Europe.jpg'),
    'wedge': ('file:Malta - Siggiewi - Triq Mons Mikel Azzopardi - Limestone Heritage - museum 04 ies.jpg', 'file:Malta - Siggiewi - Triq Mons Mikel Azzopardi - Limestone Heritage - museum 03 ies.jpg', 'file:Malta - Siggiewi - Triq Mons Mikel Azzopardi - Limestone Heritage - museum 02 ies.jpg'),
    'week': ('file:Printemps de Bourges 2019-36.jpg', 'file:Paris-Nice 2021, affiche (extrait).jpg', 'file:Календарь в двух вариантах.jpg'),
    'weekend': ('file:Sign-1240032, Dublin, Ireland.jpg', 'file:Kids play 2.jpg', 'file:Sunday House Texas historical marker in Fredericksburg, Texas.jpg'),
    'white': ('file:Cute white puppy sits on a cozy blanket in a warm living room surrounded by furniture.jpg',),
    'wife': ('file:Habit of the Turkish lady of the grand seigniors seraglio, in 1568. Dame de condition Turque, dans le serail (NYPL b14140320-1638019).jpg', "file:Wives of Officers of the 13th Minnesota Regiment at Col. McC Reeve's - DPLA - edf01beba5c7a6857ee3941658b41843.jpg", 'file:Wives of the Officers of the 13th Minnesota Regiment at the House of General Reeve - DPLA - 3370ab842113d1a2deb6c320ce886707.jpg'),
    'witch': ('file:Beauty in Darkness.jpg', 'file:A Boszorkánymúzezm parkolója.jpg', 'file:Der Abtenauer Perchtenlauf 2017- 03.jpg'),
    'witness': ('file:Bund-Nazi powerful tieup in this country former reporter tells House Committee. Washington, D.C., Aug. 12. First mystery witness today before the Special House Committee investigating LCCN2016873902.jpg', 'file:Mystery witness before Dies Un-American Committee today. Washington, D.C., Aug. 18. The mystery witness presenting charges against Harry Bridges to the House Committee on Un-American LCCN2016873933.jpg', 'file:Mystery witness at Dies hearing. Washington, D.C., Oct. 27. J.E. Creighton, reporter for the Lansing, Mich. State journal, was introduced as the mystery witness promised for today. He LCCN2016874229.jpg'),
    'writer': ('file:Authors Tomazinho Cardozo, WIlly Goes and Domnic Fernandes, in Goa, India.jpg', 'file:Author Chat.jpg', 'file:Aritz Galarraga by Dani Blanco Argia-fototekan.jpg'),
    'yellow': ('file:Alone and afloat (36126013761).jpg', 'file:Alone and afloat (35427424254).jpg', 'file:Basketball at the 2012 Summer Olympics (8016976849).jpg'),
    'zebra': ('file:Upright Zebra Mayana Rock Paintings.jpg', 'file:Lake Nakuru National Park Zebras 05.jpg', 'file:Lake Nakuru National Park Zebras 02.jpg'),
    'zoology': ('file:Fighting fish.jpg', 'file:Bighorn Sheep Capture.jpg', 'file:Dorsal ornementations.jpg'),
}
